### ISSUE TITLE
Incorrect informational assembly version render for ASP.NET Core 2.1 app

### ISSUE THREAD

**Issue by psmolkin** [NLog/NLog#2783] opened 2018-06-22 12:48 UTC
Layout `"${assembly-version:type=Informational}"` works incorrect in ASP.NET Core 2.1 applications.
It renders value of "AssemblyVersion" attribute instead of "Version" if both seted

### Steps to reproduce
- exec `dotnet new mvc`
- set **app.csproj**:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AssemblyVersion>1.2.3</AssemblyVersion>
    <Version>4.5.6.9999-foo</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="NLog" Version="4.5.6" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.5.4" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Update="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```

- add targets to **NLog.config**:
```xml
<targets >
    <target xsi:type="Console" name="structured-stdout" >
      <layout xsi:type="JsonLayout">
       <attribute name="message" layout="${message}" encode="false"/>
       <attribute name="InformationalVersion" layout="${assembly-version:type=Informational}"/>
      </layout>
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="structured-stdout"/>
  </rules>
```
 - add code to **Program.cs**:
```cs
var logger = NLogBuilder.ConfigureNLog("NLog.config").GetCurrentClassLogger();
var assembly = System.Reflection.Assembly.GetEntryAssembly();
logger.Info("Get version {ver}", 
// got it from https://github.com/NLog/NLog/blob/master/src/NLog/LayoutRenderers/AssemblyVersionLayoutRenderer.cs#L188
assembly?.GetCustomAttribute<System.Reflection.AssemblyInformationalVersionAttribute>()?.InformationalVersion);
```
### Expected behavior
`"InformationalVersion"` should be equals with `<Version>` attribute

### Actual behavior
They are different
```
{ "message": Get version "4.5.6.9999-foo", "InformationalVersion": "1.2.3.0" }
```

### Environment
**.NET Core**: 2.1
**NLog version**: 4.5.6

**Comment by snakefoot** [comment] 2018-06-22 20:07
Sounds like a duplicate of this:

https://github.com/NLog/NLog.Web/issues/293

With this PR on the queue:

https://github.com/NLog/NLog.Web/pull/296

**Comment by alexangas** [comment] 2018-06-26 16:24
Yes it looks like a duplicate. I will test with ASP.NET Core 2.1 as part of fixing it.

**Comment by 304NotModified** [comment] 2018-07-05 21:09
closing in favor of NLog/NLog.Web#293

**Closed by 304NotModified** 2018-07-05 21:09 UTC
Labels: duplicate
