### ISSUE TITLE
Custom NLog target outputs duplicate LogEvent once a month

### ISSUE THREAD

**Issue by Hussein-Dahir** [NLog/NLog#5077] opened 2022-09-28 11:17 UTC
Hi,

I am using NLog with a Custom Target (which extends AsyncTaskTarget abstract class) to write logs to DB, however, I noticed that sometimes I have a log entered twice!

**NLog version**: 
NLog Version: 3.7.6
NLog.Web.AspNetCore Version: 4.10

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Xamarin Android / Xamarin iOS / .NET Core / .NET5 / .NET6
 .NET Core 3.1

**Current NLog config** (xml or C#, if relevant)

```c#
/*
 * Configuring NLog for database logging
 */

// Create configuration object 
var config = new LoggingConfiguration();

// Configure NLog target
// Register Custom Target
string targetName = "MyCustomDatabaseTarget ";
Target.Register<MyCustomDatabaseTarget >(targetName);

ServiceProvider serviceProvider = services.BuildServiceProvider();
IEventsLogRepository eventsLogRepository = serviceProvider.GetRequiredService<IEventsLogRepository>();

MyCustomDatabaseTarget myCustomDatabaseTarget = new MyCustomDatabaseTarget (eventsLogRepository)
{
    Name = targetName
};

// add target to config
config.AddTarget(myCustomDatabaseTarget);


/* 
 * Define filteration rules 
 */

string loggerNamePattern = "MyProject.*";

// define a rule for non-exceptions
var nonExceptionsRule = new LoggingRule(loggerNamePattern, LogLevel.Trace, LogLevel.Error, myCustomDatabaseTarget)
{
    Final = true,
    DefaultFilterResult = FilterResult.LogFinal
};

// ignore SignalR requests
nonExceptionsRule.Filters.Add(new ConditionBasedFilter
{
    Condition = "contains('${aspnet-Request-Url}','SignalR')",
    Action = FilterResult.IgnoreFinal
});

// adding filters to specifiy which APIs to ignore
// filteration condition will be as "Controller - API" == "ControllerName - ApiName"
foreach (var controller in APIsToIgnore.Controllers)
{
    controller.Value.ForEach(api =>
    {
        nonExceptionsRule.Filters.Add(new ConditionBasedFilter
        {
            Condition = "'${aspnet-mvc-controller} - ${aspnet-MVC-Action}' == " + $"'{controller.Key.Replace("Controller", string.Empty)} - {api}'",
            Action = FilterResult.IgnoreFinal
        });
    });
}

// define a rule for exceptions (always log exceptions)
var exceptionsRule = new LoggingRule(loggerNamePattern, LogLevel.Fatal, myCustomDatabaseTarget)
{
    Final = true,
};

// add these rules to config
config.LoggingRules.Add(nonExceptionsRule);
config.LoggingRules.Add(exceptionsRule);


/*
 * configure the time zone for LogTime to be in UTC
 */
TimeSource.Current = new FastUtcTimeSource();


/*
 * Activate the configuration
 */
LogManager.Configuration = config;
```

- What is the current result?
  Getting Log inserted to DB twice, see attached image:

![image](https://user-images.githubusercontent.com/26072899/192763370-b9a733c9-75d5-4259-a53a-d52122c41db8.png)

- What is the expected result?
  Getting Log inserted to DB only once

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
   Yes, nothing helpful there.
- Please post full exception details (message, stacktrace, inner exceptions)
  No exceptions.
- Are there any workarounds? yes/no
  This is what I am trying to figure out.
- Is there a version in which it did work? 
  No idea
- Can you help us by writing an unit test?
  Sorry, doesn't have experience in unit testing.

**Comment by snakefoot** [comment] 2022-09-28 16:05
It seems that your 2 logging-rules are configured correctly, so I cannot spot why you see 2 log-entries.

If you are able to create an unit-test that reproduces the issue, or an example application, then I don't mind taking a look.

**Comment by Hussein-Dahir** [comment] 2022-09-28 17:39
@snakefoot Thank you for your response.
The problem is that this issue is rarely happening (happened only once this month), but I will make my best to provide you with more information.

**Comment by snakefoot** [comment] 2023-01-02 18:09
Closing issue, since no new clues has been provided. If able to reproduce the issue in some way, then please re-open.

**Closed by snakefoot** 2023-01-02 18:09 UTC
Labels: question, nlog-configuration
