### ISSUE TITLE
System.DivideByZeroException in Dictionary TryGetValue

### ISSUE THREAD

**Issue by alexherbert** [NLog/NLog#4576] opened 2021-09-20 12:01 UTC
Anyone else seen a System.DivideByZeroException error when trying to get the logger from the LogManager. Seems to have happened as a once off but concerned it could reappear.

nLog version: 4.6.5

Any ideas?

```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DivideByZeroException
   at System.Collections.Generic.Dictionary`2[[NLog.LogFactory+LoggerCacheKey, NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FindEntry(LoggerCacheKey)
   at System.Collections.Generic.Dictionary`2[[NLog.LogFactory+LoggerCacheKey, NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TryGetValue(LoggerCacheKey, System.__Canon ByRef)
   at NLog.LogFactory+LoggerCache.Retrieve(LoggerCacheKey)
   at NLog.LogFactory.GetLoggerThreadSafe(System.String, System.Type)
)
```

**Comment by snakefoot** [comment] 2021-09-20 12:26
What platform are you running on? Unity ?

**Comment by alexherbert** [comment] 2021-09-20 12:36
No, just a standard windows service. When the service was restarted the error was not thrown again.

**Comment by snakefoot** [comment] 2021-09-20 12:43
I cannot see anything out of the ordinary:

https://github.com/NLog/NLog/blob/5bcdd4951392828eef4a48d3e4bd923d8265a5cc/src/NLog/LogFactory.cs

And everything is done under a lock, so not a threading issue either. I have no idea why Dictionary should DivideByZeroException.

What version of Windows and .NET Framework / .NET Core are you running with?

**Comment by alexherbert** [comment] 2021-09-20 13:09
Very strange but will just keep an eye on it. 

.NETFramework v4.6.1

**Comment by snakefoot** [comment] 2021-09-20 16:21
Maybe take a look in Windows System-EventLog or Application-EventLog and look for any hardware errors.

**Comment by snakefoot** [comment] 2021-10-02 16:48
Closing issue as external issue. If finding details showing that the issue is in NLog, then please re-open.

**Closed by snakefoot** 2021-10-02 16:48 UTC
Labels: question, external
