### ISSUE TITLE
data obfuscation

### ISSUE THREAD

**Issue by markkerins** [NLog/NLog#4091] opened 2020-08-19 21:42 UTC
Hi there,

this is a general question.

Is there by any chance a sensitive data obfuscation tool that we can use with NLog.
I'm trying to implement company logging standards and one important one is 'dont save sensitive / Personal Information' to logs.
it would be really cool if there was some funky obfuscation tool out there

thanks

**Comment by snakefoot** [comment] 2020-08-20 15:13
Duplicate of password masking #1155 ?

**Comment by 304NotModified** [comment] 2020-08-20 18:51
obfuscation != Secure. It's security by obscurity. 

I'm many companies I see the following rule:

- don't log sensitive data on level info and higher
- disable logging in production/sensitive environment for logs lower than info level. 
- don't log objects you won't own (e.g. exception) with reflection etc.

**Comment by markkerins** [comment] 2020-08-20 19:53
@304NotModified  I do agree with you.
The best practice is not to log sensitive data, and we are working to implement the rules you've mentioned. 

I'm looking for to potentially **add** obfuscation as a tool to combat security and not for obfuscation to  be the **only ** security tool.

**Comment by 304NotModified** [comment] 2020-08-20 20:01
If #1155 isn't helping, please describe an example as this is really broad.

**Comment by markkerins** [comment] 2020-08-20 20:10
I was hoping (wishful thinking )  that someone would have done something like a  object.obfuscate  or json.obfuscate  to which you could decorate the attribute as sensitive maybe something like this


public class MixedSensitivityModel 
{
[sensitive]
public datetime DateOfBirth { get; set; }

public string  Randomtext { get; set; }
}
then when we go to  do something like this
var myobject = new MixedSensitivityModel ()
.
.
.
.
.
logger.debug(Newtonsoft.Json.JsonConvert.SerializeObject(myobject.sensitise())) 
the contents saved to the Nlog target would have DateOfBirth obfuscated or even removed

**Comment by 304NotModified** [comment] 2020-08-20 20:14
What platform are you using? ASP.NET Core? .Net Core? .Net framework x?

**Comment by markkerins** [comment] 2020-08-20 20:15
I was hoping for the solution to be platform agnostic

**Comment by markkerins** [comment] 2020-08-20 20:19
I consider my solution to be 'optimistic'  obfuscation. i.e. the class by default is relatively safe , and that only some attributes need to be secured 

we could also have  'pessimistic'  obfuscation , i.e. the class by default needs to be secured, and that should you want to make properties logible, you'd decorate them the same.

thinking about it an extension to  
Newtonsoft.Json.JsonConvert would possibly be better  

`Newtonsoft.Json.JsonConvert.SecurelySerializeObject(myobject)`

**Comment by 304NotModified** [comment] 2020-08-20 20:41
You could do nowadays something like this, but it's a bit harder to get this working with attributes:


```
public class MixedSensitivityModel
{
    public DateTime DateOfBirth { get; set; }

    public string Randomtext { get; set; }
}

[Fact]
public void SensitiveTest()
{
    // Setup 
    LogManager.Setup().SetupSerialization(s => s.RegisterObjectTransformation<MixedSensitivityModel>(o => new { RandomText = o.Randomtext, DateOfBirth = "*****" }));

    // Demo
    // config
    var config = new LoggingConfiguration();
    var memoryTarget = new MemoryTarget("target1");
    config.AddRuleForAllLevels(memoryTarget);
    LogManager.Configuration = config;

    // logging
    var logger = LogManager.GetLogger("logger1"); //or LogManager.GetLogger()

    var testObject = new MixedSensitivityModel
    {
        DateOfBirth = DateTime.Now.AddYears(-30),
        Randomtext = "Not really random"
    };

    var order = new { OrderId = 5, Date = DateTime.Now };

    logger.Info("Hi {@Test} {@Order}", testObject, order);

    var message = memoryTarget.Logs.First(); // 2020-08-20 22:39:11.0706|INFO|logger1|Hi {"RandomText":"Not really random", "DateOfBirth":"*****"} {"OrderId":5, "Date":"2020-08-20T20:39:11.0676764Z"}
}
```

**Comment by 304NotModified** [comment] 2020-08-20 20:46
This is also possible by using ToString


```
public class MixedSensitivityModel
{
    public DateTime DateOfBirth { get; set; }

    public string Randomtext { get; set; }

    /// <inheritdoc />
    public override string ToString()
    {
        return $"DateOfBirth: *****, Randomtext: {Randomtext}";
    }
}

[Fact]
public void SensitiveTest()
{
    // Setup 
 
    // Demo
    // config
    var config = new LoggingConfiguration();
    var memoryTarget = new MemoryTarget("target1");
    config.AddRuleForAllLevels(memoryTarget);
    LogManager.Configuration = config;

    // logging
    var logger = LogManager.GetLogger("logger1"); //or LogManager.GetLogger()

    var testObject = new MixedSensitivityModel
    {
        DateOfBirth = DateTime.Now.AddYears(-30),
        Randomtext = "Not really random"
    };

    var order = new { OrderId = 5, Date = DateTime.Now };

    logger.Info("Hi {Test} {@Order}", testObject, order);

    
```

See also [How to use structured logging](https://github.com/NLog/NLog/wiki/How-to-use-structured-logging)

**Comment by 304NotModified** [comment] 2020-08-20 20:53
Or you could use JSON.NET, e.g. with [JsonIgnore] or a custom converter:


```c#
public class MixedSensitivityModel
{
    [JsonIgnore]
    public DateTime DateOfBirth { get; set; }

    public string Randomtext { get; set; }

}

public class JsonNetConverter : IJsonConverter
{
    #region Implementation of IJsonConverter

    /// <inheritdoc />
    public bool SerializeObject(object value, StringBuilder builder)
    {
        var jsonSerializerSettings = new JsonSerializerSettings();
        var result = Newtonsoft.Json.JsonConvert.SerializeObject(value, jsonSerializerSettings);
        builder.Append(result);
        return true;
    }

    #endregion
}

[Fact]
public void SensitiveTest()
{
    // Setup 

    LogManager.Setup().SetupSerialization(b =>
         b.RegisterJsonConverter(new JsonNetConverter())
        );

    // Demo
    // config
    var config = new LoggingConfiguration();
    var memoryTarget = new MemoryTarget("target1");
    config.AddRuleForAllLevels(memoryTarget);
    LogManager.Configuration = config;

    // logging
    var logger = LogManager.GetLogger("logger1"); //or LogManager.GetLogger()

    var testObject = new MixedSensitivityModel
    {
        DateOfBirth = DateTime.Now.AddYears(-30),
        Randomtext = "Not really random"
    };

    var order = new { OrderId = 5, Date = DateTime.Now };

    logger.Info("Hi {@Test} {@Order}", testObject, order);

    var message = memoryTarget.Logs.First(); // 2020-08-20 22:52:38.8773|INFO|logger1|Hi {"Randomtext":"Not really random"} {"OrderId":5,"Date":"2020-08-20T22:52:38.874358+02:00"}
}
```

**Comment by markkerins** [comment] 2020-08-20 21:00
oh JsonIgnore looks like a nice approach. 

It does look like , no matter what way we go there will be an onus on the developer to do the right thing (i.e. protect the data)

**Closed** 2020-08-27 20:01 UTC
Labels: needs info, question

**Comment by snakefoot** [comment] 2021-05-10 18:13
Alternative you could ensure that the sensitive-data is encapsulated in a custom class/struct. Ex. `class SensitiveInformation`.

Then let the class implement `IFormattable` and ensure that ToString() returns an obfuscated version of the truth.

But a good alternative is making use of [RegisterObjectTransformation](https://github.com/NLog/NLog/issues/4091#issuecomment-677892844) for the custom `class SensitiveInformation`.
