### ISSUE TITLE
some properties of nlog.config in docs on wiki  are not match with the NLog.xsd

### ISSUE THREAD

**Issue by John0King** [NLog/NLog#3037] opened 2018-12-07 08:32 UTC
I enable `nlog.xsd` today by  enable auto download schema file from network(options->text editor-> xml->Miscellaneous ) and  add `xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd http://www.nlog-project.org/schemas/NLog.xsd"` to the `nlog` element

I find that there may case not match in the document:

https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2  
![image](https://user-images.githubusercontent.com/13639146/49635596-4c9a5f80-fa3b-11e8-9871-6e9c33221a2f.png)

https://github.com/NLog/NLog/wiki/Configuration-file
![image](https://user-images.githubusercontent.com/13639146/49635883-0a255280-fa3c-11e8-89fa-e420f8980dd9.png)

I hope that there's a better way to create `nlog.config` ( such like `dotnet new` ) and help people enable intellisense

**Comment by 304NotModified** [comment] 2018-12-17 08:22
Thanks for reporting. I don't fully understand what you are proposing. Do we need to change something?

**Comment by John0King** [comment] 2018-12-17 09:18
basic change:
 add a document  that provide the basic nlog.config file with the `xsi:schemaLocation`  explain how to enable intellisence in visual studio.

Advanced:
`dotnet new` template (eg. `dotnet new nlog.config` )  or a nlog global tools  (eg. `nlog new aspnetcore/console`)

**Comment by 304NotModified** [comment] 2018-12-17 12:36
> add a document 

Do you mean, document it online? Or in the nlog.config with XML comments? 

> that provide the basic nlog.config file

Do you mean, the nlog.config from [NLog config Nuget package](https://www.nuget.org/packages/NLog.config)?

**Comment by John0King** [comment] 2018-12-17 14:15
yes, add a online document on github wiki and your website .

> Do you mean, the nlog.config from NLog config Nuget package?

what does this nuget package do ?  what I mean  is a example nlog.config file that has the `xsi:schemaLocation` attribute embeded in the "Enable Intellisence in visual studio" doucment

**Comment by 304NotModified** [comment] 2019-03-15 20:38
FYI: Feel free to edit the wiki or send a PR

**Comment by snakefoot** [comment] 2020-03-28 10:59
Duplicate of this is #3822. Happy that users have sharp eyes. 

Issue #3403 has been created to capture the idea with `dotnet new`.

Can only agree that people are always welcome to improve the Wiki.

**Closed by snakefoot** 2020-03-28 10:59 UTC
Labels: documentation
