### ISSUE TITLE
NLog Should Target net46

### ISSUE THREAD

**Issue by Silvenga** [NLog/NLog#4027] opened 2020-06-24 14:48 UTC
**NLog version**: `4.7.2`
**Platform**: .Net 4.5 (targeting .Net 4.7.1) / .NET Core 2 / .NET Core 3

When NLog is referenced from a project targeting net46 through net48 some "modern" implementations of types are not used.

For example:

https://github.com/NLog/NLog/blob/099a07e2c7e502861c5eaaa6674d12577e40693c/src/NLog/Contexts/MappedDiagnosticsLogicalContext.cs#L407-L411

When building net45, `CallContext.LogicalGetData` is used over `AsyncLocal`. Preferably, the net46 `AsyncLocal` should be used in applications built against >= net46.

While net48 is compatible with netstandard2.0, the tooling selects net45 as the closest target. So I propose adding another target (net46) to NLog to handle the 14 locations where the legacy implementation is selected.

```
Found 14 texts
  <NLog> (14 items)
    Internal (4 items)
      ObjectHandleSerializer.cs (2 items)
        (37,6) #if !NET4_6 && !NETSTANDARD && !SILVERLIGHT
        (37,6) #if !NET4_6 && !NETSTANDARD && !SILVERLIGHT
      ThreadLocalStorageHelper.cs (2 items)
        (62,22) #elif NETSTANDARD || NET4_6
        (94,22) #elif NETSTANDARD || NET4_6
    MappedDiagnosticsLogicalContext.cs (5 items)
      (224,5) #if NET4_6 || NETSTANDARD
      (326,5) #if NET4_6 || NETSTANDARD
      (390,5) #if NET4_6 || NETSTANDARD
      (402,5) #if NET4_6 || NETSTANDARD
      (409,5) #if NET4_6 || NETSTANDARD
    NestedDiagnosticsLogicalContext.cs (5 items)
      (214,5) #if NET4_6 || NETSTANDARD
      (228,5) #if NET4_6 || NETSTANDARD
      (266,5) #if NET4_6 || NETSTANDARD
      (278,5) #if NET4_6 || NETSTANDARD
      (285,5) #if NET4_6 || NETSTANDARD
```

**Comment by Silvenga** [comment] 2020-06-24 14:50
This additional target would also indirectly fix a "bug" we are experiencing with some AppDomain weirdness that I'm still trying to trackdown.

I can make a PR for this. Just wanted to get feedback before doing the work.

**Comment by 304NotModified** [comment] 2020-06-24 18:45
Thanks, there is already a PR for this (but out dated) https://github.com/NLog/NLog/pull/3818

This will be fixed in nlog 5. We will drop the .net 4.0 dll in favor of 4.6 (and we still keep .net 3.5 for nlog 5)

**Comment by snakefoot** [comment] 2020-06-24 19:26
When removing .Net4 and adding .Net46, then I think we should remove the custom NLog defines NET3_5 + NET4_5 + NET4_6 and instead use the default ones NET35 + NET45 + NET46

Also the defines should changed from opt-in:
```c#
#if NET45 || NET46
// blah blah
#endif
```
To opt-out:
```c#
#if !NET35
// blah blah
#endif
```

**Comment by Silvenga** [comment] 2020-06-24 23:17
Ah, perfect. I'll wait for NLog 5. We've recreated the MDLC system in custom code to work around the issue with app domains.

Let me know if I could be useful in making this happen in NLog 5, I made a pr or update an existing one.

**Comment by snakefoot** [comment] 2020-06-29 21:48
Marking as duplicate of #3979

**Closed** 2020-06-29 21:48 UTC
Labels: duplicate, feature
