### ISSUE TITLE
Not getting an internal log message when email fails to send

### ISSUE THREAD

**Issue by attrib75** [NLog/NLog#710] opened 2015-05-19 15:32 UTC
We're experiencing some intermittent email delivery issues in a production environment which led us to discover that NLog is not logging internally when there is an exception sending an email.  To test this, I purposefully set the wrong SMTP address in the NLog config file.  I expected to see an internal NLog message saying there was an exception sending to that mail server.  In the NLog source, it looks like there's a try {send mail} catch {always log}.  Is there a way we can see exceptions when sending email?

**Comment by 304NotModified** [comment] 2015-05-19 17:33
This is probably solved in 4.0(and so in the master). I have to check that.

**Comment by attrib75** [comment] 2015-05-19 18:45
Ok thanks!  We'll stand by.  Is there a target release date for 4.0?

**Comment by 304NotModified** [comment] 2015-05-19 19:03
Yes 2 June. But first a beta release

**Comment by 304NotModified** [comment] 2015-05-19 21:16
Confirm. this is fixed in 4.0. 

See line 324 in [v3.2.1](https://github.com/NLog/NLog/blob/v3.2.1/src/NLog/Targets/MailTarget.cs)


and line 306 in [master](https://github.com/NLog/NLog/blob/master/src/NLog/Targets/MailTarget.cs)

**Comment by 304NotModified** [comment] 2015-05-19 21:18
So thanks for the report. Marking this a duplicate and closing as it has been resolved in 4.0.

**Closed by 304NotModified** 2015-05-19 21:18 UTC

**Comment by 304NotModified** [comment] 2015-05-19 21:19
duplicate of #261

**Comment by attrib75** [comment] 2015-05-20 21:38
Ok thank you
