### ISSUE TITLE
Support xamarinmac20

### ISSUE THREAD

**Issue by tofutim** [NLog/NLog#1946] opened 2017-02-07 19:16 UTC
**Type** (choose one):
- Feature request

**NLog version**: (e.g. 4.2.3)
Latest

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin Mac 2.0

**Current NLog config** (xml or C#, if relevant)
n/a

in case of a FEATURE REQUEST:
 
 - Why do we need it? - because I need it? :)  It is parallel to Xamarin iOS and Android and ought to be supported as well.

**Comment by 304NotModified** [comment] 2017-02-07 23:16
Agree, we should support this. 

Is it possible to create a PR if I guide you in the needed changes?

**Comment by jnajerasc** [comment] 2018-02-26 22:00
I'm interested in this feature request.  Are there any plans for supporting Xamarin Mac 2.0 in an upcoming release?

**Comment by snakefoot** [comment] 2018-02-26 22:10
@jnajerasc Can Xamarin 2.0 not use NetStandard ? NLog 4.5 supports NetStandard

**Comment by snakefoot** [comment] 2018-02-26 22:34
```
  <PropertyGroup Condition=" '$(TargetFramework)' == 'xamarinmac20' ">
    <Title>NLog for Xamarin Mac 2.0</Title>
    <TargetFrameworkIdentifier>Xamarin.Mac</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v2.0</TargetFrameworkVersion>
    <LanguageTargets Condition="Exists('$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.Mac.CSharp.targets')">$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.Mac.CSharp.targets</LanguageTargets>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <DefineConstants>$(DefineConstants);__IOS__</DefineConstants>
</PropertyGroup>
```

**Comment by jnajerasc** [comment] 2018-02-26 23:03
I've been able to reference the NetStandard 2.0 NLog library in my app, but I'm seeing an issue where the LogManager has a null Configuration, even though I have my NLog.config file defined and declared in my Xamarin Mac csproj file.  I figured that Xamarin Mac isn't fully supported yet.

**Comment by snakefoot** [comment] 2018-02-27 06:02
Have you checked the internal logger like everyone else troubleshooting NLog?

https://github.com/NLog/NLog/wiki/Logging-troubleshooting

Most likely scenario is that you are missing a "Copy Always" for the NLog.config file, so it cannot be found in `AppDomain.CurrentDomain.BaseDirectory` for auto-loading.

You can also use `NLog.LogManager.LoadConfiguration` with an explicit path to `NLog.config`, and see if it works.

**Comment by jnajerasc** [comment] 2018-02-27 21:50
Success!  I got NLog 4.5.0-rc05 working with Xamarin Mac, after making the following changes in my application:

- In my app's csproj file, I had to add an AfterBuild target that copies the NLog.config to the Contents/MonoBundle/ directory of my app.

- In the NLog.config file, I had to set the autoReload attribute to "false".  My config file originally had autoReload set to true, which caused my app to throw an exception on startup by FileSystemWatcher_mobile.cs which doesn't have an implemented Dispose method.

Here's the auto reload error that I saw, in case it helps others searching for this issue:

`Unhandled Exception:
System.NotImplementedException: The method or operation is not implemented.
  at System.IO.FileSystemWatcher.Dispose (System.Boolean disposing) [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.0.0.216/src/mono/mcs/class/System/System.IO/FileSystemWatcher_mobile.cs:62 
  at System.ComponentModel.Component.Finalize () [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.0.0.216/src/mono/mcs/class/referencesource/System/compmod/system/componentmodel/Component.cs:35`

**Comment by snakefoot** [comment] 2018-02-27 23:05
@jnajerasc Great job. Funny how "Xamarin.Mac" uses something called "FileSystemWatcher_mobile"

Will make a commit for NLog, so it will not die when exception occurs in the FileSystemWatcher

**Comment by snakefoot** [comment] 2018-02-28 15:54
@jnajerasc Created https://github.com/mono/mono/issues/7338, as I think it is difficult to catch this exception, since NLog will never be able to create a FileSystemWatcher:

https://github.com/mono/mono/blob/master/mcs/class/System/System.IO/FileSystemWatcher_mobile.cs

Think it is the finalizer-thread that dies in the attempt of cleanup, after the failed constructor.

**Comment by snakefoot** [comment] 2019-10-20 16:45
@304NotModified Guess this should be closed as won't fix, since we are trying to reduce the targetplatforms to: net35, net45, netstandard (and maybe introducing net472)

**Comment by snakefoot** [comment] 2020-01-20 21:58
Closing this question as duplicate of #2871 (When there is only .NET Framework and .NetStandard then it will be resolved).

**Closed by snakefoot** 2020-01-20 21:58 UTC
Labels: feature
