### ISSUE TITLE
Layout renderers are invoked too late / on wrong thread when using async / buffer

### ISSUE THREAD

**Issue by andersjoh** [NLog/NLog#1105] opened 2015-12-21 07:46 UTC
In an async/buffered scenario, layout renderers should be invoked much earlier. As is, the calling thread could be long gone and ActivityId etc. is null.

**Comment by andersjoh** [comment] 2015-12-21 13:43
Maybe take a peek at SiriLog? I know they invoke the renderers on Log. As long as the renderer code is realatively lightweight (which they should!), this won't be a problem.

**Comment by 304NotModified** [comment] 2015-12-21 14:01
> Maybe take a peek at SiriLog? I know they invoke the renderers on Log. As long as the renderer code is realatively lightweight (which they should!), this won't be a problem.

Sure :) But it's not the problem how to do this, but when. 
Rendering is never lightweight as those are string manipulations. 


> edit 
> How about invoking renderers on Logging and buffer by default? Nowadays you'll want to write to Elastic or some cloud service?

I think that would hurt performance too much. But that's never timed or something like that.

**Comment by andersjoh** [comment] 2015-12-21 14:18
Right, sorry i'm not expressing myself clearly enough. I'm suggesting a renderer that extracts the data it needs and write's to an intermediary object that is then put into a buffer. When the buffer is flushed the object is translated into a string. Would that be possible? I haven't dived that deeply into the source code.

**Comment by 304NotModified** [comment] 2015-12-21 16:49
Thanks for elaborating,

> I'm suggesting a renderer that extracts the data it needs and write's to an intermediary object that is then put into a buffer. When the buffer is flushed the object is translated into a string.

Good idea but I'm not sure if that will fit. If we have the layout `"${ActivityId} ${message}"`, then we store as intermediate (if ActivityId=123), `"123 ${message}"`? So a string. I don't think we can fit that in an object? 

When converting to a string, I think it is then the same as the layout-renderer-wrapper `${force-render:${aspnet-sessionid}}` I proposed before.

**Comment by andersjoh** [comment] 2015-12-22 11:45
I'd have to spend som time with the code, but wouldn't this be possible:
We have a layout "${ac}tivityId} ${aspnet:sessionId} ${message}". This is loaded from config on runtime.
The renderers know if they access thread specific data. If a async / buffered wrapper is specified, the renderers evaluate at the LogEvent, emitting an object with data that is put into, if not the eval to a string at buffer flush.

When the buffer is flushed, each entry in the buffer will contain an array of data needed for the target. Then it should be a simple case of invoking a Write on them to get the string representation? Or am i misunderstanding something. Sorry if this is a hassle, i'll try to find some time to fork and try it out. 

I just figure if you are doing something ASP.NET you'd end up with layouts where everything is wrapped in ${force-render:}, and loosing perf. if they all do string manipulation.

**Comment by TheCloudlessSky** [comment] 2016-01-06 20:50
+1 To solve this problem. For most of our targets, we've had to disable async because they usually use some sort of thread/task-sensitive value (HttpContext etc).

**Comment by 304NotModified** [comment] 2016-01-06 21:11
Indeed, the issue is only with async and/or buffered rendering. 

Too bad we didn;t have time to look at this in more detail. The issue can be solved, but it's unclear what the performance impacts are.

**Comment by TheCloudlessSky** [comment] 2016-01-06 21:24
@304NotModified Do you have any ideas/workarounds for the time being (other that disabling async/buffer)? I saw usage of `[ThreadAgnostic]` on different layour renderers in the source. But if I implement my own `LayoutRenderer`, it is *not* thread agnostic when rendering the layout (without the attribute). I assume it's the Layout's job to detect whether or not the layout renderer should be `Precalculated()`?

**Comment by 304NotModified** [comment] 2016-01-07 07:05
I think this will work as work around : a new target wrapper which renders the logeventinfo and passes it. 

Does this makes sense? If you need any help implementing it,  just let us know :)

**Comment by 304NotModified** [comment] 2016-01-07 07:15
Edit. I think `PrecalculateVolatileLayouts` should already fix this issue, but it is not working then.  So this is a bug. 

This code isn't documented well (yet) so I'm not sure if `PrecalculateVolatileLayouts` is designed for this case. 

Does anyone has an idea if this worked in previous versions of NLog?

**Comment by TheCloudlessSky** [comment] 2016-01-07 13:13
@304NotModified This is exactly what I found after my initial post yesterday.

I actually realized that the logging (the `log.Error()` calls -- not just the Target execution) was happening *outside* of the scope that I wanted logged... so of course the layout renderers weren't going to grab the correct scope. What lead me a stray was coming here to this issue and then thinking it was the problem. One detail I left out was the another app (a web probject that used the exact same async targets) was working as expected with HttpContext. So, I was still puzzled.

The good news is that by *default*, NLog assumes that LayoutRenderers and Layouts are *not* thread agnostic. They have to explicitly marked with `[ThreadAgnostic]`.

Please ignore my initial post because it was an error on my side with configuration. Moving the logging to the correct scope correctly pre-renders the layout before the async wrapper enqueues it for later processing. I'm not sure about @andersjoh though, perhaps it's the same sort of configuration problem?

**Comment by 304NotModified** [comment] 2016-01-07 14:19
So it does work @TheCloudlessSky ?

I see a point with confused me. It should work with layout renders due to the missing `[ThreadAgnostic]`, but I doesn't work with targets which also are bound to the main thread,

eg. [AspNetTrace-target](https://github.com/NLog/NLog.Web/blob/master/NLog.Web/Targets/AspNetTrace.cs), see https://github.com/NLog/NLog/issues/865

**Comment by TheCloudlessSky** [comment] 2016-01-07 15:14
@304NotModified It **does work** for me using Layouts/Layout Renderers.

As you mention something like the `AspNetTraceTarget` wouldn't work when wrapped in async/buffer. I don't think there's an easy way to get around that since it is very thread-sensitive.

For those cases, I think what would be required is to allow and use `[ThreadAgnostic]` for targets as well. And if the async/buffer wrapper calls a target that *isn't* thread-agnostic, it'll ignore async and write a warning to the internal logger. Then, similar to f405c7e62be5582157fde761606b7edd5fd847fa, mark all possible Targets as `[ThreadAgnostic]`. I'd consider this a breaking change since anyone implementing their own Target and wanting to opt-in to async would need to be aware of using `[ThreadAgnostic]`.

**Comment by TheCloudlessSky** [comment] 2016-01-07 15:20
@304NotModified I also think you may be mistaken in https://github.com/NLog/NLog/issues/865#issuecomment-169679822 and #1136 since `[ThreadAgnostic]` (and thus `IsThreadAgnostic`) is not used **on** `Target` (it's used *within* a target via the Layouts).

**Comment by 304NotModified** [comment] 2016-01-07 19:31
I think your right. Didn't checked the isthreadagnostic usage yet. 

The target implementation needs to be backwards compatible, so opt out. We can fix that with a virtual property instead of attribute

**Comment by 304NotModified** [comment] 2016-01-12 22:01
> Please ignore my initial post because it was an error on my side with configuration. Moving the logging to the correct scope correctly pre-renders the layout before the async wrapper enqueues it for later processing. I'm not sure about @andersjoh though, perhaps it's the same sort of configuration problem?

@andersjoh is it already working for you?

**Comment by andersjoh** [comment] 2016-01-13 08:45
Sorry i got moved to another project and nuked my computer. Can't test right now, i'll see if i can get the new owner to take some time with me to try it out. 
For reference our current config looks like this. 
```
  <nlog>
    <extensions>
      <add prefix="bom" assembly="Kombit.BygOgMiljoe.Common.System" />
      <add assembly="NLog.Targets.ElasticSearch" />
    </extensions>
    <variable name="logPath" value="c:/logs" />
    <variable name="applicationName" value="PublicWeb" />
    <targets>
      <target name="elastic" type="BufferingWrapper" flushTimeout="5000">
        <target type="ElasticSearch" uri="http://localhost:9200" layout="${logger}|${message}">
          <field name="correlationId" layout="${bom.correlationid}" />
          <field name="userIp" layout="${bom.ipaddress}" />
          <field name="host" layout="${machinename}" />
          <field name="sessionId" layout="${bom.sessionid}" />
          <field name="userIdentification" layout="${bom.userIdentification}" />
          <field name="application" layout="${applicationName}" />
          <field name="MeasuredTarget" layout="${event-context:item=MeasuredTarget}" />
          <field name="MeasuredTimeInMilliseconds" layout="${event-context:item=MeasuredTimeInMilliseconds}" />
          <field name="MeasureStartTime" layout="${event-context:item=MeasureStartTime}" />
        </target>
      </target>
      <target type="File" name="audit" fileName="${logPath}/bygogmiljoe-publicweb--${machinename}--AUDIT--${shortdate}.log" layout="${longdate}|${logger}|${bom.ipaddress}|aspnetsessionid:${bom.sessionid}|${bom.userIdentification}|${bom.correlationid}|${ThreadId}|${uppercase:${level}}|${message}|${onexception:EXCEPTION:${exception:format=tostring}}" />
      <target type="File" name="f" fileName="${logPath}/bygogmiljoe-publicweb--${machinename}--${shortdate}.log" layout="${longdate}|${logger}|${bom.ipaddress}|aspnetsessionid:${bom.sessionid}|${bom.userIdentification}|${bom.correlationid}|${ThreadId}|${uppercase:${level}}|${message}|${onexception:EXCEPTION:${exception:format=tostring}}|${event-context:item=MeasuredTarget}|${event-context:item=MeasuredTimeInMilliseconds}|${event-context:item=MeasureStartTime}" />
    </targets>
    <rules>
      <logger name="*" minlevel="Trace" writeTo="elastic" />
      <!-- audit logger must be first and final in order to audit log statements not to appear in the f log (System log)-->
      <logger name="audit" final="True" minLevel="Trace" writeTo="audit" />
      <logger name="*" minlevel="Info" writeTo="f" />
    </rules>
  </nlog>
```

**Comment by 304NotModified** [comment] 2016-01-16 11:26
OK, just let us know if it's still a problem. I think this should be an issue now. Will try to add some unit tests for it

**Comment by 304NotModified** [comment] 2016-02-03 15:33
I will close this as I see it's working from testresults. 

@andersjoh if you still experience problems, please open a new Github issue.

**Closed by 304NotModified** 2016-02-03 15:33 UTC
Labels: invalid
