### ISSUE TITLE
Add Layout property to WebServiceTarget

### ISSUE THREAD

**Issue by mniak** [NLog/NLog#2589] opened 2018-02-21 20:29 UTC
**Type**: Feature request
**NLog version**: any
**Platform**: any

I suggest creating a `HttpTarget` or enhancing the `WebServiceTarget` to enable specifing a layout for the entire body of a HTTP request.

Example (desired):
```xml
<target type="WebService" name="http" url="http://localhost:9093">
  <protocol>JsonPost</protocol>
  <layout xsi:type="JsonLayout" includeAllProperties="true"> <!-- This property (layout) cannot be specified today -->
    <attribute name="timestamp"   layout="${longdate}"                 />
    <attribute name="level"       layout="${level}"                    />
    <attribute name="logger"      layout="${logger}"                   />
    <attribute name="message"     layout="${message}"                  />
    <attribute name="exception"   layout="${exception:format=tostring}"/>
    <attribute name="thread_name" layout="${threadid}"                 />
    <attribute name="thread_id"   layout="${threadname}"               />
  </layout>
</target>
```

This shows very useful when using structured logging.

I'll try to create a prototype and send a pull request.

**Comment by snakefoot** [comment] 2018-02-21 21:58
Duplicate of #1905

**Comment by snakefoot** [comment] 2018-02-21 22:02
Think a simple "hack" would be for `JsonPost` to recognize that when the a single parameter with empty-name, then it doesn't have to wrap the JsonResult with a Parameter-name.

The problem with WebServiceTarget is that it tries to be everything. Notice how `XmlPost` is missing the ability to provide a root-name (Mainly because the NLog-core is missing a XmlLayout)

**Comment by snakefoot** [comment] 2018-02-21 23:06
@mniak Made an example of my suggestion here: #2590 (Maybe you can dream up a unit-test?)

**Comment by snakefoot** [comment] 2018-02-22 07:22
Maybe you can do a manual test with this custom build:

https://ci.appveyor.com/project/nlog/nlog/build/4.5.0-beta7219/artifacts

Notice the use of nameless parameter:

```
<target type="WebService" name="http" url="http://localhost:9093">
  <protocol>JsonPost</protocol>
  <parameter name="">
  <layout xsi:type="JsonLayout" includeAllProperties="true">
    <attribute name="timestamp"   layout="${longdate}"                 />
    <attribute name="level"       layout="${level}"                    />
    <attribute name="logger"      layout="${logger}"                   />
    <attribute name="message"     layout="${message}"                  />
    <attribute name="exception"   layout="${exception:format=tostring}"/>
    <attribute name="thread_name" layout="${threadid}"                 />
    <attribute name="thread_id"   layout="${threadname}"               />
  </layout>
  </parameter>
</target>
```

**Comment by 304NotModified** [comment] 2018-04-06 22:32
Closing this on as it's a duplicate

**Closed by 304NotModified** 2018-04-06 22:32 UTC
Labels: duplicate, feature, webservice-target
