### ISSUE TITLE
NLog Starts logging but then stops

### ISSUE THREAD

**Issue by joshuaashton** [NLog/NLog#3709] opened 2019-11-27 15:02 UTC
NLog version: 4.6.8

Platform: .Net 4.5.1

Current NLog config:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Trace" internalLogFile="c:\temp\nlog-internal.log">

  <targets>
    <target name="debugger"
            xsi:type="Debugger"
            layout="${date:format=HH\:mm\:ss}|${level}|${message}"
            />
    <target name="activityLogFile"
            xsi:type="File"
            fileName="${specialfolder:folder=CommonApplicationData}/LL/TQC/Logs/Activity/${shortdate}.txt"
            layout="${date} (Thread: ${threadid} - ${threadname:whenEmpty=${literal:text=Worker}}) - (${level}) => ${message} ${exception:format=toString,Data:exceptionDataSeparator=\r\n:maxInnerExceptionLevel=10}"
            />
    <target name="errorLogFile"
            xsi:type="File"
            fileName="${specialfolder:folder=CommonApplicationData}/LL/TQC/Logs/Error/${shortdate}.txt"     
            layout="${date} (Thread: ${threadid} - ${threadname:whenEmpty=${literal:text=Worker}}) - (${level}) => ${message} ${exception:format=toString,Data:exceptionDataSeparator=\r\n:maxInnerExceptionLevel=10}"
            />
  </targets>

  <rules>
    <logger name="*" writeTo="debugger" minlevel="Trace"  />
    <logger name="*" writeTo="errorLogFile" minlevel="Error"  />
    <logger name="*" writeTo="activityLogFile" minlevel="Info" maxlevel="Warn" />
  </rules>
</nlog>
````

I've been using NLog for a while with no issues but our QA department noticed something yesterday when testing which I've not seen before. It would appear that NLog started logging correctly as usual but then, after restarting the app, it never started writing to the file again. I was unsure if some internal errors were occurring so i enabled internal logging however then i saw some unusual repeated logs with the message below (internal logs attached).

```
2019-11-27 14:40:24.7270 Trace Opening C:\ProgramData\LL\TQC\Logs\Activity\2019-11-27.txt with allowFileSharedWriting=False
```

Another note worth point is that i noticed deleting the file it created, but was unable to append to after restarting the software, seemed to make it work again. I can also see from the logs that i've got 'allowFileSharedWriting=false'.. is it possible that upon closing the app NLog didn't close correctly and then was unable to open it again because of this setting (essentially locking the file)?

Any support is greatly appreciated. 

Thanks!
[nlog-internal.log](https://github.com/NLog/NLog/files/3897388/nlog-internal.log)

**Comment by joshuaashton** [comment] 2019-11-27 15:03
Sorry.. it seemed to not include my config file!

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Trace" internalLogFile="c:\temp\nlog-internal.log">

  <targets>
    <target name="debugger"
            xsi:type="Debugger"
            layout="${date:format=HH\:mm\:ss}|${level}|${message}"
            />
    <target name="activityLogFile"
            xsi:type="File"
            fileName="${specialfolder:folder=CommonApplicationData}/LabLogic/TracerQC/Logs/Activity/${shortdate}.txt"
            layout="${date} (Thread: ${threadid} - ${threadname:whenEmpty=${literal:text=Worker}}) - (${level}) => ${message} ${exception:format=toString,Data:exceptionDataSeparator=\r\n:maxInnerExceptionLevel=10}"
            />
    <target name="errorLogFile"
            xsi:type="File"
            fileName="${specialfolder:folder=CommonApplicationData}/LabLogic/TracerQC/Logs/Error/${shortdate}.txt"     
            layout="${date} (Thread: ${threadid} - ${threadname:whenEmpty=${literal:text=Worker}}) - (${level}) => ${message} ${exception:format=toString,Data:exceptionDataSeparator=\r\n:maxInnerExceptionLevel=10}"
            />
  </targets>

  <rules>
    <logger name="*" writeTo="debugger" minlevel="Trace"  />
    <logger name="*" writeTo="errorLogFile" minlevel="Error"  />
    <logger name="*" writeTo="activityLogFile" minlevel="Info" maxlevel="Warn" />
  </rules>
</nlog>

**Comment by 304NotModified** [comment] 2019-11-27 15:35
> Sorry.. it seemed to not include my config file!

It's there, but you need a triple backtrick :) Fixed in the opening post

**Comment by 304NotModified** [comment] 2019-11-27 15:37
@snakefoot any idea? Maybe testing with an older version of NLog? (which one?)

**Comment by snakefoot** [comment] 2019-11-27 19:45
No idea. But also very limited clues for how to reproduce the issue. Could also be the application crashed/blocked and that is why it was not writing.

When looking in the attached nlog-internal.log:

2019-11-27 14:36:21.8738 Application starts
2019-11-27 14:36:21.9785 Application changes/reloads NLog.config (why is that?)
2019-11-27 14:36:22.2278 Application ready
2019-11-27 14:36:46.5267 Application writes first log-entry to "activityLogFile"
2019-11-27 14:39:04.4546 Application writes last log-entry to "activityLogFile"
2019-11-27 14:39:04.4546 Application writes first log-entry to "errorLogFile" (Did the app break?)
2019-11-27 14:39:15.4356 Application shutdown

2019-11-27 14:40:03.5285 Application starts
2019-11-27 14:40:03.9777 Application ready
2019-11-27 14:40:04.0006 Application writes first log-entry to "activityLogFile"
2019-11-27 14:43:40.1592 Application writes last log-entry to "activityLogFile"
2019-11-27 14:43:53.4377 Application writes first log-entry to "errorLogFile" (Did the app break?)
2019-11-27 14:43:54.3419 Application shutdown

The multiple entries saying:

`Trace Opening C:\ProgramData\LabLogic\TracerQC\Logs\Activity\2019-11-27.txt with allowFileSharedWriting=False`

Is just because you are using `keepFileOpen="true"` so NLog opens/closes the file for each logevent

**Comment by snakefoot** [comment] 2019-12-01 20:34
@joshuaashton Can you add some details about the 2 startups. In the first case the app stops 10 sec after the error-event. In the second case the app stops 1 sec after the error-event.

10 secs and 1 secs is not a "very" long time. How long did it take for the QA department to detect that the App had stopped logging? (Hats off for a QA department that reacts to pauses in the time-range of seconds).

**Closed** 2019-12-09 18:58 UTC
Labels: file-target, needs info
