### ISSUE TITLE
Allow loading configuration from a string instead of file

### ISSUE THREAD

**Issue by jjxtra** [NLog/NLog#2819] opened 2018-07-30 17:04 UTC
Please allow loading config from a string rather than file.

Use case: framework that needs to do it's own logging but doesn't want to require an nlog or app config file to be brought along with in deployment.

**Comment by snakefoot** [comment] 2018-07-30 23:15
Looks like a duplicate of #2820. Maybe close the other?

If you load the string into a `XmlDocument` then it should work nicely:

https://github.com/nlog/NLog/wiki/Explicit-NLog-configuration-loading

**Comment by jjxtra** [comment] 2018-07-31 02:47
That doesn't compile on .NET core

**Comment by snakefoot** [comment] 2018-07-31 06:09
> That doesn't compile on .NET core. I have an xml reader option and a string file name option as the two parameters...

What is the build-error? Remember I'm not sitting next to you :)

**Comment by jjxtra** [comment] 2018-08-01 22:29
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'System.Xml.XmlElement' to 'string'
Error	CS1503	Argument 2: cannot convert from 'string' to 'NLog.LogFactory'

System.Xml.XmlDocument xmlDoc = new System.Xml.XmlDocument();
xmlDoc.LoadXml(Resources.nlog_config); // this is a string
string currentDir = System.IO.Directory.GetCurrentDirectory();
NLog.LogManager.Configuration = new NLog.Config.XmlLoggingConfiguration(xmlDoc.DocumentElement, currentDir);
```

**Comment by jjxtra** [comment] 2018-08-01 22:30
Looking at the code I am only seeing XmlReader overloads. However those also ask for a filename which seems odd. I tried using the XmlReader methods and wrapping my config string with an xml text reader but that didn't work either.

**Comment by snakefoot** [comment] 2018-08-01 22:33
Sorry my mistake. Redirected you to an internal method. Try this instead:

```C#
                System.IO.StringReader sr = new System.IO.StringReader(xmlString);
                System.Xml.XmlReader xr = System.Xml.XmlReader.Create(sr);
                NLog.LogManager.Configuration = new NLog.Config.XmlLoggingConfiguration(xr, null);
```

Will update the wiki

**Comment by jjxtra** [comment] 2018-08-01 22:53
I would add the last lines needed to create a logger:

```csharp
LogFactory factory = LogManager.LogFactory;
Logger logger = factory.GetCurrentClassLogger();
```

**Comment by 304NotModified** [comment] 2018-08-02 09:44
we will add a helper to NLog in the future

**Comment by snakefoot** [comment] 2018-08-02 09:50
Maybe one day the XmlConfig will not be part of Nlog-Core



Sent from my Samsung device


-------- Original message --------

**Closed** 2018-11-07 22:11 UTC
Labels: feature
