### ISSUE TITLE
Error:  System.TypeInitializationException

### ISSUE THREAD

**Issue by GCClaudio** [NLog/NLog#1052] opened 2015-11-17 14:36 UTC
Hello to all,
I've tried to define a database target, but iI've always the error: System.TypeInitializationException.
In the NLog. config with the follow simply target:
 <target xsi:type="Database" name="db"> I've the error, but with no attribute name, like:
 <target xsi:type="Database">  
it's ok.

My really target config is:

<target xsi:type="Database" name="db"
      connectionString="Data Source=MyDb Source;Initial Catalog=MyDb;User=MyUser;Password=MyPwd"
          keepConnection="true"
          commandText=" insert into LOG (
      Application, Level, Message,
      Username,
      ServerName, Logger, CallSite, Exception, StackTrace
    ) values (
      @Application, @Level, @Message,
      @Username,
      @ServerName, @Logger, @Callsite, @Exception,@stacktrace);"   
     commandType="Text">
    <parameter name="@application" layout="${appsetting:name=AppName:default=Unknown\: set AppName in appSettings}"></parameter>
    <parameter name="@level" layout="${level}" />
    <parameter name="@message" layout="${message}" />
    <parameter name="@username" layout="${identity}" />
    <parameter name="@serverName" layout="${aspnet-request:serverVariable=SERVER_NAME}" />
    <parameter name="@logger" layout="${logger}" />
    <parameter name="@callSite" layout="${callsite}" />
    <parameter name="@exception" layout="${exception:tostring}" />
    <parameter name="@stacktrace" layout="${stacktrace}"/>
    </target>

I've tried with NLog 4.1.0 / 4.2.0 with .net framework 4.0 (windows form application)

Thank's very much for any help
Claudio

**Comment by 304NotModified** [comment] 2015-11-17 19:10
Can you check the inner exception? That one tells the cause of this. (some static field which crashes)

**Comment by GClaudio** [comment] 2015-11-18 14:30
HI, you can see the attached file.

[NLog_Error.docx](https://github.com/NLog/NLog/files/37933/NLog_Error.docx)

Thank's,
Claudio

**Comment by 304NotModified** [comment] 2015-11-18 14:52
So the error is: layoutrender cannot found 'appsetting`.

You need also NLog.extended for that (see [wiki](https://github.com/NLog/NLog/wiki/Layout-Renderers)).  Just install the latest https://www.nuget.org/packages/NLog.Extended/ - no additional config is needed.

Ps. I removed your docx with a screenshot

**Comment by GClaudio** [comment] 2015-11-18 17:23
Hello, 

ok now it's running,r, thank's ! 

But when a call Log, after an error (try catch), I haven't the row in my
table db, which my mistake ? 

I didn't found some examples for windows form with database target.... 

Claudio 

Il 2015-11-18 15:52 Julian Verdurmen ha scritto: 

> So the error is: layoutrender cannot found 'appsetting`. 
> 
> You need also NLog.extended for that (see wiki [1]). Just install the latest https://www.nuget.org/packages/NLog.Extended/ [2] - no additional config is needed. 
> 
> Ps. I removed your docx with a screenshot 
> 
> --
> Reply to this email directly or view it on GitHub [3].

-- 

CLAUDIO ORLANDI

 IT Software

Indicom s.r.l. - Via Carnevali 39 - 20158 Milano 

E-MAIL: claudio.orlandi@indicom.biz

WEB: www.indicom.biz [4] - www.fatturafacile.com [5] 

Links:
------
[1] https://github.com/NLog/NLog/wiki/Layout-Renderers
[2] https://www.nuget.org/packages/NLog.Extended/
[3] https://github.com/NLog/NLog/issues/1052#issuecomment-157738316
[4] http://www.indicom.biz
[5] http://www.fatturafacile.com

**Comment by 304NotModified** [comment] 2015-11-18 17:38
> But when a call Log, after an error (try catch), I haven't the row in my
> table db, which my mistake ?

Please check the internal log: https://github.com/NLog/NLog/wiki/Internal-Logging


> I didn't found some examples for windows form with database target....

Everything is modular, so there are no special requirements to combine Windows.Forms + Database Target. This should work.

**Comment by GClaudio** [comment] 2015-11-19 11:04
Hi Julian, 

it works perfectly !! With internal log I found some error on NLog db
parameters definition 

Thank You very much. 

Claudio 

Il 2015-11-18 18:38 Julian Verdurmen ha scritto: 

>> But when a call Log, after an error (try catch), I haven't the row in my
>> table db, which my mistake ?
> 
> Please check the internal log: https://github.com/NLog/NLog/wiki/Internal-Logging [1] 
> 
>> I didn't found some examples for windows form with database target....
> 
> Everything is modular, so there are no special requirements to combine Windows.Forms + Database Target. This should work. 
> 
> --
> Reply to this email directly or view it on GitHub [2].

-- 

CLAUDIO ORLANDI

 IT Software

Indicom s.r.l. - Via Carnevali 39 - 20158 Milano 

E-MAIL: claudio.orlandi@indicom.biz

WEB: www.indicom.biz [3] - www.fatturafacile.com [4] 

Links:
------
[1] https://github.com/NLog/NLog/wiki/Internal-Logging
[2] https://github.com/NLog/NLog/issues/1052#issuecomment-157792591
[3] http://www.indicom.biz
[4] http://www.fatturafacile.com

**Comment by 304NotModified** [comment] 2015-11-19 12:41
OK closing this one :)

Thanks for the feedback!

**Closed by 304NotModified** 2015-11-19 12:41 UTC
Labels: question
