### ISSUE TITLE
System.TypeInitializationException from missing variable in configuration

### ISSUE THREAD

**Issue by ShaneCourtrille** [NLog/NLog#1097] opened 2015-12-18 22:25 UTC
I have a Console application with the following target:

`		<target xsi:type="ColoredConsole"
						name="console"
						layout="${NormalLayout}"/>`

When I start my application I receive the following exception:

System.TypeInitializationException was unhandled
Message: An unhandled exception of type 'System.TypeInitializationException' occurred in mscorlib.dll
Additional information: The type initializer for 'ServiceHostConsole.Program' threw an exception.

The dialog that VS 2015 gives me is a bit odd and there is no way to access the inner exception.  I turned on logging in NLog at Trace level but I don't see any problems reported.  

I realized that I forgot to declare the NormalLayout variable but I'm still surprised by the exception I received and how unhelpful it was.

**Comment by 304NotModified** [comment] 2015-12-18 23:34
Hi,



> The dialog that VS 2015 gives me is a bit odd and there is no way to access the inner exception.

I should be possible to check the inner exception in VS. You can also use the quickwatch. It's really important to check the inner exception, because that's the only good way to find the real problem.

There is a big change that the issue isn't in NLog. That the error is reported when NLog is enabled, is just a result of NLog being initialized really early. We also cannot catch that exception. For example, this following code  can raise the same exception:

```c#
class test
{
   static string _test = null.ToString();
}
```

**Comment by 304NotModified** [comment] 2015-12-29 23:22
@ShaneCourtrille can you give us some more info?

**Comment by 304NotModified** [comment] 2016-02-25 23:24
This has been fixed in Nlog 4.3 with https://github.com/NLog/NLog/pull/1238

**Closed by 304NotModified** 2016-02-25 23:24 UTC
Labels: needs info, question
