### ISSUE TITLE
Daily file log rotation not working on medium volume logging activity under mono

### ISSUE THREAD

**Issue by bpress** [NLog/NLog#2737] opened 2018-05-24 08:18 UTC
**Type**: Bug
**NLog version**: 4.5.4
**Platform**: Mono 4
**Current NLog config**

```c#
LoggingConfiguration config = new LoggingConfiguration();
AsyncTargetWrapper logfile = new AsyncTargetWrapper(
	new FileTarget() { 
		Name = "file",
		Layout = new SimpleLayout("${longdate} ${event-properties:item=timer}[${level}:${threadid}:${event-properties:item=method}:${event-properties:item=context}] ${message}"),
		Encoding = Encoding.UTF8,
		FileName = "/....somepath..../alert.log",
		ArchiveNumbering = ArchiveNumberingMode.Date,
		ArchiveEvery = FileArchivePeriod.Day,
		ArchiveDateFormat = "yyyyMMdd",
		KeepFileOpen = true,
		OpenFileCacheTimeout = 10
	},
	256,
	AsyncTargetWrapperOverflowAction.Discard
);
config.LoggingRules.Add(new LoggingRule("main", LogLevel.Info, logfile));
LogManager.Configuration = config;
```

In case of a BUG:

- What is the current result?
On one node where the average logged lines per second is above 4, after midnight the file is not rotated

- What is the expected result?
There should be a new file named alert.log and a previous one named for instance alert.20180523.log

- Did you checked the [Internal log]?
Not yet, I need to set up a separate test environment in order to do so

- Please post full exception details (message, stacktrace, inner exceptions)
No exceptions thrown or involved

- Are there any workarounds?
Well of course I could use unix tricks to rotate logs just like logrotate

- Is there a version in which it did work? 
This is the first time I'm using nlog

- Can you help us by writing an unit test?
Yes if necessary

**Comment by bpress** [comment] 2018-05-25 14:27
Sorry for the delay in replying but I had to setup a dedicated test environment in order not to break my live servers.

I've created a simple c# console process that spawns 200 threads, each one of them logging a random 64-character string at WARN level every 5 seconds (that makes a total of about 40 lines per second).

The process is writing to a file named /opt/console/test.log, which is not rotated after 00:00AM.

Here is an internal trace log extract around midnight:

```
2018-05-25 23:59:59.6701 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-25 23:59:59.7204 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-25 23:59:59.7707 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-25 23:59:59.8210 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-25 23:59:59.8713 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-25 23:59:59.9217 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-25 23:59:59.9720 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-26 00:00:00.0225 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-26 00:00:00.0733 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-26 00:00:00.0736 Trace FileTarget(Name=file): Archive attempt for file '/opt/console/test.log'
2018-05-26 00:00:00.0736 Debug FileAppender Closing Invalidate - /opt/console/test.log
2018-05-26 00:00:00.0736 Debug Stopping file watching for path '/opt/console' filter 'test.*.log'
2018-05-26 00:00:00.0736 Debug Stopping file watching for path '/opt/console' filter 'test.log'
2018-05-26 00:00:00.0744 Trace Closing '/opt/console/test.log'
2018-05-26 00:00:00.0744 Trace FileTarget(Name=file): Archive already performed for file '/opt/console/test.log'
2018-05-26 00:00:00.0744 Debug FileTarget(Name=file): Process file '/opt/console/test.log' on startup
2018-05-26 00:00:00.0753 Debug Creating file appender: /opt/console/test.log
2018-05-26 00:00:00.0753 Trace Opening /opt/console/test.log with allowFileSharedWriting=True
2018-05-26 00:00:00.0753 Debug Watching path '/opt/console' filter 'test.*.log' for changes.
2018-05-26 00:00:00.0753 Debug Watching path '/opt/console' filter 'test.log' for changes.
2018-05-26 00:00:00.1264 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-26 00:00:00.1768 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-26 00:00:00.2272 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-26 00:00:00.2776 Trace AsyncWrapper(Name=): Writing 2 events (Timer)

```

**Comment by snakefoot** [comment] 2018-05-25 16:18
This line:

`Archive already performed for file '/opt/console/test.log'`

Indicates NLog suddenly receives a different timestamp from the file after it has closed its filehandle. 

Maybe it is caused by `AutoFlush = false`, so when NLog closes the file to archive the file, then it perform one last file-write to flush. Because not all Linux instances support file-birth-time, then NLog will perform fallback to last-file-write-time.

Maybe NLog could have some bonus logic, that if using `ConcurrentWrites = false`, then instead of doing fallback to last-file-write-time, then it will do fallback to previousLogEventTimestamp.

Again all this is just random guessing.

**Comment by snakefoot** [comment] 2018-05-27 21:59
@bpress It would really help if you could exercise this pre-release-build on your setup:

https://ci.appveyor.com/project/nlog/nlog/build/4.5.0-7857/artifacts

Remember to configure both `KeepFileOpen=true` AND `concurrentWrites=false` (If you need `concurrentWrites=true` then this pre-release-build will not help).

**Comment by bpress** [comment] 2018-05-28 06:51
@snakefoot 

I've recompiled and re-run the test app with the suggested pre-release build and now it seems to handle rotation properly. The test was repeated 3 times resetting the clock at 23:59.

Here's the piece of internal log from one of the runs:

```
2018-05-27 23:59:59.9393 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-27 23:59:59.9895 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-28 00:00:00.0398 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-28 00:00:00.0398 Trace FileTarget(Name=file): Archive attempt for file '/opt/console/test.log'
2018-05-28 00:00:00.0407 Debug FileAppender Closing Invalidate - /opt/console/test.log
2018-05-28 00:00:00.0407 Debug Stopping file watching for path '/opt/console' filter 'test.log'
2018-05-28 00:00:00.0686 Trace Closing '/opt/console/test.log'
2018-05-28 00:00:00.0700 Debug FileTarget(Name=file): Do archive file: '/opt/console/test.log'
2018-05-28 00:00:00.0700 Trace FileTarget(Name=file): Archive pattern '/opt/console/test.log'
2018-05-28 00:00:00.0728 Trace FileTarget(Name=file): Calculating archive date. File-LastModifiedUtc: 05/27/2018 21:59:59; Previous LogEvent-TimeStamp: 05/27/2018 23:59:59
2018-05-28 00:00:00.0728 Trace FileTarget(Name=file): Using previous log event time (is more recent)
2018-05-28 00:00:00.0746 Trace FileTarget(Name=file): FinalizeFile '/opt/console/test.log, isArchiving: True'
2018-05-28 00:00:00.0778 Info FileTarget(Name=file): Archiving /opt/console/test.log to /opt/console/test.20180527.log
2018-05-28 00:00:00.0778 Debug FileTarget(Name=file): Move file from '/opt/console/test.log' to '/opt/console/test.20180527.log'
2018-05-28 00:00:00.0778 Debug FileTarget(Name=file): Process file '/opt/console/test.log' on startup
2018-05-28 00:00:00.0784 Debug Creating file appender: /opt/console/test.log
2018-05-28 00:00:00.0784 Trace Opening /opt/console/test.log with allowFileSharedWriting=False
2018-05-28 00:00:00.0784 Debug Watching path '/opt/console' filter 'test.log' for changes.
2018-05-28 00:00:00.1294 Trace AsyncWrapper(Name=): Writing 3 events (Timer)
2018-05-28 00:00:00.1797 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-28 00:00:00.2300 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
```

**Comment by bpress** [comment] 2018-05-30 07:33
@snakefoot I've run again the console application with version 4.5.6 and everything works just fine.
I've successfully tried both with and without internal logging.

This, for reference, is the extract from internal log:

```
2018-05-30 00:00:00.0655 Trace AsyncWrapper(Name=): Writing 2 events (Timer)
2018-05-30 00:00:00.0655 Trace FileTarget(Name=file): Archive attempt for file '/opt/console/test.log'
2018-05-30 00:00:00.0655 Debug FileAppender Closing Invalidate - /opt/console/test.log
2018-05-30 00:00:00.0667 Debug Stopping file watching for path '/opt/console' filter 'test.log'
2018-05-30 00:00:00.0922 Trace Closing '/opt/console/test.log'
2018-05-30 00:00:00.0930 Debug FileTarget(Name=file): Adjusted file creation time from 05/30/2018 00:00:00 to 05/29/2018
 23:59:59. Linux FileSystem probably don't support file birthtime.
2018-05-30 00:00:00.0944 Debug FileTarget(Name=file): Do archive file: '/opt/console/test.log'
2018-05-30 00:00:00.0946 Trace FileTarget(Name=file): Archive pattern '/opt/console/test.log'
2018-05-30 00:00:00.0971 Trace FileTarget(Name=file): Calculating archive date. File-LastModifiedUtc: 05/29/2018 22:00:0
0; Previous LogEvent-TimeStamp: 05/29/2018 23:59:59
2018-05-30 00:00:00.0980 Trace FileTarget(Name=file): Using previous log event time (previous log overlapped period)
2018-05-30 00:00:00.0996 Trace FileTarget(Name=file): FinalizeFile '/opt/console/test.log, isArchiving: True'
2018-05-30 00:00:00.1029 Info FileTarget(Name=file): Archiving /opt/console/test.log to /opt/console/test.20180529.log
2018-05-30 00:00:00.1029 Debug FileTarget(Name=file): Move file from '/opt/console/test.log' to '/opt/console/test.20180
529.log'
2018-05-30 00:00:00.1036 Debug FileTarget(Name=file): Process file '/opt/console/test.log' on startup
2018-05-30 00:00:00.1036 Debug Creating file appender: /opt/console/test.log
2018-05-30 00:00:00.1036 Trace Opening /opt/console/test.log with allowFileSharedWriting=False
2018-05-30 00:00:00.1046 Debug Watching path '/opt/console' filter 'test.log' for changes.
2018-05-30 00:00:00.1549 Trace AsyncWrapper(Name=): Writing 4 events (Timer)
```

Today I will be canary-testing in production environment.
Thanks a lot for resolving so fast!

**Comment by 304NotModified** [comment] 2018-05-30 18:45
👍 thanks for the feedback, @snakefoot thanks for the fix!

**Closed by 304NotModified** 2018-05-30 18:45 UTC
Labels: file-target, needs info
