### ISSUE TITLE
NLog.config not found in asp.net app running from UNC path

### ISSUE THREAD

**Issue by fiss7** [NLog/NLog#843] opened 2015-08-12 12:50 UTC
NLog version : 4.0.0.1
Exception: System.TypeInitializationException
```
Error message : "The type initializer for 'NLog.Config.ConfigurationItemFactory' threw an exception."
StackTrace :  at NLog.Config.XmlLoggingConfiguration..ctor(String fileName)
   at NLog.LogFactory.LoadLoggingConfiguration(String configFile)
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogManager.GetCurrentClassLogger()
   at XCMS.Logging.NLogImpl.LogEngineWrapper..ctor()
   at XCMS.Logging.NLogImpl.LogEngine..cctor()

InnerException: System.IO.DirectoryNotFoundException

Message: Could not find a part of the path 'c:\www\develop\bin'.
StackTrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption, Boolean checkHost)
   at System.IO.Directory.InternalGetFiles(String path, String searchPattern, SearchOption searchOption)
   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
   at NLog.Config.ConfigurationItemFactory..cctor()
```
-------------------------------
Hi,

This error occured when calling :
```
LogManager.GetCurrentClassLogger()
```
The sources of the ASP.NET application is located on a network shared folder like this : "\\server\www\develop\bin" ; but NLog seems to look for NLog.config file in "c:\www\develop\bin" which does not exist and throw this exception.

Any ideas ?
Thanks.

**Comment by 304NotModified** [comment] 2015-08-12 19:01
This is a know bug and already solved. It will be released with 4.1

**Comment by fiss7** [comment] 2015-08-12 19:37
Ok, thank you a lot for your quick answer. 
Is there any estimated release date for 4.1 ?
Shall I close this Issue ?

**Comment by 304NotModified** [comment] 2015-08-12 21:18
2-3 weeks from now.

**Comment by 304NotModified** [comment] 2015-08-12 21:19
I will close when we released it :)

**Comment by fiss7** [comment] 2015-08-12 21:20
Ok, thanks a lot ! :)

**Comment by 304NotModified** [comment] 2015-08-13 20:47
duplicate of https://github.com/NLog/NLog/issues/793

**Comment by gliljas** [comment] 2015-08-27 07:08
4.1.0-rc1 did not contain the fix. Error in packaging?

**Comment by 304NotModified** [comment] 2015-08-27 12:55
@gliljas  OK, thanks for testing. Then it isn't solved yet. Does it work in NLog 4.0.0 (it's broken in 4.0.1)

**Comment by gliljas** [comment] 2015-08-27 14:12
Sorry. The fault was with VS2015's NuGet update which claimed success, but didn't update the reference.

**Comment by 304NotModified** [comment] 2015-08-29 19:50
but is this now fixed in 4.1?

**Comment by 304NotModified** [comment] 2015-08-29 19:50
I checking this now, but can't reproduce

**Comment by 304NotModified** [comment] 2015-08-29 19:52
@gliljas a response ASAP would be great, a this issue blocks the release of 4.1. Thanks in advance!

**Comment by gliljas** [comment] 2015-08-29 21:23
It is fixed!

**Comment by 304NotModified** [comment] 2015-08-29 21:24
Great! 

Thanks for the fast feedback!

**Closed** 2015-08-29 21:35 UTC
Labels: almost ready, bug, must have

**Comment by 304NotModified** [comment] 2015-08-31 17:35
4.1 has been released!
