### ISSUE TITLE
Unexpected behavior with dbType="DateTime" VS dbType="DateTime2" using Postgres

### ISSUE THREAD

**Issue by CooperZuranskiSEP** [NLog/NLog#5663] opened 2024-11-12 20:45 UTC
**NLog version**: 5.3.4, DB:5.3.4, Npgsql:8.0.5

**Platform**: .NET8

**Current NLog config** (This is just the relevant portion)
```xml
<target name="postgresDb" 
                xsi:type="Database"
                dbProvider="Npgsql.NpgsqlConnection, Npgsql"
                connectionString="..."
                commandType="StoredProcedure"
                commandText="public.insert_log_entry">        
            <parameter name="@p_timestamp" layout="${longdate}" dbType="DateTime2" />
            <parameter name="@p_timestamp2" layout="${longdate:universalTime=true}" dbType="DateTime" />
</target>
```

![image](https://github.com/user-attachments/assets/e1ad3240-a4e3-4b02-98e7-27bd0fe9d39f)

- What is the current result?
  - The above snippet is what works 
  - my stored procedure/col types do not care whether they are `TIMESTAMP` or `TIMESTAMPTZ` (with timezone always assumes +00, which also seems odd)
- What is the expected result?
   - Changing db type should change precision, not timezone compatibility, as per [DbType](https://learn.microsoft.com/en-us/dotnet/api/system.data.dbtype?view=net-8.0) 
   - I should have less precision where using p_timestamp2, and i should be able to use either dbtype regardless of universal time
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  - If i use universalTime:true and DateTime2 in conjunction, the error is the following:
```
Error DatabaseTarget(Name=postgresDb_wrapped): Error when writing to database. Exception: System.ArgumentException: Cannot write DateTime with Kind=UTC to PostgreSQL type 'timestamp without time zone', consider using 'timestamp with time zone'. Note that it's not possible to mix DateTimes with different Kinds in an array, range, or multirange. (Parameter 'value')
   at Npgsql.Internal.Converters.DateTimeConverterResolver`1.Get(DateTime value, Nullable`1 expectedPgTypeId, Boolean validateOnly)
   at Npgsql.Internal.Converters.DateTimeConverterResolver.<>c.<CreateResolver>b__0_0(DateTimeConverterResolver`1 resolver, DateTime value, Nullable`1 expectedPgTypeId)
   at Npgsql.Internal.Converters.DateTimeConverterResolver`1.Get(T value, Nullable`1 expectedPgTypeId)
   at Npgsql.Internal.PgConverterResolver`1.GetAsObjectInternal(PgTypeInfo typeInfo, Object value, Nullable`1 expectedPgTypeId)
   at Npgsql.Internal.PgResolverTypeInfo.GetResolutionAsObject(Object value, Nullable`1 expectedPgTypeId)
   at Npgsql.Internal.PgTypeInfo.GetObjectResolution(Object value)
   at Npgsql.NpgsqlParameter.ResolveConverter(PgTypeInfo typeInfo)
   at Npgsql.NpgsqlParameter.ResolveTypeInfo(PgSerializerOptions options)
   at Npgsql.NpgsqlParameterCollection.ProcessParameters(PgSerializerOptions options, Boolean validateValues, CommandType commandType)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at NLog.Targets.DatabaseTarget.ExecuteDbCommandWithParameters(LogEventInfo logEvent, IDbConnection dbConnection, IDbTransaction dbTransaction)
   at NLog.Targets.DatabaseTarget.WriteLogEventSuppressTransactionScope(LogEventInfo logEvent, String connectionString)
```

- Is there a version in which it did work? 
  - Not checked

**Comment by snakefoot** [comment] 2024-11-13 17:20
Maybe duplicate of this: https://github.com/NLog/NLog/issues/4665 ?

Notice [${longdate}](https://github.com/NLog/NLog/wiki/LongDate-Layout-Renderer) always follows the default [NLog TimeSource](https://github.com/NLog/NLog/wiki/Time-Source).

**Comment by CooperZuranskiSEP** [comment] 2024-11-14 14:43
I wouldn't quite say it's a duplicate. Also longdate _can_ also apply the UTC option. 

> dbType - One of the values of [DbType](https://docs.microsoft.com/en-us/dotnet/api/system.data.dbtype) (e.g. "Int32", "Decimal", "DateTime"), or a value of DBType like prefixed with the property name, e.g. "SqlDbType.NChar" will set the property "SqlDbType" on "NChar".

According to the Nlog docs, I would expect:
1. Either UTC/non-UTC as a result of my timesource/ having UTC=true - regardless of if i am using DateTime or DateTime2. 
   - Eg, When I use DateTime2 with universalTime=true, I get this: `Cannot write DateTime with Kind=UTC to PostgreSQL type 'timestamp without time zone',` . But using regular DateTime works fine. 
   - The alternate applies when using UTC=false in combination with DateTime
   - Using DateTime vs DateTime2 should not change the mapping vs TIMESTAMP vs TIMESTAMPTZ
3. different precision if i chose DateTime vs DateTime2 

To me, this seems related to some sort of odd mapping Nlog is doing under the hood when ingesting the DbType value.

**Comment by snakefoot** [comment] 2024-11-14 17:51
Sounds like you know a lot more than me, so you are wellcome to create a pull-request to improve any illogical behavior in the mapping:

https://github.com/NLog/NLog/blob/0d8aa5e1a4525826170ea5ebd80a35a7a110b247/src/NLog.Database/DatabaseParameterInfo.cs#L50-L60

**Comment by CooperZuranskiSEP** [comment] 2024-11-14 21:09
Haha i apologize for my bluntness, (im getting the sense that came across wrong) - My understanding only goes as far as what i've witnessed and the documentation. I was trying to lay out my understanding of the problem/observation and see how it lines up with yours, as it doesn't quite line up with the other issues ive seen in the repo (i did try and look first). I also was not sure if this is intentional behavior that I just couldn't discern from the documentation of MSDN/Nlog?

How does the dbType turn into something npgsql can understand? Is that is a responsibility within nlog, npgsql, both or some other piece of software?

If you want me to try running that case with trace, I can, or provide more details. I won't have time to contribute myself for a while.

In my case I can get the behavior I want, I was just mostly surprised i couldn't use DateTime2 with UTC and v.v..

**Comment by snakefoot** [comment] 2024-11-14 22:56
You can see from the mapping that I posted that both DbType Datetime and Datetime2 specify that NLog should provide Datetime value.

I'm guessing NLog provides the exact same parameter input value, and the only difference is the DbType. This can confirmed by checking the
NLog InternalLogger output.

NpgSql handles the mapping from DbType to it's own internal format.

I don't have the bandwidth to do the debugging for you. Maybe you can find someone at Stackoverflow.com?


Sent from my Galaxy



-------- Original message --------
From: Cooper Zuranski ***@***.***>
Date: 14/11/2024 22:09 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] Unexpected behavior with dbType="DateTime" VS dbType="DateTime2" using Postgres (Issue #5663)


Haha i apologize for my bluntness, (im getting the sense that came across wrong) - My understanding only goes as far as what i've witnessed and the documentation. I was trying to lay out my understanding of the problem/observation and see how it lines up with yours, as it doesn't quite line up with the other issues ive seen in the repo (i did try and look first). I also was not sure if this is intentional behavior that I just couldn't discern from the documentation of MSDN/Nlog?

How does the dbType turn into something npgsql can understand? Is that is a responsibility within nlog, npgsql, both or some other piece of software?

If you want me to try running that case with trace, I can, or provide more details. I won't have time to contribute myself for a while.

In my case I can get the behavior I want, I was just mostly surprised i couldn't use DateTime2 with UTC and v.v..

**Comment by snakefoot** [comment] 2024-11-15 18:28
You can also experiment with assigning the native [NpgsqlDbType](https://www.npgsql.org/doc/api/NpgsqlTypes.NpgsqlDbType.html) like this:
```xml
<parameter name="@p_timestamp" layout="${longdate:universalTime=true}" dbType="NpgsqlDbType.Timestamp" valueType="System.DateTime" />
```

**Comment by CooperZuranskiSEP** [comment] 2024-11-18 21:39
I initially couldn't get the Npgsqltype thing to work - I'll try this again in the coming days with the valuetype field, think i was missing that.

Outside of that i'll look down the npgsql route.

**Comment by snakefoot** [comment] 2024-11-26 17:56
Closing due to inactivity.

**Closed by snakefoot** 2024-11-26 17:56 UTC
Labels: question, database-target, external
