### ISSUE TITLE
Archiving logs by hour is sporadically working

### ISSUE THREAD

**Issue by DbTestMonkey** [NLog/NLog#1182] opened 2016-01-22 00:09 UTC
We are currently using Common.Logging with NLog 4.2.3 in a Windows .NET 4.5.2 service for diagnostic logging.

One of the targets we have set up can receive a reasonable throughput of logs so we have set it up to archive hourly rather than daily like the rest of our logs.

In the three or so days that we've been soak testing the service it appears that this hourly archive sometimes works every hour, other times it can take up to 23 hours to archive (resulting in a single file 23 times bigger than we expected, rather than 23 separate files).

I see there was a bug fix in NLog 4.2.0 where daily archiving would not always work so I'm wondering if this is related or if anyone else has experienced this.

Here is a sanitised sample of our configuration showing how it has been set up for this service:

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" internalLogToConsole="true">

   <variable name="LogFormat" value="${date:format=yyyy-MM-dd},${date:format=HH\:mm\:ss.fff},${counter},${processid},${threadid},${processtime},${level:uppercase=true},&quot;${processname}&quot;,&quot;${callsite:includeSourcePath=false:methodName=false}&quot;,&quot;${callsite:className=false:includeSourcePath=false:methodName=true}&quot;,&quot;${message}${onexception:inner= ${exception:format=tostring}}&quot;" />

   <variable name="FileNameFormat" value="Current.tlg" />

   <variable name="BaseLogDirectory" value="${whenEmpty:whenEmpty=${basedir}/Logs:inner=${registry:value=Folder:key=HKEY_LOCAL_MACHINE/PathToSettingStore:defaultValue=}}/TheService/" />

   <targets>
      <target name="Messaging" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Block">
         <target xsi:type="File" layout="${LogFormat}" fileName="${BaseLogDirectory}/Messaging/${FileNameFormat}" keepFileOpen="true" archiveEvery="Hour" archiveNumbering="Date" archiveFileName="${BaseLogDirectory}/Messaging/{#}h.tlg" archiveDateFormat="yyyyMMdd-HH" maxArchiveFiles="336" />
      </target>         
   </targets>

   <rules>
      <logger name="MyMessagingLibrary.*" minlevel="Debug" writeTo="Messaging" final="true" />
   </rules>
</nlog>
```

**Comment by 304NotModified** [comment] 2016-01-22 12:13
Hi,

we had some bugs regarding the day switch with archiving.  See https://github.com/NLog/NLog/pull/1100

This has been fixed in 4.3 . Can you test with https://www.nuget.org/packages/NLog/4.3.0-alpha4 ? 

4.3-beta release is expected in 2 weeks.

**Comment by DbTestMonkey** [comment] 2016-01-27 20:25
So we've been running 4.3.0-alpha4 for a few days now and the sporadic archiving error appears to have been fixed but it's been replaced by another bigger issue.

We are now seeing files being archived prematurely which then stops that target from ever archiving again in future and as such, logs are being lost.

An example of this:
- An archive log is created for 20160128-15h.tlg which contains logs from 14:00:00 - 14:59:59 (incorrect behaviour).
- Current.tlg now contains logs from 15:00:00-15:59:59
- At the 16h rollover NLog tries to archive Current.tlg to 20160128-15h.tlg which already exists, so it fails. All future logs are now thrown away as NLog constantly errors trying to archive the file.

When NLog is in fail state we see the following log in the internal log every time it tries to archive:
2016-01-28 08:53:17.6962 Info Archiving D:\...PathToServiceLog...\Messaging\Current.tlg to D:\...PathToServiceLog...\Messaging\20160127-15h.tlg

**Comment by 304NotModified** [comment] 2016-01-27 21:37
Thanks for this feedback! We have to fix this in 4.3 RTM. 

In 4.3 beta (just released) we improved the errors logging to the internal log. Maybe that could help identify the problem. Is it possible to the with 4.3 beta?

**Comment by 304NotModified** [comment] 2016-01-27 21:43
This one isn't in alpha 4, but is in beta 1

https://github.com/NLog/NLog/pull/1126. I think that could be the issue.

**Comment by DbTestMonkey** [comment] 2016-01-27 22:30
Alright thanks for that. We've upgraded the service to 4.3 beta 1 and will let it soak for a day or so. I'll post back here if it gets stuck again with any additional information logged to the internal log.

**Comment by 304NotModified** [comment] 2016-01-27 22:39
OK! I'm for a few days off (holiday), but posting your findings would be great. Will be back Monday

**Comment by DbTestMonkey** [comment] 2016-01-28 20:37
Alright as expected fail state has been achieved within 24 hours. 

I'll set the concurrentWrites flag to false for all File Targets over the weekend and see if that makes any difference.

Here is the internal log from when the situation occurred:

2016-01-28 15:00:00.7370 Trace Closing 'D:\PathToServiceLog\Messaging\Current.tlg'
2016-01-28 15:00:00.7370 Info Stopping file watching for path 'D:\PathToServiceLog\Messaging' filter '*h.tlg'
2016-01-28 15:00:00.7370 Info Archiving D:\PathToServiceLog\Messaging\Current.tlg to D:\PathToServiceLog\Messaging\20160128-15h.tlg
2016-01-28 15:00:00.7370 Trace Opening D:\PathToServiceLog\Messaging\Current.tlg with allowFileSharedWriting=True
2016-01-28 15:00:00.7370 Info Watching path 'D:\PathToServiceLog\Messaging' filter '*h.tlg' for changes.
2016-01-28 16:00:01.6125 Trace Closing 'D:\PathToServiceLog\Messaging\Current.tlg'
2016-01-28 16:00:01.6125 Info Stopping file watching for path 'D:\PathToServiceLog\Messaging' filter '*h.tlg'
2016-01-28 16:00:01.6125 Info Archiving D:\PathToServiceLog\Messaging\Current.tlg to D:\PathToServiceLog\Messaging\20160128-16h.tlg
2016-01-28 16:00:01.6125 Trace Opening D:\PathToServiceLog\Messaging\Current.tlg with allowFileSharedWriting=True
2016-01-28 16:00:01.6125 Info Watching path 'D:\PathToServiceLog\Messaging' filter '*h.tlg' for changes.
2016-01-28 17:00:01.3038 Trace Closing 'D:\PathToServiceLog\Messaging\Current.tlg'
2016-01-28 17:00:01.3038 Info Stopping file watching for path 'D:\PathToServiceLog\Messaging' filter '*h.tlg'
2016-01-28 17:00:01.3038 Info Archiving D:\PathToServiceLog\Messaging\Current.tlg to D:\PathToServiceLog\Messaging\20160128-17h.tlg
2016-01-28 17:00:01.3038 Trace Opening D:\PathToServiceLog\Messaging\Current.tlg with allowFileSharedWriting=True
2016-01-28 17:00:01.3038 Info Watching path 'D:\PathToServiceLog\Messaging' filter '*h.tlg' for changes.
2016-01-28 18:00:01.2012 Trace Closing 'D:\PathToServiceLog\Messaging\Current.tlg'
2016-01-28 18:00:01.2012 Info Stopping file watching for path 'D:\PathToServiceLog\Messaging' filter '*h.tlg'
2016-01-28 18:00:01.2012 Info Archiving D:\PathToServiceLog\Messaging\Current.tlg to D:\PathToServiceLog\Messaging\20160128-17h.tlg
2016-01-28 18:00:01.2012 Error Error has been raised. Exception: System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName, Boolean enableCompression)
   at NLog.Targets.FileTarget.RollArchiveForward(String existingFileName, String archiveFileName, Boolean allowCompress)
   at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, LogEventInfo logEvent)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
   at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)
2016-01-28 18:00:03.1683 Info Archiving D:\PathToServiceLog\Messaging\Current.tlg to D:\PathToServiceLog\Messaging\20160128-17h.tlg
2016-01-28 18:00:03.1683 Error Error has been raised. Exception: System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName, Boolean enableCompression)
   at NLog.Targets.FileTarget.RollArchiveForward(String existingFileName, String archiveFileName, Boolean allowCompress)
   at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, LogEventInfo logEvent)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
   at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)

**Comment by bhaeussermann** [comment] 2016-01-30 13:59
The archive is supposed to use the hour that had elapsed. So the first three archives above (15h, 16h, 17h) are wrong. They should have been 14h, 15h, 16h respectively. The last archive that fails is correct.

To be specific, we use the last-write-time of the file when it is archived, or the time of the previous call to the `Write()` method if that is more recent.

I tried to produce the bug with both a unit test and with an actual program but without success. It always uses the hour that elapsed. 

I *could* produce an NLog dll to write more information to the internal log to help with debugging this issue, if you would run that for us and share the log.

Are you sure that there is no separate process or thread that accesses the file? If something alters the file's last-write-time, that would break the archiving.

**Comment by bhaeussermann** [comment] 2016-02-01 05:29
I created an adhoc dll with more archive logging, which you can download [here](https://www.dropbox.com/s/4vgr29t1oxbe6bq/NLog.dll?dl=0).

**Comment by DbTestMonkey** [comment] 2016-02-02 02:00
Thanks for the adhoc binary. 
We gave it a go this morning and managed to get it to fail within a few hours. 

Here is the internal log snippet with your increased logging:

2016-02-02 10:00:01.5902 Info lastWriteTime: 02/02/2016 10:00:01
2016-02-02 10:00:01.5902 Info previousLog: 
2016-02-02 10:00:01.5902 Info previousLogIsMoreRecent: False
2016-02-02 10:00:01.5902 Info overlapped: False
2016-02-02 10:00:01.5902 Info Archiving D:\PathToServiceLog\Messaging\Current.tlg to D:\PathToServiceLog\Messaging\20160202-10h.tlg
2016-02-02 10:00:01.5902 Trace Opening D:\PathToServiceLog\Messaging\Current.tlg with allowFileSharedWriting=False
2016-02-02 11:00:01.9413 Info lastWriteTime: 02/02/2016 11:00:00
2016-02-02 11:00:01.9413 Info previousLog: 
2016-02-02 11:00:01.9413 Info previousLogIsMoreRecent: False
2016-02-02 11:00:01.9413 Info overlapped: False
2016-02-02 11:00:01.9413 Info Archiving D:\PathToServiceLog\Messaging\Current.tlg to D:\PathToServiceLog\Messaging\20160202-11h.tlg
2016-02-02 11:00:01.9413 Trace Opening D:\PathToServiceLog\Messaging\Current.tlg with allowFileSharedWriting=False
2016-02-02 12:00:01.8797 Info lastWriteTime: 02/02/2016 12:00:01
2016-02-02 12:00:01.8797 Info previousLog: 
2016-02-02 12:00:01.8797 Info previousLogIsMoreRecent: False
2016-02-02 12:00:01.8797 Info overlapped: False
2016-02-02 12:00:01.8797 Info Archiving D:\PathToServiceLog\Messaging\Current.tlg to D:\PathToServiceLog\Messaging\20160202-12h.tlg
2016-02-02 12:00:01.8797 Trace Opening D:\PathToServiceLog\Messaging\Current.tlg with allowFileSharedWriting=False
2016-02-02 13:00:00.4046 Info lastWriteTime: 02/02/2016 12:59:59
2016-02-02 13:00:00.4046 Info previousLog: 
2016-02-02 13:00:00.4046 Info previousLogIsMoreRecent: False
2016-02-02 13:00:00.4046 Info overlapped: False
2016-02-02 13:00:00.4046 Info Archiving D:\PathToServiceLog\Messaging\Current.tlg to D:\PathToServiceLog\Messaging\20160202-12h.tlg
2016-02-02 13:00:00.4046 Error Error has been raised. Exception: System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName, Boolean enableCompression)
   at NLog.Targets.FileTarget.RollArchiveForward(String existingFileName, String archiveFileName, Boolean allowCompress)
   at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, LogEventInfo logEvent)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
   at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)

Your comment about a separate process accessing the file actually rings a bell. 

I made absolutely sure that we only have one process logging to these files however it's possible another file watcher application we have is accessing the logs' metadata. This application doesn't write any data to them but it may be inspecting file details and/or actually inspecting contents for line counts etc.

To check whether this is the case I've changed the log folder for this service to somewhere the other application is not watching and I'll reply back as to whether that was the problem or not.

**Comment by DbTestMonkey** [comment] 2016-02-02 19:23
So it appears the file watcher application is not the problem. We are seeing the same behaviour even in folders it is not watching.

Has anyone had problems with anti-virus or change-detection software causing issues like these? I'll start trialing a few theories down this path now.

**Comment by bhaeussermann** [comment] 2016-02-02 19:33
@DbTestMonkey Thanks for the feedback, but I don't think we're on the right path with the external file access theory. 

I have looked at your internal log and it seems to me that the issue is caused by the `AsyncWrapper`. This causes a different method to be called on the `File` target, and that method is not covered by our unit tests D:. I'm currently looking into broadening the scope of the unit tests, and subsequently fixing the bug.

In the meanwhile, removing the `AsyncWrapper` should fix the issue, if that would not cause excessive overhead on the application.

**Comment by DbTestMonkey** [comment] 2016-02-02 19:40
@bhaeussermann Alright fair call. I'll try removing the AsyncWrapper instead and will see if that makes a difference.

**Comment by 304NotModified** [comment] 2016-02-02 23:04
> 2016-02-02 12:00:01.8797 Info lastWriteTime: 02/02/2016 12:00:01
> 2016-02-02 12:00:01.8797 Info previousLog: 
> 2016-02-02 12:00:01.8797 Info previousLogIsMoreRecent: False
> 2016-02-02 12:00:01.8797 Info overlapped: False
> 2016-02-02 12:00:01.8797 Info Archiving D:\PathToServiceLog\Messaging\Current.tlg to D:\PathToServiceLog\Messaging\20160202-12h.tlg
> 2016-02-02 12:00:01.8797 Trace Opening D:\PathToServiceLog\Messaging\Current.tlg with allowFileSharedWriting=False
> 2016-02-02 13:00:00.4046 Info lastWriteTime: 02/02/2016 12:59:59

Is this not a inaccuracy issue? (12:59:59 is almost 13:00...)

**Comment by bhaeussermann** [comment] 2016-02-03 04:26
> Is this not a inaccuracy issue? 

I think this is a manifestation of an issue that was reported and fixed earlier where a log write would start before midnight and end after midnight. This is more likely to happen when logs occur frequently (which I believe is the case here).

The reason why I believe the issue is caused by the fact that the async-method is called instead of the regular method is due to the internal log above indicating that the `previousLog` variable remains `null`. We use this variable to overcome the day-overlapping problem, but I noticed yesterday that it is not set in the async-method.

I am currently working on this.

**Comment by 304NotModified** [comment] 2016-02-03 15:57
@bhaeussermann thanks for the adhoc binary. I think it's a good idea to include the extra logs to NLog 4.3. if it's trace level, it wont affect the performance (much). Can you send a PR for that?

**Comment by bhaeussermann** [comment] 2016-02-03 16:23
> I think it's a good idea to include the extra logs to NLog 4.3. if it's trace level, it wont affect the performance (much).

Good idea. I will see if I can formulate those logs in a more meaningful way and create a separate PR for that.

**Comment by 304NotModified** [comment] 2016-02-03 16:34
:)

related: https://github.com/NLog/NLog/pull/1213

**Comment by DbTestMonkey** [comment] 2016-02-03 19:37
I can confirm the issue has been resolved by removing the AsyncWrapper around those File targets. We've seen it run without issue for 24 hours now.

**Comment by 304NotModified** [comment] 2016-02-03 22:35
Thanks for the confirm!

**Comment by 304NotModified** [comment] 2016-02-04 10:41
@DbTestMonkey  This is probably fixed in the master. I will publish a new beta release of 4.3 soon (or you can test from the source code). It would be great if you could retest it then. :)

**Comment by DbTestMonkey** [comment] 2016-02-04 20:43
@304NotModified Sure thing. As soon as 4.3.0-beta2 hits the feed I'll pull it down and give it a test.

**Comment by 304NotModified** [comment] 2016-02-04 20:57
Cool, https://github.com/NLog/NLog/issues/1203 is the only waiting issue for beta2

**Comment by 304NotModified** [comment] 2016-02-04 23:02
Will create beta3 when #1203 is fixed.

beta2 is now released: https://www.nuget.org/packages/NLog/4.3.0-beta2

Thanks in advance for checking!

**Comment by DbTestMonkey** [comment] 2016-02-04 23:18
@304NotModified Thanks for that. I've got one service running 4.3.0-beta1 with the AsyncWrappers removed and one service running 4.3.0-beta2 with the AsyncWrappers still in place.

I'll leave them both running over this long weekend (Monday's a public holiday here) and I'll report back on Tuesday.

**Comment by 304NotModified** [comment] 2016-02-04 23:32
Thanks in advance!

**Comment by DbTestMonkey** [comment] 2016-02-08 21:00
Alright both services are happily ticking along after three uninterrupted days and all logs look correct. It appears the fix applied in 4.3.0-beta2 was successful.

**Comment by 304NotModified** [comment] 2016-02-08 22:24
:)

**Comment by 304NotModified** [comment] 2016-03-07 21:51
Close this as it has been fixed (but not released yet)

**Closed by 304NotModified** 2016-03-07 21:51 UTC
Labels: almost ready, bug, file-target, must have
