### ISSUE TITLE
Logs are dropped when sent over network with NLogViewer target

### ISSUE THREAD

**Issue by stil** [NLog/NLog#2145] opened 2017-06-02 23:06 UTC
**Type** : Bug
**NLog version**: 5.0.0-beta07
**Platform**: .NET Core 
**Current NLog config**:

```xml
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Warn" internalLogFile="c:\temp\nlog-internal.log">
  
  <targets>
    <target name="log4view" xsi:type="NLogViewer" address="tcp://127.0.0.1:878" />
    <target xsi:type="ColoredConsole" name="console" layout="${longdate} ${logger} ${uppercase:${level}} ${message}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="log4view,console" />
  </rules>
</nlog>
```

**Steps to reproduce:**

1. Create new Console App .NET Core project in VS2017. Install NLog 5.0.0-beta07.
2. Create following `Main` method.

```csharp
using System;
using System.Threading.Tasks;
using NLog;

namespace ConsoleApp1
{
    internal class Program
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        private static void Main(string[] args)
        {
            Parallel.For(0, 1000, i => { Logger.Debug($"#{i}"); });

            Console.ReadLine();
        }
    }
}
```

3. Start [log4view](http://www.log4view.com/log4view/) and connect to `tcp://127.0.0.1:878`.

**In case of a BUG:**

> What is the current result?

Only ~25% of the logs are received by log4view.  Animated screenshot: ![screenshot](http://i.imgur.com/LLOHtYI.gif)

> What is the expected result?

It should receive all 1000 logs. Console target receives all logs, but Network target (NLogViewer) somehow drops majority of logs.

> Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Yes, I set level to `Warn` and it stays empty.

> Are there any work arrounds?

I'm not aware of any.

> Is there a version in which it did worked?

I don't know.

> Can you help us by writing an unit test?

I'm not sure where the problem lies to begin with.

**Comment by 304NotModified** [comment] 2017-06-03 19:14
Hi!

Is it possible to check with NLog 4 for this? 

I will also test this first in NLog 4.

**Comment by 304NotModified** [comment] 2017-06-03 19:24
See the same result on NLog4 and Log4view:

![image](https://cloud.githubusercontent.com/assets/5808377/26756451/f90baf0e-48a2-11e7-8e95-5eeb99f258cf.png)


Dunno what the read errors are, and if this is a NLog of Log4view issue

**Comment by 304NotModified** [comment] 2017-06-03 19:26
added the tester here: https://github.com/NLog/NLog.TestCases

**Comment by 304NotModified** [comment] 2017-06-03 19:47
some things i noticed,

when settings
```
 internalLogLevel="Trace" internalLogFile="c:\temp\nlog-internal.log">
```

Most of the time (but not always), log4view gets 1000 records

![image](https://cloud.githubusercontent.com/assets/5808377/26756556/9e12a9d8-48a5-11e7-9087-6778f504e8ed.png)

In the internal log, there is always 1000 records

![image](https://cloud.githubusercontent.com/assets/5808377/26756564/d250f4d4-48a5-11e7-8a60-343c6286cd33.png)

**Comment by 304NotModified** [comment] 2017-06-03 19:54
Other observations:

- when writing with a thread sleep, more messages are arriving
- when *not* logging to console, only 17 messages are succeeded (from the 1000)
![image](https://cloud.githubusercontent.com/assets/5808377/26756606/c2e6d742-48a6-11e7-920f-8dcc1e0051a2.png)
- don't saw any error in the log


So I think it's a max connections in parallel thing.

**Comment by 304NotModified** [comment] 2017-06-03 20:07
- It seems it won't help to use the bufferingwrapper. Still testing though

**Comment by stil** [comment] 2017-06-03 20:07
Network target has this `onConnectionOverflow` property, which is by default set to `AllowNewConnnection`. Is it however possible to configure it in NLogViewer target?

**Comment by 304NotModified** [comment] 2017-06-03 20:09
yes, good one. NLogViewerTarget inherits NetworkTarget, so NLogViewerTarget  has all the NetworkTarget properties. (not clear in the docs I guess)

**Comment by 304NotModified** [comment] 2017-06-03 20:13
unfortunately ` OnConnectionOverflow="Block" MaxConnections="1" />` won't help muc

**Comment by 304NotModified** [comment] 2017-06-03 20:16
this seems to work :)

```xml
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Warn" internalLogFile="c:\temp\nlog-internal.log">

  <targets>

    <!--<target xsi:type="BufferingWrapper" name="buffer1" bufferSize="1" flushTimeout="5000" >
      <target name="log4view" xsi:type="NLogViewer" address="tcp://127.0.0.1:878" />
    </target>-->

    <target name="log4view" xsi:type="NLogViewer" address="tcp://127.0.0.1:878" KeepConnection="false" OnConnectionOverflow="Block" MaxConnections="5" />
  
    <target xsi:type="ColoredConsole" name="console" layout="${longdate} ${logger} ${uppercase:${level}} ${message}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="log4view" />
  </rules>
</nlog>
```

**Comment by stil** [comment] 2017-06-03 20:18
Wow, it works for me too. Thank you so much for help.

Don't you think it's worth to override default values so it won't cause troubles for other people?

**Comment by 304NotModified** [comment] 2017-06-03 20:21
yes, that's a good idea. I think most users will use these kind of targets only local, or also over the network/intranet/internet? 

final recommendations:

-add the following properties: `keepConnection="false" onConnectionOverflow="Block" maxConnections="100"`
- don't use buffertarget
- ignore the XML validation errors in nlog.config when using the XSD

**Comment by 304NotModified** [comment] 2017-06-03 20:36
Closing this now in favor of 3 new Github issues :)

**Closed by 304NotModified** 2017-06-03 20:36 UTC
Labels: network/NLogViewer-target, question

**Comment by snakefoot** [comment] 2018-03-13 23:49
I guess the NLogViewer-target should have some kind of auto-removal of newLines in the layout-result, when newLine="true" (Avoid issues from having additional newlines in the log-message)

**Comment by snakefoot** [comment] 2018-03-13 23:53
Think the message loss issue is caused by Log4View receiving multiple LogEvents in a single read, and instead of using the xml-format to seperate them, then it depends on newlines. 

Thus a multiple logevents are turned into a single logevent-chunk, giving the appearance of message-loss, but actually it is Log4View having problems with parsing these chunks and only showing the first logevent in the chunk.

**Comment by snakefoot** [comment] 2018-03-14 17:42
Tried using the Log2Console-viewer and it has no issues with keeping up, independent of using NewLine=true or false.

I guess Log4View is just a very sensitive application.

**Comment by snakefoot** [comment] 2021-10-08 16:00
Updated Wiki with description of how to throttle NLog, so it will not overflow the Log-Viewer-Application:

https://github.com/NLog/NLog/wiki/NLogViewer-target#example

This becomes even more important with NLog 5.0, that doubles performance of NetworkTarget.

**Comment by AlexHolly** [comment] 2024-01-24 14:20
I use a custom `LogReceiverService` (I don't see one for .NET 8).
The solution from @304NotModified worked for me
`keepConnection="false" onConnectionOverflow="Block" maxConnections="100"`

The solution with newline did not work.

**Comment by snakefoot** [comment] 2024-01-25 16:36
The [NLog WCF LogReceiverService](https://github.com/NLog/NLog/wiki/LogReceiverService-target) has been extracted to its own nuget-package:
- https://www.nuget.org/packages/NLog.Wcf


The `newline`-setting for the [NLog NetworkTarget](https://github.com/NLog/NLog/wiki/Network-target) requires that the remote-receiver recognize the `newline` as delimiter between each LogEvent-payload.

It is possible to change the actual `lineEnding` from `\n` to something more exotic like `NULL - Null terminator (ASCII 0)`. This can forexample be used with Graylog GELF over TCP that recognizes null terminator line ending mode. It's called null frame delimiter.
