### ISSUE TITLE
EventLog target only writes to Application log

### ISSUE THREAD

**Issue by ChrizC** [NLog/NLog#2251] opened 2017-08-16 13:30 UTC
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):

- Bug

**NLog version**: 4.4.12

**Platform**: .Net 4.6.1

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">
  
  <targets>
    <target xsi:type="EventLog" name="eventlog" log="GatewayAPI" source="GatewayAPI" layout="${message}${newline}${exception:format=ToString}" />
    <target xsi:type="File" name="logfile" fileName="errors.txt" />
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="eventlog" />
    <logger name="*" minlevel="Error" writeTo="logfile" />
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?
EventLog target writes to the Application log even when a custom log (or System) has been defined.
- What is the expected result?
EventLog target should write to the specified log when provided.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes, it states it sets the Log name to the custom one defined in the XML, but NLog still writes to Application log.
- Please post full exception details (message, stacktrace, inner exceptions)
No exceptions.
- Are there any work arrounds? 
no
- Is there a version in which it did worked?
Unsure, first version used/installed.
- Can you help us by writing an unit test?
Unsure how to unit test this.

**Comment by 304NotModified** [comment] 2017-08-16 20:40
Duplicate of https://github.com/NLog/NLog/issues/950

Please continue the discussion there. As far as I remember we don't know how to solve this.

**Closed by 304NotModified** 2017-08-16 20:40 UTC
