### ISSUE TITLE
Time issue on GetLogger (slow)

### ISSUE THREAD

**Issue by Steven-6tm** [NLog/NLog#1002] opened 2015-10-26 09:05 UTC
Hi,

I'm sorry if this issue has already been told, but I couldn't find it. I use NLog for logging purpose (of course) on a .NET application and sometimes I can see the "GetLogger" function taking several seconds, like 10 or 30!!

I don't understand why it act like this, mostly because it really seems random to me.
Have you ever heard about that issue?

Thx,
Steven

**Comment by BrutalCode** [comment] 2015-10-26 11:28
Is your application multithreaded? 

Could you please provide more specific information? 
(NLog version, configuration, target type, application type and environment.)

Thank you for the feedback!

**Comment by 304NotModified** [comment] 2015-10-26 11:42
Posting the config, NLog version and internal log could be also helpful :)

See https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#bug-reports

**Comment by Steven-6tm** [comment] 2015-10-26 12:07
Sorry, there are the missing informations:
- NLog version: 3.2.0.0
- Multithreaded: Yes

And the config:
- In my web.config:
&lt;nlog xmlns=&quot;http://www.nlog-project.org/schemas/NLog.mono2.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
    &lt;include file=&quot;${basedir}/Settings/nlog.local.config&quot; /&gt;
  &lt;/nlog&gt;
- In my nlog.*.config (I use local/debug/release config files):
&lt;nlog xmlns=&quot;http://www.nlog-project.org/schemas/NLog.mono2.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; internalLogFile=&quot;C:\Temp\file.txt&quot; internalLogLevel=&quot;Trace&quot; throwExceptions=&quot;true&quot;&gt;
  &lt;extensions&gt;
    &lt;add assembly=&quot;MyAssembly&quot; /&gt;
  &lt;/extensions&gt;
  &lt;variable name=&quot;LogDir&quot; value=&quot;D:\Travail\&quot; /&gt;
  &lt;variable name=&quot;LogDay&quot; value=&quot;${date:format=yyyy-MM-dd}&quot; /&gt;

  &lt;targets&gt;
    &lt;target name=&quot;500File&quot; xsi:type=&quot;File&quot; fileName=&quot;${LogDir}/500/${LogDay}.log&quot; layout=&quot;${longdate} ${uppercase:${level}} ${message} : ${exception:format=tostring}&quot; /&gt;
    &lt;target name=&quot;404File&quot; xsi:type=&quot;File&quot; fileName=&quot;${LogDir}/404/${LogDay}.log&quot; layout=&quot;${longdate} ${uppercase:${level}} ${message}&quot; /&gt;
    &lt;target name=&quot;LogFile&quot; xsi:type=&quot;File&quot; fileName=&quot;${LogDir}/Traces/${LogDay}.log&quot; layout=&quot;${longdate} ${uppercase:${level}} ${message}&quot; /&gt;
    &lt;target name=&quot;MailFile&quot; xsi:type=&quot;File&quot; fileName=&quot;${LogDir}/Mails/${LogDay}.log&quot; layout=&quot;${longdate} ${uppercase:${level}} ${message}&quot; /&gt;
    &lt;target name=&quot;500Mail&quot; xsi:type=&quot;Mail&quot;
          smtpServer=&quot;10.0.20.222&quot;
          from=&quot;steven.lollivier@6tm.com&quot;
          to=&quot;steven.lollivier@6tm.com&quot;
          html=&quot;true&quot;
          replaceNewlineWithBrTagInHtml=&quot;true&quot;
          subject=&quot;[Europcar] - 500&quot;
          header=&quot;&amp;lt;head&amp;gt;&amp;lt;style&amp;gt;BODY{FONT-FAMILY: Arial;FONT-SIZE: 7pt;}
         Table{font-family:arial;cellspacing=0;font-size=8pt;border-collapse:collapse;}
         TH{background-color: #5978D9 ; color: white;font-weight: bold;font-family: Arial;border:solid 1px black;}
         TD{font-family:arial;font-size=8pt;padding:2px;border:solid 1px black;}
         &amp;lt;/style&amp;gt;&amp;lt;/head&amp;gt;&amp;lt;body&amp;gt;&quot;
          footer=&quot;&amp;lt;/table&amp;gt;&amp;lt;/body&amp;gt;&amp;lt;/html&amp;gt;&quot;
          body=&quot;${Mvc500}&quot;
         /&gt;
  &lt;/targets&gt;
  &lt;rules&gt;
    &lt;logger name=&quot;500&quot; minlevel=&quot;Error&quot; writeTo=&quot;500File&quot; /&gt;
    &lt;logger name=&quot;500&quot; minlevel=&quot;Fatal&quot; writeTo=&quot;500Mail&quot; /&gt;
    &lt;logger name=&quot;404&quot; minlevel=&quot;Error&quot; writeTo=&quot;404File&quot; /&gt;
    &lt;logger name=&quot;Log&quot; minlevel=&quot;Trace&quot; writeTo=&quot;LogFile&quot; /&gt;
    &lt;logger name=&quot;Mail&quot; minlevel=&quot;Trace&quot; writeTo=&quot;MailFile&quot; /&gt;
  &lt;/rules&gt;
&lt;/nlog&gt;

I couldn&#39;t find the internal log, it should be in &quot;C:\Temp\file.txt&quot;, but the &quot;C:\Temp&quot; directory doesn&#39;t exist. Should I create it ?

Hope this might help.

Steven

**Comment by 304NotModified** [comment] 2015-10-26 12:28
yes, you need to create the directory for the internal logger (note fixed in NLog 4.1 -  #802 )

**Comment by BrutalCode** [comment] 2015-10-26 12:30
Thank you Steven! We will investigate it.

**Comment by Steven-6tm** [comment] 2015-10-26 12:55
There is a full trace (sorry there is some french in there x) ... ) :

Catégorie	Message	À partir des premiers	À partir des derniers
	Get LoggerName		
	Get Logger	0,000124	0,000124
	Ini logger	0,004109	0,003985
	Enter GetConfiguration	0,004734	0,000625
	Conf not loaded	0,004753	0,000018
	Load default	0,004770	0,000017
	default loaded	3,575612	3,570843
	config chargée, dump	3,575649	0,000036
	watch file	8,081117	4,505469
	InitAll config	8,081624	0,000507
	enter initall	8,082050	0,000426
	enter validateconfig	8,082740	0,000689
	5 logging rules	8,082777	0,000037
	5 target values 	8,082800	0,000024
	FindReachableObjects	8,082814	0,000014
	FindReachableObjects ok	14,056323	5,973509
	check params logNamePattern: (500:Equals) levels: [ ] appendTo: [ 500File ]	14,058611	0,002288
	check params File Target[500File]	14,059014	0,000403
	check params 'D:\Travail\Europcar\Logs\Front/500/${date:format=yyyy-MM-dd}.log'	14,059066	0,000052
	check params Layout Renderer: ${literal}	14,059091	0,000025
	check params Layout Renderer: ${date}	14,059109	0,000018
	check params Layout Renderer: ${literal}	14,059127	0,000018
	check params '${longdate} ${uppercase:${level}} ${message} : ${exception:format=tostring}'	14,059136	0,000008
	check params Layout Renderer: ${longdate}	14,059152	0,000016
	check params Layout Renderer: ${literal}	14,059168	0,000017
	check params Layout Renderer: ${uppercase}	14,059189	0,000021
	check params '${level}'	14,059200	0,000011
	check params Layout Renderer: ${level}	14,059216	0,000016
	check params Layout Renderer: ${literal}	14,059232	0,000016
	check params Layout Renderer: ${message}	14,059248	0,000016
	check params Layout Renderer: ${literal}	14,059265	0,000017
	check params Layout Renderer: ${exception}	14,059281	0,000016
	check params logNamePattern: (500:Equals) levels: [ ] appendTo: [ 500Mail ]	14,059301	0,000020
	check params Mail Target[500Mail]	14,059320	0,000020
	check params 'administration@6tm.com'	14,059350	0,000029
	check params Layout Renderer: ${literal}	14,059367	0,000017
	check params 'vincent.jezequel@6tm.com'	14,059375	0,000008
	check params Layout Renderer: ${literal}	14,059393	0,000019
	check params '[Europcar] - 500 - Europcar FRONT - LOCAL'	14,059402	0,000008
	check params Layout Renderer: ${literal}	14,059418	0,000016
	check params 'blabla'	14,059426	0,000008
	check params Layout Renderer: ${literal}	14,059442	0,000016
	check params '10.0.20.222'	14,059450	0,000008
	check params Layout Renderer: ${literal}	14,059465	0,000016
	check params '</table></body></html>'	14,059473	0,000008
	check params Layout Renderer: ${literal}	14,059492	0,000019
	check params '<head><style>BODY{FONT-FAMILY: Arial;FONT-SIZE: 7pt;}          Table{font-family:arial;cellspacing=0;font-size=8pt;border-collapse:collapse;}          TH{background-color: #5978D9 ; color: white;font-weight: bold;font-family: Arial;border:solid 1px black;}          TD{font-family:arial;font-size=8pt;padding:2px;border:solid 1px black;}          </style></head><body>'	14,059500	0,000009
	check params Layout Renderer: ${literal}	14,059516	0,000016
	check params logNamePattern: (404:Equals) levels: [ ] appendTo: [ 404File ]	14,059527	0,000011
	check params File Target[404File]	14,059545	0,000018
	check params 'D:\Travail\Europcar\Logs\Front/404/${date:format=yyyy-MM-dd}.log'	14,059574	0,000029
	check params Layout Renderer: ${literal}	14,059608	0,000034
	check params Layout Renderer: ${date}	14,059624	0,000016
	check params Layout Renderer: ${literal}	14,059640	0,000016
	check params '${longdate} ${uppercase:${level}} ${message}'	14,059648	0,000008
	check params Layout Renderer: ${longdate}	14,059663	0,000015
	check params Layout Renderer: ${literal}	14,059678	0,000015
	check params Layout Renderer: ${uppercase}	14,059696	0,000018
	check params '${level}'	14,059706	0,000010
	check params Layout Renderer: ${level}	14,059721	0,000015
	check params Layout Renderer: ${literal}	14,059736	0,000015
	check params Layout Renderer: ${message}	14,059750	0,000014
	check params logNamePattern: (Log:Equals) levels: [ Trace Debug Info Warn Error Fatal ] appendTo: [ LogFile ]	14,059763	0,000013
	check params File Target[LogFile]	14,059824	0,000061
	check params 'D:\Travail\Europcar\Logs\Front/Traces/${date:format=yyyy-MM-dd}.log'	14,059869	0,000046
	check params Layout Renderer: ${literal}	14,059897	0,000028
	check params Layout Renderer: ${date}	14,059923	0,000025
	check params Layout Renderer: ${literal}	14,059939	0,000016
	check params '${longdate} ${uppercase:${level}} ${message}'	14,059946	0,000008
	check params Layout Renderer: ${longdate}	14,059964	0,000018
	check params Layout Renderer: ${literal}	14,059980	0,000016
	check params Layout Renderer: ${uppercase}	14,059996	0,000016
	check params '${level}'	14,060005	0,000009
	check params Layout Renderer: ${level}	14,060020	0,000015
	check params Layout Renderer: ${literal}	14,060035	0,000015
	check params Layout Renderer: ${message}	14,060049	0,000015
	check params logNamePattern: (Mail:Equals) levels: [ Trace Debug Info Warn Error Fatal ] appendTo: [ MailFile ]	14,060064	0,000015
	check params File Target[MailFile]	14,060082	0,000018
	check params 'D:\Travail\Europcar\Logs\Front/Mails/${date:format=yyyy-MM-dd}.log'	14,060109	0,000027
	check params Layout Renderer: ${literal}	14,060125	0,000016
	check params Layout Renderer: ${date}	14,060139	0,000015
	check params Layout Renderer: ${literal}	14,060158	0,000019
	check params '${longdate} ${uppercase:${level}} ${message}'	14,060166	0,000008
	check params Layout Renderer: ${longdate}	14,060181	0,000015
	check params Layout Renderer: ${literal}	14,060197	0,000015
	check params Layout Renderer: ${uppercase}	14,060212	0,000016
	check params '${level}'	14,060221	0,000009
	check params Layout Renderer: ${level}	14,060236	0,000015
	check params Layout Renderer: ${literal}	14,060251	0,000015
	check params Layout Renderer: ${message}	14,060268	0,000017
	validateconfig ok	14,060276	0,000008
	Initializing Layout Renderer: ${message}	14,060477	0,000201
	Initializing Layout Renderer: ${literal}	14,063389	0,002912
	Initializing Layout Renderer: ${level}	14,065730	0,002341
	Initializing '${level}'	14,067932	0,002202
	Initializing Layout Renderer: ${uppercase}	14,076384	0,008451
	Initializing Layout Renderer: ${literal}	14,079318	0,002934
	Initializing Layout Renderer: ${longdate}	14,081402	0,002085
	Initializing '${longdate} ${uppercase:${level}} ${message}'	14,083315	0,001912
	Initializing Layout Renderer: ${literal}	14,103659	0,020344
	Initializing Layout Renderer: ${date}	14,105556	0,001897
	Initializing Layout Renderer: ${literal}	14,107322	0,001766
	Initializing 'D:\Travail\Europcar\Logs\Front/Mails/${date:format=yyyy-MM-dd}.log'	14,109093	0,001771
	Initializing File Target[MailFile]	14,121691	0,012599
	Initializing Layout Renderer: ${message}	14,158520	0,036829
	Initializing Layout Renderer: ${literal}	14,161354	0,002834
	Initializing Layout Renderer: ${level}	14,163493	0,002139
	Initializing '${level}'	14,165497	0,002004
	Initializing Layout Renderer: ${uppercase}	14,173534	0,008037
	Initializing Layout Renderer: ${literal}	14,175456	0,001922
	Initializing Layout Renderer: ${longdate}	14,177767	0,002311
	Initializing '${longdate} ${uppercase:${level}} ${message}'	14,180305	0,002537
	Initializing Layout Renderer: ${literal}	14,255396	0,075091
	Initializing Layout Renderer: ${date}	14,257228	0,001832
	Initializing Layout Renderer: ${literal}	14,259225	0,001998
	Initializing 'D:\Travail\Europcar\Logs\Front/Traces/${date:format=yyyy-MM-dd}.log'	14,261426	0,002201
	Initializing File Target[LogFile]	14,274167	0,012740
	Initializing Layout Renderer: ${message}	14,306866	0,032699
	Initializing Layout Renderer: ${literal}	14,310486	0,003620
	Initializing Layout Renderer: ${level}	14,312987	0,002501
	Initializing '${level}'	14,316038	0,003051
	Initializing Layout Renderer: ${uppercase}	14,323941	0,007903
	Initializing Layout Renderer: ${literal}	14,326036	0,002095
	Initializing Layout Renderer: ${longdate}	14,328256	0,002220
	Initializing '${longdate} ${uppercase:${level}} ${message}'	14,330296	0,002040
	Initializing Layout Renderer: ${literal}	14,350665	0,020369
	Initializing Layout Renderer: ${date}	14,352842	0,002177
	Initializing Layout Renderer: ${literal}	14,354672	0,001831
	Initializing 'D:\Travail\Europcar\Logs\Front/404/${date:format=yyyy-MM-dd}.log'	14,357125	0,002453
	Initializing File Target[404File]	14,372004	0,014879
	Initializing Layout Renderer: ${literal}	14,405490	0,033487
	Initializing '<head><style>BODY{FONT-FAMILY: Arial;FONT-SIZE: 7pt;}          Table{font-family:arial;cellspacing=0;font-size=8pt;border-collapse:collapse;}          TH{background-color: #5978D9 ; color: white;font-weight: bold;font-family: Arial;border:solid 1px black;}          TD{font-family:arial;font-size=8pt;padding:2px;border:solid 1px black;}          </style></head><body>'	14,407464	0,001974
	Initializing Layout Renderer: ${literal}	16,208547	1,801082
	Initializing '</table></body></html>'	16,670860	0,462313
	Initializing Layout Renderer: ${literal}	18,603351	1,932491
	Initializing '10.0.20.222'	19,059695	0,456344
	Initializing Layout Renderer: ${literal}	20,845712	1,786017
	Initializing 'blabla'	21,291891	0,446179
	Initializing Layout Renderer: ${literal}	23,047825	1,755935
	Initializing '[Europcar] - 500 - Europcar FRONT - LOCAL'	23,487519	0,439693
	Initializing Layout Renderer: ${literal}	23,943194	0,455676
	Initializing 'vincent.jezequel@6tm.com'	23,945373	0,002179
	Initializing Layout Renderer: ${literal}	23,954593	0,009219
	Initializing 'administration@6tm.com'	23,956731	0,002138
	Initializing Mail Target[500Mail]	23,967408	0,010677
	Initializing Layout Renderer: ${exception}	26,247141	2,279734
	Initializing Layout Renderer: ${literal}	26,685608	0,438467
	Initializing Layout Renderer: ${message}	27,139903	0,454295
	Initializing Layout Renderer: ${literal}	27,598655	0,458752
	Initializing Layout Renderer: ${level}	28,085873	0,487217
	Initializing '${level}'	28,594798	0,508925
	Initializing Layout Renderer: ${uppercase}	30,397497	1,802699
	Initializing Layout Renderer: ${literal}	30,841368	0,443871
	Initializing Layout Renderer: ${longdate}	31,275933	0,434565
	Initializing '${longdate} ${uppercase:${level}} ${message} : ${exception:format=tostring}'	31,279177	0,003244
	Initializing Layout Renderer: ${literal}	31,306208	0,027031
	Initializing Layout Renderer: ${date}	31,308190	0,001982
	Initializing Layout Renderer: ${literal}	31,310229	0,002039
	Initializing 'D:\Travail\Europcar\Logs\Front/500/${date:format=yyyy-MM-dd}.log'	31,312891	0,002662
	Initializing File Target[500File]	31,326428	0,013537
	InitAll ok	31,365512	0,039084
	InitAll log	31,370293	0,004781
	GetConfigurationForLogger 500	31,371195	0,000902
	targetsByLevel créées sur 51 levels	31,371219	0,000025
	lasttargetsByLevel créées sur 51 levels	31,371227	0,000008
	suppressedLevels créées sur 51 levels	31,371234	0,000007
	GetTargetsByLevelForLogger 	31,371306	0,000071
	targets ok	31,372430	0,001124
	calcul stack 500File	31,372490	0,000060
	calcul stack 500File	31,414021	0,041531
	targets ok	31,452056	0,038036
	calcul stack 500File	31,452093	0,000037
	calcul stack 500File	31,493125	0,041032
	targets ok	33,462975	1,969851
	calcul stack 500File	33,463012	0,000036
	calcul stack 500File	37,473528	4,010517
	GetTargetsByLevelForLogger ok	39,332785	1,859257
	Trace =>	40,211162	0,878377
	Debug =>	40,647700	0,436538
	Info =>	41,080505	0,432805
	Warn =>	41,521948	0,441443
	Error => 500File	41,971723	0,449776
	Fatal => 500File 500Mail	42,401871	0,430147
	Create LoggerConfiguration	42,401920	0,000050
	Return GetConfigurationForLogger	42,402204	0,000283
	get conf ok	42,402220	0,000016
	Enter init	42,402338	0,000118
	Init > set conf	42,402544	0,000206
	Enter set conf	42,402850	0,000306
	Exit set conf	42,402943	0,000093
	Exit init	42,402954	0,000011
	logger init ok	42,402961	0,000007
	Logger getté	42,403227	0,000266

**Comment by Steven-6tm** [comment] 2015-10-26 13:03
And when we remove the "Mail" type, we fall from 30/45s to 1.5/3s.
(Sorry for this multi post ... We're trying to figure it out ourself)

**Comment by BrutalCode** [comment] 2015-10-26 13:37
Don't worry. Details are welcome. We will investigate it as soon as possible.
If you find thing out more, please feel free to let we know.

Thank you again.

**Comment by Steven-6tm** [comment] 2015-10-26 14:14
So, it seems that when we don't set any value inside our mail, we don't have 30s for the first init :

&lt;targets&gt;
    &lt;target name=&quot;MailFile&quot; xsi:type=&quot;File&quot; fileName=&quot;${LogDir}/Mails/${LogDay}.log&quot; layout=&quot;${longdate} ${uppercase:${level}} ${message}&quot; /&gt;
    &lt;target name=&quot;500Mail&quot; xsi:type=&quot;Mail&quot;
          smtpServer=&quot;10.0.20.222&quot;
          from=&quot;steven.lollivier@6tm.com&quot;
          to=&quot;steven.lollivier@6tm.com&quot;
          html=&quot;true&quot;
          replaceNewlineWithBrTagInHtml=&quot;true&quot;
          subject=&quot;[Europcar] - 500&quot;
          header=&quot;a&quot;
          footer=&quot;b&quot;
          body=&quot;c&quot;
         /&gt;
  &lt;/targets&gt;

And my coworker found out that if I don't respect the minLevel, like this:
&lt;logger name=&quot;500&quot; minlevel=&quot;Fatal&quot; writeTo=&quot;500Mail&quot; /&gt;

And I try to log:
LogHelper.GetLogger(LogHelper.ELoggerName.Log500).Trace("Just a little trace");
instead of using:
LogHelper.GetLogger(LogHelper.ELoggerName.Log500).Fatal("That's a big error");

I'm good for 10s of waiting. (Well that's my fault, but I thought you might have some use of this.)

**Comment by 304NotModified** [comment] 2015-10-26 16:28
@BrutalCode I expect this is a timeout somewhere

**Comment by 304NotModified** [comment] 2015-10-26 21:36
@Steven-6tm can you test with a recent NLog version? (4.2.0?)

**Comment by Steven-6tm** [comment] 2015-10-27 08:33
@304NotModified Unfortunately, we did test with the 4.2.0 without any improvements.

(And sorry, again, for the missing fences, I kind of skimmed the bug-report rules ^^' ...)

**Comment by 304NotModified** [comment] 2015-10-27 13:14
OK, no problem, but good to know because we can easier test in the latest version

**Comment by 304NotModified** [comment] 2015-11-02 23:04
@UgurAldanmaz any results on this?

**Comment by 304NotModified** [comment] 2015-11-02 23:15
@Steven-6tm I tested it locally, and it's super-fast. Would it be possible to extract the issue to a demo application?

**Comment by 304NotModified** [comment] 2015-11-02 23:21
PS a trace log would be also helpful :)

**Comment by UgurAldanmaz** [comment] 2015-11-30 22:56
I have no time unfortunately. I am working on another issue. 

Is there anybody to look this?

**Comment by Steven-6tm** [comment] 2015-12-01 07:29
@304NotModified This will be difficult for me to give you that demo, but I will try to give you a log with the 4.2.0 version.

**Comment by 304NotModified** [comment] 2015-12-01 12:18
@Steven-6tm  that would be great!

**Comment by 304NotModified** [comment] 2015-12-17 20:09
@Steven-6tm is this issue still a problem?

**Comment by 304NotModified** [comment] 2016-03-27 20:45
I will close ghost one as we can't reproduce it.

**Closed by 304NotModified** 2016-03-27 20:45 UTC
Labels: bug, needs info
