### ISSUE TITLE
basedir network path

### ISSUE THREAD

**Issue by innominate227** [NLog/NLog#831] opened 2015-08-06 15:25 UTC
In NLog 4.0.1 if I run an exe from a network folder (eg \\\Computer\MyFolder\MyApp\bin) NLog does not properly substitute the ${basedir} render with the correct path.  It instead doubles the name of the first folder (eg \\\Computer\MyFolder\MyFolder\MyApp\bin).  This issue does not occur in 4.0.0.

**Comment by innominate227** [comment] 2015-08-06 15:27
Here is my config file:

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  
  <targets async="true">
    <target name="fileAsync" xsi:type="AsyncWrapper" batchSize="200" queueLimit="10000" overflowAction="Discard">
      <target xsi:type="File" createDirs="true" name="f" fileName="${basedir}\Logs\${date:format=yyyy-MM-dd}.csv">
        <layout xsi:type="CsvLayout">
          <withHeader>true</withHeader>
          <column layout="${date}" name="Date"/>
          <column layout="${message}" name="Message"/>
        </layout>
      </target>
    </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="f" />
  </rules>
</nlog>



And here is a test app:


namespace NLogTest
{
    class Program
    {

        private static readonly Logger _logger = LogManager.GetLogger("A");

        static void Main(string[] args)
        {
            _logger.Info("TEST");
        }
    }
}

**Comment by 304NotModified** [comment] 2015-08-06 17:56
That's weird! 

I will look at,  this week

**Comment by 304NotModified** [comment] 2015-08-07 19:54
Hi,

I tried this locally with the unit tests, but I cannot reproduce this

https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/LayoutRenderers/BaseDirTests.cs

Can you run those unit tests? 

I also checked the changes from 4.0.0 to 4.0.1, but I cannot find anything related

**Comment by 304NotModified** [comment] 2015-08-07 20:21
EDIT: the unit tests are succeseeding, but when creating a test application, it indeed fails for 4.0.1 (but not for 4.0.0)

Excception:

```
System.TypeInitializationException was unhandled
  HResult=-2146233036
  Message=The type initializer for 'NLog.Config.ConfigurationItemFactory' threw an exception.
  Source=NLog
  TypeName=NLog.Config.ConfigurationItemFactory
  StackTrace:
       at NLog.Config.ConfigurationItemFactory.get_Default()
       at NLog.Config.XmlLoggingConfiguration..ctor(String fileName)
       at NLog.LogFactory.LoadLoggingConfiguration(String configFile)
       at NLog.LogFactory.get_Configuration()
       at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
       at NLog.LogFactory.GetLogger(String name)
       at NLog.LogManager.GetLogger(String name)
       at ConsoleApplication1.Program.Main(String[] args) in \\dell-julian\nlogtest\ConsoleApplication1\ConsoleApplication1\Program.cs:line 16
  InnerException: System.IO.DirectoryNotFoundException
       HResult=-2147024893
       Message=Could not find a part of the path '\\Dell-julian\Nlogtest\Nlogtest\ConsoleApplication1\ConsoleApplication1\bin\Debug'.
       Source=mscorlib
       StackTrace:
            at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
            at System.IO.FileSystemEnumerableIterator`1.CommonInit()
            at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
            at System.IO.Directory.GetFiles(String path, String searchPattern)
            at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
            at NLog.Config.ConfigurationItemFactory..cctor()
       InnerException: 

```

**Comment by innominate227** [comment] 2015-08-07 20:37
Here is a test app similar to the unit tests: http://pastebin.com/EFGwx63G
Here is what I see with 4.0.0: http://pastebin.com/N8rzfV4M
And here is 4.0.1: http://pastebin.com/4aK6FKA3

**Comment by 304NotModified** [comment] 2015-08-07 20:43
Thanks!

does the unit test fail or succeeded in your unit-test-test app?

**Comment by innominate227** [comment] 2015-08-07 20:49
I don't have XUnit on my machine, but my guess is that when running from the unit test runner that AppDomain.CurrentDomain.BaseDirectory is some directory on a local drive.

**Comment by 304NotModified** [comment] 2015-08-07 20:55
This seems to be fixed in 4.1.0,

you can validate this with this version:

https://www.nuget.org/packages/NLog/4.1.0-alpha1

**Comment by innominate227** [comment] 2015-08-07 20:59
Yep that version is working for me.
Thanks for your help!

**Comment by 304NotModified** [comment] 2015-08-07 21:02
Thanks for verifying! :+1: 

status: fixed in master already. Waiting for 4.1.0 release.

**Closed** 2015-08-07 21:49 UTC
Labels: almost ready, bug

**Comment by 304NotModified** [comment] 2015-08-31 17:36
4.1 has been released!
