### ISSUE TITLE
ConfigSettingLayoutRenderer does not fallback to environment variables

### ISSUE THREAD

**Issue by andrew-vdb** [NLog/NLog#3943] opened 2020-05-04 14:00 UTC
https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer

Spent hours wondering why its working on my local but not in Kubernetes
It works because my appsettings.development.json contains the settings that I need within the target of nlog.config, when I deploy to Kubernetes, appsettings.json only contains "placeholder" value, then it does not work because the setting exists in environment variables

Can we have fallback like that the setting is read from environment variables too?
Its asp.net core default behaviour
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1

**Comment by snakefoot** [comment] 2020-05-04 16:18
The override should happen automatically since ConfigSetting is just doing lookup in the provided IConfiguration-interface.

Did you remember to add environment-variables when initializing the MEL-Configuration-Builder?

Maybe you can show some code of how you initialize the application and load MEL-Configuration and initialize NLog. Maybe also show your NLog.config so one can see where `${configsetting}` is being used in NLog.config.

**Comment by andrew-vdb** [comment] 2020-05-06 07:06
Program.cs
```
public class Program
    {
        public static void Main(string[] args)
        {
            var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
            try
            {
                logger.Debug("init main");
                CreateHostBuilder(args).Build().Run();
            }
            catch (Exception exception)
            {
                //NLog: catch setup errors
                logger.Error(exception, "Stopped program because of exception");
                throw;
            }
            finally
            {
                // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
                NLog.LogManager.Shutdown();
            }
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                }).ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    // logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
                })
            .UseNLog();
    }
```

I assume you want me to add this line?
```
Host.CreateDefaultBuilder(args).ConfigureAppConfiguration(c => { c.AddEnvironmentVariables(); })
```
In the past i did that but for new project, even without that line, it works with env variables

nlog.config
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Info"
      internalLogFile="internal-nlog.txt">

  <!-- enable asp.net core layout renderers -->
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
    <add assembly="Microsoft.ApplicationInsights.NLogTarget" />
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <target xsi:type="Console"
          name="ConsoleLogger"
          layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />
    <target xsi:type="ApplicationInsightsTarget" name="AiTarget">
      <instrumentationKey>${configsetting:item=ApplicationInsights.InstrumentationKey}</instrumentationKey>
      <contextproperty name="threadid" layout="${threadid}" />      
    </target>
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <logger name="*" minlevel="Trace" writeTo="ConsoleLogger" />
    <logger name="*" minlevel="Trace" writeTo="AiTarget" />
    <logger name="Microsoft.*" maxlevel="Info" final="true" />
  </rules>
</nlog>
```

**Comment by snakefoot** [comment] 2020-05-06 08:17
Duplicate of this issue: https://github.com/NLog/NLog.Extensions.Logging/issues/265

Right now you have these options:
- Remove explicit call to  `NLog.Web.NLogBuilder.ConfigureNLog()`, then it will correctly NLog.config when MEL-Configuration is ready (Happens in `UseNLog`)
- Explicit load appsettings-options (and environment-variables) before calling `NLog.Web.NLogBuilder.ConfigureNLog()`). See example [here](https://github.com/NLog/NLog.Extensions.Logging/issues/265#issue-419649328)

When NLog 4.7.1 arrives then you can replace `NLog.Web.NLogBuilder.ConfigureNLog()` with this:

`var logger = NLog.LogManager.Setup().LoadConfigurationFromAppSettings().GetCurrentClassLogger();`

See also: https://github.com/NLog/NLog.Web/pull/540

**Closed** 2020-05-13 09:24 UTC
Labels: duplicate, nlog-configuration, question
