### ISSUE TITLE
JsonLayout - Encoding UTF-8 - accentuation error

### ISSUE THREAD

**Issue by mfavinha** [NLog/NLog#2170] opened 2017-06-16 14:42 UTC
NLog Version: NLog.5.0.0-beta07

Hi,

      When i use this configuration:

    <target name="logDaily_ALL" xsi:type="File"
            fileName="${basedir}/logs/daily/log_daily_ALL.json"
            archiveFileName="${basedir}/logs/archive/archive.ALL.{#}.zip"
            archiveEvery="Day"
            archiveNumbering="DateAndSequence"
            archiveDateFormat="yyyy-MM-dd"
            maxArchiveFiles="1000"
            archiveAboveSize="1048576"
            concurrentWrites="true"
            keepFileOpen="false"   
            encoding="UTF-8"
            enableArchiveFileCompression="true"
            fileAttributes="Archive"
            autoFlush="true"
            >
      <layout xsi:type="JsonLayout" >
        <attribute name="time" layout="${longdate:json}" encode="true" />
        <attribute name="level" layout="${level:uppercase=true}" encode="true"/>
        <attribute name="logger" layout="${logger}" encode="true"/>
        <attribute name="callsite" layout="${callsite}" encode="true"/>
        <attribute name="message" layout="${message}" encode="true" />
        <attribute name="exception" layout="${exception:format=tostring,Data:maxInnerExceptionLevel=10}" encode="true" />
      </layout>
    </target>

     I create the log with the command:

                logger.Error(_ex, "Licença de uso expirada!");

    But the log generated was:

{ "time": "2017-06-16 11:27:22.4521", "level": "ERROR", "logger": "webapp.source.page.dacPage", "callsite": "webapp.source.page.dacPage.Error_Handling", "message": "Licen\u00e7a de uso expirada!", "exception": "webapp.source.exception.custom: Licen\u00e7a de uso expirada!\r\n   em webapp.login.Page_Load(Object sender, EventArgs e) na S:\\Projetos\\SVN\\webapp\\login.aspx.cs:linha 39 TitleMessage: Erro!;ActionMessage: Entre em contato com o suporte.;exception_LocalException: Page" }

    This layout don´t respect the UTF-8 (the correct is "Licença", not "Licen\u00e7a")

    Using normal text file, works or If i change encode=false on attribute property works too... but the format of my json changes. I really would like to still using json pure format.

    Can you help me ?

Regards..

Marcello Favinha

**Comment by snakefoot** [comment] 2017-06-16 15:55
Duplicate of #2160

**Comment by 304NotModified** [comment] 2017-06-17 10:58
This will be fixed in 5.0 beta 8, see indeed #2160

**Closed by 304NotModified** 2017-06-17 10:58 UTC
