### ISSUE TITLE
async="true" loses current thread identity

### ISSUE THREAD

**Issue by niemyjski** [NLog/NLog#1426] opened 2016-05-02 19:49 UTC
I'm setting `async="true"` for perf reasons and I know that causes targets to be called on a secondary thread. I was wondering how I can keep the user identity (even the identity.name) of the thread when the log message was created. I see that the layout renders have access to this but my custom targets do not have identity information cached anywhere. I think if this isn't possible, we should at least pass the existing identity along to the target.

**Comment by niemyjski** [comment] 2016-05-02 19:54
Looks like the layout cache has this info but it's internal. It would be great if we could just expose this on the logger context!

**Comment by 304NotModified** [comment] 2016-05-02 19:54
do you mean `${windows-identity}`?

**Comment by niemyjski** [comment] 2016-05-02 19:56
In our nlog target I'd like to set the current user if it hasn't already been set. I try to use different contexts but I wanted a fallback to `System.Threading.CurrentThread.Identity` https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Platforms/NLog/ExceptionlessClientExtensions.cs#L11

**Comment by 304NotModified** [comment] 2016-05-02 19:58
If you write a custom layout renderer, it should work?

**Comment by niemyjski** [comment] 2016-05-02 19:58
My target looks like this:

```xml
 <targets async="true">
    <target name="file"
      xsi:type="File"
      layout="${longdate} ${threadid:padding=4} ${level:uppercase=true:padding=5} ${logger:shortName=true} ${message} ${exception:format=tostring}"
      fileName="${logDirectory}/log.txt"
      archiveFileName="${logDirectory}/log.{#}.txt"
      archiveEvery="Day"
      archiveNumbering="Rolling"
      maxArchiveFiles="7"
      concurrentWrites="true"
      createDirs="true"
      autoFlush="true" />
    
    <target name="exceptionless"  xsi:type="Exceptionless">
      <field name="host" layout="${machinename}" />
      <field name="identity" layout="${identity}" />
      <field name="process" layout="${processname}" />
      <field name="project" layout="${event-context:item=project}" />
    </target>
  </targets>
```

I first noticed that we weren't setting the user for some exceptions but our layout had rendered a custom object that had it.. Upon investigation this was from the current thread and the authenticated web api user.. So I was hoping to pass this user through our exceptionless code as a fallback but it's not on any nlog context just internal cached layouts

**Comment by niemyjski** [comment] 2016-05-02 19:58
I don't want to do that, I just want access to the current threads identity when the log was created.

**Comment by 304NotModified** [comment] 2016-05-02 19:59
Maybe i'm missing it, but `${identity}` won't work well with async?

**Comment by niemyjski** [comment] 2016-05-02 20:00
No it won't, but there is no reason it can't be passed along with all of the other contextual information in the context property of `LogEventInfo`. This information as well as all renderer info is there but thrown away and hidden.

**Comment by niemyjski** [comment] 2016-05-02 20:04
![screen shot 2016-05-02 at 3 03 15 pm](https://cloud.githubusercontent.com/assets/1020579/14966259/0f68c5c6-1077-11e6-9a58-a5265ed70190.png)

Notice in this screenshot that I'm looking at my target that's being called in an async manner.. The current thread isn't set and I know why and that's a good thing.. But the private layoutcache contains that info and the context doesn't contain any data either.. There is no reason this and other useful info couldn't be passed along to the target.

**Comment by 304NotModified** [comment] 2016-05-02 20:12
>>  ${identity} won't work well with async?

> No it won't,

I guess this should be fixed ?

**Comment by niemyjski** [comment] 2016-05-02 20:15
Yes. Well it happens on a secondary thread and I'm not sure of the architecture here but this secondary thread might handle multiple different messages (which may mean each of those could be from a different Identity). I think it would be super useful to populate this info on each LogEventInfo context so it can be accessed no matter how the log target is being called,

**Comment by 304NotModified** [comment] 2016-05-02 20:22
> I think it would be super useful to populate this info on each LogEventInfo context so it can be accessed no matter how the log target is being called,

Agree, but it's more important to have the bug fixed.

**Comment by 304NotModified** [comment] 2016-05-02 21:34
Works on my machine? 

https://github.com/NLog/NLog/pull/1428

**Comment by niemyjski** [comment] 2016-05-03 17:05
@304NotModified that test doesn't really test this issue. The layout render is right and always has been right. The issue is when the target is called in an async wrapper, the Thread.CurrentThread.Identity may not be set (which I don't think should be because it could be buffered messages?), and there is no way to get a hold of what the current thread identity was when the layout was rendered/log call was made

**Comment by 304NotModified** [comment] 2016-05-03 17:49
Can you give me an example/tesrlt repo? Because I don't get what isn't working.

**Comment by 304NotModified** [comment] 2016-05-04 12:42
I think we have two cases here, and that confusing

1. A bug? (according to your title), which I cannot reproduce
2. The feature request to read the layout renderer cache

I think it's wise to discuss them separate GitHub issues. I like to fix 1, if it is really a bug, but AFAIK all works.

**Comment by niemyjski** [comment] 2016-05-04 14:11
If you want I'd be more than happy to launch a teamviewer session and show you this issue first hand. I'm on [slack](http://slack.exceptionless.com) all day.

I think 1. is a bug and 2 kinda ties into this, it's not just the layout render cache but the context object should be populated with as much info as possible so the target can do anything the layout render can.

**Comment by 304NotModified** [comment] 2016-05-14 18:35
@niemyjski 

Sorry about the delayed response. Also I was too busy for a (small) meeting. 

Good news (or maybe not) is that the unit test I wrote sometimes fails: https://github.com/NLog/NLog/issues/1441. So there is something bad going on.

Don't understand why it fails, as the prerender always will be done in the calling thread.

About 2), reading the layout can be done by re-rendering the layout? E.g. 

```c#
Layout l = "${identity};
string identity = l.render(logEvent); //logEvent with layoutCache

**Comment by 304NotModified** [comment] 2016-08-06 00:18
This is still an issue I guess?

**Comment by niemyjski** [comment] 2016-08-08 17:40
Yes, when running in async you are not guaranteed to be on the same thread. My issues is not with layouts (which seems to have the correct info). It's that I want to get access to this cached info later in the process after layouts have ran. We need to copy this data some place and have layouts use it regardless of what thread you are on.

**Comment by 304NotModified** [comment] 2016-08-08 18:42
Is it possible to create a litre sample app or unit test? Clearly I don't fully understand the issue, but I think it could be fixed.

**Comment by niemyjski** [comment] 2016-08-08 18:52
- http://stackoverflow.com/questions/21838651/i-thought-await-continued-on-the-same-thread-as-the-caller-but-it-seems-not-to
- http://blog.stephencleary.com/2013/11/there-is-no-thread.html

Those both are worth reading. You could create a test that does something like this

```
// log
// await Task.Delay(50);
// log
// await Task.Delay(50);
```

You'd probably want to use https://github.com/StephenCleary/AsyncEx/wiki/AsyncCountdownEvent to ensure that you hooks to verify logs have been created / event handlers called.  We do this in our tests :) https://github.com/exceptionless/Foundatio/blob/eb16268f037975f00482f41257d20f7fbe2c4093/test/Foundatio.Tests/Utility/ScheduledTimerTests.cs#L36-L59

Based on the task scheduler context, you are not guaranteed  to be running on the same thread. Which is exactly what happens when you have async=true.

**Comment by 304NotModified** [comment] 2016-08-08 19:57
Sure, but the async renderer isn't using await.

**Comment by niemyjski** [comment] 2016-08-08 22:10
Forget the render.... I want all of this contextual information in my custom target which is called async...

**Comment by 304NotModified** [comment] 2016-08-09 10:28
Please provider a simple example / unit test.

**Comment by 304NotModified** [comment] 2016-09-14 22:31
I think we need a test application, otherwise we cannot fix this. Please provide one, otherwise I have to close this one. Thanks!

**Comment by niemyjski** [comment] 2016-09-24 21:15
https://github.com/NLog/NLog/pull/1660

**Comment by niemyjski** [comment] 2016-09-24 21:15
I didn't even have to startup a new thread, just a single await task delay..

**Comment by niemyjski** [comment] 2016-09-24 21:16
It shows off how fragile this is, layouts will be rendered exactly how they should be but targets lose the contextual information. If you fix this by putting all of the contextual information that layouts have (the cached data), then this will work properly too if you do any buffered/bulk target writes.

**Comment by 304NotModified** [comment] 2016-09-24 22:48
Thanks for the unit test

**Comment by niemyjski** [comment] 2016-09-24 22:56
No problem :) Sorry for the delay. I finally got some free time.

**Comment by snakefoot** [comment] 2021-11-09 20:13
`async="true"` does not cause current user-identity-info to be lost, this is handled by NLog Layout Precalculate.

But you are right that the user-identity-rights are lost, when logging within impersonation-scope, and the actual logging happens on a background-thread after impersonation-scope-exit.

NLog doesn't have any magic to recreate the impersonation-scope of the original user. The only option currently available is https://github.com/NLog/NLog/wiki/LimitingWrapper-target

This is not a bug, but just working as designed.

**Closed by snakefoot** 2021-11-09 20:13 UTC
Labels: bug
