### ISSUE TITLE
Intuitive way to configure logger filters

### ISSUE THREAD

**Issue by MarekPokorny** [NLog/NLog#2232] opened 2017-07-31 17:27 UTC
**Type**: Feature request

Let's say we want to [configure an target to only log exceptions](https://stackoverflow.com/questions/9306835/how-do-i-configure-an-nlog-target-to-only-log-exceptions). 
Stackoverflow suggestion is this:

### 17 votes for this configuration
```xml
<logger name="*" writeTo="file">
    <filters>
        <when condition="length('${exception}') > 0" action="Log" />
    </filters>
</logger>
```
This configuration **is wrong**, because by **default** - **all logs** are written and `action="Log"` doesn´t change it. It took me many hours to find it -> filtering logic is inverted.

### 2 votes only for this configuration
```xml
<logger name="*" writeTo="file">
    <filters>
        <when condition="length('${exception}') = 0" action="Ignore" />
    </filters>
</logger>
```
This configuration **is good**, because by **default** - **all logs** are written and `action="Ignore"` will exclude messages with zero exception length.

### Add new configuration option - attribute condition to logger
```xml
<logger name="*" writeTo="file" condition="length('${exception}') > 0" />
```
### Why do we need it?
- it is intuitive (filtering logic is not inverted - say what logs want, not what logs want to ignore)
- exactly same filtering system as FilteringWrapper
- shorter configuration syntax
- you will probably make less errors using new `condition` syntax then when using old style of filtering using `<when condition.../>` inside `<filters>`

For backward compatibility keep old style of filtering.

**Comment by snakefoot** [comment] 2017-07-31 17:46
Duplicate of #2151 ?

**Comment by MarekPokorny** [comment] 2017-07-31 18:19
It is similar...
But my suggestion is different.

**Comment by 304NotModified** [comment] 2017-08-11 13:43
Thanks for the suggestion.

The change of the `<logger` xml element has IMO to much impact (for us and for the users)

This is indeed a duplicate of https://github.com/NLog/NLog/issues/2151, so closing this. Feel free to add suggestions to https://github.com/NLog/NLog/issues/2151

**Closed by 304NotModified** 2017-08-11 13:43 UTC
