### ISSUE TITLE
Event Log not creating custom folder 

### ISSUE THREAD

**Issue by dev-4488** [NLog/NLog#1151] opened 2016-01-11 06:16 UTC
![logsfolder](https://cloud.githubusercontent.com/assets/13965580/12227962/db59c042-b85a-11e5-8f84-1beae9b06ab6.PNG)
I have a requirement where in we want our event logs to be written to a custom folder in Event Logs, however when i am specifying layout in NLog.config file it is directing it to Application folder.
Looked into source code , and looks like this is how it is implemented.
My exact requirement is to log events from my application is below manner:
![Uploading LogsFolder.PNG…]()

Any pointers from any one on how to achieve it.
Thanks in advance.

Uploaded image again...Tx

**Comment by UgurAldanmaz** [comment] 2016-01-11 06:29
Your image does not displayed. Could you upload it again?

**Comment by UgurAldanmaz** [comment] 2016-01-11 07:07
Are you looking for something like this: http://stackoverflow.com/questions/5171155/creating-an-application-and-event-logs-in-the-applications-and-services-logs-s

**Comment by dev-4488** [comment] 2016-01-11 08:38
Yes something like this but i want to write logs to it using NLog logger and want to set up the same using nlog config file.

**Comment by UgurAldanmaz** [comment] 2016-01-11 09:28
You need to specifiy `source` and `log` in the configuration.

[Event Log Target](https://github.com/NLog/NLog/wiki/EventLog-target) wiki page can guide you to do this.

To find out which value is required, you can look at the MSDN page. Because `source` and `log` values are the same thing that defined [MSDN page](https://msdn.microsoft.com/en-us/library/system.diagnostics.eventsourcecreationdata.eventsourcecreationdata(v=vs.110).aspx)

Please try and inform us. If it will not work for you, I will take a look again.

**Comment by dev-4488** [comment] 2016-01-11 09:34
Yup using the guidelines specified on wiki page, i am not able to get the folder i have mentioned in first post, also i specify layout of message in nlog config file it ignores the value given in "log" configuration and directs it to application folder in event log.
This is the config file value i have set:
![mylog](https://cloud.githubusercontent.com/assets/13965580/12230210/a438f276-b874-11e5-9f3b-7624335cd378.PNG)
<target name="eventlog" xsi:type="EventLog"  machineName="." source="mysource1" log="mylog1"/>

**Comment by UgurAldanmaz** [comment] 2016-01-11 09:50
Could you post your full NLog config at here?

**Comment by dev-4488** [comment] 2016-01-11 09:59
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log" >


  
  <variable name="myvar" value="myvalue"/>

  
  <targets>

    

    
    

     
    <target name="eventlog" xsi:type="EventLog"  machineName="." source="mysource1" log="mylog1"  layout="${longdate} | ${guid} |${logger} | ${level} | ${message} | ${exception:format=ToString}"/>
  
    
  </targets>

  <rules>
    

    
    
    <logger name="*" minlevel="Debug" writeTo="eventlog" />
    
  </rules>
</nlog>

**Comment by 304NotModified** [comment] 2016-01-27 22:50
@UgurAldanmaz are you looking at this?

**Comment by 304NotModified** [comment] 2016-02-03 23:13
bump @UgurAldanmaz

**Comment by 304NotModified** [comment] 2016-02-25 23:27
@dev-4488 I guess this is still an issue?

**Comment by dev-4488** [comment] 2016-03-02 17:00
Yes it is, any pointers on how to fix it or when it will be fixed??

**Comment by 304NotModified** [comment] 2016-03-02 17:39
I will look at this, but I need some more info to understand the issue. 

As far I understand you would like to write to "mylog1/operation" (logname), is that correct?

So if you set 

```
 target name="eventlog" xsi:type="EventLog"  machineName="." source="mysource1" log="mylog1/operation"  layout="${longdate} | ${guid} |${logger} | ${level} | ${message} | ${exception:format=ToString}"/>
```

that won't work?

**Comment by dev-4488** [comment] 2016-03-02 17:57
Yes you are correct, because if you specify Layout for an event log target it will start putting logged events information in default folder i.e. Application.

**Comment by 304NotModified** [comment] 2016-03-02 18:05
I'm not sure if I fully understand you.

But you like to use a Layout for the log name?

e.g.

```xml
<target log="${test}" >
```

**Comment by dev-4488** [comment] 2016-03-02 18:08
Nope, i am using below xml to write to event logs:

 
    <target name="eventlog" xsi:type="EventLog"  machineName="." source="mysource1" log="mylog1"  layout="${longdate} | ${guid} |${logger} | ${level} | ${message} | ${exception:format=ToString}"/>

However the log information is going to Application folder in Event Viewer rather than to a custom folder "mylog1".

**Comment by 304NotModified** [comment] 2016-03-02 19:08
Ah, so this is https://github.com/NLog/NLog/issues/950 ?

**Comment by dev-4488** [comment] 2016-03-02 21:38
Yes.... :)  is there any solution for it ??

**Comment by 304NotModified** [comment] 2016-03-02 22:53
Well I can't reproduce it. 

But if you willing to help, you can test if you can write to the log just with some c# statements (without nlog) . If that's working, we will move the working code into NLog.

**Comment by 304NotModified** [comment] 2016-03-28 16:28
Closing this as it's a duplicate of #950

**Closed by 304NotModified** 2016-03-28 16:28 UTC
Labels: duplicate, event-log-target, question
