### ISSUE TITLE
Support Environment Variables in internalLogFile/NLOG_INTERNAL_LOG_FILE

### ISSUE THREAD

**Issue by anton-gogolev** [NLog/NLog#2213] opened 2017-07-13 08:38 UTC
As of now, the `internalLogFile` or `NLOG_INTERNAL_LOG_FILE` can only contain paths to files where NLog will write its internal log messages:

    <nlog internalLogFile="d:\logs\nlog.txt">
    setx /M NLOG_INTERNAL_LOG_FILE "d:\logs\nlog.txt"

When hosting multiple applications on a single machine, it would be nice to have those logs separated by Process ID, Application Pool Name or whatnot.

This can be done by, [as usual](https://www.wikiwand.com/en/Fundamental_theorem_of_software_engineering), adding an extra level of indirection:

    <nlog internalLogFile="%APPLICATION_LOG_ROOT%\%APP_POOL_ID%\nlog.txt">
    setx /M NLOG_INTERNAL_LOG_FILE "%APPLICATION_LOG_ROOT%\%APP_POOL_ID%\nlog.txt"

(in this example, `%APPLICATION_LOG_ROOT%` is a system-wide environment variable, and `%APP_POOL_ID%` is set automatically for each application by Internet Information Services).

The required change looks trivial enough ([`InternalLogger.cs`](https://github.com/NLog/NLog/blob/master/src/NLog/Common/InternalLogger.cs#L419)):

        private static string GetSettingString(string configName, string envName)
        {
            // ...
            // Existing code goes here
            // ...

            settingValue = Environment.ExpandEnvironmentVariables(settingValue);
            return settingValue;
        }

**Comment by anton-gogolev** [comment] 2017-07-13 10:38
Now that I think about it, [https://github.com/NLog/NLog/blob/master/src/NLog/Common/InternalLogger.cs#L283](this location) is where the magic should happen.

**Comment by 304NotModified** [comment] 2017-07-13 16:41
> Now that I think about it, this location is where the magic should happen.

Yes, I think also :)

Looks good! PR would be great. please not that maybe this isn't supported on all platforms (Silverlight etc), just use `#if` etc.

**Comment by anton-gogolev** [comment] 2017-07-15 12:41
Will do.

**Comment by anton-gogolev** [comment] 2017-07-15 14:46
Backwards compatibility?

When older versions of NLog will encounter an environment variable placeholder in `LogFile`, the `File.AppendText()` call will fail, most likely with `DirectoryNotFoundException`.

The only way of resolving this is to introduce another environment variable (e.g. `NLOG_INTERNAL_LOG_FILE_EXT`) and use it first, and only if it is missing fall back to the original `NLOG_INTERNAL_LOG_FILE`.

**Comment by 304NotModified** [comment] 2017-07-15 19:02
The environment variables are between `%` isn't?

As the internal log isn't a production tool, i think the small breaking change isn't a prob

**Comment by anton-gogolev** [comment] 2017-07-15 19:24
Julian,

Breaking change warrants 5.0, doesn't it?

**Comment by anton-gogolev** [comment] 2017-07-17 13:04
Nah, does't look like a good idea after all. Internal logging should be robust and reliable, yet with this change previous versions of NLog will be failing all over the place.

@304NotModified, it's your call. Should I introduce another environment variable or just close this issue for good?

**Comment by 304NotModified** [comment] 2017-07-17 15:51
> Nah, does't look like a good idea after all. Internal logging should be robust and reliable,

agree, but do you think ` Environment.ExpandEnvironmentVariables(settingValue)` would be unstable?



> Breaking change warrants 5.0, doesn't it?

Breaking changes in production stuff indeed (targets, layouts, rules), but not for the internal log. IMO the internal log is a debug tool and is not meant for parsing etc.

**Comment by anton-gogolev** [comment] 2017-07-18 07:09
> do you think `Environment.ExpandEnvironmentVariables(settingValue)` would be unstable?

It's not that. The `NLOG_INTERNAL_LOG_FILE` is global, so _every_ application running on the server will start attempting to write to an internal log, which they will be unable to do successfully, since `File.AppendText("%TEMP%\nlog.txt")` will throw an exception on each and every call.

**Comment by 304NotModified** [comment] 2017-07-18 09:43
ah the problem is there when you mix older and newer versions of NLog, isn't?

**Comment by 304NotModified** [comment] 2017-10-10 20:09
I agree, impact to high. Won't fix. 

Thanks for your feedback!

**Closed by 304NotModified** 2017-10-10 20:09 UTC
Labels: feature
