### ISSUE TITLE
Memory Leak With Async File Target on Mono 4.2

### ISSUE THREAD

**Issue by eleonel1** [NLog/NLog#1137] opened 2016-01-07 18:33 UTC
We found that when we updated to the latest Mono Version (4.2) our services began to show an increase in memory usage, after some profiling and testing and some research we found out it was the Logging section the one to be blamed, this section uses NLog async writting to save different purpose logs. We removed the async part and the problem was fixed. You can find some test code and more details here https://github.com/eleonel1/Mono4.2NLogMemoryLeak

**Comment by 304NotModified** [comment] 2016-01-07 19:27
Hey! Can you create a PR for this?

**Comment by 304NotModified** [comment] 2016-01-07 23:45
I have read your post wrong. First of all, there is a config two (common) mistakes with the following config:

```xml
  <targets async="true">
    <target name="asyncFileDebug" xsi:type="AsyncWrapper">
      <target xsi:type="File" name="fileLogDebug" ...  />
    </target>
  </targets>
  <rules>
    <logger name="MemoryLeakTestLog" level="Debug" writeTo="fileLogDebug" />
  </rules>
```

1. We have now two nested async wrappers
2. You won't write to the async wrapper.

It should be (no wrapper)

```xml
  <targets async="true">
    <target xsi:type="File" name="fileLogDebug" ...  />
  </targets>
  <rules>
    <logger name="MemoryLeakTestLog" level="Debug" writeTo="fileLogDebug" />
  </rules>
```

OR (no async attr, write to wrapper)

```xml
  <targets >
    <target name="asyncFileDebug" xsi:type="AsyncWrapper">
      <target xsi:type="File" name="fileLogDebug"       ...        />
    </target>
  </targets>
  <rules>
    <logger name="MemoryLeakTestLog" level="Debug" writeTo="asyncFileDebug" />
  </rules>
```

Can you test with one of the two configs?

Also, can you give me:

- The exact version number (nuget package version number)
- If this is new, and if so, which NLog version worked well
- Is this only under Mono?
- Is there a lot of log messages? How much?

Thanks in Advance!

**Comment by eleonel1** [comment] 2016-01-08 15:39
Hello, glad to help, i tested both configurations and the result is the same, memory consumption increases over time.

This is the output when installing NLog from nuget

PM> Install-Package NLog
Attempting to gather dependencies information for package 'NLog.4.2.3' with respect to project 'MemoryLeakTest', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'NLog.4.2.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'NLog.4.2.3'
Resolved actions to install package 'NLog.4.2.3'
Adding package 'NLog.4.2.3' to folder 'C:\Users\Edgar\Documents\Visual Studio 2015\MemoryLeakTest\packages'
Added package 'NLog.4.2.3' to folder 'C:\Users\Edgar\Documents\Visual Studio 2015\MemoryLeakTest\packages'
Added package 'NLog.4.2.3' to 'packages.config'
Successfully installed 'NLog 4.2.3' to MemoryLeakTest

If i see the propertys of NLog.dll i get the following

![image](https://cloud.githubusercontent.com/assets/12548446/12201642/1c1989ae-b5eb-11e5-9a34-2c587dc00655.png)

This only hapens when running under mono

Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Thu Nov 12 09:52:44 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

This didn't happen with the previous mono version, and this behaviour is shown even if the service isn't processing any requests. If you send 1 request and leave the service running idle the memory starts rising even if you don't send any other request.

**Comment by 304NotModified** [comment] 2016-01-08 18:49
> This didn't happen with the previous mono version

Whats the previous version? 4.2.2? 4.1.0?

**Comment by 304NotModified** [comment] 2016-01-08 20:02
PS the changes of 4.2.3 (limited)

https://github.com/NLog/NLog/compare/4.2.2...4.2.3

**Comment by eleonel1** [comment] 2016-01-08 20:21
In Mono 3.12.1 NLog runs async without a problem.

**Comment by 304NotModified** [comment] 2016-01-08 20:27
I'm sorry, but what version do you mean? There is no NLog 3.12.1?

**Comment by eleonel1** [comment] 2016-01-08 20:29
No, that's the mono version where the same code works without any problem.

**Comment by 304NotModified** [comment] 2016-01-08 20:31
Ow, so it's only a problem in Mono 4 and not in Mono 3.1.2?

But is there an NLog version (you know) which works well on Mono 4?

**Comment by eleonel1** [comment] 2016-01-08 20:40
Negative, only thing i did was update the mono version from 3.12.1 to 4.2.1, the NLog version is 4.2.3 and the process started to consume more memory over time. 

I have 6 identical servers, i took one and removed the Async configurations of NLog and i got this results

![image](https://cloud.githubusercontent.com/assets/12548446/12208935/8388f3de-b615-11e5-93f0-b1e661016baa.png)

**Comment by 304NotModified** [comment] 2016-01-08 20:54
you're using the nuget package right?

There is some mono-optimized code in NLog, but it won't work with the NuGet packages :( (there is no mono platform)

**Comment by eleonel1** [comment] 2016-01-08 21:19
Yeah, i'm using the nuget package

**Comment by 304NotModified** [comment] 2016-01-08 21:55
I think this is related or this issue: http://lists.ximian.com/pipermail/mono-devel-list/2005-March/010883.html

**Comment by 304NotModified** [comment] 2016-01-09 01:15
There was also a PR for Mono 4 a while ago,

but AFAIK it did only copied the code https://github.com/NLog/NLog/pull/958

**Comment by 304NotModified** [comment] 2016-02-25 23:26
Has this een fixed in newer Mono builds?

**Comment by 304NotModified** [comment] 2016-03-28 16:35
I don't know if we can fix this. At least we need more info to look into this.

**Comment by 304NotModified** [comment] 2016-08-06 00:26
Is this still an issue?

**Comment by nyxiscoo1** [comment] 2016-12-16 09:17
Yes, I'm expiriencing exact same issues when using NLog 4.4 with sync file target. Mono 4.6 and 4.8, but I believe leak is due mono bug. Donwgrade to Mono 4.0.4 solves the issue.

**Comment by snakefoot** [comment] 2016-12-17 08:42
>  I'm expiriencing exact same issues when using NLog 4.4 with sync file target

Sounds like a different problem, as the original poster doesn't have the problem when using sync-target (removes async).

My the problem is reduced for original poster if the async-target uses timeToSleepBetweenBatches=0 (Requires NLog ver. 4.3.11 or newer)

**Comment by snakefoot** [comment] 2016-12-17 10:20
An example of MONO_GC_PARAMS for keeping memory as low as possible:

> export MONO_GC_PARAMS="nursery-size=1m,soft-heap-limit=128m,evacuation-threshold=90,save-target-ratio=0.1,default-allowance-ratio=1.0"
> mono --desktop ASF.exe

If the device has a limited physical memory, then one can also consider to configure ex max-heap-size=150M for MONO_GC_PARAMS

**Comment by Sarsue** [comment] 2017-01-13 18:20
Is anyone having this issues also when deploying with docker??

**Comment by snakefoot** [comment] 2017-01-28 21:07
> Is anyone having this issue when deploying with docker??

Not sure what your issue is, but apparently there can be dragons when using console-out:

- http://stackoverflow.com/questions/27628276/docker-daemon-memory-leak-due-to-logs-from-long-running-process
- https://github.com/docker/docker/issues/9139

**Comment by snakefoot** [comment] 2017-01-30 20:46
Btw. original poster also posted a bug report to MONO, but their testers failed to reproduce the leak. When major collection occurred then memory dropped correctly:

https://bugzilla.xamarin.com/show_bug.cgi?id=37486

**Comment by Sarsue** [comment] 2017-01-30 21:49
I dropped my mono version to v3.8.0 and the memory leak disappeared which works for me at the moment when I am less busy. I'll update my project .NET framework to 4.6 and test with mono version 4.2 again. Its just a hunch but I think there is some sort of correlation between the mono version and .NET framework.

**Comment by 304NotModified** [comment] 2017-02-17 20:25
Will close this as this is a known issue as it's polluting the issue list - there is no action for us here.

**Closed by 304NotModified** 2017-02-17 20:25 UTC
Labels: known issue, performance
