### ISSUE TITLE
The type initializer for 'NLog.Common.InternalLogger' throws an exception on PreApplicationStartMethod

### ISSUE THREAD

**Issue by JBaltika** [NLog/NLog#387] opened 2014-07-13 17:20 UTC
Hey guys,
I been using NLog on this project for 2 years right now. I just upgraded to Nlog 3.1 recently and getting en error  {"The type initializer for 'NLog.Common.InternalLogger' threw an exception."} on Web application  'PreApplicationStartMethod' if code throws exception. Any ideas. I think its bug. It should silently fail if cannot find current class logger or  go to default, in another words do something but not kill app. 

[assembly: System.Web.PreApplicationStartMethod(typeof(ConfigurationManager), "PreApplicationStart")]

        public static void PreApplicationStart()
        {
            try
            {
                var config = RavenStoreManagerConfigSection.Instance;
                if (config == null)
                {
                    throw new HttpException(580, Minion.Web.Raven.Properties.Resources.ConfigurationManagerPreApplicationStartExceptionMessage);
                }
            }
            catch (Exception exception)
            {
                var logger = NLog.LogManager.GetCurrentClassLogger();
                logger.Error(exception.Message, exception);

                throw;
            }
        }

**Comment by 304NotModified** [comment] 2015-01-17 13:36
@JBaltika if this is still a problem, please submit the requested info and re-open this issue.

**Comment by Leonsoft** [comment] 2015-04-28 03:34
I got the same error and resolved it by clearing folder C:\Users\yourName\AppData\Local\yourApp.

**Comment by Xharze** [comment] 2015-05-10 23:05
@304NotModified Should we close this until more information is available?

**Comment by 304NotModified** [comment] 2015-05-10 23:06
I think we should document this and then closing it.

**Comment by Xharze** [comment] 2015-05-10 23:07
Let's do that

**Comment by 304NotModified** [comment] 2015-05-11 20:53
Some info about these kind of exceptions: 

http://stackoverflow.com/a/4398374

**Comment by 304NotModified** [comment] 2016-05-17 22:58
This is probably another issue and this is fixed with the introduction of throwConfigExceptions in NLog 4.3.

If someone experience this problem, please let us know.

**Closed by 304NotModified** 2016-05-17 22:58 UTC
Labels: bug, needs documentation on wiki, needs info

**Comment by parvizEmami** [comment] 2017-02-21 07:13
I got this problem when use 4.4.3

**Comment by 304NotModified** [comment] 2017-02-21 18:02
Please open a new issue. 

Ps most of the time is caused by an invalid config. Full reason is a long story ;)

**Comment by sllewellyn13** [comment] 2018-01-17 02:32
I'm getting this error with version NLog.4.4.12, because I have set up a new Build/Release process for my organization. I have a Solution with two projects in it. We use Build/Release transforms for security reasons and the NLog's config is getting confused about:  xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"

I have App.Debug.config and App.Release.config, and on top of that NLog.config. Somehow the build process seems to munge these together.

The solution contains an MVC 5 web application which references a DLL which is in the same solution. That DLL contains my production code and makes use of appSettings. (FYI)

-sulu
