### ISSUE TITLE
Unexpected ordering of format items.

### ISSUE THREAD

**Issue by EltonInAtlanta** [NLog/NLog#1518] opened 2016-06-23 18:32 UTC
**Type** - Bug

When entering string tokens I expect them to behaving as the would with String.Format. NLog is not respecting the index of the format item.  Example:

```
Console.WriteLine("zero: {0} two: {2} one: {1}", "zero", "one", "two");
output: zero: zero two: two one: one

Logger.LogTrace("zero: {0} two: {2} one: {1}", "zero", "one", "two");
output: zero: zero two: one one: two
```

**NLog version**: (e.g. 4.2.3)
4.3.4 
Package; "NLog.Extensions.Logging": "1.0.0-rc2-final-2016-05-21",

**Platform**: 
ASP.NET Core RC2 (4.6.1 framework)

In case of a BUG:
- What is the current result?

```
Logger.LogTrace("zero: {0} two: {2} one: {1}", "zero", "one", "two");
zero: zero two: one one: two
```
- What is the expected result?

```
Logger.LogTrace("zero: {0} two: {2} one: {1}", "zero", "one", "two");
zero: zero two: two one: one

```
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  Yes
- Please post full exception details (message, stacktrace, inner exceptions)
  None
- Are there any work arrounds? yes/no
  Yes - sequence token indexes in order of actual parameters.
- Is there a version in which it did worked? 
- Can you help us by writing an unit test?

**Comment by 304NotModified** [comment] 2016-06-23 20:44
Hmm this seems the default Microsofts tokenizer. Strange.  Will look in depth after holiday (next week)

**Comment by 304NotModified** [comment] 2016-07-13 21:18
issue confirmed. Now I have to find out why

**Comment by 304NotModified** [comment] 2016-07-13 21:29
We are using the default formatter, so asked: https://github.com/aspnet/Logging/issues/462

**Comment by 304NotModified** [comment] 2016-07-26 17:25
This is (too bad) by design. 



> Eilon commented a minute ago
It is certainly by design at this time. The keys are always opaque, so even if they happen to "look like" numbers, they're still opaque strings.

https://github.com/aspnet/Logging/issues/462#issuecomment-235340689

**Comment by 304NotModified** [comment] 2016-07-26 17:26
AFAIK we cannot work around it, as all the logs of MS will be wrong ordered.

**Comment by 304NotModified** [comment] 2017-02-17 20:24
Will close this as this is a known issue as it's polluting the issue list - there is no action for us here.

**Closed by 304NotModified** 2017-02-17 20:24 UTC
Labels: known issue
