### ISSUE TITLE
autoReload not working if config file get replaced

### ISSUE THREAD

**Issue by gordingin** [NLog/NLog#298] opened 2014-01-15 15:38 UTC
I have a windows service in Windows 8.1 that uses nlog. I have to trace messages, one with a Info Level and one with a Debug Level. I configure NLog.Config to use both Info and Debug and run my service. The log file produces the correct data. Then I edit the NLog.config file and remove Info, save it, delete MY log file and rerun the process that produces the log file. I still get Debug and Info log message. If I stop and stop the windows service with the revised config file, it then only produces Debug message.
I do have the autoReload="true" in the config file but for some reason, it does reread the config file after I changed and save it.

**Comment by kubal5003** [comment] 2015-04-16 09:12
I have the same issue. When using Windows Service the changes in configuration file are not reflected.  When I run the service as console application(I'm using Topshelf library) it's working fine. I'm unable to reproduce this in a sample application. I'm thinking whether this might be permission related issue? I turned on internal logging, but nothing interesting in there.

**Comment by 304NotModified** [comment] 2015-04-16 13:35
Hi @kubal5003 ,

could you provide the information listed at https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#bug-reports ? Thanks

**Comment by kubal5003** [comment] 2015-04-16 13:59
Version: 3.2.0.0
Error message: no error message, just doesn't do the job.
Internal log: no information is logged when I save the file
Current result: Nothing is being logged in the destination directory. 
Expected result: Logs should start appearing in the destination directory.

Current config:```

<?xml version="1.0"?>
<nlog autoReload="true" throwExceptions="false" xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" internalLogFile="E:\Logs\PCC1\nlog.txt" internalLogLevel="Info">
  <targets>
    <target name="PrimaryLog" xsi:type="File"
        fileName="E:\Logs\PCC1\web.txt"
        archiveFileName="E:\Logs\PCC1\archives\web.{#####}.txt"
        archiveAboveSize="10240000"
        archiveNumbering="Sequence"
        concurrentWrites="false"
        keepFileOpen="true"/>

    <target name="AllLog" xsi:type="File"
            fileName="E:\Logs\PCC1\all.txt"
            archiveFileName="E:\Logs\PCC1\archives\all.{#####}.txt"
            archiveAboveSize="10240000"
            archiveNumbering="Sequence"
            concurrentWrites="false"
            keepFileOpen="true"/>

    <target name="RebusLog" xsi:type="File"
            fileName="E:\Logs\PCC1\rebus.txt"
            archiveFileName="E:\Logs\PCC1\archives\rebus.{#####}.txt"
            archiveAboveSize="10240000"
            archiveNumbering="Sequence"
            concurrentWrites="false"
            keepFileOpen="true"/>
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" maxlevel="Error" writeTo="AllLog" />
    <logger name="Default" minlevel="Debug" maxlevel="Error" writeTo="PrimaryLog" />
    <logger name="Rebus*" minlevel="Debug" maxlevel="Error" writeTo="RebusLog" />
  </rules>
</nlog>


```

**Comment by 304NotModified** [comment] 2015-04-16 19:17
Your description is very different to the initial bug Report.  Doesn't log at all or is auto reload not working?

**Comment by kubal5003** [comment] 2015-04-20 09:42
It's true that my description might be misleading. The full story is:
While deploying our application we are using Powershell to remove Nlog.config and then we're renaming NLog.DeploymentTemplate.config to NLog.config. Those files are pretty different and if the new one is not picked up by the application it's not going to be logging anything. The fact of not logging is caused solely by the fact that those files are very different (i.e. have different paths).

I hope that this explanation is a little better. If not I can provide more info.

**Comment by 304NotModified** [comment] 2015-04-23 19:10
Does the config works after restart of the Window service? 

- if not: there is something wrong with the config file (invalid xml for example) or a permission problem (check the Windows account where the Windows service is running under)
- if it works after restart: maybe 'touch' (small edit, change datetime) of the config?

**Comment by kubal5003** [comment] 2015-04-23 20:33
It does work after restart. I will try to modify the scripts to do this and I wouldn't be surprised to see if it works. If this is the case then maybe there's something wrong with the FileSystemWatcher?

**Comment by kubal5003** [comment] 2015-04-23 21:04
I did investigate the source code of NLog. If `MultiFileWatcher` is the class that is used to get notifications about configuration then it has a bug. I did a PoC and with the current filter flags the Delete & Create events are never raised. The fix is to add filter flag: `NotifyFilters.FileName`. 

That means that when we're deleting a file and later renaming another one to Nlog.config no events are going to be raised and hence configuration is not going to be reloaded.

**Comment by 304NotModified** [comment] 2015-04-23 21:08
Thanks for looking at this. I now understand also your issue. 

It seems a good thing to fix it. Can you create a PR for this?

**Comment by kubal5003** [comment] 2015-04-23 21:22
This requires a little more attention and testing to make sure that the fix doesn't break something else. I can imagine Nlog configuration reloading if another file in the directory changes.. I'll work on this next week and create a PR when I'm confident I didn't break it.

**Comment by 304NotModified** [comment] 2015-07-19 07:53
Hi @kubal5003

Any results on this? 

I think your proposed chsnfe

**Comment by 304NotModified** [comment] 2015-07-19 08:07
Ps http://www.codeproject.com/Articles/58741/FileSystemWatcher-Pure-Chaos-Part-of

**Comment by 304NotModified** [comment] 2015-07-23 21:41
@kubal5003 I have created an unit test, but it won't fail.  Do you know why? https://github.com/NLog/NLog/pull/813

**Comment by kubal5003** [comment] 2015-07-23 21:45
Sorry for not taking care of it recently. I'm back on the project where it was issue right now, so I should be able to take care of this soon.

**Comment by 304NotModified** [comment] 2015-07-25 10:10
Thanks for the feedback!

**Comment by 304NotModified** [comment] 2015-08-14 18:23
@kubal5003 Any luck?

**Comment by bhaeussermann** [comment] 2015-12-27 14:02
@304NotModified I created a test application in an attempt produce the issue, and I can't find it either. The test application logs continuously. While it does so, I delete the config file and copy a different config file to the same file path. The application reloads the new config successfully.

However, when I first delete the config file before starting the application, there is no logging, which is expected. If I then copy the config file to the correct file path, it is not loaded (there is still no logging). No exceptions occur in the application. @kubal5003 could this be what is happening with your Windows service (config file does not exist upon service-start)?

**Comment by 304NotModified** [comment] 2015-12-27 15:08
I think that makes sense. Autoreload is off by default,  and when it's off it will never go (automatically) on.

**Comment by snakefoot** [comment] 2019-05-02 21:47
@304NotModified  #1878 actually fixes something in `MultiFileWatcher`. It is adding this line:

`watcher.Renamed += OnFileChanged;`

So maybe this issue has been resolved with NLog 4.4.2.

**Comment by 304NotModified** [comment] 2019-05-02 22:23
OK, I assume its fixed. Latest response is years ago.

**Closed by 304NotModified** 2019-05-02 22:23 UTC
Labels: bug, code proposed, could Have, nlog-configuration, up-for-grabs
