### ISSUE TITLE
Use TestContext.Progress logging method from NUnit

### ISSUE THREAD

**Issue by LiohAu** [NLog/NLog#4198] opened 2020-12-09 22:16 UTC
Hello,

I have a lot of existing code that uses Debug / Info / Error methods, and I would like to redirect those logs to the TestContext.Progress TextWriter provided by NUnit (because this one is buffering standard output, and only that TextWriter is able to avoid NUnit buffering), is there a simple way to achieve that ?

Thanks.

**Comment by snakefoot** [comment] 2020-12-09 22:27
Maybe something like this:

```c#
using NUnit.Framework;

        var logger = LogManager.Setup().LoadConfiguration(builder => {
              var target = new MethodCallTarget("MyTarget", (logEvent,parms) => 
 TestContext.Progress.WriteLine(logEvent.FormattedMessage));
              builder.Configuration.AddRuleForAllLevels(target);
        }).GetCurrentClassLogger();
        logger.Info("log message");
```

Can also use NLog.config and have the MethodCallTarget point to a static-method. See also https://github.com/NLog/NLog/wiki/MethodCall-target

Alternative create your own [custom NLog Target](https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target) that writes to `TestContext.Progress`

**Comment by LiohAu** [comment] 2020-12-10 08:35
OK That's what I did (the way using an NLog target in config file).

Anyway that does not solve my problem, output is still buffered, I don't know if it's NUnit, NUnitAdapter, or Visual Studio Mac, but I get the output at the end of my tests....

**Comment by snakefoot** [comment] 2020-12-10 11:29
Then it sounds like NLog is working as intended, and it is an external problem.

Maybe ask on StackOverflow, since this place is mostly for issues about NLog.

**Comment by 304NotModified** [comment] 2020-12-29 00:01
Closing this as there is nothing to do for use here

**Closed by 304NotModified** 2020-12-29 00:01 UTC
Labels: external, question
