### ISSUE TITLE
Nlog does not perform zipping of archived files if the log file contains a date stamp

### ISSUE THREAD

**Issue by RonnyTechie** [NLog/NLog#3565] opened 2019-08-26 17:04 UTC
Hi Team,
Currently I am replacing my existing logging framework with Nlog.
However, I found that if the log file name contains date stamp, then the zipping of those files are not performed.
I could not understand the logic behind it.

A similar post is :
https://github.com/NLog/NLog/issues/1271

I just don't understand if it was ever fixed.

Versions tries: 4.5.10 & 4.6.x

**Comment by RonnyTechie** [comment] 2019-08-26 17:11
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-Logger" xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd" autoReload="true" throwExceptions="true" internalLogLevel="Off" internalLogFile="C:\\temp\\nloginternallog.log">
  
  <variable name="appName" value="Test" />
  
  <targets>
    <target xsi:type="AsyncWrapper" name="Wrapper" overflowAction="Grow">
    <target xsi:type="File" name="logfile" fileName="D:\Sample\TestApp_${longdate}.log" 
            layout="${date:format=dd/MM/yyyy hh\:mm\:ss.fff} - [${machinename}] - ${level:uppercase=true}: [${threadid}] ${message}${onexception:${newline}EXCEPTION\: ${exception:format=ToString}}"
            archiveOldFileOnStartup="true" ArchiveNumbering="Date"
            archiveFileName="D:\Sample\TestApp_{#}.log.zip"
            keepFileOpen="true"
            concurrentWrites="false"
            maxArchiveFiles="0"
            archiveAboveSize="1024"
            archiveDateFormat="yyyy-MM-dd hh.mm.ss.fff"
            enableArchiveFileCompression="true"
            />
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="Wrapper"/>
  </rules>
</nlog>

**Comment by 304NotModified** [comment] 2019-08-26 17:48
> I just don't understand if it was ever fixed.

It was fixed in NLog 4.3, see https://github.com/NLog/NLog/pull/1274

**Comment by 304NotModified** [comment] 2019-08-26 21:38
Could you please check the internal log? Please post the it on the trace level.

**Comment by RonnyTechie** [comment] 2019-08-27 05:53
> Could you please check the internal log? Please post the it on the trace level.
Upon testing it again and giving it more time to log, the issue does not seem to happen.
I guess initially I did not give it enough time to zip-up the  things.

However, what I now found that :
Sometimes, upon log rollover, the log file does not change even though I append my filename with 
${date:format=dd-MM-yyyy_hh-mm-ss.fff_tt}.log

So what happens is that 
My current file name say is Test_27-08-2019_11-17-08.058_AM.log
The compressed zipped file name is Test_27-08-2019_11-17-08.558_AM.log.zip
Now the current file name also uses the Test_27-08-2019_11-17-08.058_AM.log as filename.

And it happens irregularly.

Do you suggest to tweak settings for :
keepFileOpen & concurrentWrites
[internal_log_file.txt](https://github.com/NLog/NLog/files/3544490/internal_log_file.txt)

**Comment by RonnyTechie** [comment] 2019-08-27 08:25
Additionally, while browsing through the internal log file (from different run), I found that the below event is logged twise:
2019-08-27 13:49:02.8854 Debug FileTarget(Name=logfile): Process file 'D:\SampleProjects\PerformantLogging\OutPutLog\Test_27-08-2019_01-49-02.600_PM.log' on startup
I am not an expert at this, but doesn't it mean that Nlog is trying to use the same filename for subsequent logging post archiving??

**Comment by RonnyTechie** [comment] 2019-08-27 10:15
Hey...
I am very new to Nlog hence getting too many doubts.
After a long day of searches and blog browsing...I got my many doubts cleared except the below:


In my existing way of logging (using home grown tool), I follow the below approach in synchronous way:
1. Write log in current file say test.log
2. Once it reached 25 MB, I rename it to Test_<<TimeStamp>>.log
3. Use test.log for new current file.
3. And then zip the renamed file (step 2) on a background thread as Test_<<TimeStamp>>.log.gz

Is there any way to achieve the above behavior using NLog framework??
Any help will be appreciated.

**Comment by snakefoot** [comment] 2019-08-27 15:38
Think the problem is having `${longdate}` in fileName:

`fileName="D:\Sample\TestApp_${longdate}.log"`

This is not currently supported with NLog File-Archive-Logic. See also duplicate of #2523 and #3455

**Closed** 2019-09-02 21:38 UTC
Labels: duplicate, file-archiving, file-target, needs info
