### ISSUE TITLE
Extensions in configuration needs to be first element to get it working

### ISSUE THREAD

**Issue by AndiRudi** [NLog/NLog#302] opened 2014-01-27 15:47 UTC
Hi,

when the extensions tag of the xml configuration is below the rules and targets the targets it isn't found and a exception is logged in the internal logging of nlog. This drove me crazy because I had the extensions for loggly registered using a web.config transformation and that transformation puts the extension tag always at the end. 

Andi

**Comment by 304NotModified** [comment] 2015-03-30 15:20
developers hint: unit test this issue and probably should be fixed in https://github.com/NLog/NLog/blob/master/src/NLog/Config/XmlLoggingConfiguration.cs

**Comment by Xharze** [comment] 2015-06-15 09:29
@AndiRudi Could you provide a sample, I can't reproduce this issue in a unit test

**Comment by 304NotModified** [comment] 2015-06-15 09:38
I think this is also fixed, I tested this before.

**Comment by 304NotModified** [comment] 2015-06-15 09:39
Proposal: submit the unit test and close

**Comment by AndiRudi** [comment] 2015-06-15 10:06
I'm sorry I am not using loggly anymore so I don't have an example.

Von: Kim Christensen [mailto:notifications@github.com]
Gesendet: Montag, 15. Juni 2015 11:29
An: NLog/NLog
Cc: AndiRudi
Betreff: Re: [NLog] Extensions in configuration is order dependent (#302)


@AndiRudi<http://t.senalquatro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2BW0lbW3N1t6q63RLpRVdDPP256dQ06f3q194d02?t=https%3a%2f%2fgithub.com%2fAndiRudi&si=6278067075416064&pi=40a3c234-7689-4997-97b0-a3fe1373a3c1> Could you provide a sample, I can't reproduce this issue in a unit test

-

**Comment by 304NotModified** [comment] 2015-06-15 20:01
Can confirm this and the cause of this problem is really clear:


In `XMLloggingConfiguration.ParseNLogElement()`

```c#
 foreach (var el in nlogElement.Children)
            {
                switch (el.LocalName.ToUpper(CultureInfo.InvariantCulture))
                {
                    case "EXTENSIONS":
                        this.ParseExtensionsElement(el, baseDirectory);
                        break;

                    case "INCLUDE":
                        this.ParseIncludeElement(el, baseDirectory);
                        break;

                    case "APPENDERS":
                    case "TARGETS":
                        this.ParseTargetsElement(el);
                        break;

                    case "VARIABLE":
                        this.ParseVariableElement(el);
                        break;

                    case "RULES":
                        this.ParseRulesElement(el, this.LoggingRules);
                        break;

                    case "TIME":
                        this.ParseTimeElement(el);
                        break;

                    default:
                        InternalLogger.Warn("Skipping unknown node: {0}", el.LocalName);
                        break;
                }
```


This "nice" switch walks every top element, like targets en extensions.

But if the `<extensions>` are not before the `<targets>`, this can give problems when parsing the targets! 

The most basic version of an unit test won't work, because AFTER the whole read, the extensions are loaded.

**Closed** 2015-07-23 22:27 UTC
Labels: bug, should Have, up-for-grabs
