### ISSUE TITLE
Nlog - NLog.NLogRuntimeException - Asynchronous exception has occurred

### ISSUE THREAD

**Issue by Praveen-A-Maxval** [NLog/NLog#3900] opened 2020-04-17 07:45 UTC
This error happens from the URL deployed in IIS (ASP.NET MVC). After few hits we are receiving exception from Nlog. Can you please advise the fix for this.
[NLog.Internal.txt](https://github.com/NLog/NLog/files/4491621/NLog.Internal.txt)

Nlog Version - 4.6.2   .NET version - 4.5.2

Nlog Config  - 
```
<?xml version="1.0" encoding="utf-8"?>
<nlog throwexceptions="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<variable name="directory" value="D:/Logs/" /> <!--This denotes the directory where the log files will be created-->
    <targets>
	    <target name="file" xsi:type="File" fileName="${directory}/${event-properties:item=ProductName}/${event-properties:item=FileName}"
      layout="[${longdate}][${level:uppercase=true}][${message}]" /> 
    </targets>
    <rules>
	   <logger name="*" minlevel="Debug"  writeTo="file" enabled="true" /> 
    </rules>
</nlog>
```

Error - 
Error with flush. Exception: NLog.NLogRuntimeException: Asynchronous exception has occurred. ---> System.TimeoutException: Timeout.
   --- End of inner exception stack trace ---
   at NLog.Common.AsyncHelpers.RunSynchronously(AsynchronousAction action)
   at NLog.LogFactory.Flush(TimeSpan timeout)

**Comment by snakefoot** [comment] 2020-04-17 11:46
Very confusing that your attached `NLog.Internal.txt` nicely shows that you are using this NLog-target:

https://www.nuget.org/packages/NLog.Targets.Syslog/

But the NLog.config you have attached to the issue is different. It makes it difficult to help you when you give wrong information.

There is a bug in NLog.Targets.Syslog that has been fixed with: https://github.com/luigiberrettini/NLog.Targets.Syslog/pull/201

Sadly enough no release has been made yet. Think you should close this issue and instead create a new issue at:

https://github.com/luigiberrettini/NLog.Targets.Syslog

Unless you can reproduce the issue without using `NLog.Targets.Syslog` ?

**Closed** 2020-04-24 11:46 UTC
Labels: external, needs info, question
