### ISSUE TITLE
File does not have nested messages and when trying to serialize I get error.

### ISSUE THREAD

**Issue by RickC10** [NLog/NLog#4048] opened 2020-07-19 00:53 UTC
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**NLog version**: 4.7.2

**Platform**: .Framewokr 4.6.1
**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  <!-- optional, add some variables
  https://github.com/nlog/NLog/wiki/Configuration-file#variables
  -->
  <variable name="myvar" value="myvalue"/>

  <!--
  See https://github.com/nlog/nlog/wiki/Configuration-file
  for information on customizing logging rules and outputs.
   -->
  <targets>

    <target xsi:type="File" name="GeneralInfo" fileName="${basedir}/Info.log">
      <layout xsi:type="JsonLayout" includeAllProperties="true">
        <attribute name="Logger" layout="${logger}" />
        <attribute name="UserIdentity" layout="${windows-identity}" />
        <attribute name="CorrelcationID" layout="${activityid}" />
        <attribute name="CallSite" layout="${callsite}" />
        <attribute name="LineNumber" layout="${callsite-linenumber}" />
        <attribute name="DateTime" layout="${longdate}" />
        <attribute name="Level" layout="${level:upperCase=true}"/>
        <attribute name="Message" layout="${message}" />
        <!--<attribute name="Properties" encode="false">
          <layout xsi:type="JsonLayout" includeAllProperties="true"/>
        </attribute>-->
      </layout>
    </target>

  </targets>

  <rules>
    <logger name="*" writeTo="GeneralInfo"/>

  </rules>
</nlog>
```
- What is the current result
```json
{
  "Logger": "General",
  "UserIdentity": "FNFIS\\e5617394",
  "CallSite": "WindowsFormsApp1.Form1.button1_Click",
  "LineNumber": "26",
  "DateTime": "2020-07-18 19:49:30.8885",
  "Level": "TRACE",
  "Message": "Trace -The content of the Person class:{\"FirstName\":\"Rick\", \"LastName\":\"Castro\", \"Address\":\"212121 Main CT, Chicago, IL\"}",
  "Person": {
    "FirstName": "Rick",
    "LastName": "Castro",
    "Address": "212121 Main CT, Chicago, IL"
  },
  "Application": "JobTracker"
} {
  "Logger": "General",
  "UserIdentity": "FNFIS\\e5617394",
  "CallSite": "WindowsFormsApp1.Form1.button1_Click",
  "LineNumber": "27",
  "DateTime": "2020-07-18 19:49:30.9753",
  "Level": "TRACE",
  "Message": "Trace -The content of the Person class:{\"FirstName\":\"Rick\", \"LastName\":\"Castro\", \"Address\":\"212121 Main CT, Chicago, IL\"}",
  "Person": {
    "FirstName": "Rick",
    "LastName": "Castro",
    "Address": "212121 Main CT, Chicago, IL"
  },
  "Application": "JobTracker"
}
```
----------------Code to create the logs
```c#
  private void button1_Click(object sender, EventArgs e)
        {
            Person p = new Person();
            p.FirstName = "Rick";
            p.LastName = "Castro";
            p.Address = "212121 Main CT, Chicago, IL";


            Logger log = LogManager.GetLogger("General");
            log.WithProperty("Application", "JobTracker").Trace("Trace -The content of the Person class:{@Person}",p);
            log.WithProperty("Application", "JobTracker").Trace("Trace -The content of the Person class:{@Person}",p);
     
        }
```

- What is the expected result?
Using Json.net to read data from file. 
`      JObject jO = JObject.Parse(File.ReadAllText(@"C:\Personal\Training\Logging\WindowFormFramework\WindowsFormsApp1\WindowsFormsApp1\bin\Debug\Info.log"));`
        
As you can see above the json is malformed. There should be a comma between objects and it should be an array of messages. 
I'm thinking like this
```json
[
{Log 1},
{Log 2}
]
```

Is there a way to create nested log entries?  Or is my approach incorrect?

**Comment by snakefoot** [comment] 2020-07-21 16:45
Sounds like a duplicate of #1658

**Closed** 2020-08-01 09:57 UTC
Labels: duplicate, json / json-layout, question
