### ISSUE TITLE
NLog does not write any lines when the code is inside a socket thread

### ISSUE THREAD

**Issue by lluisga** [NLog/NLog#4276] opened 2021-02-02 09:22 UTC
Hello, I have been struggling over the last few days due to the following issue. I've tried to look it up on several forums but all similar issues I found do not seem to be the one I am experiencing.

The application affected is a C# .NET (I've tried both with .NET 4.6.1 and 4.8) application which currently uses NLog 4.7.7 Nuget package in order to create several log files. I've upgraded the NLog package to the latest version in order to make sure the issue was not already solved in previous upgrades and it is therefore also reproducible in previous versions.

The application runs on Windows 10 Enterprise. The issue is also reproducible on Windows Server 2016 Standard.

I've tried with several NLog.config settings, but with a very simple one the issue can be reproduced. An example of such NLog.config would be the following:

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">	  
  <targets>  
            <target name="Socket_f" 
			xsi:type="File" 
			fileName="${basedir}/log/MachineProtocolSocket_${date:format=dd-MM-yyyy}.log"			 
            layout="${date:format=dd/MM/yyyy HH\:mm\:ss} ${message}"/>
  </targets>
  <rules>
	<logger name="Socket" minlevel="Trace" writeTo="Socket_f" />	
  </rules>
</nlog>
```

I am using a unique Logger for the whole application defined in the App.xaml.cs file as such:

public static Logger _Nlogger = LogManager.GetLogger("Socket");

Which is used in the application through methods such as: App._Nlogger.Info("whatever message");

The thing is that this logs are correctly written only as long as I am not using them inside on of the application socket threads implemented using the Socket .NET class.

I've also tried changing the folder where the log is saved and I've tried using concurrentWrites="true", autoFlush="true" and keepFileOpen="true" with the same result. Also tried to use AsyncWrapper with no success too. It also does not seem to be permession issue, since it also happens when running the application as Admin.

When I enable internalLogFile the file is correctly created and written even for the lines that afterwards do not appear in the log, but I am not able to see any particular error, even if enable throwConfigExceptions="true" and throwExceptions="true".

If I show in the log lines Identity: ${identity} notauth:: is shown, but these does not seem to impede the lines outside the socket threads to be written. Also using LogManager.Flush() does not get the lines written.

The lines that are not written into the log file are the ones that appear in the code inside the methods that are directly accessed by the application only as a result of incoming messages that the socket is listening to.

Another odd thing is that this logging was actually working fine several months ago and has starting having this particular behaviour from a certain point on. So I don't exclude the possibility that the issue comes from a certain Windows upgrade or something similar.

Has anyone faced anything of the kind? If you need any kind of extra information, log or test on my side please do not hesitate to tell me.

Thanks and regards.

**Comment by snakefoot** [comment] 2021-02-02 21:15
This is just me guessing but I think the problem is the configuration of your NLog FileTarget.

The NLog FileTarget uses `keepFileOpen="false"` by default, which means it can only handle 200 logevents/sec. If you change to `keepFileOpen="true"` then it will be faster.

I'm guessing that you have multiple threads in your application, since you are dealing with socket operations. By default NLog is synchronous, so when calling the NLog Logger, then the application-thread will be stuck until target write has completed. If having more than 2 threads writing to the same NLog target, then performance of those threads will suffer. If you change to `<targets async="true">` then NLog will not be blocking application threads.

Try using this NLog.config instead:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">	  
  <targets async="true">  
            <target name="Socket_f" 
			xsi:type="File" 
                        keepFileOpen="true"
                        concurrentWrites="false"
			fileName="${basedir}/log/MachineProtocolSocket_${date:format=dd-MM-yyyy}.log"			 
            layout="${date:format=dd/MM/yyyy HH\:mm\:ss} ${message}"/>
  </targets>
  <rules>
	<logger name="Socket" minlevel="Trace" writeTo="Socket_f" />	
  </rules>
</nlog>
```

See also: https://github.com/NLog/NLog/wiki/Performance#file-logging-performance

**Comment by lluisga** [comment] 2021-02-03 12:14
Hello snakefoot, and thanks for your answer.

I had already played around with async and keepfileopen options, and I have retested everything with the NLog.config you propose and the result is the same.

I have also reread the links you provide and I think in this case the code mostly follows the recommendations. Flushing and shuting down also does not write the missing lines either.

The application only deals with one Socket thread, not many, and at that point, I don't think that the issue might be related to NLog synchronization issues, since as I said, on the one side this logging worked ok previously in Windows 7 systems and because the logs written outside the thread keep also being written without issues.

I am more keen to think that the issue might be related to some Windows 10 or .NET update regarding thread functionality, or something of the kind. This is why, after many attempts, I thought about sharing the situation here in order to see if someone might also have faced or is currently facing the same issue.

I will keep doing tests with that in mind and I will share here whatever I may find, if on the meanwhile someone has any other ideas they are more then welcome :)

**Comment by snakefoot** [comment] 2021-02-03 18:48
If you can provide some example project that can reproduce the issue. Then please post it here.

**Comment by snakefoot** [comment] 2021-02-05 11:14
Closing the issues, but if you are able to make an example project that reproduces the issue, then please tell.

**Closed by snakefoot** 2021-02-05 11:14 UTC
Labels: file-target, needs info, question

**Comment by lluisga** [comment] 2021-02-05 11:57
![image](https://user-images.githubusercontent.com/78408060/107029992-38d01c80-67b0-11eb-8cab-29d7cf2be12f.png)
![image](https://user-images.githubusercontent.com/78408060/107030042-47b6cf00-67b0-11eb-88cd-2d10e31605b4.png)

Sorry for recommenting. I am trying to generate a small couple of client-server socket projects where I can consistently reproduce the issue. Maybe on the meanwhile I will be able to solve it myself thanks to that (and due to your suggestion).
What I can already tell you is that the issue has to do with the fact that for some reason the isdebugenabled, istraceenabled and iswarnenabled properties are automatically set to false after a certain period of time apparently, in spite of the content of the NLog.config file. I attach two screenshots of the different behaviour. Since I cannot manually set the value of these properties from the code (they are getters but not setters, or they are readonly) I am not sure on how to solve it and what is causing it, but I'll keep investigating it and eventully I'll post here the progress or solution if I find it. A quick googling has only thrown one post with practically the same unsolved issue in StackOverFlow, I leave it here too just for the sake of completeness: https://stackoverflow.com/questions/63790335/nlog-isdebugenabled-and-all-otheres-are-false

Thanks for your help, I'll keep you posted (and if you prefer to keep the issue closed on the meanwhile unless you have to something to say about it no problem either).

**Comment by snakefoot** [comment] 2021-02-06 07:56
I can see that the logger-name has changed between the two screenshots:
- UMA_AppSockets.LiteAsynchronousSocketListener
- AppSockets.LiteAsynchronousSocketListener
Maybe that is causing the "automatically" change in `IsDebugEnabled`

**Comment by lluisga** [comment] 2021-02-08 16:51
Hello again and thanks for your message.
Sorry about this. That was my bad because I am trying to reproduce the issue in several different projects in order to see if I can find out the root cause of it. I attach again the same screenshots corresponding to same piece of code of the same project before and after the automatic change I am refering to:
![image](https://user-images.githubusercontent.com/78408060/107252934-1b13e900-6a36-11eb-968d-3f44a164ce62.png)
![image](https://user-images.githubusercontent.com/78408060/107252982-26ffab00-6a36-11eb-8230-7f341c17876a.png)
I haven't still been able to find it out, but I will post here any progress I might make.

Thanks again

**Comment by snakefoot** [comment] 2021-02-08 21:41
That looks very weird. Curious if you could show the Logger.Factory.Configuration-property for those two cases.

I would guess that one of your dependencies is taking over the NLog-Configuration, and replaces it with something different.

**Comment by lluisga** [comment] 2021-02-09 14:08
Hello again and thanks for your answer.

It is weird indeed, yes. I attach new screenshots of the Factory.Configuration property before and after. Effectively many values of its content seem to change too, including FileNamesToWatch, which afterwards seems to be empty:
![image](https://user-images.githubusercontent.com/78408060/107374903-68e92980-6ae8-11eb-8dc5-ef7f2af3b59a.png)
![image](https://user-images.githubusercontent.com/78408060/107374912-6d154700-6ae8-11eb-9e43-b68245f2d9aa.png)
I can now reproduce the situation pretty easily so do not hesitate to ask me any other information you may need.

Thanks again

**Comment by snakefoot** [comment] 2021-02-09 17:38
I guess you should enable the [NLog InternalLogger](https://github.com/NLog/NLog/wiki/Internal-Logging) on Debug.Level and see what happens between those two screenshots.
