### ISSUE TITLE
The separator between seconds and milliseconds is culture independent in date and longdate layouts

### ISSUE THREAD

**Issue by Ryzhikh-Roman** [NLog/NLog#5476] opened 2024-02-27 13:36 UTC
**NLog version**: 5.2.8

**Platform**: .NET 4.5.2

**Current NLog config** 

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  internalLogLevel="Debug"
      internalLogFile="c:\temp\nlog-internal.txt"
      internalLogToConsole="false"
      throwConfigExceptions="true">
	<targets>
		<target
			name ="AsyncTrimCSV"
			xsi:type="AsyncWrapper"
			timeToSleepBetweenBatches="0"
			batchSize="200"
			queueLimit="10000"
			overflowAction="Block">
			<target
					  xsi:type="File"
					  encoding="utf-8"
					  fileName="${basedir}/Logs/ResistorAdjustment/${shortdate}.csv"
					  keepFileOpen="False"
					  concurrentWrites="True"
					  maxArchiveDays="730">
				<layout xsi:type="CsvLayout">
					<column name="Date" layout="${date}" />
					<column name="Time" layout="${time}" />
					<column name="Filename" layout="${event-properties:item=filename}" />
					<column name="Resistor Serial Number" layout="${event-properties:item=ResistorSerialNumber}" />
					<column name="Resistor Value After Trim" layout="${event-properties:item=ResistorValueAfterTrim}" />
					<column name="Resistor Start Value" layout="${event-properties:item=ResistorStartValue}" />
					<column name="Target Resistor Value" layout="${event-properties:item=TargetResistorValue}" />
					<column name="Laser Precision" layout="${event-properties:item=LaserPrecision}" />
					<column name="Power" layout="${event-properties:item=Power}" />
					<column name="Speed" layout="${event-properties:item=Speed}" />
					<column name="Freq" layout="${event-properties:item=Freq}" />
					<column name="Pulse Width" layout="${event-properties:item=PulseWidth}" />
					<column name="Beam Wobble" layout="${event-properties:item=BeamWobble}" />
					<column name="Path To Image" layout="${event-properties:item=pathToImage}" />
				</layout>
			</target>
		</target>
		<target name="logfile" xsi:type="File" fileName="${basedir}/Logs/task.log"
				layout="${longdate} ${logger} ${event-properties:task_name} ${message}${exception:format=ToString}"/>
	</targets>
	<rules>
		<logger name="asynctrim" minlevel="Info" writeTo="AsyncTrimCSV" />
	</rules>
</nlog>

```

- What is the current result?
With "ru-RU" culture the date looks like this: 
2024.02.26 16:06:38.212
- What is the expected result?
2024.02.26 16:06:38,212
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes
- Please post full exception details (message, stacktrace, inner exceptions)
There are no exception
- Are there any workarounds? yes/no
Yes, for example "date:format=yyyy-MM-dd HH\:mm\:ss,fff", but this is works only for one culture and not for the others.
Also, you can separate the date and time, while the time works correctly with the culture
- Is there a version in which it did work? 
Didn't look
- Can you help us by writing an unit test?
I don't know how, but I'll try

By the way time layout works well with different cultures.

**Comment by snakefoot** [comment] 2024-02-27 16:37
Both `${date}` and `${time}` uses `public CultureInfo Culture { get; set; } = CultureInfo.InvariantCulture;` by default in NLog v5, unless one have specified LogEventInfor-FormatProvider (which probably should be fixed in NLog v6, so a layoutrenderer can override the LogEventInfor-FormatProvider).

It would be very helpful if you can write a small unit-test that reproduces the issue, or provide a simple code-example that shows how you are logging and reproduces the issue.

**Comment by Ryzhikh-Roman** [comment] 2024-03-01 11:17
**NLog.config**
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<targets>
		<target name="logconsole" xsi:type="Console"
				layout="${date} ${time} ${message}"/>
	</targets>
	<rules>
		<logger name="console" minlevel="Info" writeTo="logconsole" />
	</rules>
</nlog>
```

**Code Example**
```
void Test()
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("ru-RU");
            NLog.LogManager.Configuration.DefaultCultureInfo = Thread.CurrentThread.CurrentCulture;
            Console.WriteLine(Thread.CurrentThread.CurrentCulture.Name);
            Logger logger = NLog.LogManager.GetLogger("console");
            logger.Info("Not correct");

            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("en-EN");
            NLog.LogManager.Configuration.DefaultCultureInfo = Thread.CurrentThread.CurrentCulture;
            Console.WriteLine(Thread.CurrentThread.CurrentCulture.Name);
            logger.Info("Correct");
        }
```

**Result**
```
ru-RU
2024.03.01 14:14:34.587 14:14:34,5873 Not correct
en-EN
2024/03/01 14:14:34.603 14:14:34.6035 Correct
```

The only problem is separator between seconds and milliseconds. It's strange to see different separators in the same culture in date and time layout.

**Comment by snakefoot** [comment] 2024-03-02 12:52
Can see that `$[time}` + `${processtime}` was updated to have extra culture-support with #1556

The `${date}` uses the default `Format=yyyy/MM/dd HH:mm:ss.fff`, and it seems that `DateTime.ToString` only applies some culture adjustements (but not the milliseconds-seperator).

If you know how to make DateTime.ToString to also perform culture adjustment for the milliseconds-seperator, then pull-request are wellcome.

I guess a work-around could be: `${date:format=yyyy/MM/dd} ${time}`

**Comment by snakefoot** [comment] 2024-03-09 11:23
Closing due to inactivity.

**Closed by snakefoot** 2024-03-09 11:23 UTC
Labels: question
