### ISSUE TITLE
Problem with Target FormControl

### ISSUE THREAD

**Issue by Xharze** [NLog/NLog#147] opened 2012-10-07 18:01 UTC
Reported in the forum at post: http://nlog-project.org/forum.html#nabble-tc1685764|a1685764

Hi,

 i have a little problem with the target FormControl. I wrote a NLog.config with 3 targets ( File, Debugger, FormControl ). The logger writes successfull all messages to the targets File and Debugger, the FormControl target is ignored by the logger. I attached my config, and the internal Nlog log.

The FormControl is a ToolStripStatusLabel Control.

 I hope somebody have an idea, thx.

 NLog.config

nlog.log

**Comment by 304NotModified** [comment] 2015-05-20 20:07
Without more info why can't resolve this. Closing For now.

**Closed by 304NotModified** 2015-05-20 20:07 UTC
Labels: bug

**Comment by Fr33dan** [comment] 2021-09-16 18:23
I wanted a logging output to show my most recent error in the status strip of my UI and it didn't work. I experienced this "bug" and was going to attempt to reactivate this/file a new one for the same thing. Although it may belong in the [NLog.Windows.Forms](https://github.com/NLog/NLog.Windows.Forms) project. In doing my due diligence to have any the information needed to diagnose it, I diagnosed it.

Turning on a higher internal logging level I can see it can't find my control on my form:
`2021-09-16 10:36:43.6446 Info Control programStatusLabel on Form ProgrammerForm not found`

I switched from a ToolStripStatusLabel to a regular Label on my form and it worked fine. I suspected this is related to the fact that ToolStripStatusLabel controls are actually parented to a StatusStrip rather than the form directly. In an effort to check I tried a ToolStripMenuItem and ToolStripTextBox which are similarly parented to a MenuStrip. All resulted in the same error.

So I did some investigating and the problem is that Both StatusStrip and MenuStrip extend ToolStrip which managed their children as Items instead of Controls. ToolStripStatusLabel isn't even an extension of Control.

Thus I ended up creating a target that I that could fill a ToolStripStatusLabel, resulting in pull request #4566 and pull request #87 on the NLog.Windows.Forms project.
