### ISSUE TITLE
Issues with UNC Path

### ISSUE THREAD

**Issue by kfuller002** [NLog/NLog#840] opened 2015-08-11 17:49 UTC
When being ran from a UNC path (even on the same machine) it maps the path incorrectly.  Mapping a drive resolves the issue, but it needs to work without the drive mapping for service accounts/non-interactive processes.

**Comment by kfuller002** [comment] 2015-08-12 16:23
This works in 4.0.0 but not in 4.0.1, below is the error we received.

Error:
Unhandled Exception: System.Configuration.ConfigurationErrorsException: An error
 occurred creating the configuration section handler for nlog: The type initiali
zer for 'NLog.Config.ConfigurationItemFactory' threw an exception. (\\computer\c$\
Feed2\FeedGenerator.exe.Config line 56) ---> System.TypeInitializationException:
 The type initializer for 'NLog.Config.ConfigurationItemFactory' threw an except
ion. ---> System.IO.DirectoryNotFoundException: Could not find a part of the pat
h 'C:\c$\Feed2'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String origina
lUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`
1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
   at NLog.Config.ConfigurationItemFactory..cctor()
   --- End of inner exception stack trace ---
   at NLog.Config.ConfigurationItemFactory.get_Default()
   at NLog.Config.XmlLoggingConfiguration..ctor(XmlElement element, String fileN
ame)
   at NLog.Config.ConfigSectionHandler.Create(XmlNode section, IAppDomain appDom
ain)
   at NLog.Config.ConfigSectionHandler.System.Configuration.IConfigurationSectio
nHandler.Create(Object parent, Object configContext, XmlNode section)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactor
y.CreateSectionImpl(RuntimeConfigurationRecord configRecord, FactoryRecord facto
ryRecord, SectionRecord sectionRecord, Object parentConfig, ConfigXmlReader read
er)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactor
y.CreateSectionWithRestrictedPermissions(RuntimeConfigurationRecord configRecord
, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentConfig,
 ConfigXmlReader reader)
   at System.Configuration.RuntimeConfigurationRecord.CreateSection(Boolean inpu
tIsTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object par
entConfig, ConfigXmlReader reader)
   at System.Configuration.BaseConfigurationRecord.CallCreateSection(Boolean inp
utIsTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object pa
rentConfig, ConfigXmlReader reader, String filename, Int32 line)
   --- End of inner exception stack trace ---
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, Se
ctionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord
sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factor
yRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boole
an getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String co
nfigKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Bool
ean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String co
nfigKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Bool
ean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String co
nfigKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Bool
ean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Intern
al.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at NLog.Config.XmlLoggingConfiguration.get_AppConfig()
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name)
   at NLog.LogManager.GetCurrentClassLogger()
   at FeedGenerator.Helpers.LogHelper..ctor() in C:\TFS\Company\Company\FeedGenerator\Helpers\LogHelper.cs:line 17
   at FeedGenerator.Program.Main(String[] args) in C:\TFS\Company\Company\FeedGenerator\Program.cs:line 39

**Comment by 304NotModified** [comment] 2015-08-12 19:00
Sorry. The unc bug us introduced in 4.0.1 and will be fixed in 4.1

**Comment by 304NotModified** [comment] 2015-08-13 20:47
duplicate of https://github.com/NLog/NLog/issues/793

**Comment by 304NotModified** [comment] 2015-08-26 21:30
fixed in 4.1

**Closed by 304NotModified** 2015-08-26 21:30 UTC
Labels: almost ready, bug, duplicate
