### ISSUE TITLE
BufferingWrapper Async with Flush got Asynchronous exception has occurred.

### ISSUE THREAD

**Issue by KennethWKZ** [NLog/NLog#1976] opened 2017-02-20 02:47 UTC
**Type** (choose one):

- Bug

**NLog version**: 4.4.3

**Platform**: .Net 4.5 

**Current NLog config** (xml or C#, if relevant)

```C#
            // Step 1. Create configuration object 
            var config = new LoggingConfiguration();

            // Step 2. Create targets and add them to the configuration
            CloudWatchLogsTarget cloudWatchLogsTarget;
                cloudWatchLogsTarget = new CloudWatchLogsTarget
                {
                    LogGroupName = cloudWatchLogConfig.LogGroupName,
                    LogStreamName = cloudWatchLogConfig.LogStreamName + "-InternalLog",
                    AWSRegion = cloudWatchLogConfig.AWSRegion,
                    Name = "CloudWatchErrors",
                    Layout = InternalLogLayoutTemplate(logObject),
                    OptimizeBufferReuse = true
                };


            var bufferingWrapper = new BufferingTargetWrapper(cloudWatchLogsTarget)
            {
                Name = "ErrorsBuffering",
                SlidingTimeout = true,
                BufferSize = 10000,
                FlushTimeout = 60000
            };

            // Step 3. Set target properties
            config.AddTarget("CloudWatchErrorsBufferingTarget", bufferingWrapper);

            // Step 4. Define rules
            var rule1 = new LoggingRule("*", LogLevel.Error, LogLevel.Fatal, bufferingWrapper) { Final = true };
            config.LoggingRules.Add(rule1);

            // Step 5. Activate the configuration
            LogManager.Configuration = config;
            LogManager.ThrowExceptions = cloudWatchLogConfig.ThrowExceptions;

```

In case of a BUG:

- What is the current result?
Asynchronous exception has occurred. When Flush.

- Please post full exception details (message, stacktrace, inner exceptions)
```json
{
	"internalException": {
		"type": "NLog.NLogRuntimeException",
		"message": "Asynchronous exception has occurred.",
		"method": "Void RunSynchronously(NLog.Common.AsynchronousAction)",
		"data": "NLog.NLogRuntimeException: Asynchronous exception has occurred. ---> System.TimeoutException: Timeout.\r\n   --- End of inner exception stack trace ---\r\n   at NLog.Common.AsyncHelpers.RunSynchronously(AsynchronousAction action)\r\n   at NLog.LogFactory.Flush(TimeSpan timeout)\r\n   at NLog.LogFactory.Flush()\r\n   at NLog.LogFactory.set_Configuration(LoggingConfiguration value)\r\n   at NLog.LogManager.set_Configuration(LoggingConfiguration value)\r\n   at NLogComponent.LogCloudWatchConfig(LogObject logObject, CloudWatchLogConfig cloudWatchLogConfig)\r\n   at LogComponent.LogToCloudWatch(LogObject logObject, CloudWatchLogConfig cloudWatchLogConfig) ",
		"stackTrace": "   at NLog.Common.AsyncHelpers.RunSynchronously(AsynchronousAction action)\r\n   at NLog.LogFactory.Flush(TimeSpan timeout)\r\n   at NLog.LogFactory.Flush()\r\n   at NLog.LogFactory.set_Configuration(LoggingConfiguration value)\r\n   at NLog.LogManager.set_Configuration(LoggingConfiguration value)\r\n   at NLogComponent.LogCloudWatchConfig(LogObject logObject, CloudWatchLogConfig cloudWatchLogConfig)\r\n   at LogComponent.LogToCloudWatch(LogObject logObject, CloudWatchLogConfig cloudWatchLogConfig)",
		"innerException": {
			"type": "\r\nSystem.TimeoutException",
			"message": "\r\nTimeout.",
			"method": "\r\n",
			"data": "\r\nSystem.TimeoutException: Timeout.",
			"stackTrace": "\r\n"
		}
	}
}
```
- Are there any work arrounds? No
- Is there a version in which it did worked?  No

**Comment by 304NotModified** [comment] 2017-02-21 21:42
Where is the exception thrown in code? Is an exception excepted at all?

**Comment by KennethWKZ** [comment] 2017-02-22 10:01
It is too hard to trace where it thrown because it just happen few times when i doing load test for web service and running in async way. 

What we can see from the StackTrace from Exception details:
It throw when NLog trying to flushing my log - NLog.LogFactory.Flush(TimeSpan timeout). I not too sure is it because my web service is running in async way?

**Comment by 304NotModified** [comment] 2017-02-22 15:19
We it flushes and it takes more that 15 sec.

That will could the TimeoutException (innerexception).

You could flush manually with your own timeout to prevent is. 
e.g.

```c#
LogManager.Flush(TimeSpan.FromMinutes(2));
```

**Comment by snakefoot** [comment] 2017-02-22 20:17
@KennethWKZ Think you have to create a reproducable case. Either as unit-test or console-application.

I guess there is some custom logic implemented in LogComponent.LogToCloudWatch and NLogComponent.LogCloudWatchConfig. Any reason why the NLog-configuration is changed at runtime?

Any reason why you are using the CloudWatchLogsTarget instead of the official [ASW-NLog-Target](https://github.com/aws/aws-logging-dotnet) ?

**Comment by KennethWKZ** [comment] 2017-02-22 20:21
Is it code like this way?

```C#
var log = logObject.LogMapping(nLogConfig);
            LogManager.Configuration = nLogConfig.LogConfig(log.Severity); //This is BufferingWrapperTarget
            log.SetVariablesLayout(nLogConfig); //This is Var Layout Renderer
            LogManager.ThrowExceptions = nLogConfig.ThrowExceptions;
            //LogManager.Configuration = LogManager.Configuration.Reload(); //Question: Not sure this need or not?
            LogManager.ReconfigExistingLoggers(); //After set config then reconfigure again?
            try
            {
                Logger.Log(LogLevel.Debug, log.Exception, log.Message);
            }
            catch (Exception ex)
            {
                Logger.Error(ex, ex.Message);
            }

LogManager.Flush(TimeSpan.FromMinutes(2)); //Put at this line?

```

**Comment by KennethWKZ** [comment] 2017-02-22 20:31
@snakefoot Currently the official AWS CloudWatch Target still lack some feature such as configurable log stream name. That why i using another open source and it is working fine.

This is my LogComponent.LogToCloudWatch
```C#
private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

public void LogToCloudWatch(LogObject logObject, CloudWatchLogConfig cloudWatchLogConfig)
{
    var log = logObject.LogMapping(cloudWatchLogConfig);
            LogManager.Configuration = cloudWatchLogConfig.LogCloudWatchConfig(); //This is BufferingWrapperTarget
            log.SetVariablesLayout(cloudWatchLogConfig); //This is Var Layout Renderer
            LogManager.ThrowExceptions = cloudWatchLogConfig.ThrowExceptions;
            //LogManager.Configuration = LogManager.Configuration.Reload(); //Question: Not sure this need or not?
            LogManager.ReconfigExistingLoggers(); //After set config then reconfigure again?
            try
            {
                Logger.Log(LogLevel.Debug, log.Exception, log.Message);
            }
            catch (Exception ex)
            {
                Logger.Error(ex, ex.Message);
            }

           LogManager.Flush(TimeSpan.FromMinutes(2)); //Put at this line?
}
```

This is my NLogComponent.LogCloudWatchConfig
```C#
            // Step 1. Create configuration object 
            var config = new LoggingConfiguration();

            // Step 2. Create targets and add them to the configuration
            CloudWatchLogsTarget cloudWatchLogsTarget;
                cloudWatchLogsTarget = new CloudWatchLogsTarget
                {
                    LogGroupName = cloudWatchLogConfig.LogGroupName,
                    LogStreamName = cloudWatchLogConfig.LogStreamName + "-InternalLog",
                    AWSRegion = cloudWatchLogConfig.AWSRegion,
                    Name = "CloudWatchErrors",
                    Layout = InternalLogLayoutTemplate(logObject),
                    OptimizeBufferReuse = true
                };


            var bufferingWrapper = new BufferingTargetWrapper(cloudWatchLogsTarget)
            {
                Name = "ErrorsBuffering",
                SlidingTimeout = true,
                BufferSize = 10000,
                FlushTimeout = 60000
            };

            // Step 3. Set target properties
            config.AddTarget("CloudWatchErrorsBufferingTarget", bufferingWrapper);

            // Step 4. Define rules
            var rule1 = new LoggingRule("*", LogLevel.Error, LogLevel.Fatal, bufferingWrapper) { Final = true };
            config.LoggingRules.Add(rule1);

            // Step 5. Activate the configuration
            LogManager.Configuration = config;
```

**Comment by snakefoot** [comment] 2017-02-22 21:30
@KennethWKZ Normally one only assign the LogManager.Configuration once, since it has a huge overhead. And not for every log-event. Any reason why you assign it multiple times ?

**Comment by KennethWKZ** [comment] 2017-02-22 22:14
@snakefoot Could you explain more any ways to avoid assign LogManager.Configuration multiple times and still can change wrapper target value? And where should I put LogManager.Flush after/before? Thank you.

**Comment by snakefoot** [comment] 2017-02-22 23:04
@KennethWKZ No idea how your application works, but normally at application initialization then the NLog-Configuration is assigned (either on runtime or from config-file), and then left untouched. Flush is normally only needed when about to close the application.

**Comment by KennethWKZ** [comment] 2017-03-04 12:48
Any best practices production config for BufferingWrapper setting?

**Comment by 304NotModified** [comment] 2017-04-03 20:44
> Any best practices production config for BufferingWrapper setting?

Depends if you are afraid of high cpu, high mem in problematic cases ;)

**Comment by 304NotModified** [comment] 2017-04-16 16:25
Closing this due to inactivity. Please let us know if this still an issue and please provide the requested info.

**Closed by 304NotModified** 2017-04-16 16:25 UTC
Labels: question
