### ISSUE TITLE
NLog  doesn't delete old log files

### ISSUE THREAD

**Issue by HongJinJua** [NLog/NLog#3846] opened 2020-03-18 10:01 UTC
Issue (Question)

ASP.NET CORE Using NLog

I have some trouble , it doesn't delete old logs file.

"MaxArchiveFiles" and "maxArchiveDays" did not execute the action of deleting logs properly.

What I do wrong? Thanks!

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog
    xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    autoReload="true"
    internalLogLevel="info"
    internalLogFile="C:\Logs\testProject\nlog-internal.txt">

  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>


    <targets>
    <!-- write logs to file  -->
    <target xsi:type="File" name="ALL"
            fileName="C:\Logs\testProject\testProject.${cached:${date:format=yyyy-MM-dd}}.log"
            layout="${longdate}|${uppercase:${level}}|${threadid}|${logger}|${message} ${exception:format=ToString}" 
            maxArchiveFiles="20"
            archiveFileName="C:\Logs\testProject\testProject{#}.log"
            archiveDateFormat="yyyy-MM-dd"
            archiveAboveSize="104857600"
            archiveNumbering="DateAndSequence"
            maxArchiveDays="3"
            archiveEvery="Day"       
          />

    </targets>




    <rules>
        <logger name="*" minlevel="Trace" writeTo="ALL" /> 
    </rules>
</nlog>
```

**Comment by snakefoot** [comment] 2020-03-18 16:46
Duplicate of #3807. See [reply here](https://github.com/NLog/NLog/issues/3807#issuecomment-587661413)

**Comment by HongJinJua** [comment] 2020-03-19 01:47
Thanks for the team's answer!!

Currently know that "archiveEvery" can be removed.
"maxArchiveFiles" is functional.

Is the date identified by "maxArchiveDays" the date of the archive name or the date the file was generated?

**Comment by snakefoot** [comment] 2020-03-19 07:22
It just strips away all non-letters in filename so it this:

`C:\Logs\testProject\testProject.${cached:${date:format=yyyy-MM-dd}}.log`

Becomes this file-wildcard used for cleanup:

`C:\Logs\testProject\testProject.*.log`

**Comment by snakefoot** [comment] 2020-03-19 15:54
Has your question been answered?

**Comment by HongJinJua** [comment] 2020-03-20 01:16
Still testing the implementation of "maxArchiveDays"

```
	<target xsi:type="File" name="ALL"
            fileName="C:\Logs\testProject\testProject.${cached:${date:format=yyyy-MM-dd}}.log"
            layout="${longdate}|${uppercase:${level}}|${threadid}|${logger}|${message} ${exception:format=ToString}" 
            maxArchiveFiles="100"
            archiveFileName="C:\Logs\testProject\testProject{#}.log"
            archiveDateFormat="yyyy-MM-dd"
            archiveAboveSize="10485760"
            archiveNumbering="DateAndSequence"
            maxArchiveDays="1"     
          />
```
Folder
```
testProject.2020-03-20
testProject.2020-03-19
testProject2020-03-19.11590
testProject2020-03-19.11591
```

maxArchiveDays="1" 
Date of the 19th should be deleted

**Comment by snakefoot** [comment] 2020-03-20 07:10
Current files (files from today) are not part of archive when using MaxArchiveDays. So `maxArchiveDays="1"` will only clean files older than yesterday.

When you have specified a custom `archiveFileName` then it will be used as wildcard for cleanup (instead of dynamic wildcard). So you should change it so it matches the format of `fileName` (Added missing dot after `testProject`)

```xml
	<target xsi:type="File" name="ALL"
            fileName="C:\Logs\testProject\testProject.${cached:${date:format=yyyy-MM-dd}}.log"
            archiveFileName="C:\Logs\testProject\testProject.{#}.log"
            archiveDateFormat="yyyy-MM-dd"
          />
```

**Comment by snakefoot** [comment] 2020-03-21 09:53
Closing issue since answer has been accepted:

https://stackoverflow.com/questions/60737058/nlog-it-doesnt-delete-old-log-files/60771563#60771563

**Closed by snakefoot** 2020-03-21 09:53 UTC
Labels: duplicate, file-archiving, file-target, needs info, question

**Comment by HongJinJua** [comment] 2020-03-23 14:01
Thanks team!

The problem is solved.

"MaxArchiveDays" is the date judgement time based on the date generated by the file.

Thank you very much for the prompt reply.
