### ISSUE TITLE
Intentional AutoFlush change in FileTarget?

### ISSUE THREAD

**Issue by broccliman** [NLog/NLog#656] opened 2015-03-31 18:30 UTC
We recently migrated from v2.1 to v3.2 and did some focused stress testing to understand lower level behavioral differences. We found a slight regression in performance using `AutoFlush=true` within `FileTarget`. To understand the change a little better, we profiled a small console application using dotTrace performance profiler and found that [this commit](https://github.com/NLog/NLog/pull/415) was a performance hot spot.

It looks like the latest version of `FileTarget.cs` in master no longer contains the logic from PR #415; [this commit](https://github.com/NLog/NLog/commit/00d53bc3b234917517e2fdc1735f8b4af2d5d8aa#diff-ed0a3fc25ad7408a5b63501fa77dbe69L1523) removed it. I wasn't able to identify the source of the change by reading through the issue list and I also saw that there was a merge conflict on `FileTarget.cs` when merging in v4. The only thing I can find in the repo history is a comment from @Xharze on issue #414, which may suggest that `FileTarget` was undergoing a much larger transformation:
>This is an ongoing improvement I'm making, the File target should be much simpler than currently

I figured it was worth mentioning to understand if this change was intentional, possibly preventing a functional regression (original change was without supporting tests).

**Comment by 304NotModified** [comment] 2015-03-31 19:07
This really sounds like a merge bug. Thanks for reporting!

**Comment by 304NotModified** [comment] 2015-03-31 19:08
@Xharze could you look at this?

**Comment by Xharze** [comment] 2015-04-14 22:32
I'll take a look at it

**Comment by 304NotModified** [comment] 2015-05-06 22:28
@Xharze did you had a change to check this?

**Comment by Xharze** [comment] 2015-05-10 21:14
@304NotModified I totally forgot about it, I'll take a look at it right away

**Comment by Xharze** [comment] 2015-05-11 10:26
@broccliman I've tried to reproduce this unsuccessful, could you post some code reproducing this issue?

**Comment by broccliman** [comment] 2015-05-11 12:12
@Xharze which issue are you trying to reproduce? .. I only reported that from 2.1 to 3.2, I noticed a dip in performance when using `AutoFlush=true`. I found the changes responsible for the perf hit (https://github.com/NLog/NLog/pull/415) and noticed that they had been lost in a merge commit. I wasn't sure if that was __intentional__.

Are you trying to reproduce the original issue that led to the changes? @richol would be a better person to task.

**Comment by 304NotModified** [comment] 2015-05-11 13:36
note: This is probably not intentional

**Comment by Xharze** [comment] 2015-05-12 13:28
I understood it as the auto flush feature didn't work, but it's "just" a performance issue?

**Comment by broccliman** [comment] 2015-05-12 15:04
Let me try to word this differently.

See this commit:https://github.com/NLog/NLog/commit/00d53bc3b234917517e2fdc1735f8b4af2d5d8aa

Note the commit comments:
```
Conflicts:
	src/NLog/Config/ConfigurationItemFactory.cs
	src/NLog/LogFactory.cs
	src/NLog/LogManager.cs
	src/NLog/NLog.sl5.csproj
	src/NLog/Targets/FileTarget.cs
```
It looks like there was a merge conflict for `FileTarget.cs`. So, what was the conflict? .. I believe @ie-zero branched before @ricol made his changes in https://github.com/NLog/NLog/pull/415 (fixing https://github.com/NLog/NLog/issues/414):

> AutoFlush does not work for all configuration options on FileTarget. Depending on which BaseFileAppender the configuration makes the FileTarget use, data written may not be flushed even if the AutoFlush property is set to true.

@ricol made the following changes to `FileTarget.cs`
```c#
+            if (this.AutoFlush)
+            {
+                appenderToWrite.Flush();
+            }
```
@Xharze you merged @ie-zero branch back into master, and @richol changes were lost; see [this diff](https://github.com/NLog/NLog/commit/00d53bc3b234917517e2fdc1735f8b4af2d5d8aa#diff-ed0a3fc25ad7408a5b63501fa77dbe69L1523).
```c#
-            if (this.AutoFlush)
-            {
-                appenderToWrite.Flush();
-            }
```
__Did you do this intentionally?__

@304NotModified believes this was a mistake. I am not reporting any bugs. I'm just trying to bring this to light because I found it odd.

**Comment by Xharze** [comment] 2015-05-12 16:38
No that was not intentionally, I'll fix it

**Comment by Xharze** [comment] 2015-05-12 16:38
And thanks for the clarification :-)

**Comment by snakefoot** [comment] 2015-06-09 16:00
Should appender.Flush() not happen after appender.Write(bytes) ?

The last log-entry will very likely stay in the buffer (instead of the file), and wait for the next 
log-entry.

**Comment by 304NotModified** [comment] 2015-06-09 17:57
No it's not planned. 4.0 will be released today.

**Comment by 304NotModified** [comment] 2015-06-09 17:59
I think your wrong with the autoflush

**Comment by 304NotModified** [comment] 2015-06-09 18:23
Thanks for reporting! 

We will double check this and release this with 4.0 RTM

**Comment by 304NotModified** [comment] 2015-06-09 18:24
If you like to check the code of #734, that would be great. 

If you really need 3.2.2, let me also know :)

**Comment by snakefoot** [comment] 2015-06-09 21:08
I don't think you need the extra flush in ReplaceFileContent(), since the using-Dispose will automatically Flush / Close the stream.

If version 4.0 is ready for RTM, then it will be fine.

**Comment by 304NotModified** [comment] 2015-06-09 21:15
Good point about the `ReplaceFileContent`. I missed the `using` and it's mabye also wrong..

**Comment by 304NotModified** [comment] 2015-06-09 21:45
We need to discuss this before release, so this will be probably 4.0.1

**Comment by 304NotModified** [comment] 2015-06-13 15:55
good seen regarding `ReplaceFileContent()` @snakefoot :+1:

**Closed** 2015-06-14 20:00 UTC
Labels: bug, should Have
