### ISSUE TITLE
[nlog 4.4.2+] when type="database" + async, nlog logs only first record and sometimes nothing

### ISSUE THREAD

**Issue by sevcarsev** [NLog/NLog#2032] opened 2017-03-28 14:23 UTC
Hello,

I upgraded my solution to nlog 4.4.4 and found that async database logging has stopped to work. Sporadically it stores ony one record, sometimes nothing. When I consistently downgraded versions and came to 4.4.1 it started to work as expected.

I tested with async="true" as well as with AsyncWrapper, symptoms are the same.
Is that only on my side cause it looks critical, but nobody reported that yet.

VS2017, .NET 4.5.2, SQL 2012.

Update: looks like the same when log to file.
Best regards

**Comment by 304NotModified** [comment] 2017-03-28 16:17
Could you check the internal log? There should be an error. If we got that one, we could fix it soon!

**Comment by snakefoot** [comment] 2017-03-28 17:10
I'm guessing duplicate of #1998

**Comment by 304NotModified** [comment] 2017-03-28 20:39
I have released 4.4.5. https://www.nuget.org/packages/NLog/4.4.5 

I'm pretty sure this is fixing your issue. Please let us know!
If this isn't fixing your issue, we will reopen the issues.

**Closed by 304NotModified** 2017-03-28 20:39 UTC
Labels: bug, duplicate

**Comment by sevcarsev** [comment] 2017-03-29 08:43
I updated to 4.4.5 and the issue is gone. Thank you for very quick fix!

**Comment by 304NotModified** [comment] 2017-03-29 11:28
thanks for the feedback!

Thanks @snakefoot for the fix 🎉
