### ISSUE TITLE
{$processtime} has incorrect formatting

### ISSUE THREAD

**Issue by jggrant** [NLog/NLog#1284] opened 2016-03-03 19:38 UTC
The layout renderer {$processtime} documentation indicates it is of the format HH:mm:ss.mmm. However, 4 digits are printed for the milliseconds part instead of 3.

Additionally, the first line printed can sometime have a negative result, resulting in a format like "00:00:00.000-5".

**Type**: Bug

**NLog version**: 4.1.2 (looking at the 4.2.3 source, the implementation bug is still there)

**Platform**: .Net 4.5

**Current NLog config** Irrelevant

In case of a BUG:

- What is the current result?
00:00:17.0564
- What is the expected result?
00:00:17.564
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No
- Please post full exception details (message, stacktrace, inner exceptions)
N/A
- Are there any work arrounds? yes/no
Write a custom renderer doing the same job with different formatting.
- Is there a version in which it did worked? 
No
- Can you help us by writing an unit test?
Maybe

**Comment by 304NotModified** [comment] 2016-03-03 19:51
Thanks for this report! Will try to fix this in 4.3

**Comment by 304NotModified** [comment] 2016-03-03 19:54
> Additionally, the first line printed can sometime have a negative result, resulting in a format like "00:00:00.000-5".

Is a negative result not a bug?

**Comment by jggrant** [comment] 2016-03-03 20:06
Yes definitely. Probably a timing issue between logEvent.TimeStamp and LogEventInfo.ZeroDate. I have not had time to investigate the possible causes. It might still be worth to safeguard it there regardless.

**Comment by 304NotModified** [comment] 2016-03-03 20:09
Ow I guess that has to do with the accuracy which is by default 16ms.

**Comment by 304NotModified** [comment] 2016-03-03 20:32
This has been fixed in NLog 4.3 if AppVeyor agrees

**Closed** 2016-03-08 07:16 UTC
Labels: bug
