### ISSUE TITLE
Allow loading config from a string

### ISSUE THREAD

**Issue by jjxtra** [NLog/NLog#2820] opened 2018-07-30 17:05 UTC
Please allow loading config from a string rather than file.

Use case: framework that needs to do it's own logging but doesn't want to require an nlog or app config file to be brought along with in deployment.

I realize I can make a temp file and load it, but that seems like an extra un-needed step.

**Comment by snakefoot** [comment] 2018-07-30 23:15
Looks like a duplicate of #2819. Maybe close the other?

If you load the string into a `XmlDocument` then it should work nicely:

https://github.com/nlog/NLog/wiki/Explicit-NLog-configuration-loading

**Closed** 2018-07-31 02:43 UTC
