### ISSUE TITLE
LoadConfigurationFromAppSettings(reloadOnChange: true) not reload after edit appsettings.json

### ISSUE THREAD

**Issue by bthulu** [NLog/NLog#5303] opened 2023-08-02 08:32 UTC
**NLog version**: 5.2.2

**Platform**: .net6 on windows

**Current NLog config** (xml or C#, if relevant)

```json
{
  "NLog": {
    "throwConfigExceptions": true,
    "targets": {
      "async": true,
      "logfile": {
        "type": "File",
        "fileName": "c:/temp/nlog-${shortdate}.log"
      },
      "logconsole": {
        "type": "Console"
      }
    },
    "rules": [
      {
        "logger": "WebApplication1.Controllers.WeatherForecastController",
        "writeTo": "logfile",
        "finalMinLevel": "Info"
      },
      {
        "logger": "*",
        "minLevel": "Info",
        "writeTo": "logconsole"
      },
      {
        "logger": "*",
        "minLevel": "Debug",
        "writeTo": "logfile"
      }
    ]
  }
}
```
```C#
var logger = LogManager.Setup()
    .LoadConfigurationFromAppSettings(reloadOnChange: true)
    .GetCurrentClassLogger();

var builder = WebApplication.CreateBuilder(args);

// NLog: Setup NLog for Dependency injection
builder.Logging.ClearProviders();
builder.Host.UseNLog();
```

```C#
public class WeatherForecastController : ControllerBase
{
    private static readonly string[] Summaries = new[]
    {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

    private readonly ILogger<WeatherForecastController> _logger;

    public WeatherForecastController(ILogger<WeatherForecastController> logger)
    {
        _logger = logger;
    }

    [HttpGet(Name = "GetWeatherForecast")]
    public IEnumerable<WeatherForecast> Get()
    {
        _logger.LogTrace("============trace============");
        _logger.LogDebug("============debug============");
        _logger.LogInformation("============info============");
        _logger.LogWarning("============warn============");
        return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
    }
}
```

- What is the current result?
while finalMinLevel of WebApplication1.Controllers.WeatherForecastController changed from debug to info, it won't reload, it still log "============debug============" to log file.
- What is the expected result?
after app started, if change finalMinLevel from debug to info while app is running, it will no longer log debug message. if change finalMinLevel from info to debug, it will log debug message.

**Comment by snakefoot** [comment] 2023-08-02 08:57
Duplicate of https://github.com/NLog/NLog.Extensions.Logging/issues/592 ?

Try adding `"internalLogToConsole": true,` + `"internalLogLevel": "Debug",` and use the console-output to see what is going on. Maybe you are modifying a `appsettings.json`-file in a different location ?

**Comment by snakefoot** [comment] 2023-08-02 09:12
Believe the issue is the missing `"autoReload": true` in appsettings.json. I guess it could be nice if `LoadConfigurationFromAppSettings` with `reloadOnChange = true` somehow forced enabled the auto-reload-feature, but right now one have to set both.

**Comment by bthulu** [comment] 2023-08-03 01:25
@snakefoot while use` "autoReload": true` with `LoadConfigurationFromAppSettings(reloadOnChange: true)`, it works.
may be a hint comment on method LoadConfigurationFromAppSettings's source code will help somebody?

**Comment by snakefoot** [comment] 2023-08-03 07:33
Created https://github.com/NLog/NLog.Web/pull/973 to improve XML docs for `LoadConfigurationFromAppSettings`

**Comment by snakefoot** [comment] 2023-08-06 17:30
NLog.Web.AspNetCore v5.3.3 has been released: https://www.nuget.org/packages/NLog.Web.AspNetCore

**Closed by snakefoot** 2023-08-06 17:30 UTC
Labels: question, nlog-configuration
