### ISSUE TITLE
Missing null-check in LogEventInfo.ResetMessageTemplateParameters ?

### ISSUE THREAD

**Issue by LadislavSopko** [NLog/NLog#4908] opened 2022-05-09 08:45 UTC
**NLog version**: dev

**Platform**: any

function : NLog.LogEventInfo.ResetMessageTemplateParameters()  will crash: 

> `if "HasMessageTemplateParameters == true" `

```c#
private bool ResetMessageTemplateParameters()
{
    if (_properties != null)
    {
        if (HasMessageTemplateParameters)
            _properties.MessageProperties = null;

        return _properties.MessageProperties.Count == 0;   // _properties.MessageProperties will be null
    }
    return false;
}
```

regards

**Comment by snakefoot** [comment] 2022-05-09 18:22
The `MessageProperties`-property is implemented like this:
```c#
        public IList<MessageTemplateParameter> MessageProperties
        {
            get => _messageProperties ?? ArrayHelper.Empty<MessageTemplateParameter>();
            internal set => _messageProperties = SetMessageProperties(value, _messageProperties);
        }
```
So even when setter-method is assigned to `null`, then the getter-method will return an empty array.

**Comment by LadislavSopko** [comment] 2022-05-10 05:36
A ok, 
I had crash there,  here part of my stack trace:

```
Exception Info: System.AccessViolationException
   at NLog.LogEventInfo.ResetMessageTemplateParameters()
   at NLog.LogEventInfo..ctor(NLog.LogLevel, System.String, System.String, System.Collections.Generic.IList`1<NLog.MessageTemplates.MessageTemplateParameter>)
   at NLog.Extensions.Logging.NLogLogger.TryCaptureMessageTemplate(NLog.LogLevel, System.String, System.Collections.Generic.IReadOnlyList`1<System.Collections.Generic.KeyValuePair`2<System.String,System.Object>>, NLog.Extensions.Logging.NLogMessageParameterList)
   at NLog.Extensions.Logging.NLogLogger.CreateLogEventInfo[[Microsoft.Extensions.Logging.FormattedLogValues, Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](NLog.LogLevel, Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.String>)
   at NLog.Extensions.Logging.NLogLogger.Log[[Microsoft.Extensions.Logging.FormattedLogValues, Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](Microsoft.Extensions.Logging.LogLevel, Microsoft.Extensions.Logging.EventId, Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.String>)
   at Microsoft.Extensions.Logging.Logger`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Microsoft.Extensions.Logging.ILogger.Log[[Microsoft.Extensions.Logging.FormattedLogValues, Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](Microsoft.Extensions.Logging.LogLevel, Microsoft.Extensions.Logging.EventId, Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.String>)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.LogLevel, Microsoft.Extensions.Logging.EventId, System.Exception, System.String, System.Object[])
   at Treu.Ogsm.Hal.Devices.DeviceBase.TryRestoreAfterEventualDeviceReset()
```
so I check code in Git and didn't inspect Getter. 
Type of MessageProperties is non nullable. Code actually should to work, anyway AccessViolationException in that point means some problem.
Then, in my modest opignion :) (and I did it for sure, too) hide null check in getter is efficent but resulting code is really hard to read. 
It's just point on style, maybe :) 

Regards Ladislav

**Comment by snakefoot** [comment] 2022-05-10 08:08
What version of NLog and NLog.Extension.Logging are you using?

You are welcome to create pull-request to improve readability of the source code.


Sent from my Galaxy



-------- Original message --------
From: Ladislav Sopko ***@***.***>
Date: 10/05/2022 07:37 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] Missing null-check in LogEventInfo.ResetMessageTemplateParameters ? (Issue #4908)


A ok,
I had crash there, here part of my stack trace:

Exception Info: System.AccessViolationException
   at NLog.LogEventInfo.ResetMessageTemplateParameters()
   at NLog.LogEventInfo..ctor(NLog.LogLevel, System.String, System.String, System.Collections.Generic.IList`1<NLog.MessageTemplates.MessageTemplateParameter>)
   at NLog.Extensions.Logging.NLogLogger.TryCaptureMessageTemplate(NLog.LogLevel, System.String, System.Collections.Generic.IReadOnlyList`1<System.Collections.Generic.KeyValuePair`2<System.String,System.Object>>, NLog.Extensions.Logging.NLogMessageParameterList)
   at NLog.Extensions.Logging.NLogLogger.CreateLogEventInfo[[Microsoft.Extensions.Logging.FormattedLogValues, Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](NLog.LogLevel, Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.String>)
   at NLog.Extensions.Logging.NLogLogger.Log[[Microsoft.Extensions.Logging.FormattedLogValues, Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](Microsoft.Extensions.Logging.LogLevel, Microsoft.Extensions.Logging.EventId, Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.String>)
   at Microsoft.Extensions.Logging.Logger`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Microsoft.Extensions.Logging.ILogger.Log[[Microsoft.Extensions.Logging.FormattedLogValues, Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](Microsoft.Extensions.Logging.LogLevel, Microsoft.Extensions.Logging.EventId, Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.String>)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.LogLevel, Microsoft.Extensions.Logging.EventId, System.Exception, System.String, System.Object[])
   at Treu.Ogsm.Hal.Devices.DeviceBase.TryRestoreAfterEventualDeviceReset()


so I check code in Git and didn't inspect Getter.
Type of MessageProperties is non nullable. Code actually should to work, anyway AccessViolationException in that point means some problem.
Then, in my modest opignion :) (and I did it for sure, too) hide null check in getter is efficent but resulting code is really hard to read.
It's just point on style, maybe :)

Regards Ladislav

**Comment by LadislavSopko** [comment] 2022-05-10 08:39
Hello,
Actually I use Nlog.Extensions.Logging_1.7.4  which depends on NLog_4.7.11  (reading dependency tree in VisualStudio)
I have not pull down Your sources, so I cant make changes. Im a bit low on time, sorry cant partecipate more personally :)
24 hours a day starts to be not enought :)

Regards Ladislav

**Comment by snakefoot** [comment] 2022-05-10 17:24
I'm very curious about this AccessViolationException, and have a hard time understanding how it could happen.

Did the error occur during high memory-usage, where AccessViolationException became an alternative to OutOfMemoryException?

Can you provide the logging-statements executed by `Treu.Ogsm.Hal.Devices.DeviceBase.TryRestoreAfterEventualDeviceReset()` ?

Are you able to reproduce the error?

**Comment by LadislavSopko** [comment] 2022-05-10 17:56
Hello,
yes its actually strange problem, it happens one time in about 2 years of execution.
it should be one of those loging lines:


all those calls are done in 
```
// there are some logs here, and they run well

Task.Run(async () =>
{
   ...
   _logger.LogError($"{Name} can't make a clone.");
   ...
   _logger.LogError($"{Name} can't make a reset preparation failed."); // name regular property
   ...
   _logger.LogError(cex, $"{Name} got error manipulating clone."); // cex is exception
   ...
}).SafeFireAndForget(false, (ex) => {
    //  function called if task fail with exception
    _logger.LogError(ex, $"Reset of {Name} failed!");
});
```

regards
ladislav

**Comment by snakefoot** [comment] 2022-05-10 20:02
None of those logging-statements are making use of message-template-properties. And `ResetMessageTemplateParameters` will only do something when  `_properties != null` (which is not the case here).

Also interesting that the context of the application-crash is async-Task, since usually they execute as background-thread-pool-threads and will just "swallow" any their exceptions.

Is your application making use of any native-libraries?

**Comment by LadislavSopko** [comment] 2022-05-11 09:58
I handle exceptions also from tasks, so i catch it correctly. I use many native libraries ( this is very complex project ).

**Comment by snakefoot** [comment] 2022-05-18 18:01
Closing issue due to lack of clues. If you are able to reproduce the issue, then don't hesitate to re-open the issue.

**Closed by snakefoot** 2022-05-18 18:01 UTC
Labels: question
