### ISSUE TITLE
Assembly 'NLog' produced AOT analysis warnings.

### ISSUE THREAD

**Issue by Balkoth** [NLog/NLog#5638] opened 2024-10-07 15:13 UTC
I don't know if this is supposed to work yet but there is this: https://nlog-project.org/2023/05/30/nlog-5-2-trim-warnings.html

**NLog version**: 5.3.4

**Platform**: .NET8

```
2>ILC(0,0): Warning IL3000: NLog.LayoutRenderers.NLogDirLayoutRenderer.ResolveNLogDir(): 'System.Reflection.Assembly.Location.get' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.
2>ILC(0,0): Warning IL3000: NLog.LayoutRenderers.NLogDirLayoutRenderer.ResolveNLogDir(): 'System.Reflection.Assembly.Location.get' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.
2>ILC(0,0): Warning IL3000: NLog.Internal.AssemblyHelpers.GetAssemblyFileLocation(Assembly): 'System.Reflection.Assembly.Location.get' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.
2>ILC(0,0): Warning IL3002: NLog.Internal.AssemblyHelpers.GetAssemblyFileLocation(Assembly): Using member 'System.Reflection.Assembly.CodeBase.get' which has 'RequiresAssemblyFilesAttribute' can break functionality when embedded in a single-file app. This member throws an exception for assemblies embedded in a single-file app.
2>ILC(0,0): Warning IL3002: NLog.Internal.AssemblyHelpers.GetAssemblyFileLocation(Assembly): Using member 'System.Reflection.Assembly.CodeBase.get' which has 'RequiresAssemblyFilesAttribute' can break functionality when embedded in a single-file app. This member throws an exception for assemblies embedded in a single-file app.
2>ILC(0,0): Warning IL3000: NLog.Internal.Fakeables.AppEnvironmentWrapper.LookupEntryAssemblyLocation(): 'System.Reflection.Assembly.Location.get' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.
2>ILC(0,0): Warning IL3000: NLog.Internal.Fakeables.AppEnvironmentWrapper.LookupEntryAssemblyFileName(): 'System.Reflection.Assembly.Location.get' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.
2>ILC(0,0): Warning IL3000: NLog.Config.LoggingConfigurationFileLoader.LookupNLogAssemblyLocation(): 'System.Reflection.Assembly.Location.get' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.
```

**Comment by snakefoot** [comment] 2024-10-07 15:47
Yes NLog v5.2.2 only supports building with build-trimming enabled (Enabled by default in NET7 / NET8).

Support for AOT-builds without warnings are planned for NLog v6. See also: https://nlog-project.org/2024/10/01/nlog-6-0-goals.html

Closing as duplicate of #5258 + #3366

**Closed by snakefoot** 2024-10-07 15:47 UTC

**Comment by snakefoot** [comment] 2024-10-07 16:24
Of course any help that can accelerate the release of NLog v6 is most welcome. 

There will also come a time where the first NLog v6 Preview-Build needs testing, but that is several iteration away (right now focus is extracting into separate nuget-packages)

**Comment by Balkoth** [comment] 2024-10-07 19:15
I'll see what i can do. Thanks for the fast response.

**Comment by snakefoot** [comment] 2025-04-29 19:23
NLog v6-preview1 has been released, that should fix AOT-build-warnings:

- https://www.nuget.org/packages/NLog/6.0.0-preview1#releasenotes-body-tab

See also: https://nlog-project.org/2025/04/29/nlog-6-0-major-changes.html
