### ISSUE TITLE
Will NLog have a plan to support JSON formatting configuration file

### ISSUE THREAD

**Issue by Jamesxql** [NLog/NLog#2230] opened 2017-07-31 10:53 UTC
**Type** (choose one):
- Feature request

**NLog version**: 
- N/A

**Platform**: 
-  .NET Core 

**Current NLog config** (xml or C#, if relevant)
- N/A

I have recently encountered this situation, I hope that NLog can read JSON format configuration files. Is there any plan to support that?

**Comment by snakefoot** [comment] 2017-07-31 17:06
Duplicate of #1588 ?

**Comment by snakefoot** [comment] 2017-07-31 17:37
"Easy" workaround is to convert the Json into a Xml-document, and then load the NLog-configuration from the Xml-document (Ex JSON.NET):

```
// To convert JSON text contained in string json into an XML node
XmlDocument doc = JsonConvert.DeserializeXmlNode(json);
```

**Comment by Jamesxql** [comment] 2017-08-01 02:41
Thanks, so it has been discussed already. Can this feature be released with 5.0?

**Comment by 304NotModified** [comment] 2017-08-01 05:24
The discussion has been started but AFAIK there are some open topics. 

We haven't started with the implementation, I really like this feature but we're working on other stuff first. 

This could be added any time to NLog, no need to wait NLog 5. Also we need probably a json schema if we create this feature. 

If someone like to start on the implementation, feel free :) 

(note: the following weeks I have very limited time, so reviews and feedback could be delayed)

**Comment by Jamesxql** [comment] 2017-08-02 10:38
So, le's finish a formal JSON configuration formatting proposal first. I will file a formal proposal so we can discuss details.

**Comment by 304NotModified** [comment] 2017-08-02 18:17
:+1:

**Comment by luoxy123** [comment] 2017-08-05 17:08
It's Easy To define a wrapper in the configuration file  with xml formatting,but not with Json formatting,Is there a better way to define a warpper with Json formatting?

**Comment by Jamesxql** [comment] 2017-08-07 08:47
@304NotModified 
Does NLog config file supperted this form

```xml
<targets>
  <target name="n" xsi:type="AsyncWrapper">
    <target xsi:type="RetryingWrapper">
      <target xsi:type="File" fileName="${file}.txt" />
    </target>
    <target xsi:type="SomeWrapper">
        <target xsi:type="db" .... />
    </target>
  </target>
</targets>
```

**Comment by 304NotModified** [comment] 2017-08-07 18:36
Partly, the asyncwrapper only supports one wrapper target, but the fallbackwrapper supports wrapping multiple targets.

**Comment by Jamesxql** [comment] 2017-08-08 04:41
I think the Database target can define like this: 
```JSON
{
    "targets":{
        "db": {
            "type": "Database",
            "commandText": "INSERT INTO [LogEntries](TimeStamp, Message, Level, Logger) VALUES(getutcdate(), @msg, @level, @logger)",
            "parameters": [
                "@msg": {
                    "layout": "${message}"
                },
                "@level": {
                    "layout": "${level}",
                    "size": 0
                },
                "@logger": {
                    "layout": "${logger}"
                }
            ],
            "dbProvider": "System.Data.SqlClient",
            "connectionString": "....."
        }
    }
}
```
The default wrapper definition is:
```JSON
{
    "targets":{
        "defaultWrapper": {
            "type": "BufferingWrapper",
            "bufferSize": 100
        },
        "f1": {
            type: "File",
            fileName: "f1.txt"
        },
        "f2": {
            type: "File",
            fileName: "f2.txt"
        }
    },
    "targets": {
        "defaultWrapper": {
            type: "AsyncWrapper",
            wrap: {
                "type": "RetryingWrapper"
            }
        },
        "n1": {
            "type": "Network",
            "address": "tcp://localhost:4001"
        },
        "n2": {
            "type": "Network",
            "address": "tcp://localhost:4002"
        },
        "n3": {
            "type": "Network",
            "address": "tcp://localhost:4003"
        }
    }

```
The default target parameters definition is: 
```JSON
{
    "targets": {
        "defaultTargetParameters": [
            {
                "type": "File",
                "parameters": {
                    "p1": "k1",
                    "p2": "k2"
                }
            },
            {
                "type": "Database",
                "parameters": {
                    "p1": "k1",
                    "p2": "k2"
                }
            }
        ],
        "f1": {
            "type": "File",
            "fileName": "f1.txt"
        },
        "db": {
            "type": "Database",
            ...
        }
    }
}
```

What do you think? @304NotModified

**Comment by 304NotModified** [comment] 2017-08-11 13:46
To avoid confusing, I will close this one in favor of https://github.com/NLog/NLog/issues/1588

**Closed by 304NotModified** 2017-08-11 13:46 UTC
Labels: question

**Comment by snakefoot** [comment] 2019-02-23 23:11
Created https://github.com/NLog/NLog.Extensions.Logging/pull/263 for people who would like to test NLog-config from `appsettings.json`. Depends on NLog 4.6-rc1
