### ISSUE TITLE
Get Name process

### ISSUE THREAD

**Issue by JinPachi** [NLog/NLog#587] opened 2015-02-19 16:14 UTC
Hi All! 

Which symbol in NLog is mean many symbols?  What I need write instead of '*'?

  <variable name ="Service_name" value="${replace:inner=${callsite}:searchFor=Server.*Service*:replaceWith=*Service:regex=true}"/>

Cheers,
JinPachi.

**Comment by JinPachi** [comment] 2015-02-19 16:15
<variable name ="Service_name" value="${replace:inner=${callsite}:searchFor=Server.*Service*:replaceWith=*Service:regex=true}"/>

**Comment by 304NotModified** [comment] 2015-02-19 18:24
duplicate of #586

**Closed by 304NotModified** 2015-02-19 18:24 UTC
