### ISSUE TITLE
nlog stops writing to log file

### ISSUE THREAD

**Issue by Contec-Jmarcantonio** [NLog/NLog#3057] opened 2018-12-27 22:04 UTC
I've been using nlog successfully for months until 12-20 when it appears that logging has stopped. Any help is greatly appreciated.

I'm using a very simple file based logging in our ASP.NET site (.net 4.5). That's below. 

If I restart the IIS site I get a little bit of logging and then it just stops, within about 10 seconds.

I'm also seeing something that seems interesting in the nlog internal logging file ... first it seems to be ready to write all log levels to the file:
```
2018-12-27 16:31:58.0412 Debug logNamePattern: (CRSLogToFile:Equals) levels: [ Trace Debug Info Warn Error Fatal ] appendTo: [ outputFile ]
```

but then a few seconds later it seems to be closing the file:

```
2018-12-27 16:32:03.1350 Debug Stopping file watching for path 'C:\WebSites\xxx.xxx.xxx' filter 'NLog.config'
2018-12-27 16:32:03.1350 Info Closing old configuration.
2018-12-27 16:32:03.1410 Trace LogFactory.Flush(00:00:15)
2018-12-27 16:32:03.1410 Trace Flushing all targets...
2018-12-27 16:32:03.1410 Trace ForEachItemInParallel() 1 items
2018-12-27 16:32:03.1590 Trace FileTarget(Name=outputFile): FlushAsync
2018-12-27 16:32:03.1590 Trace Continuation invoked: 
2018-12-27 16:32:03.1590 Trace Parallel task completed. 0 items remaining
2018-12-27 16:32:03.1730 Trace FileTarget(Name=outputFile): FlushAsync Done
2018-12-27 16:32:03.1730 Debug Closing logging configuration...
2018-12-27 16:32:03.1730 Trace Closing File Target[outputFile]
2018-12-27 16:32:03.1730 Debug Closing target 'File Target[outputFile]'.
2018-12-27 16:32:03.1730 Debug Closed target 'File Target[outputFile]'.
```

nlog.config:
![nlog config](https://user-images.githubusercontent.com/18339113/50495898-3bb98a00-09fa-11e9-9562-34daabfed9d4.png)

**Comment by snakefoot** [comment] 2018-12-27 22:15
Since it doesn't say `Logger closing down...` then I guess something has assigned a new NLog configuration (causing the old one to be closed).

Maybe try to change `autoReload="true"` into `autoReload="false"` and see if it helps. Else you have some rogue library that modifies the global NLog configuration.

If something is modifying the files in the wwwroot, then I heard about AppDomain recycle that can be triggered. That can cause all sorts of issues. Again don't know much about ASP.NET

**Comment by Contec-Jmarcantonio** [comment] 2018-12-27 23:58
Tried autoReload="false". Same deal. Things look a little different in nlog-internal.log, I've attached that.
[nlog-internal-12-27.txt](https://github.com/NLog/NLog/files/2713589/nlog-internal-12-27.txt)

**Comment by snakefoot** [comment] 2018-12-28 00:01
The output shows the following line:

`2018-12-27 18:45:53.4865 Info Logger closing down...`

Means that you have a shutdown event, maybe caused by an unhandled exception. Maybe you can see something in your Windows EventLog? Have you setup a UnhandledException-handler and added some logging there?

**Comment by Contec-Jmarcantonio** [comment] 2018-12-31 15:05
Nothing in the event log. Cleared it before reproducing the problem just to be sure.

Yes, there's a handler for unhanded exceptions - and I see that working as expected. 

Is there any way for me to get more info on what's occurred to make the logger shutdown ?

**Comment by snakefoot** [comment] 2019-01-02 12:14
Since it says:

`2018-12-27 18:45:53.4865 Info Logger closing down...`

And not:

`Shutting down logging...`

Then it is probably caused by something calling 'LogManager.Shutdown()'. Whether your own code, or a sub-library that I cannot tell you. I guess you could make a custom build of NLog where the 'LogManager.Shutdown()' captures stacktrace and outputs it into the Internal Logger.

**Comment by Contec-Jmarcantonio** [comment] 2019-01-03 19:02
Yes, that was it. I've located the call to LogManager.Shutdown() in our code. 

Thank you very much for the help.

**Comment by 304NotModified** [comment] 2019-01-05 00:11
I'm glad is has been resolved 👍

thanks @snakefoot !

**Closed by 304NotModified** 2019-01-05 00:11 UTC
Labels: needs info
