### ISSUE TITLE
Nlog creates empty logs (file size = 0 bytes)

### ISSUE THREAD

**Issue by lansman** [NLog/NLog#5379] opened 2023-10-24 11:53 UTC
At some moment empty logs began to be created. It worked fine before for a long time but suddenly stopped, not sure if application or configs were updated right before the problem started.

We have several dotnet applications, each contains its own appsettings configs, problem appeared with lots of them, with different types of logs (error logs, infomartion logs). Probably some OS related issue.

![image](https://github.com/NLog/NLog/assets/1588720/b0ff9a65-2564-44a7-a6b8-ed9bc61c1a2c)

**NLog version**: 5.2.4

**Platform**: net 7.0

**OS**: Linux 5.10.182

**Current NLog config**

I removed rules and targets related to other types of logs, for simplicity i left error target only and related rules.

1/2
```json
// appsettings.json
{
  "NLog": {
    "autoReload": true,
    "throwConfigExceptions": true,
    "variables": {
      "var_errorMessage": "${when:when='${exception:format=toString,Data:maxInnerExceptionLevel=10}'=='':inner=${message}:else=${message}${newline}${exception:format=toString,Data:maxInnerExceptionLevel=10}}",
      "dateLongCustom": "${date:format=yyyy-MM-dd_HHmmss:cached=true}",      
      "log_postfix": "-planned"
    },    
    "targets": {       
      "logErrorFile": {
        "type": "File",
        "fileName": "${var:base_dir}/${var:subdir_name}${var:logical_date}-bad-error.log",
        "layout": "${longdate}|${level:uppercase=true}|${Callsite:cleanNamesOfAnonymousDelegates=true:cleanNamesOfAsyncContinuations=true}|${processid}|${var_errorMessage}",
        "lineEnding": "LF",
        "encoding": "UTF-8"
      }
    },
    "rules": {      
      "071": {
        "logger": "*",
        "levels": "Error,Fatal",
        "writeTo": "logErrorFile"
      }
    }
  }
}
```

2/2
```json
// appsettings.production.json
{
  "NLog": {
      "logErrorFile": {
        "keepFileOpen": true,
        "OpenFileCacheTimeout": 30,
        "autoFlush": false,
        "OpenFileFlushTimeout": 5
    }
  }
}
```

- What is the current result? - **When error occurs - an empty log is created (file size=0)**
- What is the expected result? - **When error occurs - a log with error data inside should be created**
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? - **There is no internal log**
- Are there any workarounds? - **Didn't find any**
- Is there a version in which it did work? - **Don't know**

**Comment by snakefoot** [comment] 2023-10-24 16:09
It obvious an environment-issue, since NLog doesn't have this behavior by default. My guess is that your machine ran out of disk-space (Maybe disk-cleanup has been performed afterwards).

> Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? - There is no internal log

You explictly have to enable the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging) and point it to a working location (write-permission and available disk-space). Either [from code](https://github.com/NLog/NLog/wiki/Internal-Logging#enabling-internal-logging-programmatically) or from config:
```json
{
  "NLog": {
    "throwConfigExceptions": true,
    "internalLogLevel": "Warn",
    "internalLogFile": "SomeDirectory",
  }
}
```

Please add the output from the NLog InternalLogger, when the issue occurs, else there is nothing that I can do.

**Comment by lansman** [comment] 2023-10-24 16:21
Its not a ran out of disk-space, there are dozens of gigabytes of free space.

And most of logs are continue to be created without problems
![image](https://github.com/NLog/NLog/assets/1588720/820db2b4-5483-460a-bd2a-f01021847f5b)

Okay, i'll try to enable internal logger explicitly.

**Comment by snakefoot** [comment] 2023-10-24 16:50
Btw. this layout can be simplified:
```json
"var_errorMessage": "${when:when='${exception:format=toString,Data:maxInnerExceptionLevel=10}'=='':inner=${message}:else=${message}${newline}${exception:format=toString,Data:maxInnerExceptionLevel=10}}",
```
To the much faster:
```json
"var_errorMessage": "${onexception:inner=${message}${newline}${exception:format=toString,Data:maxInnerExceptionLevel=10}:else=${message}}",
```
NLog v5.0.5 introduced the `else=`-option for [${onexception}](https://github.com/NLog/NLog/wiki/OnException-Layout-Renderer)  with #5057

**Comment by snakefoot** [comment] 2023-10-24 18:43
Been looking at the FileTarget-code, and it has the ability to create empty File, and if unable to create a FileStream to the newly created file, then could give this behavior.

https://github.com/NLog/NLog/blob/d8a999f162bfbfe980c99b7069cf903e7dbb9fcf/src/NLog/Internal/FileAppenders/BaseFileAppender.cs#L324

Lets say one have a very aggressive malware-scanner / windows-defender that scans all newly created files, then it could jump-in and prevent NLog from getting the FileStream and prevent logging to the.

Ther original pre-create-file-logic was introduced with #1100 with NLog v4.3

I guess an ugly work-around could be to assign FileTarget-option `concurrentWrites: true`.

**Comment by lansman** [comment] 2023-10-24 18:58
> An alternative cause could be that you have multiple application-instances running on the same machine, and logging to the same file-path
This is clearly not the case. Each application writes to its own log with unique date and timestamp and even several random characters stamp.

>very aggressive malware-scanner / windows-defender 
OS (Linix) was reinstalled several months ago and i'm pretty sure there was no anti-virus software installed. But i'll check that.

**Comment by lansman** [comment] 2023-10-31 09:59
Here is list of running processes

```
$ ps -e | awk '{ print $4 }' | uniq | sort
agetty
alteratord
ata_sff
awk
bash
bash
bash
blkcg_punt_bio
charger_manager
CMD
cpuhp/0
cpuhp/1
cpuhp/2
cpuhp/3
cpuhp/4
cpuhp/5
cpuhp/6
cpuhp/7
crond
crond
cryptd
dbus-daemon
devfreq_wq
dotnet
edac-poller
ext4-rsv-conver
ext4-rsv-conver
flock
iprt-VBoxTscThr
iprt-VBoxWQueue
ipv6_addrconf
irq/24-pciehp
irq/25-pciehp
irq/26-pciehp
irq/27-pciehp
irq/28-pciehp
irq/29-pciehp
irq/30-pciehp
irq/31-pciehp
irq/32-pciehp
irq/33-pciehp
irq/34-pciehp
irq/35-pciehp
irq/36-pciehp
irq/37-pciehp
irq/38-pciehp
irq/39-pciehp
irq/40-pciehp
irq/41-pciehp
irq/42-pciehp
irq/43-pciehp
irq/44-pciehp
irq/45-pciehp
irq/46-pciehp
irq/47-pciehp
irq/48-pciehp
irq/49-pciehp
irq/50-pciehp
irq/51-pciehp
irq/52-pciehp
irq/53-pciehp
irq/54-pciehp
irq/55-pciehp
jbd2/dm-0-8
jbd2/sda1-8
kaluad
kauditd
kblockd
kcompactd0
kdevtmpfs
kdmflush
khugepaged
khungtaskd
kintegrityd
kmpathd
kmpath_handlerd
kmpath_rdacd
ksmd
ksoftirqd/0
ksoftirqd/1
ksoftirqd/2
ksoftirqd/3
ksoftirqd/4
ksoftirqd/5
ksoftirqd/6
ksoftirqd/7
kstrp
kswapd0
kthreadd
kthrotld
kworker/0:0-events
kworker/0:0H-events_highpri
kworker/0:1H-kblockd
kworker/0:2-events
kworker/1:0H-events_highpri
kworker/1:1H-kblockd
kworker/1:1-mm_percpu_wq
kworker/1:2-cgroup_destroy
kworker/2:0H-events_highpri
kworker/2:1-events
kworker/2:1H-kblockd
kworker/2:2-cgroup_destroy
kworker/3:0
kworker/3:0H-events_highpri
kworker/3:1-events
kworker/3:1H-kblockd
kworker/3:2-events_power_efficient
kworker/4:0H-events_highpri
kworker/4:1H-kblockd
kworker/4:1-mm_percpu_wq
kworker/4:2-events
kworker/5:0-events
kworker/5:0H-events_highpri
kworker/5:1-events
kworker/5:1H-kblockd
kworker/5:2-events
kworker/6:0H-events_highpri
kworker/6:1-cgroup_destroy
kworker/6:1H-kblockd
kworker/6:2-mm_percpu_wq
kworker/7:0-events
kworker/7:0H-events_highpri
kworker/7:1H-kblockd
kworker/7:1-mm_percpu_wq
kworker/7:2-cgroup_destroy
kworker/u16:0-events_unbound
kworker/u16:1-flush-253:0
kworker/u16:2-events_unbound
kworker/u16:3-events_unbound
kworker/u17:0
master
md
migration/0
migration/1
migration/2
migration/3
migration/4
migration/5
migration/6
migration/7
mm_percpu_wq
netns
nginx
nginx
nscd
nslcd
ntpd
ntpd
nvme-delete-wq
nvme-reset-wq
nvme-wq
oom_reaper
php
php
php7-fpm
php7-fpm
pickup
postdrop
ps
qmgr
rcu_gp
rcu_par_gp
rcu_sched
rcu_tasks_kthre
rcu_tasks_rude_
rcu_tasks_trace
redis-server
rpcbind
scsi_eh_0
scsi_eh_1
scsi_eh_10
scsi_eh_11
scsi_eh_12
scsi_eh_13
scsi_eh_14
scsi_eh_15
scsi_eh_16
scsi_eh_17
scsi_eh_18
scsi_eh_19
scsi_eh_2
scsi_eh_20
scsi_eh_21
scsi_eh_22
scsi_eh_23
scsi_eh_24
scsi_eh_25
scsi_eh_26
scsi_eh_27
scsi_eh_28
scsi_eh_29
scsi_eh_3
scsi_eh_30
scsi_eh_31
scsi_eh_32
scsi_eh_4
scsi_eh_5
scsi_eh_6
scsi_eh_7
scsi_eh_8
scsi_eh_9
scsi_tmf_0
scsi_tmf_1
scsi_tmf_10
scsi_tmf_11
scsi_tmf_12
scsi_tmf_13
scsi_tmf_14
scsi_tmf_15
scsi_tmf_16
scsi_tmf_17
scsi_tmf_18
scsi_tmf_19
scsi_tmf_2
scsi_tmf_20
scsi_tmf_21
scsi_tmf_22
scsi_tmf_23
scsi_tmf_24
scsi_tmf_25
scsi_tmf_26
scsi_tmf_27
scsi_tmf_28
scsi_tmf_29
scsi_tmf_3
scsi_tmf_30
scsi_tmf_31
scsi_tmf_32
scsi_tmf_4
scsi_tmf_5
scsi_tmf_6
scsi_tmf_7
scsi_tmf_8
scsi_tmf_9
(sd-pam)
(sd-pam)
(sd-pam)
sendmail
sftp-server
sh
sort
sshd
sshd
sshd
sshd
sshd
sshd
su
sudo
systemd
systemd
systemd
systemd
systemd-journal
systemd-logind
systemd-udevd
systemd-userdbd
systemd-userwor
systemd-userwor
tpm_dev_wq
uniq
vmtoolsd
vmw_pvscsi_wq_0
watchdogd
writeback
zabbix_agentd
zswap-shrink
```

**Comment by lansman** [comment] 2023-10-31 10:05
There is nothing interesting in internal log, just

```
2023-10-31 10:00:24.3031 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 10:30:02.4160 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 10:30:23.3750 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 11:00:03.0969 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 11:00:24.1977 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 11:30:02.7570 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 11:30:23.9652 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 12:00:02.9974 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 12:00:25.5088 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 12:30:02.7052 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 12:30:22.8973 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 13:00:03.0750 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 13:00:23.8738 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 13:30:02.6241 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 13:30:23.5285 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 14:00:05.3521 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 14:00:27.9046 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 14:30:03.2779 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 14:30:24.9357 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 15:00:02.5822 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
2023-10-31 15:00:23.7342 Warn Unused target detected. Add a rule for this target to the configuration. TargetName: logDebugFile
```

**Comment by snakefoot** [comment] 2023-10-31 16:44
> Here is list of running processes, i have no idea of purpose most of them

I don't know what background applications that might affect NLog FileTarget on Linux.

> There is nothing interesting in internal log, just

It is interesting that your application is constantly logging messages that signals NLog-configuration has been loaded.

Is your application shutdown/restarted every 30 minutes? Or is there a background-application touching the appsettings.json, that triggers automatic-reload of NLog-configuration ? (Because of `"autoReload": true`)

Would it be possible to set `InternalLogger.LogLevel = LogLevel.Info` ?

> I guess error log renderer just cannot render error message. Or error data is too short, less than buffer size and buffer just isn't be flushed to the log file. Something like that. Is that possible?

I don't know the file-viewer that you are using. NLog will by default call FileStream.Flush() after each LogEvent-batch. This should flush to the operating-system, so if the application terminates, then file-output stays. But if the operating-system file-system-cache doesn't flush to disk until closing file-handle, then it might not be visible for the file-viewer.

https://github.com/NLog/NLog/blob/34c26bc02dd3026459228f1915ca27f93b46a0d0/src/NLog/Targets/FileTarget.cs#L2228-L2231

But maybe you can configure `"KeepFileOpen": false` for your FileTarget `"logErrorFile"`.

**Comment by lansman** [comment] 2023-10-31 17:09
>Is your application shutdown/restarted every 30 minutes?
We have several console applications, they are launched by cron, some of them are launched every 30 minutes.

>(Because of "autoReload": true)
It's really not needed and not used.

> Would it be possible to set InternalLogger.LogLevel = LogLevel.Info ?
Yes.

>I don't know the file-viewer that you are using. NLog will by default call FileStream.Flush() after each LogEvent-batch. This should flush to the operating-system, so if the application terminates, then file-output stays. But if the operating-system file-system-cache doesn't flush to disk until closing file-handle, then it might not be visible for the file-viewer.
Im not sure how it's related to my issue, i dont check logs at the moment they are created, i connect to server and look at logs when process have created them already stopped, a long time ago. As you can see on screenshots.

> But maybe you can configure "KeepFileOpen": false for your FileTarget "logErrorFile", and see if it cures your pain.
Okay.

**Comment by snakefoot** [comment] 2023-10-31 17:17
>Im not sure how it's related to my issue

Lets say you have an application, that is stuck an doesn't shutdown properly. Then that application will not close its file-handles. And if the operating-system is not showing "unwritten" bytes until file-handles is closed, then you will see 0 bytes. Again I'm just making up random excuses.

Btw. have you made sure to call `NLog.LogManager.Shutdown()` as the last thing before applicatin-exit ? (Or using `NLogProviderOptions.ShutdownOnDispose` = true).

**Comment by lansman** [comment] 2023-11-01 06:43
> But maybe you can configure "KeepFileOpen": false for your FileTarget "logErrorFile", and see if it cures your pain.

It worked! Application's fresh error log that were empty before now contains data.

**Comment by snakefoot** [comment] 2023-11-01 07:57
Then I guess there is some file-caching in the operating-system or your file-viewer that is causing the 0 bytes files. And the file-caching is refreshed/fixed when NLog closes the file-handle after each file-write.

Notice `"KeepFileOpen": false` is very slow (300 logevents/sec). So it can be a good idea to enable `"async": true` if application-performance is important.

**Comment by snakefoot** [comment] 2023-11-06 16:33
Closing issue due to inactivity.

Believe the issue is in the file-viewer being usedc, which fails to refresh correctly, unless NLog closes file-handle after each log-write.

**Closed by snakefoot** 2023-11-06 16:33 UTC
Labels: question, file-target, external

**Comment by lansman** [comment] 2023-11-07 08:26
> > It worked! Application's fresh error log that were empty before now contains data.
> 
> Then I guess there is some file-caching in the operating-system or your file-viewer that is causing the 0 bytes files. And the file-caching is refreshed/fixed when NLog closes the file-handle after each file-write. Similar issue here with non-working file-viewer-app: #4977
> 
> Notice `"KeepFileOpen": false` is very slow (300 logevents/sec). So it can be a good idea to enable `"async": true` if application-performance is important.

How to use "async": true? I tried to put it inside Target:
```
    "targets": {
      "logErrorFile": {
        "keepFileOpen": false,
        "async": true,
        "OpenFileCacheTimeout": 30,
        "autoFlush": false,
        "OpenFileFlushTimeout": 5
      }
    },
```

But got error:
```
Unhandled exception. NLog.NLogConfigurationException: 'FileTarget' cannot assign unknown property 'async'='True'
   at NLog.Config.LoggingConfigurationParser.SetPropertyValueFromString[T](T targetObject, String propertyName, String propertyValue, ValidatedConfigurationElement element)
   at NLog.Config.LoggingConfigurationParser.ConfigureObjectFromAttributes[T](T targetObject, ValidatedConfigurationElement element, Boolean ignoreType)
   at NLog.Config.LoggingConfigurationParser.ParseTargetElement(Target target, ValidatedConfigurationElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.LoggingConfigurationParser.AddNewTargetFromConfig(String targetTypeName, ValidatedConfigurationElement targetElement, Boolean asyncWrap, Dictionary`2 typeNameToDefaultTargetParameters, ValidatedConfigurationElement defaultWrapperElement)
   at NLog.Config.LoggingConfigurationParser.ParseTargetsElement(ValidatedConfigurationElement targetsElement)
   at NLog.Config.LoggingConfigurationParser.ParseNLogSection(ILoggingConfigurationElement configSection)
   at NLog.Config.LoggingConfigurationParser.LoadConfig(ILoggingConfigurationElement nlogConfig, String basePath)
   at NLog.Extensions.Logging.NLogLoggingConfiguration.LoadConfigurationSection(IConfigurationSection nlogConfig)
   at NLog.Extensions.Logging.NLogLoggingConfiguration..ctor(IConfigurationSection nlogConfig, LogFactory logFactory)
   at NLog.Extensions.Logging.NLogLoggingConfiguration..ctor(IConfigurationSection nlogConfig)
```

**Comment by lansman** [comment] 2023-11-07 08:27
And i'm still not sure what do mean "file-viewer"?

**Comment by snakefoot** [comment] 2023-11-07 08:40
File Viewer is the blue application in your screenshots, that is showing file size 0 bytes.

You can see how to enable "async" here: https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json


Sent from my Galaxy



-------- Original message --------
From: lansman ***@***.***>
Date: 07/11/2023 09:27 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, State change ***@***.***>
Subject: Re: [NLog/NLog] File viewer listing logfiles with incorrect file size of 0 bytes (Issue #5379)


And i'm still not sure what do mean "file-viewer"?

**Comment by lansman** [comment] 2023-11-07 08:55
This is Far Manager.
As i told you i launch this app just before creating a screenshot. It is _not_ working during the night when the problem occurs. So there is no chance it can somehow hurt log creation.

**Comment by snakefoot** [comment] 2023-11-07 09:00
I don't know how FAR manager retrieves file sizes. But until there is some evidence that NLog FileTarget is failing to write, then I'm guessing that it is a caching issue causing file size showing 0 bytes.



Sent from my Galaxy



-------- Original message --------
From: lansman ***@***.***>
Date: 07/11/2023 09:55 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, State change ***@***.***>
Subject: Re: [NLog/NLog] File viewer listing logfiles with incorrect file size of 0 bytes (Issue #5379)


This is Far Manager.
As i told you i launch this app just before creating a screenshot. It is not working during the night when the problem occurs. So there is no chance it can somehow hurt log creation.

**Comment by snakefoot** [comment] 2023-11-07 09:11
BTW You are now showing that you have explicitly configured. AutoFlush=false.

This will give you the bad behavior. Remove the setting of AutoFlush and OpenFileFlushTimeout. These options requires that your application is shutdown correctly without crashing or being killed by operating system.


Sent from my Galaxy



-------- Original message --------
From: lansman ***@***.***>
Date: 07/11/2023 09:55 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, State change ***@***.***>
Subject: Re: [NLog/NLog] File viewer listing logfiles with incorrect file size of 0 bytes (Issue #5379)


This is Far Manager.
As i told you i launch this app just before creating a screenshot. It is not working during the night when the problem occurs. So there is no chance it can somehow hurt log creation.

**Comment by snakefoot** [comment] 2023-11-07 09:16
You should just remove all settings overrides in appsettings.production.json for target logErrorFile. None of them provide any improvements with NLog v5



Sent from my Galaxy



-------- Original message --------
From: lansman ***@***.***>
Date: 07/11/2023 09:55 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, State change ***@***.***>
Subject: Re: [NLog/NLog] File viewer listing logfiles with incorrect file size of 0 bytes (Issue #5379)


This is Far Manager.
As i told you i launch this app just before creating a screenshot. It is not working during the night when the problem occurs. So there is no chance it can somehow hurt log creation.

**Comment by lansman** [comment] 2023-11-07 09:25
After some investigation we found a logger collector on server, written by our coallegue, that reads logs every 10 minutes. What should we do to avoid creating empty logs (besides using slow "KeepFileOpen": false), make colleсtor read files in non-blocking mode, something like that?

And using _"KeepFileOpen": false + async: true_ is slower than _"KeepFileOpen": true_ or not?

**Comment by lansman** [comment] 2023-11-07 09:26
> BTW You are now showing that you have explicitly configured. AutoFlush=false.

No, it was on my first message already.

> This will give you the bad behavior. 
> You should just remove all settings overrides in appsettings.production.json for target logErrorFile. None of them provide any improvements with NLog v5
Okay, i'll try

**Comment by lansman** [comment] 2023-11-07 09:39
I found logger collector is not an issue. It didn't work for several days but empty logs were still created these days. Just for the clarity.

**Comment by snakefoot** [comment] 2023-11-07 10:33
The issue with KeepFileOpen=false is that NLog FileTarget can loose it's file-handle and cause application logging to fail completely (Along with the entire application when not using async=true)

But yes async=true with keepFileOpen=false will work okay when only logging 1 mbyte/hour. But there is natural overhead from opening and closing file for each file-write)

KeepFileOpen=true is  more predictable and faster. As long you don't use AutoFlush=false. But always a good idea to perform your own performance testing in the actual environment.

Sent from my Galaxy



-------- Original message --------
From: lansman ***@***.***>
Date: 07/11/2023 10:25 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, State change ***@***.***>
Subject: Re: [NLog/NLog] File viewer listing logfiles with incorrect file size of 0 bytes (Issue #5379)


After some investigation we found a logger collector on server, written by our coallegue, that reads logs every 10 minutes. What should we do to avoid creating empty logs (besides using slow "KeepFileOpen": false), make colleсtor read files in non-blocking mode, something like that?

And using "KeepFileOpen": false + async: true is slower than "KeepFileOpen": true or not?

**Comment by snakefoot** [comment] 2023-11-07 17:51
Sorry for not immediately seeing the use of `appsettings.json` togther with override functionality that activates the use of `"autoflush": false`, and accusing FAR-manager for being faulty.

I can see that the [FileTarget Wiki](https://github.com/NLog/NLog/wiki/File-target#configuration-syntax) doesn't really explain the side-effects of using `autoflush=false`, and almost invites people to use the exotic setting:

> **AutoFlush** - Indicates whether to automatically flush the file buffers after each log message. Disabling this will improve performance (See also openFileFlushTimeout). [Boolean](https://github.com/NLog/NLog/wiki/Data-types) Default: True

Will try and update the wiki-page, so it doesn't invite using `autoflush=false` unless one really knows what they are doing.

**Comment by snakefoot** [comment] 2023-11-07 18:55
Since your console application was able to generate log-files with file size 0 bytes, then it seems that the console-application terminates prematurely either because of crashing or forced shutdown. If this is the case then`"async": true` might not be good advice, since one can loose critical log-messages.

Ofcourse you should make sure that the console-application correctly shutdown NLog before leaving program-main-method.

```csharp
public class Program
{
  private static int Main()
  {
    try
    {
        // Application code
        return 0;
    }
    catch(Exception ex)
    {
        NLog.LogManager.GetLogger("Application").Error(ex, "Unhandled exception");
        throw;   // Give it to the operating system
    }
    finally
    {
        NLog.LogManager.Shutdown();
    }
  }
}
```
