### ISSUE TITLE
NLog 4.3.8 onward writing logs to wrong folder with custom app domain

### ISSUE THREAD

**Issue by Tommyknocker1982** [NLog/NLog#1828] opened 2016-12-05 15:40 UTC
**Type** - Bug

**NLog version** - 4.3.8

**Platform**: - .Net 4.5

**Current NLog config** (xml or C#, if relevant)

```xml
  <nlog autoReload="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <variable name="layout" value="${longdate:universalTime=true}|${level:uppercase=true}|${threadid}|${logger}|${message}" />
    <targets async="true">
      <target name="debugger" xsi:type="Debugger" layout="${layout}" />
      <target name="logfile" xsi:type="File" fileName="logs\app.log" archiveFileName="logs\app.{###}.log" archiveEvery="Day" archiveAboveSize="1024000" archiveNumbering="Rolling" maxArchiveFiles="10" concurrentWrites="false" keepFileOpen="false" layout="${layout}" />
    </targets>
    <rules>
      <logger name="*" minlevel="Info" writeTo="logfile" />
      <logger name="*" minlevel="Debug" writeTo="debugger" />
    </rules>
  </nlog>
```

Hi

We recently upgraded from NLog 4.3.3 to 4.3.11, and noticed that the logs for our application started to be written to the wrong folder.  I narrowed it down to a change introduced in 4.3.8.  The structure of our application is:

```
AppFolder
  \ Bin
    app.exe
  bootstrapper.exe
  \ Logs
```

bootstrapper.exe is run first, with a working directory of AppFolder.  It creates an app domain, into which it loads and runs Bin\app.exe.  app.exe is configured to write logs to Logs\app.log.  Up to and including NLog 4.3.7, it would correctly pick up the working directory of the bootstrapper.exe process and write logs fo AppFolder\Logs\app.log.  But from NLog 4.3.8, it started writing logs to AppFolder\Bin\Logs\app.log.  It seems that instead of using the working directory, it is using the location of the executable which is being loaded and run dynamically at runtime.

I couldn't find anything in the 4.3.8 release notes which suggests this change was intended, so if it is a bug, can it be fixed or reverted?

Thanks very much,

Graham Stoneman.

**Comment by 304NotModified** [comment] 2016-12-05 16:47
Could you post your config? Especially of the fileTarget?

**Comment by Tommyknocker1982** [comment] 2016-12-05 16:49
Hi,

I'd included it but had forgotten to enclose it in markup so it was hidden.  I've fixed the post now, sorry about that!

Thanks,

Graham.

**Comment by 304NotModified** [comment] 2016-12-05 16:51
Thx!

**Comment by 304NotModified** [comment] 2016-12-05 16:53
summary:

setting: `fileName="logs\app.log"`
3.4.7: `AppFolder\Logs\app.log` (correct)
4.3.8: ` AppFolder\Bin\Logs\app.log` (wrong)

**Comment by snakefoot** [comment] 2016-12-05 20:08
Committed changes 4.3.7 -> 4.3.8:

https://github.com/NLog/NLog/compare/v4.3.7...v4.3.8

**Comment by 304NotModified** [comment] 2016-12-05 20:54
I expect that the issue is in this file: https://github.com/NLog/NLog/compare/v4.3.7...v4.3.8#diff-69ebd0fa25d676375e25b068f68b3c11

**Comment by 304NotModified** [comment] 2016-12-05 21:08
I think this goed wrong with only when app domains are created.

@Tommyknocker1982 could you help us in writing an unit test? Probable we don't even have to write to a file in the unit test, but test this


```C#
//create app domain, set basepath?

var layout = FilePathLayout(value, true, null);
var filename = Render(LogEventInfo.CreateNullEvent());
Assert.Equal(..., filename);
```

Dunno how the app domain code would look like

**Comment by Tommyknocker1982** [comment] 2016-12-06 09:06
Hi,

Having looked at that change in 4.3.8, I think that most users would expect it to use the base directory of the current app domain by default.  So instead of reverting the behaviour, would it be possible to add a new token ${processdir} which resolves to the directory of the parent process?  This would let us have the old behaviour by specifying "${processdir}\logs\app.log" in our config, and is consistent with existing tokens like ${processinfo} etc...

**Comment by snakefoot** [comment] 2016-12-06 09:31
So something like this:

> string appFilePath = new Uri(System.Reflection.Assembly.GetExecutingAssembly().CodeBase).LocalPath;
> appBaseDir = System.IO.Path.GetDirectoryName(appFilePath);

**Comment by snakefoot** [comment] 2016-12-06 09:36
> string appFilePath = System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName;
> string appBaseDir = System.IO.Path.GetDirectoryName(appFilePath);

**Comment by Tommyknocker1982** [comment] 2016-12-06 10:01
Yes, that would work.  Could that please be added to NLog 4.4?  Thanks very much, Graham.

**Comment by 304NotModified** [comment] 2016-12-06 18:00
> Having looked at that change in 4.3.8, I think that most users would expect it to use the base directory of the current app domain by default.

yes `a/b ` should be equals to `${basedir}/a/b` IMO.

But I really like to know, is this a bug? Is path.getfullname using the "processdir"? In which case is this not a problem? 


> Maybe it could just be an option on the BaseDirLayoutRenderer, whether it should use AppDomain-BaseDir or CurrentProcess-BaseDir.

Good idea!

**Comment by Tommyknocker1982** [comment] 2016-12-07 11:25
Hi, no I think that if anything a bug was present up to 4.3.7 and fixed in 4.3.8.  I've managed to get the old behaviour back by writing a custom layout renderer, so we don't require any changes to NLog now.  Thanks to everybody who helped investigate the issue, you've been brillient!  This issue can be marked as closed now.  Cheers, Graham.

**Comment by 304NotModified** [comment] 2016-12-07 16:39
@Tommyknocker1982 I still like to add this :) 

Do you have time to send a PR with this proposal? (including some tests)? 

> option on the BaseDirLayoutRenderer, whether it should use AppDomain-BaseDir or CurrentProcess-BaseDir.

**Comment by 304NotModified** [comment] 2017-01-14 16:39
how could we test this in an unit test?

**Comment by snakefoot** [comment] 2017-01-14 16:52
> how could we test this in an unit test?

Guess you could create a normal AppDomain (instead of a Medium-Trust-One) with a custom basedir, and see the file is written in the test-runner-bin-folder (Like where DoConcurrentTest is currently writing).

**Comment by 304NotModified** [comment] 2017-01-14 17:33
thanks @snakefoot !

I will give it a try

**Closed** 2017-01-14 18:25 UTC
Labels: bug, file-target
