### ISSUE TITLE
${exception} limit the results of .Data (and change default)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog#3463] opened 2019-06-08 11:32 UTC
By truncate result, or only print primitives(-likes)

split of https://github.com/NLog/NLog/issues/2588

**Comment by 304NotModified** [comment] 2019-06-08 11:34
related: https://github.com/RehanSaeed/Serilog.Exceptions

**Comment by 304NotModified** [comment] 2019-06-08 11:42
@snakefoot please continue here thanks :)

**Comment by 304NotModified** [comment] 2019-06-08 11:43
From snakefoot:

> Yes people who know their own app and all its dependent libraries are not injecting funky stuff into Data-dictionary can then explicitly add it to their NLog-config. But very few apps can make this promise.
> […](#)


> Funny how you mention the serilog exception enricher. It is actually because of issues with out-of-memory caused by this enricher that I want NLog to avoid the same mistakes.
> […](#)

**Comment by snakefoot** [comment] 2019-06-08 11:46
Funny how you mention the serilog exception enricher. It is actually because of issues with out-of-memory caused by this enricher that I want NLog to avoid the same mistakes.


Either remove "Data" from default-output. Or ensure only primitive types like IConvertible + IFormatable are included.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


@snakefoot<https://github.com/snakefoot> please continue here thanks :)

**Comment by snakefoot** [comment] 2021-01-18 21:59
After seeing that `ExceptionLayoutRenderer.AppendData` only appends the `ToString()`-output and not performs object-reflection of any kind, then I think all my worries are unwarranted.

Closing this issue as I think it is fine with having `Format=ToString,Data` as default.

**Closed by snakefoot** 2021-01-18 21:59 UTC
Labels: enhancement
