### ISSUE TITLE
GetCurrentClassLogger in base class wrong Class logger

### ISSUE THREAD

**Issue by giammin** [NLog/NLog#683] opened 2015-04-24 14:06 UTC
public abstract class BaseClass
    {
        private Logger _logger;
        protected Logger Logger
        {
            get { return _logger ?? (_logger = LogManager.GetCurrentClassLogger()); }
        }
    }

    public class Derived : BaseClass
    {
        public Derived()
        {
            Logger.Info("test");
            // Logger "BaseClass"
            // Expected "Derived"  
        }
    }

Workaround:
_logger = LogManager.GetLogger(GetType().Name)

**Comment by 304NotModified** [comment] 2015-04-25 21:37
I would expect "baseclass" because it's defined in baseclass.

This is expected behavior.

**Comment by 304NotModified** [comment] 2015-04-25 21:39
What would you expect with `class Derived2: BaseClass `...?

**Comment by giammin** [comment] 2015-04-27 08:00
>What would you expect with class Derived2: BaseClass...?
logger: Derived2

**Comment by 304NotModified** [comment] 2015-04-27 08:10
Yes but the method is not `abstract`

**Comment by giammin** [comment] 2015-04-27 08:36
the method says: GetCurrentClassLogger

I expect the current instantiated class, maybe I'm wrong...

**Comment by giammin** [comment] 2015-04-28 10:02
So what is the best practice if i want to have a base abstract class with a logger?

**Comment by 304NotModified** [comment] 2015-04-30 20:17
The best practice it to create a private field for each class. So each class have:

```
private Logger _logger = LogManager.GetCurrentClassLogger(); //or static if desired. 
```

There is no benefit creating this in an abstract class IMO

**Comment by giammin** [comment] 2015-05-01 15:47
the benefit is to not have to implement a logger in all derived classes

**Comment by 304NotModified** [comment] 2015-05-03 10:58
It saves 1 line of code for each class, yes.

`LogManager.GetLogger(GetType().Name)` looks fine to me.

**Comment by Xharze** [comment] 2015-05-10 22:39
Closed as this seems answered, please reopen if needed

**Closed by Xharze** 2015-05-10 22:39 UTC
Labels: question
