### ISSUE TITLE
WebService Target httpPost body starts with BOM in case of UTF-8

### ISSUE THREAD

**Issue by skironDotNet** [NLog/NLog#250] opened 2013-07-31 16:37 UTC
Hi Jarek (co slychac)

Could you fix stream to not include BOM, it messes up first parameter of httpPost body

here is more details about the problem (from someone else):

http://nlog-forum.1685105.n2.nabble.com/WebService-target-HttpPost-and-HttpGet-not-working-td7577418.html

**Comment by 304NotModified** [comment] 2015-01-17 11:36
Duplicate of #212

**Closed by 304NotModified** 2015-01-17 11:36 UTC
Labels: bug, duplicate
