### ISSUE TITLE
jsonLayout encoding problem

### ISSUE THREAD

**Issue by tayfunatas** [NLog/NLog#1566] opened 2016-07-27 11:10 UTC
Hi I'm using jsonLoyout, but I'm having trouble encoding (utf-8). I can't show turkish character.

can you help me ?

**Type** :

- Question

**NLog version**: (4.3.4)

**Platform**: ..Net 4.5

**Current NLog config** (xml)

```xml
    <target xsi:type="File"
				name="GateloggerTarget"
				fileName="C:\Logs\Payflex.Collection\GateLogger\${date:format=yyyy}\${date:format=MM}\${shortdate}.txt"
				encoding="utf-8"
				layout="${longdate}|${message}">
      <layout xsi:type="JsonLayout">
				<attribute name="Direction" layout="${event-context:item=Direction}" />
				<attribute name="TrackId" layout="${event-context:item=TrackId}" />
				<attribute name="MethodName" layout="${event-context:item=MethodName}" />
				<attribute name="HostAddress" layout="${event-context:item=HostAddress}" />
				<attribute name="Date" layout="${date:format=MM/dd/yyyy HH\:mm\:ss.fff}" />
				<attribute name="Message" layout="${message}" />
			</layout>
    </target>

```

Log output : 
Message=\"**## 2304 \u0130\u015flem y\u00fcr\u00fct\u00fcl\u00fcyor.\**"

**Comment by 304NotModified** [comment] 2016-07-27 17:00
@UgurAldanmaz could you help with this case?

**Comment by tayfunatas** [comment] 2016-07-28 07:24
if I do not use jsonLayout there is no problem. but JsonLayout it doesn't work. sample Nlog config. Like above

**Comment by 304NotModified** [comment] 2016-07-28 08:46
Ah then the bug is probable in https://github.com/NLog/NLog/blob/master/src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs

**Comment by UgurAldanmaz** [comment] 2016-07-28 13:12
Sorry for late reply. I am investigating the reason.

**Comment by UgurAldanmaz** [comment] 2016-07-28 23:31
As @304NotModified said, problem is in `JsonEncodeLayoutRendererWrapper`. But it is not a bug, just a config issue.

You need to disable JSON encoding for log messages. Set `encode` as `false` of the message attribute.

`<attribute name="Message" layout="${message}" encode="false" />`

See https://github.com/NLog/NLog/wiki/JsonLayout

P.S. Do not remove     `encoding="utf-8"`. You need it for file encoding.

I am closing this issue. If solution does not work for you, please let us know.

**Closed by UgurAldanmaz** 2016-07-28 23:31 UTC
Labels: question

**Comment by 304NotModified** [comment] 2016-07-29 15:52
Thanks @UgurAldanmaz !

**Comment by ManuelAfonso** [comment] 2020-09-04 12:58
If you add encode="false" and use something like 
`logger.LogWarning("{@item} nao é anónimo", new Item {Id = 100, Name = "CEM"});`
You get this result:
```
    "message": {
         @ item
    }
    nao é anónimo,

```
Note: I'm using `layout="${message:raw=true}"` because without it the values are written on the message, loosing the advantage of structered logging.
