### ISSUE TITLE
Compressed Archive failing in .Net Core Console App

### ISSUE THREAD

**Issue by thisisjagan** [NLog/NLog#4272] opened 2021-01-28 06:27 UTC
Hi Team,

I have a .Net Core 3.1 Console App with Dependency Injection configured. I have configured NLog and logging works fine. However, the Compressed Archive does not happen. I have the same configuration working in Asp .Net Core 3.1 Web API.

Please help.

**NLog version**: 
<PackageReference Include="NLog" Version="4.7.6" />
<PackageReference Include="NLog.Extensions.Logging" Version="1.6.5" />

**Platform**: .Net Core 3.1

**Current NLog config**:

```xml

<?xml version="1.0" encoding="utf-8" ?>
<!-- XSD manual extracted from package NLog.Schema: https://www.nuget.org/packages/NLog.Schema-->
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xsi:schemaLocation="NLog NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Info"
      internalLogFile="${basedir}/Logs/internal-nlog.txt">

  <variable name="Layout"
            value="${date:format=dd-MM-yyyy HH\:mm\:ss.fff}|${level:uppercase=true}|${logger}|${message}"/>

  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file -->
    <target xsi:type="File"
            name="allfile"
            fileName="${basedir}/Logs/Auto_ZDEmailIntegration_${date:format=ddMMyyyy}.log"
            archiveFileName="${basedir}/Logs/Archive/Auto_ZDEmailIntegration_Archive_{#}.zip"
            archiveEvery="Day"
            archiveAboveSize="10485760"
            archiveNumbering="Date"
            archiveDateFormat="ddMMyyyyHHmm"
            maxArchiveDays="7"
            enableArchiveFileCompression="true"
            layout="${Layout}" />

    <!-- write to the void aka just remove -->
    <target xsi:type="Null" name="blackhole" />
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />

    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
  </rules>
</nlog>

```

- What is the current result? Archive and Old log file deletion doesnt happen.
- What is the expected result? Old Log files should be Compressed and should be archived.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes, No errors found.
- Please post full exception details (message, stacktrace, inner exceptions): No exceptions found.
- Are there any workarounds? No
- Is there a version in which it did work? It worked with ASP .Net Core 3.1 Web API.
- Can you help us by writing an unit test?

**Comment by snakefoot** [comment] 2021-01-28 06:51
This issue is a duplicate of this. #3807 (That is a duplicate of many others).

The issue is this (Using of dynamic `${date}`):

> fileName="${basedir}/Logs/Auto_ZDEmailIntegration_${date:format=ddMMyyyy}.log"

Dynamic archive logic doesn't work together with static archive logic:

> archiveFileName="${basedir}/Logs/Archive/Auto_ZDEmailIntegration_Archive_{#}.zip"

See also https://github.com/NLog/NLog/issues/3807#issuecomment-587661413

**Comment by snakefoot** [comment] 2021-01-28 11:29
Hope this answers your question?

**Closed** 2021-02-04 11:29 UTC
Labels: file-archiving, file-target, needs info, question
