### ISSUE TITLE
Windows 10: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by Valhadon** [NLog/NLog#1939] opened 2017-01-30 21:59 UTC
**Type:** Bug

**NLog version:** 5.0.0-beta04

**Platform:**  .NET Core (win-x64.1.1.0)

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="logs/internal-nlog.txt">
  <targets>
    <target name="console" xsi:type="Console" />
    <target name="file" xsi:type="File" fileName="logs/nlog-linux.txt" />
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="console" />
    <logger name="*" minlevel="Info" writeTo="file" />
  </rules>
</nlog>
```

Hi,

On Windows 10 I am unable to write to my file target when running a .NET Core Console Application in a Linux container, but the console target seems to work just fine. The weird thing is the "internal-nlog.txt" file seems to work and is writing to the same mounted volume directory, following the same naming conventions. I have tested the app in a Windows container as well and everything seems to work fine.

internal-nlog.txt
```txt
2017-01-30 20:52:27.1706 Error Error has been raised. Exception: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.CreateArchiveMutex()
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Factory.NLog.Internal.FileAppenders.IFileAppenderFactory.Open(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.FileAppenderCache.AllocateAppender(String fileName)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
```

I have tried several different paths, as well as manually creating the directories, and even files to make sure they were available. Nothing seems to work.

Dockerfile
```txt
# Sample Dockerfile for .NET Core Example

# The FROM keyword tells Docker which image your image is based on.
# https://hub.docker.com/r/microsoft/dotnet/
FROM microsoft/dotnet:latest

# Indicates the working directory for this app.
WORKDIR /app

# indicates to copy the /app folder from the current application in the context to the /app folder within the image.
COPY /app /app

# This is the command or application that will run when the container starts.
ENTRYPOINT ["dotnet", "NETCoreExample.dll"]
```
This is the command I am using when running my docker image and I have made sure to share my **D:** drive in the docker settings.

```cmd
docker run --rm -v "d:/logs:/app/logs netcore-example"
```

**Comment by 304NotModified** [comment] 2017-01-30 22:02
This is Fixed in beta5

**Comment by 304NotModified** [comment] 2017-02-01 15:29
duplicate of https://github.com/NLog/NLog/issues/1882

Please use the search next time

**Closed by 304NotModified** 2017-02-01 15:29 UTC
Labels: duplicate
