### ISSUE TITLE
Add net46 Target Framework

### ISSUE THREAD

**Issue by TheXenocide** [NLog/NLog#3817] opened 2020-02-25 23:17 UTC
**NLog version**: 4.6.8

**Platform**: .NET Framework 4.8, .NET Core 3.1

I'm having an issue with a dual-targeting unit test project where the .NET Standard tests succeed, but the .NET Framework tests fail to run with the following error:

An exception occurred while invoking executor 'executor://mstestadapter/v2': Unable to find assembly 'NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.

After this error no tests run. It appears this may be related to the use of `CallContext.LogicalSetData` (per [this issue](https://github.com/microsoft/testfx/issues/180)). We recently switched all our usage of `CallContext` to `AsyncLocal` which has alleviated a number of AppDomain-specific issues that don't apply to how we intend to use it and I figured your .NET Standard implementation was already using it, so I figured I'd go see what the code looked like when I noticed [this line](https://github.com/NLog/NLog/blob/86fba05e272a07d508b32475957b9310f607061d/src/NLog/Contexts/MappedDiagnosticsLogicalContext.cs#L390) which shows you were already prepared to make this migration, but TargetFrameworks didn't contain net46 so this isn't shipped in the NuGet package. 

I pulled the source locally and made the couple small modifications necessary to test this and when I build the package with a net46 target included it solves my issues so I'm hoping you'll consider including the net46 target in the 4.7 release.

Thanks kindly.

**Comment by TheXenocide** [comment] 2020-02-26 15:18
I believe pull request #3818 establishes most of the work necessary for this, I'm checking to see if the couple failing unit tests are related to these changes or not now

**Comment by TheXenocide** [comment] 2020-02-26 15:41
Verified, all tests that were failing locally were already failing before my changes. Also note that the above indicates 2 commits, but there's actually only 1 (I amended it because I forgot to stage a change)

**Comment by snakefoot** [comment] 2020-02-26 20:41
See also #2871. Think net461 is the official platform-target for multi-target platforms (For some reason not net46 / net462 / net47 / net471 / net472 / net48)

**Comment by TheXenocide** [comment] 2020-02-27 18:41
Hi there and thanks for checking in. I tried looking around to understand what you mean by the recommendation for targeting net461 in multi-target apps, but I can't find anything specifically recommending that. I've always understand the premise of targeting the lowest version compatible with the required feature set (in this case `AsyncLocal<T>` which is fully functional in net46. It doesn't really impact me since we're targeting net48 anyway, so I can change that if necessary, but I question if it's actually necessary. 

As for the version 5 reference, I'm not 100% sure what about that is particularly similar here, unless you mean to remove net45 support in conjunction with removing Xamarin/WP/SL/etc. (or just want to ensure conversation about changing target frameworks are able to keep each other in mind)? In case it's about removing net45 support, it doesn't look super necessary (and, from my brief passage through the code to implement this, doesn't seem like it would help code cleanup efforts much unless 40/35 were also removed).

On a side-note, though, I did notice while googling around about target frameworks that MSBuild is already providing preprocessor symbols (at the bottom of [this section](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-target-frameworks)), which seem to be somewhat duplicated; instead of using `NET4_5` and `NET4_6` everywhere we could have used the built in `NET45`/`NET46` symbols. Not a big deal and sometimes they're being used differently than the default behavior would apply them, but thought I'd make a note of it since I just touched a bunch of code using hand-rolled ones that could have benefited from these instead.

**Comment by TheXenocide** [comment] 2020-02-27 18:49
Also, if anybody else having this issue stumbles on this ticket and is awaiting a solution, this is the workaround we have in place for MSTest projects. All of our MSTest projects reference a base library and the following is in a `.props` file included in that library's NuGet Package. It can be simplified if you want to include it directly in a specific test project:

```xml
  <PropertyGroup>
    <!-- This is here because MSbuild is supposed to support a "GeneratePathProperty" on PackageReference, but it doesn't seem to 
         be working correctly. The main advantage of that feature is just that this is another spot to maintain a version number
         but it's not that concerning since the version is also just a couple lines down from here
         -->
    <PkgNLog>$(NuGetPackageRoot)nlog\4.6.8\</PkgNLog>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' != 'netstandard2.0' ">
    <!-- This is only here because it's distributed in a NuGet Package; since the consuming project could add its own 
         PackageReference we ensure our definition is the one used. -->
    <PackageReference Remove="NLog" /> 
    
    <!-- Here's the real workaround; PrivateAssets="All" is quite optional, but consistent with how we want our downstream 
         packages defined since they are only adding this package reference to apply this workaround. -->
    <PackageReference Include="NLog" Version="4.6.8" ExcludeAssets="Compile" GeneratePathProperty="true" PrivateAssets="All" />
    <Reference Include="NLog">
      <HintPath>$(PkgNLog)lib\netstandard2.0\NLog.dll</HintPath>
    </Reference>
  </ItemGroup>
```

**Comment by snakefoot** [comment] 2020-02-27 20:14
The recommendation about using net461 is here:

> CONSIDER adding a target for net461 when you're offering a netstandard2.0 target.

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

The reason for telling about #2871. Is because plans have already been made for removing the following Silverlight and Xamarin in NLog 5 (And maybe also net40)

When adding a new target, then builds will become even slower as unit-tests has to be executed for yet another platform.

**Comment by TheXenocide** [comment] 2020-02-27 22:26
Okay, that makes more sense and I'll take a look at the link. Unfortunately some testing is showing some issues with the workaround unless it's manually applied directly to each test project which is a bit inconvenient.

**Comment by TheXenocide** [comment] 2020-02-27 22:48
Ahh, I'm pretty confident that compatibility advice is specifically about packaging a library that would otherwise only target .NET Standard. What they're getting at is that if your code builds against 4.6.1 just fine without additional packages from (or targeting only) .NET Standard 2 it's more convenient for projects targeting greater than 4.6 and less than .NET 4.7.2 (one thing that does is dramatically reduce the number of shim assemblies in your output directory necessary to target .NET Standard 2 prior to .NET 4.7.2); they call out 4.6.1 particularly in this case because it's the first version compatible with .NET Standard 2.0 (though not without some inconvenience). 

If there is value in providing a .NET 4.6 target (i.e. it doesn't require packages that only target .NET Standard 2/4.6.1 and can be compiled directly against 4.6) it should be fine to package it in this way. For one, it's available even to those who can't consume .NET Standard 2.0, and beyond that it will still provide the same convenience to 4.6.1-4.7.1 consumers.

**Comment by 304NotModified** [comment] 2020-05-28 02:13
I think adding 4.6 is the best way (and dropping 4.0, see #3979)

**Comment by snakefoot** [comment] 2020-06-29 21:51
Closing this as duplicate of #3979

**Closed** 2020-06-29 21:52 UTC
Labels: discussion, duplicate, platform support
