### ISSUE TITLE
Combine ArchiveEvery day setting, together with an ArchiveAboveSize setting - stops logging to soon

### ISSUE THREAD

**Issue by attrib75** [NLog/NLog#569] opened 2015-02-11 21:39 UTC
We're seeing an issue where the file target, with async wrapper no longer writes after moderate use.  We're using other targets at the same time, which continue to write, namely the database target.  If we restart the application that is using nlog, the text file writes again.

thanks

**Comment by tibel** [comment] 2015-02-12 12:08
We are seeing the same behavior with NLog 3.2.0

**Comment by Xharze** [comment] 2015-02-13 18:42
Could you provide a sample project for this?

**Comment by attrib75** [comment] 2015-02-13 22:07
Unfortunately its proprietary.  I could try to throw something together from scratch

**Comment by Xharze** [comment] 2015-02-13 23:15
That would be great if possible. I can't reproduce it, but it is a serious
bug what you describe.

**Comment by 304NotModified** [comment] 2015-02-14 04:57
Does anyone know if this bug is introduced in 3.2.0?

**Comment by 304NotModified** [comment] 2015-02-25 12:32
@attrib75 because we can't reproduce we need a sample project or unit tests. Otherwise I will need to close this issue.

**Comment by attrib75** [comment] 2015-03-12 21:18
I'll try to find time to reproduce the issue with a test app and submit it.  Looking at it more closely, I think we are configuring it wrong, or its not behaving as expected?  If you configure an ArchiveEvery day setting, together with an ArchiveAboveSize setting,  then each day, when that day's log messages hit the ArchiveAboveSize limit, its done logging for that day.  The next day, it will generate a new log file and log until it hits the ArchiveAboveSize limit, etc.

Is this the intended behavior?

 <target name="asyncFile" xsi:type="AsyncWrapper" queueLimit="1000" overflowAction="Grow">
      <target 
        xsi:type="File" archiveEvery="Day"  archiveAboveSize="1000000" archiveNumbering="Date"
        fileName="pathtolog\TaxHelper_Log.txt"   
     
        layout="${longdate}|${callsite:methodName=true} ${message} ${newline} ${windows-identity:userName=true:domain=true} ${newline}${exception:format=ToString} "/>
    </target>

thanks!

**Comment by 304NotModified** [comment] 2015-03-20 20:56
@Xharze do you know this?

**Comment by 304NotModified** [comment] 2015-04-15 20:53
I don't think that archive options should stop logging. So it's a bug.

**Comment by Xharze** [comment] 2015-04-16 05:12
I didn't know this, if it's the case it is a serious bug

**Comment by 304NotModified** [comment] 2015-04-19 21:05
@attrib75
I renamed the issue. Did I subscribed it well?

**Comment by attrib75** [comment] 2015-05-19 15:04
Yes, but this is the intended result right? If so, its not an issue, I just didn't understand how to configure it

**Comment by 304NotModified** [comment] 2015-05-19 17:31
Thanks

**Comment by 304NotModified** [comment] 2015-07-15 21:06
Hi @attrib75 

Is it possible to test this more with : archive every minute and a lower archiveabovesize? Can you get it reproduced? 

We can then create a unit test and fix this

**Comment by 304NotModified** [comment] 2015-08-04 20:18
@attrib75 is it possible to test it for me?

**Comment by 304NotModified** [comment] 2015-08-04 20:54
I have found the issue. We cannot create multiple archive files with the same name (`archiveNumbering="Date"`).

It's unclear what to do. Don't archive? Append to the same archive file? 

The solution is to choose for `archiveNumbering="DateAndSequence"`

So proposal: wontfix.

**Comment by 304NotModified** [comment] 2015-08-04 20:57
@attrib75 please you input :)

**Comment by attrib75** [comment] 2015-08-05 03:04
Hi yes that makes sense.   I would agree to append a sequence to the archive above setting. Thank you for looking into this!

**Comment by 304NotModified** [comment] 2015-08-05 19:52
Thanks for the feedback!

**Comment by 304NotModified** [comment] 2015-08-07 21:27
Warning notes added at: https://github.com/NLog/NLog/wiki/File-target

**Closed by 304NotModified** 2015-08-07 21:27 UTC
Labels: must have, needs documentation on wiki, wontfix
