### ISSUE TITLE
ReconfigExistingLoggers sometimes throws an Exception

### ISSUE THREAD

**Issue by jpdillingham** [NLog/NLog#2228] opened 2017-07-29 16:20 UTC
**Type** (choose one):

- Bug

**NLog version**: (e.g. 4.2.3) 4.4.11

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5 / Mono 4 / Silverlight 4 / Silverlight 5 / Xamarin Android / Xamarin iOs / .NET Core 

The fix I contributed for #2130,

```List<WeakReference> loggerReferences = new List<WeakReference>(loggerCache.Values.ToList());```

Sometimes throws an Exception related to the new List being too small to be initialized with the ToList() of loggerCache.Values.  My CI has caught it a few times but I don't recall the exact Exception and can't reproduce it easily as it is concurrency related.  

I investigated the problem when I first saw it and it stems from the fact that the destination list is constructed of size equal to the capacity of the ToList, and if the initializing list grows (via another thread) before the assignment is made the Exception occurs.

I will submit a PR shortly with the following change to this line:
```List<WeakReference> loggerReferences = loggerCache.Values.ToList();```

This was suggested by @snakefoot in the discussion of my original PR and I regret not implementing the change then.

**Comment by snakefoot** [comment] 2017-07-29 16:47
If the problem is caused by the Values-Collection-Enumerator is detecting that the dictionary has been modified while enumerating, then the correct fix is to make the clone under a lock (See alternative solution here: #2131)

**Comment by jpdillingham** [comment] 2017-08-03 02:15
Here's the Exception from Travis:

```      
System.ArgumentException : Destination array is not long enough to copy all the items in the collection. Check array index and length.
      Stack Trace:
          at System.ThrowHelper.ThrowArgumentException (System.ExceptionResource resource) [0x0000b] in <a07d6bf484a54da2861691df910339b1>:0 
          at System.Collections.Generic.Dictionary`2+ValueCollection[TKey,TValue].CopyTo (TValue[] array, System.Int32 index) [0x0002d] in <a07d6bf484a54da2861691df910339b1>:0 
          at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x0003b] in <a07d6bf484a54da2861691df910339b1>:0 
          at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <26aedeede9534b948c539f8734c8492d>:0 
          at NLog.LogFactory+LoggerCache.GetLoggers () [0x0001c] in <5dc7a5839cbe4c63afddb1315bb49ae9>:0 
          at NLog.LogFactory+LoggerCache.get_Loggers () [0x00000] in <5dc7a5839cbe4c63afddb1315bb49ae9>:0 
          at NLog.LogFactory.ReconfigExistingLoggers () [0x00030] in <5dc7a5839cbe4c63afddb1315bb49ae9>:0 ```

**Comment by 304NotModified** [comment] 2017-08-04 08:49
This is a serious bug and I'm thinking to release 4.3.12 for it, if someone has time to fix it ;)

**Comment by 304NotModified** [comment] 2017-08-08 19:27
Fixed by #2229 

Thanks!

**Closed by 304NotModified** 2017-08-08 19:27 UTC
Labels: bug, must have

**Comment by JustArchi** [comment] 2017-08-27 21:48
Could we get a V5 release with this fix it? I've met with similar issue in https://github.com/JustArchi/ArchiSteamFarm/issues/628#issuecomment-325209033

```
2017-08-27 15:12:15|ArchiSteamFarm-6352|FATAL|ASF|OnUnhandledException() System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.CopyTo(TValue[] array, Int32 index)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NLog.LogFactory.LoggerCache.GetLoggers()
   at NLog.LogFactory.ReconfigExistingLoggers()
   at ArchiSteamFarm.Program.GetUserInput(EUserInputType userInputType, String botName) in C:\projects\archisteamfarm\ArchiSteamFarm\Program.cs:line 84
   at ArchiSteamFarm.Bot.InitLoginAndPassword(Boolean requiresPassword) in C:\projects\archisteamfarm\ArchiSteamFarm\Bot.cs:line 1252
   at ArchiSteamFarm.Bot.<OnConnected>d__136.MoveNext() in C:\projects\archisteamfarm\ArchiSteamFarm\Bot.cs:line 1526
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 
```

Thank you in advance.

**Comment by 304NotModified** [comment] 2017-08-28 06:43
Please open a new github issue. That's easier to track as this one is fixed (for NLog 4). Thx!
