### ISSUE TITLE
XML log append

### ISSUE THREAD

**Issue by ammaade** [NLog/NLog#3870] opened 2020-03-31 15:37 UTC
Hello

Could you tell me how to append in a XML log file?
I would like to add a new element attached to the root node element.

Thanks

**Comment by 304NotModified** [comment] 2020-03-31 18:04
If you mean, 

mylogfile.txt

```
<root>
   LOGS WRITTEN HERE
</root>
```
Then you cant, as we can only append to a file, not insert.

Example that work, see here: https://github.com/NLog/NLog/wiki/XmlLayout

**Comment by snakefoot** [comment] 2020-03-31 18:15
Duplicate of  #3537

**Comment by snakefoot** [comment] 2020-03-31 18:16
Rewrite of Footer-Layout on file-append discussed here: https://github.com/NLog/NLog/issues/1658#issuecomment-604589881

**Closed** 2020-04-17 18:48 UTC
Labels: duplicate, question, xml-layout
