### ISSUE TITLE
Set writeTo from variable in appsettings.json

### ISSUE THREAD

**Issue by ufonator** [NLog/NLog#4398] opened 2021-04-12 14:01 UTC
**Question:** Hi, could you please give me an advice how can i use variable to set writeTo property in rule def.? I don't no why but when i'm using it like in example below nlog gives me error message like:

`Error has been raised. Exception: NLog.NLogConfigurationException: Target '${var:useTargets}' not found for logging rule: *.`

**NLog version**: 4.7.8
**NLog.Extensions.Logging version**: 1.7.1

**Platform**: .NET Core 3.1

**Current NLog config** 

```json
"NLog": {
        "autoReload": true,
        "throwConfigExceptions": false,
        "internalLogLevel": "Warn",
        "internalLogFile": "${basedir}/_logs/nlog-internal.log",
        "extensions": [
            {
                "NLog.Extensions.Logging": {
                    "assembly": "NLog.Web.AspNetCore"
                }
            }
        ],
        "default-wrapper": {
            "type": "AsyncWrapper",
            "overflowAction": "Block"
        },
        "variables": {
            "appId": "5303F133-6C1C-421F-B013-F1CCD2854ADA",
            "app": "XYZapi",
            "level": "Trace",
            "useTargets": "logfile,console",
            "redishost": "localhost",
            "redisport": "6379",
            "rediskey": "preduBotLogs"
        },
        "targets": {
            "tracefile": {
                "type": "File",
                "name": "tracefile",
                "fileName": "_logs/trace.${shortdate}.log",
                "layout": "${longdate}|${threadid}|${uppercase:${level}}|${logger}|${callsite}|${message}|${onexception:inner=${newline}${exception:format=tostring}}",
                "archiveFileName": "_logs/archives/trace.{#}.zip",
                "archiveAboveSize": 10000000,
                "archiveNumbering": "DateAndSequence",
                "archiveDateFormat": "yyyyMMdd",
                "enableArchiveFileCompression": true,
                "maxArchiveDays": 60,
                "keepFileOpen": true,
                "concurrentWrites": true
            },
            "logfile": {
                "type": "File",
                "name": "logfile",
                "fileName": "_logs/${shortdate}.log",
                "layout": "${longdate}|${threadid}|${uppercase:${level}}|${logger}|${callsite}|${message}|${onexception:inner=${newline}${exception:format=tostring}}",
                "archiveFileName": "_logs/archives/{#}.zip",
                "archiveAboveSize": 10000000,
                "archiveNumbering": "DateAndSequence",
                "archiveDateFormat": "yyyyMMdd",
                "enableArchiveFileCompression": true,
                "maxArchiveDays": 60,
                "keepFileOpen": true,
                "concurrentWrites": true
            },
        },
        "rules": [
            {
                "logger": "*",
                "minLevel": "Trace",
                "writeTo": "tracefile",
                "enabled": true
            },
            {
                "logger": "Microsoft.*",
                "minLevel": "Info",
                "final": true
            },
            {
                "logger": "*",
                "minLevel": "${var:level}",
                "writeTo": "${var:useTargets}"
            }
        ]
    },
```

minLevel from variable works just fine, thanks a lot

**Comment by snakefoot** [comment] 2021-04-12 16:44
Closing as duplicate of https://github.com/NLog/NLog.Extensions.Logging/issues/502

**Closed by snakefoot** 2021-04-12 16:44 UTC
