### ISSUE TITLE
Incorrect ${logger:shortName=true} with Generic logger names

### ISSUE THREAD

**Issue by anton-gogolev** [NLog/NLog#3127] opened 2019-02-18 11:23 UTC
Looking at the [code](https://github.com/NLog/NLog/blob/dev/src/NLog/LayoutRenderers/LoggerNameLayoutRenderer.cs#L61), this applies to pretty much any NLog version out there.

Imagine:

    public class FileConfigurationService<T> : 
        IFileConfigurationService<T>
        where T : class
    {
        private static readonly Logger Log =
            LogManager.GetLogger(typeof(FileConfigurationService<T>).FullName);

The `LogEventInfo.LoggerName` will now be equal to, e.g. 

> REDACTED.Platform.Impl.Configuration.Impl.FileConfigurationService`1[[REDACTED.Platform.Shared.ObjectModel.Configuration.HotelServiceOnlineCancellationConfiguration, REDACTED.Platform.Shared.ObjectModel, Version=3.19.7.3, Culture=neutral, PublicKeyToken=null]]

Which in turns makes `${logger:shortName=true}` render to

> 3, Culture=neutral, PublicKeyToken=null]]

That's even remotely not correct.

Should I tackle this with a PR?

**Comment by 304NotModified** [comment] 2019-02-18 12:50
Not sure, but isn't the issue in `typeof(FileConfigurationService<T>).FullName`? 

GetLogger won't alter the name ;)

**Comment by anton-gogolev** [comment] 2019-02-18 15:30
If we dropped generics altogether:

public class FileConfigurationService
{
    private static readonly Logger Log =
        LogManager.GetLogger(typeof(FileConfigurationService).FullName);

(or even replace `GetLogger()` with `GetCurrentClassLogger()`), that would produce a perfectly reasonable (albeit long-ish) `LoggerName` of "REDACTED.Platform.Impl.Configuration.Impl.FileConfigurationService". This is something that NLog users are already well used to, but somehow classes being generic break this behavior.

**Comment by snakefoot** [comment] 2019-02-18 19:06
The problem is the Assembly-strong-name that is sometimes are included with FullName. What if you change to Type.ToString?

```c#
public class FileConfigurationService<T> : 
    IFileConfigurationService<T>
    where T : class
{
    private static readonly Logger Log =
        LogManager.GetLogger(typeof(FileConfigurationService<T>).ToString());
```

And what happens if you use `GetCurrentClassLogger` ?

```c#
public class FileConfigurationService<T> : 
    IFileConfigurationService<T>
    where T : class
{
    private static readonly Logger Log = LogManager.GetCurrentClassLogger();
```

**Comment by anton-gogolev** [comment] 2019-03-05 10:00
@304NotModified, @snakefoot I'm hopless at explaining :)

My basic idea is to make it so that [${logger:shortName=true}](https://github.com/NLog/NLog/wiki/Logger-Layout-Renderer#rendering-options) returns not just

> ...the part after the trailing dot character

but

> ...the part between the trailing dot character and either the end of the string, or `` ` ``, or ` + ` characters

because that is presumably what users are expecting. Short Name of 

> REDACTED.Platform.Impl.Configuration.Impl.FileConfigurationService`1[[REDACTED.Platform.Shared.ObjectModel.Configuration.HotelServiceOnlineCancellationConfiguration, REDACTED.Platform.Shared.ObjectModel, Version=3.19.7.3, Culture=neutral, PublicKeyToken=null]]

should be `FileConfigurationService` (or even `HotelServiceOnlineCancellationConfiguration`, which is debatable), but decidedly not "the part after the trailing dot character"

**Comment by snakefoot** [comment] 2019-03-05 11:26
GetLogger will accept any string format. So trying to handle all weird inputs will probably generate more overhead than value


The easy solution is just stopping yourself from including the assembly name in the logger-name (Use ToString instead off FullName)


Sent from my Sony Xperia


---- Anton Gogolev wrote ----


@304NotModified<https://github.com/304NotModified>, @snakefoot<https://github.com/snakefoot> I'm hopless at explaining :)

My basic idea is to make it so that ${logger:shortName=true}<https://github.com/NLog/NLog/wiki/Logger-Layout-Renderer#rendering-options> returns not just

...the part after the trailing dot character

but

...the part between the trailing dot character and either the end of the string, or `, or + characters

because that is presumably what users are expecting. Short Name of

REDACTED.Platform.Impl.Configuration.Impl.FileConfigurationService`1[[REDACTED.Platform.Shared.ObjectModel.Configuration.HotelServiceOnlineCancellationConfiguration, REDACTED.Platform.Shared.ObjectModel, Version=3.19.7.3, Culture=neutral, PublicKeyToken=null]]

should be FileConfigurationService (or even HotelServiceOnlineCancellationConfiguration, which is debatable), but decidedly not "the part after the trailing dot character"

**Comment by anton-gogolev** [comment] 2019-03-05 11:50
I am aware that `GetLogger()` accepts pretty much anything. NLog itself more or less expects logger name to be a sequence of dot-separated strings. Ostensibly, the most widely used method of obtaining such names is something akin to `GetLogger(typeof(...).FullName)` or `GetCurrentClassLogger()`. With this, users are correctly expecting that the `shortName=true` option will effectively return class name and nothing more.

What I'm saying is that the behaviour of `shortName=true` option (and _only_ of that option) is inadequate in certain cases: specifically, when used with nested and generic classes. And I'm proposing to fix this behavior, but not by trying to "handle all weird inputs".

**Comment by snakefoot** [comment] 2019-03-05 12:03
Pretty sure GetCurrentClassLogger is doing it correctly. If not then it should be fixed.


Sent from my Sony Xperia


---- Anton Gogolev wrote ----


I am aware that GetLogger() accepts pretty much anything. NLog itself more or less expects logger name to be a sequence of dot-separated strings. Ostensibly, the most widely used method of obtaining such names is something akin to GetLogger(typeof(...).FullName) or GetCurrentClassLogger(). With this, users are correctly expecting that the shortName=true option will effectively return class name and nothing more.

What I'm saying is that the behaviour of shortName=true option (and only of that option) is inadequate in certain cases: specifically, when used with nested and generic classes. And I'm proposing to fix this behavior, but not by trying to "handle all weird inputs".

**Comment by snakefoot** [comment] 2019-03-05 13:01
Can actually see that FullName is used by the stack walker logic. Will make a PR to fix this.


But please make a PR with your idea. And if the overhead is non existing. Then let's improve.


Sent from my Sony Xperia


---- Anton Gogolev wrote ----


I am aware that GetLogger() accepts pretty much anything. NLog itself more or less expects logger name to be a sequence of dot-separated strings. Ostensibly, the most widely used method of obtaining such names is something akin to GetLogger(typeof(...).FullName) or GetCurrentClassLogger(). With this, users are correctly expecting that the shortName=true option will effectively return class name and nothing more.

What I'm saying is that the behaviour of shortName=true option (and only of that option) is inadequate in certain cases: specifically, when used with nested and generic classes. And I'm proposing to fix this behavior, but not by trying to "handle all weird inputs".

**Comment by 304NotModified** [comment] 2019-03-05 19:01
I'm sorry, but garbage in = garbage out.

**Comment by snakefoot** [comment] 2019-03-05 19:55
Created #3157 to remove use of Type.FullName to avoid Assembly-Info to be included in class-name.

**Comment by 304NotModified** [comment] 2019-03-15 20:37
Closing this as there is nothing to do for us

**Closed by 304NotModified** 2019-03-15 20:37 UTC
Labels: wontfix
