### ISSUE TITLE
Native AOT warnings

### ISSUE THREAD

**Issue by philfontaine** [NLog/NLog#5258] opened 2023-06-17 02:26 UTC
NLog 5.2 just got released, which removes trim warnings. 

Therefore, all issues related to that got closed, namely https://github.com/NLog/NLog/issues/5198 and https://github.com/NLog/NLog/issues/3777.

However, compiling for Native AOT still gives AOT warnings. Is this a separate topic, or was that intended to be fixed in 5.2 as well?

Here's a screenshot of a very simple reproduction. I can put the repro on github if needed.

![image](https://github.com/NLog/NLog/assets/16233697/7fab5936-6546-4a17-a52d-33d5edafc4cd)

**NLog version**: 5.2.0

**Platform**: .NET 7

**Comment by snakefoot** [comment] 2023-06-17 08:19
NLog uses compiled expression trees to optimize speed for doing object-reflection of custom logging-objects. Ex:
```c#
var v = new { Amount = 108, Message = "Hello" };
_logger.Info("{@Hello}", v);  // Uses reflection
```

I'm guessing that is also why your build also warns about `System.Linq.Expressions` is part of the build, because it is referenced by NLog.

When reading about [PublishAOT](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/) then it says:
- Requires trimming
- No dynamic loading (for example, Assembly.LoadFile).
- No run-time code generation (for example, System.Reflection.Emit).
- [System.Linq.Expressions](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions) always use their [interpreted form](https://github.com/dotnet/runtime/issues/17973#issuecomment-1325429181)

When using PublishAOT then there is no JIT-compiler available for optimizing Expression-Trees, and I'm guessing that is why that warnings are generated.

I'm not sure there is anyway to work-around this, besides waiting for NLog v6 that hopefully will extract the use of Expression-Trees into a separate nuget-package. Or maybe Microsoft will optimize their support for Expression-Trees in NET8 / NET9 so it no longer gives build-warnings. Until that happens, then you have to live with using [PublishReadyToRun](https://learn.microsoft.com/en-us/dotnet/core/deploying/ready-to-run)

If you find places where NLog can be optimized in regard to trimming / ready-to-run / AOT, then pull-requests are most wellcome.

**Comment by snakefoot** [comment] 2023-06-17 10:35
Getting the following warnings from NLog TestTrimPublish-example-project when using `<PublishAot>true</PublishAot>´ with `<TargetFramework>net7.0</TargetFramework>`:
```
3>"C:\Users\snakefoot\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\7.0.5\tools\\ilc" @"obj\Release\net7.0\win-x64\native\TestTrimPublish.ilc.rsp"
3>NLog.Layouts.LayoutParser.ParseLayoutRendererPropertyValue(ConfigurationItemFactory,SimpleStringReader,Nullable`1<Boolean>,String,PropertyInfo): Using member 'System.Type.MakeGenericType(Type[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. The native code for this instantiation might not be available at runtime.
3>NLog.Layouts.ValueTypeLayoutInfo.CreateTypedLayout(Type,Object): Using member 'System.Type.MakeGenericType(Type[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. The native code for this instantiation might not be available at runtime.
3>NLog.Internal.ObjectReflectionCache.TryLookupExpandoObject(Object,ObjectPropertyList&): Using member 'System.Type.MakeGenericType(Type[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. The native code for this instantiation might not be available at runtime.
3>NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type,String,ConfigurationItemFactory,Object&): Using member 'System.Type.MakeGenericType(Type[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. The native code for this instantiation might not be available at runtime.
3>NLog.Internal.PropertyHelper.CreateCollectionHashSetInstance(Type,Object,MethodInfo&): Using member 'System.Type.MakeGenericType(Type[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. The native code for this instantiation might not be available at runtime.
3>NLog.Internal.PropertyHelper.CreateCollectionHashSetInstance(Type,Object,MethodInfo&): Using member 'System.Type.MakeGenericType(Type[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. The native code for this instantiation might not be available at runtime.
3>NLog.Internal.PropertyHelper.CreateCollectionListInstance(Type,MethodInfo&): Using member 'System.Type.MakeGenericType(Type[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. The native code for this instantiation might not be available at runtime.
3>NLog.Internal.PropertyHelper.CreateCollectionListInstance(Type,MethodInfo&): Using member 'System.Type.MakeGenericType(Type[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. The native code for this instantiation might not be available at runtime.
3>NLog.Internal.PropertyHelper.ExtractHashSetComparer(Object,PropertyInfo): Using member 'System.Type.MakeGenericType(Type[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. The native code for this instantiation might not be available at runtime.
3>Assembly 'System.Linq.Expressions' produced AOT analysis warnings.
3>Assembly 'System.Private.Xml' produced AOT analysis warnings.
```

**Comment by snakefoot** [comment] 2023-06-24 14:26
Closing as duplicate of #3366

**Closed by snakefoot** 2023-06-24 14:26 UTC
Labels: question, platform support

**Comment by snakefoot** [comment] 2023-09-28 16:11
Current work-around is adding NLog to `rd.xml`:
```xml
<Project>
  <ItemGroup>
      <RdXmlFile Include="rd.xml" />
  </ItemGroup>

</Project>
```

**rd.xml**:
```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
        <!-- .NET Native fix -->
        <Assembly Dynamic="Required All" Name="NLog"/>
  </Application>
</Directives>
```

**Comment by snakefoot** [comment] 2025-04-29 19:24
NLog v6 has been released, that fixes AOT-build-warnings:

- https://www.nuget.org/packages/NLog/6.0.0#releasenotes-body-tab

See also: https://nlog-project.org/2025/04/29/nlog-6-0-major-changes.html

**Comment by robindegen** [comment] 2025-05-15 13:33
Can confirm that with the 6.0.0 preview there are no more warnings

**Comment by snakefoot** [comment] 2025-05-15 15:20
@robindegen Thank you for the confirmation.
