### ISSUE TITLE
Archiving non-static fileName every day after downtime

### ISSUE THREAD

**Issue by ghost** [NLog/NLog#3455] opened 2019-06-07 12:13 UTC
Using v4.6.4

```xml
<target xsi:type="AsyncWrapper" name="asyncFile">
    <target xsi:type="File"
              fileName="${basedir}\log_${date:format=yyyy-MM-dd}.log" 
              archiveFileName="${basedir}\log\log_{#}.log"
              archiveNumbering="Date"
              archiveEvery="Day"
              archiveDateFormat="yyyy-MM-dd"
              concurrentWrites="true"
              keepFileOpen="false"
              layout="${longdate} ${uppercase:${level}} ${message}"/>
    </target>
</target>
```

Same scenario as in issue #2523:
if the "_archiveEvery_" parameter (in my case Day) changes when the app is not running, it won't archive the existing logs if the "_fileName_" is non-static (if it's static, it works)

![log_example](https://user-images.githubusercontent.com/9258622/59102158-ed5ad080-8933-11e9-9753-62ed8414e2df.jpg)

In the above example, **log_2019-06-09** and **log_2019-06-10** (initially) were added instead of replacing the existing ones because the change happened during downtime.
The next 2 logs **log_2019-06-11** (which replaced _log_2019-06-10_) and **log_2019-06-12** (which replaced _log_2019-06-11_) were created when the app was up

In the mentioned issue #2523, one response was "You need to change your logging-setup, so the fileName remains static"

As I am bound to using a date in the fileName, is there a way of achieving this? Is there an option that I'm missing?

**Workaround attempt:**

"_archiveOldFileOnStartup_" doesn't help in this regard and even if it did, it would mean the current file being archived multiple times if the app would be restarted multiple times in the same day, but again, it doesn't help with the root problem, archiving when "_fileName_" is non-static

Thank you

**Comment by 304NotModified** [comment] 2019-06-21 16:21
Sorry for the late reply, we still need to check this in code.

**Comment by 304NotModified** [comment] 2019-08-01 19:13
I see this is a duplicate of https://github.com/NLog/NLog/issues/2523

This is unfortunate still an known issue.

**Comment by 304NotModified** [comment] 2019-08-01 19:14
PR for fixing this would be welcome:)

**Comment by snakefoot** [comment] 2020-09-01 22:22
Work-around is doing this (Stop using static-filename-archive-logic and just use dynamic-archive-logic):

```xml
    <target xsi:type="File"
              fileName="${basedir}\log_${date:format=yyyy-MM-dd}.log"
              maxArchiveFiles="7"
              concurrentWrites="true"
              keepFileOpen="false"
              layout="${longdate} ${uppercase:${level}} ${message}"/>
```

See also https://github.com/NLog/NLog/issues/3807#issuecomment-587661413

**Comment by snakefoot** [comment] 2021-12-09 17:04
Closing due to inactivity. Wellcome to create pull-request with improvements.

**Closed by snakefoot** 2021-12-09 17:04 UTC
Labels: bug, up-for-grabs, file-target, help wanted, file-archiving
