### ISSUE TITLE
Configuration search sequence - 

### ISSUE THREAD

**Issue by wilhelmmedetz** [NLog/NLog#1569] opened 2016-07-28 08:32 UTC
**Type**:

- Feature request

**NLog version**: 4.3.5

**Platform**: .Net 4.5

According to the documentation configurations are searched in the following sequence:

1. standard application configuration file (usually applicationname.exe.config)
2. applicationname.exe.nlog in application’s directory
3. NLog.config in application’s directory
4. NLog.dll.nlog in a directory where NLog.dll is located (only if NLog isn't installed in the GAC)

Based on my tests, if both, an applicationname.exe.nlog file and an NLog.config file coexist in one directory, the application will use the NLOG.config file.

It would be desirable, that configurations are searched in the defined sequence, and if a configuration is found it is used and further configuration searching is aborted. In my specific case, if an applicationname.exe.nlog exists, the NLog.config file should not be read.

This would allow to deploy multiple exe files in one directory and to have applicationname.exe.nlog specific configurations together with a default NLog.config file (for those exe files with no applicationname.exe.nlog).

**Comment by 304NotModified** [comment] 2016-07-28 08:44
Agree, but because this a breaking change, the first opportunity will be NLog 5

**Comment by 304NotModified** [comment] 2016-08-01 20:09
Duplicate of https://github.com/NLog/NLog/issues/223

**Closed** 2016-08-01 20:10 UTC
Labels: breaking change, bug, duplicate, nlog-configuration
