### ISSUE TITLE
Assembly Version of NLog remains the same, although the ProductVersion is different.

### ISSUE THREAD

**Issue by fgheysels** [NLog/NLog#2939] opened 2018-09-28 13:03 UTC
**NLog version**: 4.2.3, 4.3.5,  4.5.10, ...

**Platform**: .Net 3.5 / .Net 4.0 / .Net 4.5

We have a product that has a dependency on NLog v4.3.5.

A user of our product mentions that he receives the following error:

`Method not found: 'Void NLog.Targets.FileTarget..ctor(System.String)`

After investigation, we found out that the user had a version of NLog v4.2.3 installed in the GAC.  (Probably a dependency of another application).
When NLog was removed from the GAC, our application ran without error.

Some further digging revealed that both versions of NLog (4.3.5 and 4.2.3) have the same assembly-version (4.0.0.0) although the public API of these versions is incompatible.

According to the Microsoft documentation, the AssemblyVersion is part of the Assembly-Identity.  
When loading an assembly, the .NET runtime will first check if it can find the assembly in the GAC.   In this case, a matching assembly was found (hence, NLog, Assembly version 4.0.0.0) and the assembly from the GAC is used.

I've verified the latest version of NLog that is available at the time of writing (4.5.10), and that version also has the same AssemblyVersion.

It seems to me that you should make sure that the AssemblyVersion is different amongst versions of NLog that are not compatible.
I think the simplest solution is to make sure that the AssemblyVersion of NLog matches the version of the product.  
For example, the AssemblyVersion for NLog v4.3.5 should be 4.3.5.0 instead of 4.0.0.0.    This will avoid these kind of problems.

**Comment by 304NotModified** [comment] 2018-09-28 14:27
Hi,

This is by design and a lot of OSS libraries do the same (e.g. JSON.NET).

If we change the assemblyversion every time, people get assembly load issues/difficulties. 

For every major version, the assemblyversion will be the same and this works because we take semantic versioning (semver) very serious. 

In you case it goes indeed wrong, and there are the following solution:

- Don't set NLog in the GAC, or
- Use the same version as in the GAC, or
- Use NLog from source.

> I think the simplest solution is to make sure that the AssemblyVersion of NLog matches the version of the product.

FYI: That's not simple as this will give many problems to other users because the assembly is strong named.

**Comment by 304NotModified** [comment] 2018-09-28 14:30
Also the same issue: https://github.com/NLog/NLog/issues/1765#issuecomment-261776513

**Comment by snakefoot** [comment] 2018-09-29 10:05
You can consider to use ILMerge for NLog.dll to always ensure you get the right version independent of what is in the GAC.

**Comment by 304NotModified** [comment] 2018-09-29 10:38
> I don't understand what issues people might have when you make sure the assembly-version is changed for each new release ?

Because people are using libraries/other project that are using NLog. Please read into strong naming for this question. 

> * Our solutions doesn't put NLog in the GAC

You can still add the new version to the GAC.

**Comment by fgheysels** [comment] 2018-10-01 07:28
Your suggestion to add the new version to the GAC will most likely not work.
Since the assembly-version of both versions is the same, both versions cannot live side-by-side inside the GAC.
The new version might overwrite the existing version and then, our application will work but the other application that uses the older version that was already in the GAC might break.

In my opinion, whenever your existing public API changes , the Major version of the Assemby-version must change (since the new version is no longer binary compatible with the existing version).  This is the only way to avoid problems like this in the future.

**Comment by 304NotModified** [comment] 2018-10-01 09:34
> Your suggestion to add the new version to the GAC will most likely not work.
> Since the assembly-version of both versions is the same, both versions cannot live side-by-side inside the GAC.
> The new version might overwrite the existing version and then, our application will work but the other application that uses the older version that was already in the GAC might break.

I mean indeed replace. NLog is using Semver, so it should not break. 

> In my opinion, whenever your existing public API changes , the Major version of the Assemby-version must change (since the new version is no longer binary compatible with the existing version). This is the only way to avoid problems like this in the future.

There is no perfect solution to handle all the strong name issues. With your suggestion NLog would be in version 100+

**Comment by 304NotModified** [comment] 2018-10-01 09:35
Another option is to remove NLog form the GAC, and place it in the bin folder for the one that is missing the NLog.dll

**Comment by snakefoot** [comment] 2018-10-01 15:47
> @fgheysels This is is the only way to avoid problems like this in the future.

Instead you will have people struggling with implementing binding redirects in their app.config/web.config.

If you don't have control of the runtime-environment, then I suggest that you use ILMerge for the NLog.dll or build it yourself without strong-name support.

**Comment by 304NotModified** [comment] 2018-11-05 17:35
Closing this as this is by-design

**Closed** 2018-11-05 17:35 UTC
Labels: question
