### ISSUE TITLE
Mocking NLog

### ISSUE THREAD

**Issue by midexsoftware** [NLog/NLog#916] opened 2015-09-17 19:53 UTC
Hi,

I am using MVVM Light with NLog and using NUnit with NSubstitute for unit testing.  I need to test a class that uses NLog.

I pass ILogger to the constructor of the class.

```c#
private readonly ILogger _Logger;
public DataService(ILogger log)
{
       _Logger = log;
}

public void WriteToLog()
{
    _Logger.Error("Some error occurred");
}
```

In the ViewModelLocator, I have the following line

```c#
SimpleIoc.Default.Register<ILogger>(() => LogManager.GetCurrentClassLogger());
```

Now, in my Unit Test I have

```c#
var log = Substitute.For<ILogger>();  
var dataService = new DataService(log);
dataService.WriteToLog();
log.ReceivedWithAnyArgs(1).Error("");
```

Everything works fine:
1. Unit Test works correctly
2. When I run the program, it works fine

But, when I compile I get the following error:
"There is already a factory registered for NLog.ILogger"

Interesting thing, it does not affect the program and I can still run it, but I am thinking that maybe something happening on the backend and it may cause some issue elsewhere.

If someone is familiar with MVVLight, can you suggest what I am doing wrong.  And if I cannot use dependency injection for NLogger, then how do you mock it for testing purposes?

**Comment by 304NotModified** [comment] 2015-09-17 20:26
Hi,

Is this really a compile error? Or is this a thrown exception? If the latter, please include the full exception including stracktrace.

**Comment by midexsoftware** [comment] 2015-09-17 20:47
Just to let you know I use VS2015 Community Edition.  
It is not an exception. The error shows up in the Error List. However, If I do build, I get "Build Succeeded"

The error points to a App.xaml file where I have my resource setup for ViewModel Locator
 <vm:ViewModelLocator
        x:Key="Locator"
        d:IsDataSource="True" xmlns:vm="clr-namespace:CutRiteLabels.ViewModel" />

Here is the screenshot

![nlogerror](https://cloud.githubusercontent.com/assets/3258797/9945403/1604f6ae-5d5b-11e5-9023-f8cd3eb67981.jpg)

**Comment by 304NotModified** [comment] 2015-09-17 20:51
I have no experience with MVVM Light, NSubsitute and almost none with XAML.

But have you tried

```c#
SimpleIoc.Default.Unregister<ILoger>(); 
```

?

Stolen from: http://stackoverflow.com/questions/14136126/idataservice-is-already-registered-in-mvvm-light-project

**Comment by 304NotModified** [comment] 2015-10-13 19:55
Has you question being answered?

**Comment by 304NotModified** [comment] 2015-10-16 20:24
I thinks this a duplicate of https://github.com/NLog/NLog/issues/923 ?

**Closed** 2015-10-17 23:40 UTC
Labels: question
