### ISSUE TITLE
Xml Configuration + loading of NLog assembly from memory may cause invalid path exception

### ISSUE THREAD

**Issue by nernst** [NLog/NLog#736] opened 2015-06-10 00:56 UTC
This was found while running integration tests with my company's Excel add-in that uses ExcelDNA & NLog. Basic synopsis is that we have an xml-based config for NLog that we embed as a resource into a C# based DLL. At runtime, we extract the resource and use this XML bit to configure NLog. This worked fine for us on NLog 2.0.1.2. But, since upgrading to 3.2.1, I've been failing in our release builds (but not debug).

After a bit (rather a lot) of debugging, realized the difference came down to not NLog, per se, but how the debug vs release builds are packaged, or not. Our debug builds for our ExcelDNA library are pretty bare bones. All of the DLLs sit in a folder with the ExcelDNA scaffolding to create the Excel XLL addin. For our release builds, we distribute 2 XLL files, one for 32-bit Excel, and a separate one for 64-bit (but this doesn't matter to the issue). What matters is the ExcelDNA library provides a facility by which it "packs" .Net libraries into a native DLL (as an XLL file) as resources. When the XLL loads, it handles resolving missing assemblies by trying to find them as native resources. Thing is, when it finds an assembly it needs, it never exists on the filesystem - it's purely in memory. This is where the problem comes in:

Our config, although never modifiable by a user, is stored as an embedded resource in xml format. We utilize the XmlReader constructor interface of XmlLoggingConfiguration to handle the initialization. However, XmlLoggingConfiguration has this member:
```C#
private readonly ConfigurationItemFactory configurationItemFactory = ConfigurationItemFactory.Default;
```
The problem comes in that if the preprocessor flag SILVERLIGHT is not defined, it assumes the NLog assembly has a valid location (in our case, the location is the empty string) @ ConfigurationItemFactory.BuildDefaultFactory (ConfigurationItemFactory.cs, line 238 on master). There is a check if the resulting assembly location is null, but the call to Path.GetDirectoryName(string.Empty) results in an exception that is not trapped, and logging fails to initialize.

I believe I've a workaround by manually creating our configuration via the configuration API (which would be fine because we don't allow our users to change the configuration currently), but I've not yet tested this.

**Comment by akamyshanov** [comment] 2015-06-10 07:12
As of 4.0.0, the problem is worse. If NLog is loaded from memory (https://github.com/Fody/Costura is used), an exception is thrown from the constructor (even empty) of `FileTarget`, `ConsoleTarget`. Everything is ok with 3.2.1 though. Not sure whether this should be a separate issue.

**Comment by 304NotModified** [comment] 2015-06-10 16:00
No need for a separate issue, as we're trying to fix things only in the latest version.

This should work from the API.

If you really need this (fancy) construction, we need at least the exceptions (stacktrace etc). ;)

**Comment by 304NotModified** [comment] 2015-06-10 16:02
What also is possibe:

```c#
        protected XmlLoggingConfiguration CreateConfigurationFromString(string configXml)
        {
#if SILVERLIGHT
            XElement element = XElement.Parse(configXml);
            return new XmlLoggingConfiguration(element.CreateReader(), null);
#else
            XmlDocument doc = new XmlDocument();
            doc.LoadXml(configXml);

            return new XmlLoggingConfiguration(doc.DocumentElement, Environment.CurrentDirectory);
#endif
        }
```

This is used in the unit tests

**Comment by nernst** [comment] 2015-06-10 18:09
Sorry I forgot to attach the stack. Here it is, with my company's namespaces redacted:
```
Type:TypeInitializationException
Message:The type initializer for 'NLog.Config.ConfigurationItemFactory' threw an exception.
Report Name:
Stack Trace:   at NLog.Config.ConfigurationItemFactory.get_Default()
   at NLog.Layouts.Layout.FromString(String layoutText)
   at NLog.Layouts.Layout.op_Implicit(String text)
   at NLog.Targets.TargetWithLayout..ctor()
   at NLog.Targets.TargetWithLayoutHeaderAndFooter..ctor()
   at NLog.Targets.FileTarget..ctor()
   at <ExcelDNA Addin>..LoggingConfiguration.Initialize()
   at <ExcelDNA Addin>.InitializeLogging()
   at <ExcelDNA Addin>.AddInImplementation.AddinScope.Initialize(RibbonAddin addin)
Inner Exception:
        Type:ArgumentException
        Message:The path is not of a legal form.
        Report Name:
        Stack Trace:   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
   at NLog.Config.ConfigurationItemFactory..cctor()
```
I can only get this from the release build (our debug builds aren't embedded into the XLL), so unfortunately some things have been inlined.  The code snippet we're using to actually do the initialization from a resource is:
```C#
            string resourceName = "<ExcelDNA AddIn>.NLog.config";

            using (Stream stream = assembly.GetManifestResourceStream(resourceName))
            using (var reader = System.Xml.XmlReader.Create(stream))
            {
                var config = new NLog.Config.XmlLoggingConfiguration(reader, null); // throws

                var target = config.ConfiguredNamedTargets.Where(t => t.Name == "asyncFile").FirstOrDefault();
                if (target != null)
                {
                    var rule = new NLog.Config.LoggingRule("*", LogLevel.Debug, target);
                    config.LoggingRules.Add(rule);
                }

                LogManager.Configuration = config;
            }
            LogManager.GetCurrentClassLogger().Info("Logging Initialized");
```
The embedded config (but it doesn't really matter what this contains):
```xml
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <targets>
    <target name="asyncFile" xsi:type="AsyncWrapper">
      <target name="file" xsi:type="File"
              layout="${longdate} ${level:uppercase=true} ${threadid} ${logger} ${message} ${exception:format=tostring}"
              fileName="${specialfolder:folder=LocalApplicationData}\Company Name\Excel Addin\log.txt"
              archiveFileName="${specialfolder:folder=LocalApplicationData}\Company Name\Excel Addin\archives\log.{#}.txt"
              archiveEvery="Day"
              archiveNumbering="Rolling"
              archiveAboveSize="1048576"
              maxArchiveFiles="7"
              concurrentWrites="false"
              keepFileOpen="false"
              encoding="iso-8859-2" />
    </target>
    <target xsi:type="Trace"
            name="console"
            layout="${longdate} ${threadid} ${logger} ${message} ${exception:format=tostring}" />
  </targets>

  <rules>
    <!--logger name="*" minlevel="Trace" writeTo="asyncFile" /-->
    <logger name="*" minlevel="Trace" writeTo="console" />
  </rules>
</nlog>
```

**Comment by 304NotModified** [comment] 2015-06-10 18:17
Thanks. 

But `CreateConfigurationFromString` isn't helpful?

**Comment by nernst** [comment] 2015-06-10 20:51
Haven't had a chance to try the CreateConfigurationFromString yet. I'll get
back to you on that one.

**Comment by akamyshanov** [comment] 2015-06-11 11:16
Version: 4.0.0

The problem's root comes from here: https://github.com/NLog/NLog/blob/a8694c733f82b0b08ad1acc2fc2d37d24eda1302/src/NLog/Config/ConfigurationItemFactory.cs#L238
```C#
var assemblyLocation = Path.GetDirectoryName(nlogAssembly.Location);
```
When assemblies are loaded from memory, `Location` is `null`. My proposal is to use `CodeBase` as a second option, it is not `null` in any circumstances:
```C#
var location = nlogAssembly.Location ?? new Uri(nlogAssembly.CodeBase).LocalPath;
var assemblyLocation = Path.GetDirectoryName(nlogAssemblyLocation);
```
This way, the behavior will not change for normal use-cases, but will fix the issue we're facing with @nernst. I will shortly make a pull request.

### Use case 1
```C#
using (var stringReader = new StringReader(Resources.NLog))
using (var xmlReader = XmlReader.Create(stringReader))
{
    var config = new XmlLoggingConfiguration(xmlReader, Environment.CurrentDirectory); // throws
    LogManager.Configuration = config;
}
```
```
System.TypeInitializationException was caught
  HResult=-2146233036
  Message=The type initializer for 'NLog.Config.ConfigurationItemFactory' threw an exception.
  Source=NLog
  TypeName=NLog.Config.ConfigurationItemFactory
  StackTrace:
       at NLog.Config.ConfigurationItemFactory.get_Default()
       at NLog.Config.XmlLoggingConfiguration..ctor(XmlReader reader, String fileName)
       at <NS>.LoggerExtensions.ConfigureNLog(Assembly assembly)
  InnerException: System.ArgumentException
       HResult=-2147024809
       Message=The path is not of a legal form.
       Source=mscorlib
       StackTrace:
            at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
            at System.IO.Path.GetDirectoryName(String path)
            at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
            at NLog.Config.ConfigurationItemFactory..cctor()
       InnerException: 
```

### Use case 2
``` C#
var target = new FileTarget(); // throws
```
```
System.TypeInitializationException was caught
  HResult=-2146233036
  Message=The type initializer for 'NLog.Config.ConfigurationItemFactory' threw an exception.
  Source=NLog
  TypeName=NLog.Config.ConfigurationItemFactory
  StackTrace:
       at NLog.Config.ConfigurationItemFactory.get_Default()
       at NLog.Layouts.Layout.FromString(String layoutText)
       at NLog.Layouts.Layout.op_Implicit(String text)
       at NLog.Targets.TargetWithLayout..ctor()
       at NLog.Targets.TargetWithLayoutHeaderAndFooter..ctor()
       at NLog.Targets.FileTarget..ctor()
       at <NS>.LoggerExtensions.ConfigureNLog(Assembly assembly)
       .....
  InnerException: System.ArgumentException
       HResult=-2147024809
       Message=The path is not of a legal form.
       Source=mscorlib
       StackTrace:
            at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
            at System.IO.Path.GetDirectoryName(String path)
            at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
            at NLog.Config.ConfigurationItemFactory..cctor()
       InnerException: 
```

**Comment by 304NotModified** [comment] 2015-06-13 21:47
PR merged so done :)

**Closed by 304NotModified** 2015-06-13 21:47 UTC
Labels: feature, question

**Comment by MgSam** [comment] 2015-08-21 04:23
I'm hitting this bug in 4.0.1. The same code as mentioned above, ConfigurationItemFactory.BuildDefaultFactory, is throwing. When it calls `GetNLogAssemblyLocation` it's getting the directory the assembly was compiled in, not the directory its currently sitting in. Therefore, I don't think the solution @akamyshanov suggested is the right one.

**Comment by 304NotModified** [comment] 2015-08-21 13:11
Can you test with the alpha if this is fixed?

https://www.nuget.org/packages/NLog/4.1.0-alpha1

**Comment by IDmedia** [comment] 2016-03-22 13:15
Found this issue while searching for a way to embed NLog.config using Costura. Using Costura I'm merging all DLL files into my main exe files, however, one of my DLL files is using NLog. Is there a way to embed NLog in my main application without writing it to disk and tell all libraries using NLog to use it from memory?

**Comment by gregmac** [comment] 2016-05-03 23:22
I'm running into this with NLog 4.3.3 when using mkbundle on mono.

```
Unhandled Exception:
System.IO.DirectoryNotFoundException: Directory '/usr/lib/mono/gac/NLog/4.0.0.0__5120e14c03d0593c' not found.
  at System.IO.Directory.ValidateDirectoryListing (System.String path, System.String searchPattern, System.Boolean& stop) <0x4069aa70 + 0x001ab> in <filename unknown>:0
  at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, FileAttributes mask, FileAttributes attrs) <0x4069a8b0 + 0x00063> in <filename unknown>:0
  at System.IO.Directory.GetFiles (System.String path, System.String searchPattern) <0x4069a880 + 0x0001b> in <filename unknown>:0
  at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory () <0x4063ca80 + 0x0019f> in <filename unknown>:0
  at NLog.Config.ConfigurationItemFactory.get_Default () <0x4063ca00 + 0x0001b> in <filename unknown>:0
  at NLog.Layouts.Layout.FromString (System.String layoutText) <0x4063c9b0 + 0x0000f> in <filename unknown>:0
  at NLog.Layouts.Layout.op_Implicit (System.String text) <0x4063c990 + 0x0000f> in <filename unknown>:0
  at NLog.Targets.TargetWithLayout..ctor () <0x4063c940 + 0x0002b> in <filename unknown>:0
  at NLog.Targets.TargetWithLayoutHeaderAndFooter..ctor () <0x4063c920 + 0x0000f> in <filename unknown>:0
  at NLog.Targets.ConsoleTarget..ctor () <0x4063c900 + 0x0000f> in <filename unknown>:0
```

I'm not quite sure if it's the same issue as MgSam is getting (directory the assembly was compiled in) but I'm sure it's an artifact of the way mono's mkbundle works. FWIW this otherwise works fine under mono, it's only an issue with mkbuild.

This was most recently changed in https://github.com/NLog/NLog/commit/93a51ac8486ee65fc6e51b79e1563419bf524c9e.

If I create the directory it's looking for, everything works fine, so probably just handling the additional case where the directory doesn't exist would be enough.
