### ISSUE TITLE
Performance problem when thread number is big

### ISSUE THREAD

**Issue by emanov** [NLog/NLog#1038] opened 2015-11-13 09:19 UTC
[NLog.config.txt](https://github.com/NLog/NLog/files/33788/NLog.config.txt)
[Processor.cs.txt](https://github.com/NLog/NLog/files/33789/Processor.cs.txt)
[Program.cs.txt](https://github.com/NLog/NLog/files/33790/Program.cs.txt)

Hello!

I'm developing the app with big number of the long running threads (900-2000). When thread number is big the program has high cpu usage. After profiling the program I found that NLog eats 30% of all CPU usage in the method WriteAsyncLogEvents. The Blocking GC is high too.

When I have 10 process with 100 threads there is no any problem

So I write simple test for NLog, where all threads process one collection. Processing of each item do 4 call to Logger.Info() with intermediate pause about 80ms. Running this test with 900 threads leads to 30% CPU usage on my Corei5 processor. But when I start 9 processes with 100 threads per process (total is 900 too) the Cpu usage less then 2-3%.

So, I'm trying to find the way to have 900 threads and low cpu usage.

**Comment by 304NotModified** [comment] 2015-11-13 10:47
Thanks for the test program!

We will try to look at this, this weekend, but it's a bit busy, so it could be also next week.

**Comment by 304NotModified** [comment] 2015-11-15 23:20
Will be next week, as my laptop is really slow after a Windows update :(

**Comment by emanov** [comment] 2015-11-16 07:24
ok. will wait!

**Comment by emanov** [comment] 2015-11-16 21:06
Hello!
I see this on my core i5
![nlog900](https://cloud.githubusercontent.com/assets/710570/11194707/b14e528a-8cbe-11e5-98f4-db91d10d6999.png)

Nlog 4.1.2
  <package id="NLog" version="4.1.2" targetFramework="net45" />

Will try 4.2

do you use NLog.config with output to file?

**Comment by emanov** [comment] 2015-11-16 21:08
The same with 4.2

**Comment by 304NotModified** [comment] 2015-11-16 21:40
> do you use NLog.config with output to the file? Looks like you do test without output or with async-wrapper with default drop-mode.

I test with your program, no line changed! Only difference that NLog is directly references instead of nuget package. I don't think nuget packages could lead to more CPU ;)

I have a SSD, i7, but's tested on a laptop. (which has already performance issues)

**Comment by 304NotModified** [comment] 2015-11-16 21:43
have you tried changing the values of keepFileOpen  / concurrentWrites?

**Comment by emanov** [comment] 2015-11-16 21:48
I'm using SSD too.
For the test I've used

keepFileOpen="true" concurrentWrites="false"
(it is in the file attached to the first post)

If I cut these settings CPU increase to 55-60%

**Comment by emanov** [comment] 2015-11-16 21:50
Could you send me your project (or binaries for test) to the email?

**Comment by emanov** [comment] 2015-11-16 21:52
Tomorrow will run the test on the server with 16 Opteron core.

**Comment by 304NotModified** [comment] 2015-11-16 21:54
I don't see any file written here. I will fix that first :)

**Comment by emanov** [comment] 2015-11-16 21:54
ok :)

**Comment by 304NotModified** [comment] 2015-11-16 22:01
![image](https://cloud.githubusercontent.com/assets/5808377/11196121/fb2fa7b8-8cb5-11e5-9088-dab002a9b1fc.png)

**Comment by 304NotModified** [comment] 2015-11-16 22:06
OK confirmed, but now, what to do about it.

Test program is here: https://github.com/NLog/NLog/tree/many-many-thread---and-nice-cpu (src/nlog/NLog.netfx45.sln), 

![image](https://cloud.githubusercontent.com/assets/5808377/11196201/797f3656-8cb6-11e5-8d2f-12161eef281e.png)

It seems the lock is a issue. Also I saw a lot of datetime.tostring()'s. I have to go, but I will look further into it. You can also check it out with VS 2015:

![image](https://cloud.githubusercontent.com/assets/5808377/11196338/a17c7ff6-8cb6-11e5-9b6c-84887bc835a4.png)

**Comment by emanov** [comment] 2015-11-16 22:39
Removing payment.Date.ToString("yyyy-MM-ddTHH:mm:ss.fffzzzz") change nothing.
The same result with 
            logger.Info("TL_ID={0}");
instead of huge string with many parameters.
Honestly the whole producer/consumer part can be removed. So the program will have 900 running threads that output 4 string with pause.

**Comment by epignosisx** [comment] 2015-11-17 00:37
Just for comparison here are the results in a third PC (i5, SSD)

![image](https://cloud.githubusercontent.com/assets/697377/11199153/1ec61e54-8c99-11e5-910c-80b9471f3ee7.png)

I did some CPU profiling and didn't find anything interesting. Most of the time was spent waiting:

![image](https://cloud.githubusercontent.com/assets/697377/11199195/7b2d7a2a-8c99-11e5-8b1f-2e2a9aa8cfaf.png)

**Comment by emanov** [comment] 2015-11-17 08:15
The interesting thing here is that 9 process with 100 thread per 1 process don't use cpu so much.

**Comment by 304NotModified** [comment] 2015-11-17 10:09
Thanks for testing @epignosisx

**Comment by emanov** [comment] 2015-11-19 11:03
Yet another thing. The problem is for Console target too. So I doubt the problem is in the BaseFileAppender only.

**Comment by 304NotModified** [comment] 2015-11-19 12:45
Is it the console or the colored-console target? 

It would be nice if it's the console target, because the will make the test case smaller. 

We're a bit stuck on this, but if you can make the test case smaller (PR on https://github.com/NLog/NLog/tree/many-many-thread---and-nice-cpu), that we shall test it again.

**Comment by emanov** [comment] 2015-11-19 13:33
Sure, I'll make it tomorrow.

**Comment by emanov** [comment] 2015-11-19 14:59
Could you get changed sources from the my cloud and insert into the project?
https://yadi.sk/d/R0rdYpPFkaEwV
I have some problem with creating correct pull request

**Comment by 304NotModified** [comment] 2015-11-19 15:13
Please restore your branch @emanov , then I will create the PR.

**Comment by 304NotModified** [comment] 2015-11-19 15:15
for the correct Pr, just choose the correct branch after PR (Xamarin5 here as example)

![image](https://cloud.githubusercontent.com/assets/5808377/11274360/aa080e5a-8ed8-11e5-9820-741cc14362da.png)

![image](https://cloud.githubusercontent.com/assets/5808377/11274354/a391a54a-8ed8-11e5-861c-971c3245d0cb.png)

**Comment by emanov** [comment] 2015-11-19 15:35
restored

**Comment by 304NotModified** [comment] 2015-11-19 15:41
Do you need to push some stuff? (to Github)


![image](https://cloud.githubusercontent.com/assets/5808377/11275109/53a04ee8-8edc-11e5-973a-9b337b5bc24e.png)

**Comment by emanov** [comment] 2015-11-19 15:48
Just created pull request from the web interface.

**Comment by 304NotModified** [comment] 2015-11-19 21:07
I think the `lock` is blocking too much:

![image](https://cloud.githubusercontent.com/assets/5808377/11284076/31e3d852-8f08-11e5-9459-3ab35cb56c91.png)


before:

1% cpu at console

![image](https://cloud.githubusercontent.com/assets/5808377/11284061/1729ed62-8f08-11e5-9a83-6d2bbab6f9e7.png)



after:

almost every cpu cycle (96%) is used for the console itself.

![image](https://cloud.githubusercontent.com/assets/5808377/11284070/25a6543e-8f08-11e5-9165-f11fcbf6663d.png)


sure, we need the `lock`, but maybe a smaller scope?

**Comment by emanov** [comment] 2016-04-08 12:58
From the my point of the view thera some places that should be optimized.

1) IsInitialized - is not thread safe, so it's used with the lock
        /// <summary>
        /// Gets a value indicating whether the target has been initialized.
        /// </summary>
        protected bool IsInitialized { get; private set; }
but what if we would use
        /// <summary>
        /// Gets a value indicating whether the target has been initialized.
        /// </summary>
        protected bool IsInitialized { get {return isInitialized;} set { isInitialized=value; } }
        private volatile bool isInitialized;

that way doesn't require lock(syncLock)

2) constructions with lock often used without prechecking
            lock (this.SyncRoot)
            {
                if (this.IsInitialized)
                {
                    foreach (Layout l in this.allLayouts)
                    {
                        l.Precalculate(logEvent);
                    }
                }
            }
that would be good to have
                if (this.IsInitialized)
before lock too.

3) 
Target.PrecalculateVolatileLayouts use lock for all precalculations:
                    foreach (Layout l in this.allLayouts)
                    {
                        l.Precalculate(logEvent);
                    }
but there is no nessecary in it as I see. Instead of this we should make
                    var layouts = this.allLayouts;
                    foreach (Layout l in layouts)
                    {
                        l.Precalculate(logEvent);
                    }
and to protect initializing this.allLayouts 
            this.allLayouts = new List<Layout>(ObjectGraphScanner.FindReachableObjects<Layout>(this));
seems to be good to replace with
           Interlocked.Exchange(ref this.allLayouts, new List<Layout>(ObjectGraphScanner.FindReachableObjects<Layout>(this)));

and so on. That's all should reduce locks.

**Comment by 304NotModified** [comment] 2016-04-08 16:38
Sounds valid. Can you send a PR for this nl

**Comment by emanov** [comment] 2016-04-08 19:47
Ok, hope to make PR next week.

**Comment by emanov** [comment] 2016-04-11 12:23
That is the PR:
https://github.com/NLog/NLog/pull/1369

I don't understand the logic in the methods: Initialize, Close. But it looks very suspiciously.

**Comment by bjornbouetsmith** [comment] 2016-05-13 21:13
A Comment regarding Console writing from multiple threads.
Console.Write is synchronized by the OS on windows, so if you have multiple threads writing to a Console Appender it is slow, not because of NLog, but because of windows. If you try to run the test, with the window minimized, you will probably see that the test runs faster, since Windows detects that the window should no longer be drawn on the screen, and things run faster.

I once had a Perl script that run on windows, to convert  Source Safe into SVN, after 4 hours of running, while it was writing to the console, I stopped the program. I then restarted the program and by accident I minimised the window, and 5 minutes after it was done.

**Comment by 304NotModified** [comment] 2016-05-14 02:11
Thanks for the info @bjornbouetsmith!

**Comment by alexmcmillan** [comment] 2016-10-03 23:05
Has this been resolved in the latest release?

**Comment by 304NotModified** [comment] 2016-10-04 15:43
No and yes as there is IMO no problem (in NLog) here.

**Comment by snakefoot** [comment] 2016-10-08 16:52
Tested this with #1663, and now very few garbage collections occur. So if the problem was time spent on garbage collection, then it can be fixed. Work-around would be to activate gcServer in app.config.

**Comment by snakefoot** [comment] 2016-10-10 00:40
Testing with #1700 and #1663 then the CPU usage stays around 10 pct, and never rises to more than 15 pct. (i5)

**Comment by 304NotModified** [comment] 2018-01-10 20:04
I think this one could be closed. If there is still an issue with NLog 4.5, we could reopen this

**Closed by 304NotModified** 2018-01-10 20:04 UTC
Labels: enhancement, performance
