### ISSUE TITLE
LogManager.Shutdown () & LogManager.Configuration = block on single threaded platforms

### ISSUE THREAD

**Issue by patrickkulling** [NLog/NLog#4266] opened 2021-01-26 14:27 UTC
**NLog version**: `4.7.6`

**Platform**: .Net 4.5 / WebGL / web assembly / Unity Engine

- What is the current result?

Any call to `LogManager.Shutdown ();` the setter of `LogManager.Configuration` twice will block the main thread on platforms that do not support threads.

- What is the expected result?

Both APIs should not stall the main thread.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes,
it stalls at `ForEachItemInParallel`

- Please post full exception details (message, stacktrace, inner exceptions)
```
LogFactory Flush with timeout=15 secs
LogFactory Flush with timeout=15 secs
Flushing all 2 targets...
Flushing all 2 targets...
ForEachItemInParallel() 2 items
```

- Are there any workarounds? yes

Do not call the API's but call `config.RemoveRuleByName ("name");` & `config.RemoveTarget ("name");` for each target

- Is there a version in which it did work?
Not that I am aware of

- Can you help us by writing an unit test?
No, because this only happens on the compiled binary.

**Comment by snakefoot** [comment] 2021-01-26 14:38
So the issue is on platforms without support for parallel-threads, where the async-logic is cooperative multitasking ?

Is it possible for the single-thread on this platform to yield its processor-time, so it can execute the async-flush-operations itself?

Would it be acceptable if there was a Shutdown-method with parameter to perform synchronous flush/close ?

**Comment by patrickkulling** [comment] 2021-01-26 15:05
> So the issue is on platforms without support for parallel-threads, where the async-logic is handled by cooperative multitasking ?
* Correct.

> Would it be acceptable if there was a Shutdown-method with parameter to perform synchronous flush/close ?
* Yes that would work for sure for the `Shutdown()` API, but not for the `LogManager.Configuration` setter.

> Is it possible for the single-thread on this platform to yield its processor-time, so it can execute the async-flush-operations itself?
* Not sure to be honest. Can you give an example how that could look like?

**Comment by snakefoot** [comment] 2021-01-26 19:31
> Not sure to be honest. Can you give an example how that could look like?

I was thinking if one created some async-versions of `LoadConfigurationAsync` and `ShutdownAsync` that returns a task that can be awaited, and those methods awaited Tasks correctly then it would work.

```c#
await NLog.LogManager.Setup().LoadConfigurationAsync(newConfig);
NLog.LogManager.GetLogger("test").Info("hello");
await NLog.LogManager.Setup().ShutdownAsync();
```

Is async await available on your single-threaded platform, so you can do this without blocking:

```c#
await Task.Run(async () => await Task.Delay(1000).ConfigureAwait(false)).ConfigureAwait(false);
```

**Comment by snakefoot** [comment] 2021-01-26 19:56
@patrickkulling Just curious. Are you using the NLog-nuget directly, or are you using a custom build for the "WebGL / web assembly / Unity"-platform? Looks like there is a lot of restrictions, so one is not allowed to using anything from System.Threading.

**Comment by patrickkulling** [comment] 2021-01-27 14:40
We are using no modified version, just the nuget one.

`async await` is usually supported as Unity has different implementations for the [Task](https://github.com/Unity-Technologies/mono/blob/unity-mono-4.8.0-branch/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs#L5909) class that usually uses `System.Threading`

**Comment by snakefoot** [comment] 2021-01-27 15:13
So this piece of code will run just fine on the platform:

`await Task.Run(async () => await Task.Delay(1000).ConfigureAwait(false)).ConfigureAwait(false);`

Again what are the main features/targets are you planning to use from NLog on this platform?

**Comment by patrickkulling** [comment] 2021-01-27 15:42
> Again what are the main features/targets are you planning to use from NLog on this platform?

- We are using custom targets, so nothing from NLog itself. The main feature set really is to use it as a logging framework with the provided APIs. They way to extend it with custom targets is great and it fits our need.

- We just didn't expected the stalling on Shutdown & when changing configuration.

**Comment by snakefoot** [comment] 2021-01-27 16:42
Yes NLog is single threaded everywhere unless you start using AsyncWrapper or inherit from AsyncTaskTarget. Except when doing flush on shutdown and changing config.

Instead of this suggestion:
```c#
await NLog.LogManager.Setup().LoadConfigurationAsync(newConfig);
NLog.LogManager.GetLogger("test").Info("hello");
await NLog.LogManager.Setup().ShutdownAsync();
```

Then I guess it could also be implemented like this:
```c#
NLog.LogManager.LoadConfiguraion(newConfig, flushParallel: false);
NLog.LogManager.GetLogger("test").Info("hello");
NLog.LogManager.Shutdown(flushParallel: false);
```

Do you have a preference?

**Comment by patrickkulling** [comment] 2021-01-27 18:01
The 2nd API looks way more intuitive imo.

**Comment by snakefoot** [comment] 2021-01-27 18:30
@patrickkulling Are you in a mood for creating a pull-request for the master-branch ? Since you know the platform better than me, and have better ability for testing.

**Comment by patrickkulling** [comment] 2021-01-27 18:40
@snakefoot Let me try and integrate the NLog sources in our repository. It may take a while for me to come back with a solution as iteration times on webgl are slow (~1hr/build)

**Comment by snakefoot** [comment] 2021-02-05 11:24
Will close this issue. And await your return with the needed changes to support your platforms.

**Closed by snakefoot** 2021-02-05 11:24 UTC
Labels: platform support
