### ISSUE TITLE
NLog 4.2.2 deadlock

### ISSUE THREAD

**Issue by dlkay0** [NLog/NLog#1203] opened 2016-01-28 16:23 UTC
I have a multi-threaded WCF web service which leverages NLog v4.2.2.  Recently my service deadlocked and I captured the stack traces.  I'm using a standalone NLog.config file which I did not modify at runtime.

```xml
<?xml version="1.0"?>
<configuration>
  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog" />
  </configSections>
  <system.web>
    <compilation targetFramework="4.0" />
  </system.web>
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">
    <variable name="MessageNoPassword"
         value="${replace:searchFor=(&lt;Password[^&gt;]*)&gt;[^&lt;]+&lt;/Password&gt;:wholeWords=false:replaceWith=$1&gt;XXXX&lt;/Password&gt;:regex=true:ignoreCase=true:inner=${Message}}" />
    <variable name="MessageNoLastName"
                                                                  value="${replace:searchFor=(&lt;LastName[^&gt;]*)&gt;[^&lt;]+&lt;/LastName&gt;:wholeWords=false:replaceWith=$1&gt;XXXX&lt;/LastName&gt;:regex=true:ignoreCase=true:inner=${MessageNoPassword}}" />
                <!-- ... -->
    <variable name="MyLayout" value="${longdate} | ${level} | ${mdc:Operator} | ${mdc:SessionId} | ${MessageNoLastName}${onexception: | EXCEPTION FOLLOWS\:${exception:format=tostring}}" />

    <targets async="true">
      <target xsi:type="File"
                                layout="${MyLayout}"
                                name="logFile"
                                fileName="${basedir}/Logs/AppName_${mdc:ClientID}_${shortdate}.log"
                                archiveFileName="${basedir}/Logs/Archive/AppName_${mdc:ClientID}_${shortdate}.{#}.log"
                                archiveEvery="Hour"
                                archiveNumbering="Rolling"
                                maxArchiveFiles="30" />
                  <!-- ... -->
    </targets>

    <rules>
      <logger name="*" minlevel="Info" writeTo="logFile" />      
      <!-- ... -->
    </rules>
  </nlog>
</configuration>
```

Thread 30 owns the lock on Target.syncRoot and needs a lock on LogFactory.syncRoot in order to get the DefaultCultureInfo from Configuration, while Thread 50 owns the lock on LogFactory.syncRoot and needs to lock the Target in order to reinitialize it.

Thread 30 is logging an Info message while thread 50 is executing the static initializer for a class which has a call to LogManager.GetCurrentClassLogger() to get the static logger instance.

```
0:030> !sos.CLRStack
OS Thread Id: 0x1f44 (30)
Child SP       IP Call Site
1be8e9fc 77a6ca2c [GCFrame: 1be8e9fc] 
1be8ead4 77a6ca2c [GCFrame: 1be8ead4] 
1be8eaf0 77a6ca2c [HelperMethodFrame_1OBJ: 1be8eaf0] System.Threading.Monitor.ReliableEnter(System.Object, Boolean ByRef)
1be8eb6c 1b6518af NLog.LogFactory.get_Configuration()  **//LogFactory.syncRoot    0411a750**
1be8eba8 1b65d0bb NLog.GlobalDiagnosticsContext.ConvertToString(System.Object, System.IFormatProvider)
1be8ebbc 1b65d028 NLog.LayoutRenderers.MdcLayoutRenderer.Append(System.Text.StringBuilder, NLog.LogEventInfo)
1be8ebd0 1b65870c NLog.LayoutRenderers.LayoutRenderer.Render(System.Text.StringBuilder, NLog.LogEventInfo)
1be8ebf8 1b65cbb4 NLog.Layouts.SimpleLayout.GetFormattedMessage(NLog.LogEventInfo)
1be8ec34 1b65cade NLog.Layouts.Layout.Precalculate(NLog.LogEventInfo)
1be8ec44 1b65ca31 NLog.Targets.Target.PrecalculateVolatileLayouts(NLog.LogEventInfo)  **//Target.Syncroot    06542af4**
1be8ec94 1b65c7fc NLog.Targets.Wrappers.AsyncTargetWrapper.Write(NLog.Common.AsyncLogEventInfo)
1be8eca8 1b65c6d6 NLog.Targets.Target.WriteAsyncLogEvent(NLog.Common.AsyncLogEventInfo) **//Target.Syncroot   06542af4**
1be8ece0 1b65c531 NLog.LoggerImpl.WriteToTargetWithFilterChain(NLog.Internal.TargetWithFilterChain, NLog.LogEventInfo, NLog.Common.AsyncContinuation)
1be8ecf8 1b65c456 NLog.LoggerImpl.Write(System.Type, NLog.Internal.TargetWithFilterChain, NLog.LogEventInfo, NLog.LogFactory)
1be8ed20 1b65c292 NLog.Logger.WriteToTargets(NLog.LogLevel, System.IFormatProvider, System.String, System.Object[])
1be8ed4c 41411ed1 NLog.Logger.Info[[System.Guid, mscorlib]](System.String, System.Guid)
```

and

```
0:050> !sos.CLRStack
OS Thread Id: 0x22b4 (50)
Child SP       IP Call Site
1f34d090 77a6ca2c [GCFrame: 1f34d090] 
1f34d168 77a6ca2c [GCFrame: 1f34d168] 
1f34d184 77a6ca2c [HelperMethodFrame_1OBJ: 1f34d184] System.Threading.Monitor.ReliableEnter(System.Object, Boolean ByRef)
1f34d200 1b65a801 NLog.Targets.Target.Initialize(NLog.Config.LoggingConfiguration)     **//target.SyncRoot    06542af4**
1f34d230 1b65a7a6 NLog.Targets.Target.NLog.Internal.ISupportsInitialize.Initialize(NLog.Config.LoggingConfiguration)
1f34d234 1b659dab NLog.Config.LoggingConfiguration.InitializeAll()         
1f34d26c 1b653874 NLog.LogFactory.ReconfigExistingLoggers()
1f34d2b4 1b6537fd NLog.LogFactory.set_GlobalThreshold(NLog.LogLevel)  **//LogFactory.syncRoot**
1f34d2e0 1b653186 NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLog.Config.NLogXmlElement, System.String)
1f34d344 1b652dc2 NLog.Config.XmlLoggingConfiguration.ParseConfigurationElement(NLog.Config.NLogXmlElement, System.String)
1f34d378 1b652bdc NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLog.Config.NLogXmlElement, System.String)
1f34d390 1b652844 NLog.Config.XmlLoggingConfiguration.Initialize(System.Xml.XmlReader, System.String, Boolean)
1f34d3c8 1b6526e4 NLog.Config.XmlLoggingConfiguration..ctor(System.String)
1f34d3f4 1b651e7d NLog.LogFactory.LoadLoggingConfiguration(System.String)
1f34d408 1b65195b NLog.LogFactory.get_Configuration()             **//LogFactory.syncRoot    0411a750**
1f34d444 1b651222 NLog.LogFactory.GetLogger(LoggerCacheKey)           //LogFactory.syncRoot    0411a750
1f34d488 1b650f55 NLog.LogFactory`1[[System.__Canon, mscorlib]].GetLogger(System.String)
1f34d49c 1b650eed NLog.LogFactory`1[[System.__Canon, mscorlib]].GetCurrentClassLogger()
```

I cannot turn on internal logging and am unable to reproduce outside of my production environment.

**Comment by 304NotModified** [comment] 2016-01-30 21:04
Thanks! We fixed some deadlocks in 4.3. We will check if this one has been fixed.

**Comment by dlkay0** [comment] 2016-02-01 23:37
I'll stay tuned as I'd like to stay on  a current version.  I've downgraded to v3 for the time being.

**Comment by 304NotModified** [comment] 2016-02-02 07:32
OK, we will let you know when it's released. What (nuget) version is working? 3.2.1?

Then we can check the differences in code.

**Comment by 304NotModified** [comment] 2016-02-03 16:00
related code:

target.cs
```c#
 /// <summary>
        /// Initializes this instance.
        /// </summary>
        /// <param name="configuration">The configuration.</param>
        internal void Initialize(LoggingConfiguration configuration)
        {
            lock (this.SyncRoot)
            {
                this.LoggingConfiguration = configuration;

                if (!this.IsInitialized)
                {
                    PropertyHelper.CheckRequiredParameters(this);
                    this.IsInitialized = true;
                    try
                    {
                        this.InitializeTarget();
                        this.initializeException = null;
                        if (this.allLayouts == null)
                        {
                            throw new NLogRuntimeException("{0}.allLayouts is null. Call base.InitializeTarget() in {0}", this.GetType());
                        }
                    }
                    catch (Exception exception)
                    {
                        InternalLogger.Error(exception, "Error initializing target '{0}'.", this);

                        this.initializeException = exception;

                        if (exception.MustBeRethrown())
                        {
                            throw;
                        }

                    }
                }
            }
        }
```

logfactory.cs
```c#
  /// </summary>
        public LoggingConfiguration Configuration
        {
            get
            {
                lock (this.syncRoot)
                {
                    if (this.configLoaded)
                    {
                        return this.config;
                    }

                    this.configLoaded = true;

#if !SILVERLIGHT  && !__IOS__ && !__ANDROID__
                    if (this.config == null)
                    {
                        // Try to load default configuration.
                        this.config = XmlLoggingConfiguration.AppConfig;
                    }
#endif
                    // Retest the condition as we might have loaded a config.
                    if (this.config == null)
                    {
                        foreach (string configFile in GetCandidateConfigFileNames())
                        {
#if SILVERLIGHT
                            Uri configFileUri = new Uri(configFile, UriKind.Relative);
                            if (Application.GetResourceStream(configFileUri) != null)
                            {
                                LoadLoggingConfiguration(configFile);
                                break;
                            }
#else
                            if (File.Exists(configFile))
                            {
                                LoadLoggingConfiguration(configFile);
                                break;
                            }
#endif
                        }
                    }

                    if (this.config != null)
                    {
#if !SILVERLIGHT && !__IOS__ && !__ANDROID__
                        config.Dump();
                        try
                        {
                            this.watcher.Watch(this.config.FileNamesToWatch);
                        }
                        catch (Exception exception)
                        {
                            if (exception.MustBeRethrownImmediately())
                            {
                                throw;
                            }

                            InternalLogger.Warn(exception, "Cannot start file watching. File watching is disabled");
                            //TODO NLog 5: check "MustBeRethrown" 


                        }
#endif
                        this.config.InitializeAll();
                        LogConfigurationInitialized();
                    }

                    return this.config;
                }
            }

            set
            {
#if !SILVERLIGHT && !__IOS__ && !__ANDROID__
                try
                {
                    this.watcher.StopWatching();
                }
                catch (Exception exception)
                {
                    InternalLogger.Error(exception, "Cannot stop file watching.");

                    if (exception.MustBeRethrown())
                    {
                        throw;
                    }
                }
#endif

                lock (this.syncRoot)
                {
                    LoggingConfiguration oldConfig = this.config;
                    if (oldConfig != null)
                    {
                        InternalLogger.Info("Closing old configuration.");
#if !SILVERLIGHT
                        this.Flush();
#endif
                        oldConfig.Close();
                    }

                    this.config = value;
                    this.configLoaded = true;

                    if (this.config != null)
                    {
                        config.Dump();

                        this.config.InitializeAll();
                        this.ReconfigExistingLoggers();
#if !SILVERLIGHT && !__IOS__ && !__ANDROID__
                        try
                        {
                            this.watcher.Watch(this.config.FileNamesToWatch);
                        }
                        catch (Exception exception)
                        {
                            //ToArray needed for .Net 3.5
                            InternalLogger.Warn(exception, "Cannot start file watching: {0}", string.Join(",", this.config.FileNamesToWatch.ToArray()));

                            if (exception.MustBeRethrown())
                            {
                                throw;
                            }
                        }
#endif
                    }

                    this.OnConfigurationChanged(new LoggingConfigurationChangedEventArgs(value, oldConfig));
                }
            }
        }
```

**Comment by 304NotModified** [comment] 2016-02-03 16:07
Some help on this would be appreciated. Locking is tricky stuff

**Comment by dlkay0** [comment] 2016-02-03 16:44
I was previously using NLog 3.1.0.0.

Here are some ideas, but I'm not familiar with other locking techniques the project has used thus far...

May not be ideal, but in NLog.LogFactory.get_Configuration() use Monitor.TryEnter() instead of calling lock() and--if unable to Enter--throw a new exception that would need to be handled by anything that also locks the LogFactory first.  If the exception is caught, the caller must release the lock on LogFactory and start over.

-or-

Use a ManualResetEvent to signal each Target to be lazily self-responsible for reconfiguration the next time they are written to rather than immediately reconfiguring all targets from LogFactory.

**Comment by 304NotModified** [comment] 2016-02-04 11:40
notes:

- 3.1 uses [`lock(this)`](https://github.com/NLog/NLog/blob/v3.1.0/src/NLog/LogFactory.cs#L137) instead of [`lock(Syncroot)`](https://github.com/NLog/NLog/blob/4.3.0-beta1/src/NLog/LogFactory.cs#L142)

**Comment by 304NotModified** [comment] 2016-02-04 11:43
@kt1996 can you help us with this? I saw you have contributed some nice fixes regarding deadlocks :)

**Comment by kt1996** [comment] 2016-02-05 20:15
@304NotModified Sure... I would be quite grateful could direct me as to what test code to run to simulate this deadlock. I'd like to analyse it first. Sorry but still a noob :-P

**Comment by bhaeussermann** [comment] 2016-02-06 11:55
The key to solving this issue might lie in first identifying how it came about.

From thread 50's stack trace we can see that the Configuration is still being loaded by this thread. This means that thread 50 is the first thread which is accessing the `LogFactory.Configuration` property (the property ensures it is loaded only once and there is no code which sets `configLoaded` back to `false`). 

Yet thread 30 already has a reference to a `Logger` object, so this object must have been acquired through a `GetLogger()` or `GetCurrentClassLogger()` call to `LogFactory` which somehow circumvented loading the configuration. It looks like this can only be done by passing `null` for the `Type loggerType` parameter of `GetLogger()` or `GetCurrentClassLogger()`, or maybe I’m missing something.

Being able to acquire a `Logger` before the configuration is loaded sounds dangerous, and we should avoid this from happening if it happens be the cause of this issue. 

@dlkay0 can you tell how thread 30 acquired its `Logger` object that it uses to write?

**Comment by 304NotModified** [comment] 2016-02-06 12:59
Good questions.  I think it's also problematic that the mdc renderers locks the configuration when rendering. (2 times by the LogManager.configuration propery)

**Comment by 304NotModified** [comment] 2016-02-06 13:02
I think that's also the difference compared to NLog 3.1, the (indirect) lock in the context renders.

**Comment by 304NotModified** [comment] 2016-02-06 13:53
#1233 will fix this case. Checked also other layout (renders) and none of the uses `LogManager.Configuration` which is good. If some one would like to review it, thanks in advance!

**Comment by bhaeussermann** [comment] 2016-02-06 15:16
> I think it's also problematic that the mdc renderers locks the configuration when rendering.

It may be difficult to guarantee that no layout-renderers or targets ever access `LogManager/LogFactory.Configuration` (eg. `VariableLayoutRenderer` needs the configuration; it first tries to access its own `LoggingConfiguration` property, and - in case it had not yet been initialized - falls back onto `LogManager.Configuration`; I don't think we can prevent that). Even if we can remove all access to `LogManager/LogFactory.Configuration`, future changes to layout-renderers or targets may reinstate access to it and hence reintroduce a potential deadlock without anyone noticing.

Therefore we should facilitate safe access to `LogManager/LogFactory.Configuration` by layout-renderers and targets. The fact that the `Configuration` property locks the `LogFactory` is not a problem as long as the configuration is already loaded:  
```
public LoggingConfiguration Configuration
{
    get
    {
        lock (this.syncRoot)
        {
            if (this.configLoaded)
            {
                return this.config;
            }
            ...
```
If the configuration is loaded, control will jump back out and immediately release the lock again (without acquiring any other locks). 

Therefore my suggestion is that we try to guarantee that the configuration is loaded before any logging can occur. The only code in `LogFactory` that I can identify that may violate this guarantee is [this if-statement](https://github.com/NLog/NLog/blob/master/src/NLog/LogFactory.cs#L909) when `cacheKey.ConcreteType` is `null` (and this should probably be fixed). This is why I would like to know from @dlkay0 how the `Logger` is acquired from the `LogFactory` (what does the method call look like?).

**Comment by 304NotModified** [comment] 2016-02-06 16:45
Agree @bhaeussermann.  A more structural change is really preferred.

**Comment by dlkay0** [comment] 2016-02-06 21:39
I don't have it readily available, but I'm using something like: (from memory)

private static readonly IMyLoggerOverride Logger = new LogFactory<MyLoggerOverride>().GetCurrentClassLogger();

The business object class has no static constructor, so its static class initializer is lazily being executed (on thread 50) when the first static property of my class is accessed--long after several instances of my class exist.  (This is a .NET 4.0 optimization)

By the time the deadlock occurs the multi-threaded application has already loaded configuration and logged several events from other classes/loggers; it just hasn't done so from this class yet (on thread 50).  Thread 30 is a background task operating on an instance of the class which needs to log something.

My override of the logger primarily exposes static methods for setting MDC values.  It doesn't look to be involved in the deadlock by absence from the call stack.

-DK

**Comment by bhaeussermann** [comment] 2016-02-07 07:24
Thanks @dlkay0! I think I see now what is happening. I was under the delusion that the configuration object was static (i.e. a static member or an instance member of a singleton), which is not the case.

In `new LogFactory().GetCurrentClassLogger()` you are creating a new `LogFactory` which will load its own configuration object (using its own lock object). The problem occurs during the configuration loading when `XmlLoggingConfiguration` sets the `GlobalThreshold` property on the global `LogFactory` object, instead of on the new `LogFactory` object.

I would suggest you change that line of code to call the static method `LogManager.GetCurrentClassLogger()`. This will get the logger from the global `LogFactory` object (which already has its configuration loaded). This should fix your deadlock.

Subsequently, the more general question of whether this can be fixed in NLog arises. I can imagine that there will be cases where it would make sense to create new `LogFactory` instances instead of accessing the global one through `LogManager`. For example, it allows you to have parts of your application use a different logging configuration from the rest. Is this something we want to support?

**Comment by 304NotModified** [comment] 2016-02-07 10:06
I would also advise to use `LogManager`. 

We like to support the `LogFactory`, especially the `LogFactory<T>` for custom loggers.

**Comment by bhaeussermann** [comment] 2016-02-07 10:49
> > The problem occurs during the configuration loading when XmlLoggingConfiguration sets the GlobalThreshold property on the global LogFactory object, instead of on the new LogFactory object.

> I think we can fix this?

I think so. I shall look into it.

**Comment by bhaeussermann** [comment] 2016-02-07 11:15
Do we want to support multiple `LogFactory` objects with multiple configurations?  
If so, then layout-renderers and targets must access their own `LoggingConfiguration`, and fail-back to `LogManager.Configuration` only when their local `LoggingConfiguration` is not set. I think #1223 fixes this, but not for the sake of avoiding deadlocks (the change to `XmlLoggingConfiguration` ought to fix that), but for the sake of using the correct configuration.

**Comment by 304NotModified** [comment] 2016-02-07 12:10
> Do we want to support multiple LogFactory objects with multiple configurations?
> 
> If so, then layout-renderers and targets must access their own LoggingConfiguration, and fail-back to LogManager.Configuration only when their local LoggingConfiguration is not set. I think #1223 fixes this, but not for the sake of avoiding deadlocks (the change to XmlLoggingConfiguration ought to fix that), but for the sake of using the correct configuration.

I think that's reasonable. https://github.com/NLog/NLog/pull/1223 fixes both, because no `lock` on Factory is used when the local LoggingConfiguration is set.

**Comment by bhaeussermann** [comment] 2016-02-07 14:56
> I think that's reasonable. #1223 fixes both, because no lock on Factory is used when the local LoggingConfiguration is set.

Ok, fair enough. But the change to `XmlLoggingConfiguration` should future-proof us against a deadlock like this (in case any layout-renderers or targets may accidentally be made to access the "global" configuration in future, this should not cause a deadlock anymore).

My pull request is almost ready ;).

**Comment by dlkay0** [comment] 2016-02-07 19:27
@bhaeussermann Are you suggesting that instead of this:
```
private static readonly MyLoggerOverride Logger = new LogFactory<MyLoggerOverride>().GetCurrentClassLogger();
```
I do this?
```
private static readonly MyLoggerOverride Logger = (MyLoggerOverride)LogManager.GetCurrentClassLogger(typeof(MyOverrideLogger));
```
I realize I left the <T> off before when I was recalling from memory.

There is no LogManager.GetCurrentClassLogger<T>() which would be a nice alternative to new'ing up a new LogFactory.

-DK

**Comment by bhaeussermann** [comment] 2016-02-07 19:35
> `private static readonly MyLoggerOverride Logger = (MyLoggerOverride)LogManager.GetCurrentClassLogger(typeof(MyLoggerOverride));`

That's correct. Either that or you can use the same `LogFactory<MyLoggerOverride>` object throughout your entire app (instead of creating a new one for each class).

> There is no LogManager.GetCurrentClassLogger() which would be a nice alternative to new'ing up a new LogFactory.

I guess we could add a generic static method to `LogManager`. Something like:

```
private static readonly MyLoggerOverride Logger = LogManager.GetCurrentClassLogger<MyLoggerOverride>();
```

Would that be better for you?

**Comment by dlkay0** [comment] 2016-02-07 19:40
@bhaeussermann Yes, I would use that since it would avoid the requirement for the explicit cast.  The absence is what led me to instantiating a new LogFactory for each class in the first place.

-DK

**Comment by 304NotModified** [comment] 2016-02-07 21:21
@bhaeussermann in the new case (NLog 4.3) `LogFactory<MyLoggerOverride>` is also OK?

```
private static readonly MyLoggerOverride Logger = LogManager.GetCurrentClassLogger<MyLoggerOverride>();
```
I think that is a nice addition, but we should add them everywhere. (also GetLogger and also in Factory?)

**Closed** 2016-02-07 23:38 UTC
Labels: bug, less easy, must have, up-for-grabs

**Comment by bhaeussermann** [comment] 2016-02-08 04:36
> I think that is a nice addition, but we should add them everywhere.

Agreed.
