### ISSUE TITLE
EventLogTarget always logs to application log

### ISSUE THREAD

**Issue by chdev2412** [NLog/NLog#950] opened 2015-10-14 05:56 UTC
In my project (ASP.NET C# class library project) , we are using NLog.dll (v 4.0.0.0) to log exceptions in eventviewer, in the below manner.

``` c#
private readonly NLog.Logger _logger;
_logger = LogManager.GetCurrentClassLogger();
_logger.Error(someText, someArgs);
```

Please find the NLog configurations used as below :

``` xml
  <target xsi:type="EventLog"
          name="eventlog"
          layout="${message}"
          machineName="."
          source="NLogLogger"
          log="Application"  />
```

It works fine and logs messages in the Application log inside “Windows Logs”.
However, we require the logging to be performed in a separately designated log (custom log, specific for my application) .

We specified the name of the designated log in the config like below.

``` xml
  <target xsi:type="EventLog"
          name="eventlog"
          layout="${message}"
          machineName="."
          source="NLogLogger"
          log=“MyOwnLog” />
```

But it still logs messages in the same Application log.

Please let me know how I can get it logged in the designated log.

**Comment by 304NotModified** [comment] 2015-10-14 21:30
I'm looking at this right now.

**Comment by 304NotModified** [comment] 2015-10-14 21:39
I can reproduce this, but the code looks good. 

Think this is the same issue. http://bytes.com/topic/c-sharp/answers/262283-eventlog-always-writes-application-log

**Comment by 304NotModified** [comment] 2015-11-19 20:21
@epignosisx Ever seen this bug?

**Comment by stile17** [comment] 2015-12-21 12:44
I think the problem is related to:
> **From MSDN**
> If a source has already been mapped to a log and you remap it to a new log, you must restart the computer for the changes to take effect.

When I was testing nlog.config my first approach was to omit the "log" attribute. Messages was sent to "Application" log. My next thing to test was my custom log "MyOwnLog" but i left the same source name, and messages was also sending to "Application" log. Bummer :(

When I changed the log name and source name at the same time everything worked correctly.

Look out for name of event log, only first eight signs is important ;)

*Please correct my english if I made terrible mistakes.*

**Comment by 304NotModified** [comment] 2015-12-21 14:12
Thanks @stile17 

I think your are right. But can you give an example in nlog.configs? That would help fully understanding it.

PS: your English is good to follow. :+1:

**Comment by stile17** [comment] 2015-12-21 14:26
First attempt (messages are writing to Application log):
```
<target xsi:type="EventLog"
                name="EventLog"
                source="MyNameEventLog"
                machineName="."
                layout="${message}${newline}${exception:format=ToString}"/>
```
Improvement (message are still writing to Application log):

```
<target xsi:type="EventLog"
                name="EventLog"
                source="MyNameEventLog"
                log="MyNameEventLog"
                machineName="."
                layout="${message}${newline}${exception:format=ToString}"/>
```
Solution (messages are writing to "NewNameEventLog" log):
```
<target xsi:type="EventLog"
                name="EventLog"
                source="NewNameEventLog"
                log="NewNameEventLog"
                machineName="."
                layout="${message}${newline}${exception:format=ToString}"/>
```
Solution (alternate) using powershell and removing "MyNameEventLog", next restarting computer, than this nlog.config begin to write messages to "MyNameEventLog":
```
<target xsi:type="EventLog"
                name="EventLog"
                source="MyNameEventLog"
                log="MyNameEventLog"
                machineName="."
                layout="${message}${newline}${exception:format=ToString}"/>
```

**Comment by UgurAldanmaz** [comment] 2016-07-30 00:55
Anyone working? I want to work on it if anyone did not start yet.

**Comment by 304NotModified** [comment] 2016-07-30 10:15
That would be great!

**Comment by UgurAldanmaz** [comment] 2016-08-17 01:36
I have tested with Log name that different than Application. As @stile17 said, it works. 
Logs can be viewed with Event Viewer, under the "Application and Services Logs" node. 

It seems that there is no bug, but we can add a feature to log into custom directories. Such as `Application and Services Logs / Microsoft / Windows / etc...` (It is also mentioned in #1151)

But I am not sure that Windows Event Log actually log into directories. Maybe Event Viewer gives the directory view. Also I did not see Regedit records for `Microsoft / Windows / etc..` directories.

What do you think about to develop this feature?

**Comment by 304NotModified** [comment] 2016-08-21 10:32
> It seems that there is no bug, but we can add a feature to log into custom directories.

It would be great to add this feature! :) Please do! :+1:

**Comment by UgurAldanmaz** [comment] 2016-08-21 11:44
Okay, I will investigate. Again, I am not sure if it is possible :)

**Comment by jamers99** [comment] 2019-11-13 20:29
Any update on this? Will this be done? It would be nice!

**Comment by snakefoot** [comment] 2019-11-13 20:37
Windows EventLog is special. Since the idea of multiple EventLogs is just a shim. All EventLog-items are stored in the same blob.

The Windows Registry Database controls where the LogEvents from registered EventLog-source should be shown. This gives the illusion of having multiple EventLogs, but it is actually more like a category.

A single EventLog-source can only exist in a single EventLog (or category). If having registered an EventLog-source to write into a special EventLog, then it cannot write to another EventLog (or category).

Anyways if you find some gold nuggets that can improve NLog EventLog, then please create a pull-request.

**Comment by 304NotModified** [comment] 2019-11-13 21:30
I think we could close this. Im pretty sure that the code is correct. 

I prefer adding (mocked) unit tests for this, but not sure if that's needed

**Comment by snakefoot** [comment] 2019-11-14 06:15
Think both me and @stile17 agree that this is not an issue in NLog EventLog Target.

It is because Windows EventLog is special regarding one EventLog-source can only write to one EventLog.

**Comment by 304NotModified** [comment] 2019-11-14 06:57
Ok close :) thanks!

**Closed by 304NotModified** 2019-11-14 06:57 UTC
Labels: bug, event-log-target, up-for-grabs

**Comment by stile17** [comment] 2019-11-14 08:23
I agree with @snakefoot that this is not an issue with NLog :)

But for me the main OP issue is that mapping between source and target EventLog cannot be changed without restarting Windows so its rather Windows issue ;)

**Comment by shafiqdev** [comment] 2020-01-13 21:48
restarting the Windows EventLog service solved this problem for me. no system reboot required.

**Comment by TYZhenn** [comment] 2020-06-25 04:55
maybe you can check if you install NLog.WindowsEventLog package
right at the beginning of this page
https://github.com/NLog/NLog/wiki/EventLog-target
![image](https://user-images.githubusercontent.com/67313749/85656164-0838e800-b6e3-11ea-94b3-435ce0c98016.png)
