### ISSUE TITLE
 Error in lazy writer timer procedure. Exception: System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by vankampenp** [NLog/NLog#3663] opened 2019-11-03 17:51 UTC
I get this error when writing from two different processes to one file. The API and the Web site write in the same log. It does not seem to be a permission issue, for test I have given Everybody write access to the folder and all files in it. But I am not sure, as a simular configuration works on another machine, albeit a bit older version.

From the internal-log.txt:
```
2019-11-03 00:11:02.8143 Error AsyncWrapper(Name=ownFile-trace): Error in lazy writer timer procedure. Exception: System.UnauthorizedAccessException: Access to the path 'Global\NLog-FileFileLock-c:_inetpub_vhosts_<domain>_httpdocs_logs_domain-trace.log' is denied.
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at NLog.Internal.FileAppenders.BaseMutexFileAppender.ForceCreateSharableMutex(String name)
   at NLog.Internal.FileAppenders.BaseMutexFileAppender.CreateSharableMutex(String mutexNamePrefix)
   at NLog.Internal.FileAppenders.MutexMultiProcessFileAppender..ctor(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.MutexMultiProcessFileAppender.Factory.NLog.Internal.FileAppenders.IFileAppenderFactory.Open(String fileName, ICreateFileParameters parameters)
   at NLog.Internal.FileAppenders.FileAppenderCache.CreateAppender(String fileName, Int32 freeSpot)
   at NLog.Internal.FileAppenders.FileAppenderCache.AllocateAppender(String fileName)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, ArraySegment`1 bytes, Boolean initializedNewFile)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, ArraySegment`1 bytesToWrite)
   at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, Exception& lastException)
   at NLog.Targets.FileTarget.Write(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncLogEvents(IList`1 logEvents)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.WriteEventsInQueue(Int32 batchSize, String reason)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(Object state)

```
The target configuration on both is the same:
```

 <targets  >
    <default-wrapper xsi:type="AsyncWrapper"  overflowAction="Block" optimizeBufferReuse ="true"/>
    <target xsi:type="File" name="ownFile-trace" fileName="${configsetting:name=Nlog.RelativeLogPath:default=logs}\${configsetting:name=Nlog.Machinename:default=testmij}-trace.log"
            layout="${longdate}|${aspnet-request-ip}|${aspnet-User-Identity}|${pad:padding=-5:${uppercase:${level}}}|${assembly-version}|${pad:padding=-3:${threadid}}|${aspnet-mvc-controller}|${callsite:className=True:includeNamespace=False:fileName=False:includeSourcePath=False:methodName=True:cleanNamesOfAnonymousDelegates=True:cleanNamesOfAsyncContinuations=True}|${message}|${exception}"
            maxArchiveFiles="14"
            archiveFileName="${configsetting:name=Nlog.RelativeLogPath:default=logs}\archive\${configsetting:name=Nlog.Machinename:default=domain}-trace.{#}.zip"
            archiveNumbering="Date"
            archiveEvery="Saturday"
            archiveDateFormat="yyyyMMdd"
            enableArchiveFileCompression ="true"
            keepFileOpen ="true"
            openFileCacheTimeout="30"
            concurrentWrites ="true"
            autoFlush ="false"
            openFileFlushTimeout ="10"
            />

```
The api appSettings uses 
"RelativeLogPath":  "../httpdocs/logs" 

where the Web site uses
"RelativeLogPath":  "logs" 

The nlog versions are:
  ```
<PackageReference Include="NLog.Web.AspNetCore" Version="4.9.0" />
  <PackageReference Include="NLog" Version="4.6.7" />
```

Runing asp.net core 3.0 on Windows

**Comment by snakefoot** [comment] 2019-11-04 06:29
Are the two applications running with the same windows-service-account?

Do the windows-service-account have access to global mutex creation?

Have read that NetCore applications running in AppContainer are not allowed to create global mutex. Are you using AppContainer?

You can try and check the permission for the global mutex, when one service is running:

https://docs.microsoft.com/en-us/sysinternals/downloads/winobj

More info: https://blogs.msdn.microsoft.com/winsdk/2009/11/10/access-denied-on-a-mutex/

**Comment by snakefoot** [comment] 2019-11-04 06:32
Work around is to configure the following (Stops using global mutex):

```
            keepFileOpen ="true"
            concurrentWrites ="false"
```

But then archive logic will not be working, since it cannot be synchronized between multiple processes without `concurrentWrites=true`. Need to change FileName-Layout to automatically change every saturday (Include a week-number in layout).

**Comment by vankampenp** [comment] 2019-11-08 12:54
Thanks @snakefoot 
I updated the other working system to the latests, and that now also does not work. There is no change in configuration. 
The two applications run with different service accounts, but trying to move it to one does not make a difference.

I would like to keep the archiving.

**Comment by snakefoot** [comment] 2019-11-08 16:53
I'm sorry but I think you have to find the problem here yourself.

Compiling your own NLog-dll and add more internal-logging output until you can figure out why your two applications cannot share the same global mutex.

**Comment by snakefoot** [comment] 2019-12-04 23:11
Possible solution could be to change the NLog from using `MutexRights.FullControl` to `MutexRights.Synchronize | MutexRights.Modify`.

See also:

https://stackoverflow.com/questions/19536697/unauthorizedaccessexception-when-trying-to-open-a-mutex

Safe road could be a fallback, when `MutexRights.FullControl`  fails.

**Comment by snakefoot** [comment] 2020-01-20 21:49
Closing this issue as caused by external setup. Changing the MutexRights will probably be a breaking change, and will most likely not work with older version of NLog.

**Closed by snakefoot** 2020-01-20 21:49 UTC
Labels: external, file-target
