### ISSUE TITLE
System.ArgumentException: LayoutRenderer cannot be found: 'longdate' when creating new target programatically

### ISSUE THREAD

**Issue by Babbie** [NLog/NLog#1599] opened 2016-08-18 14:44 UTC
**Type**: Bug

**NLog version**: 4.3.7 (latest)

**Platform**: Xamarin Android

**Current NLog config**

``` c#
public static void ConfigureAll()
{
        LoggingConfiguration config = new LoggingConfiguration();
        config = ConfigureConsole(config);
        LogManager.Configuration = config;
        Debug.Write("Logger linked!");
}

public static LoggingConfiguration ConfigureConsole(LoggingConfiguration config)
{
        ConsoleTarget consoleTarget = new ConsoleTarget();

        consoleTarget.Name = "Console";
        consoleTarget.Layout = @"${date:format=HH\:mm\:ss.fff}|${pad:padding=5:inner=${level:uppercase=true}}|${pad:padding=30:fixedLength=True:inner=${logger}}: ${message}";

        LoggingRule rule1 = new LoggingRule("*", Constants.ConsoleLogLevel, consoleTarget);

        config.AddTarget("console", consoleTarget);
        config.LoggingRules.Add(rule1);

        return config;
}
```
- What is the current result?
  -- When running the above code, the application throws a `System.ArgumentException` on the `new ConsoleTarget();` with the message that the `longdate` `LayoutRenderer` cannot be found.
- What is the expected result?
  -- No exception (obviously)
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  -- No, cannot work out how to do this on Android.
- Please post full exception details (message, stacktrace, inner exceptions)

```
08-18 16:38:19.120 I/MonoDroid(21457): UNHANDLED EXCEPTION:
08-18 16:38:19.130 I/MonoDroid(21457): System.ArgumentException: LayoutRenderer cannot be found: 'longdate'
08-18 16:38:19.130 I/MonoDroid(21457):   at NLog.Config.Factory`2[TBaseType,TAttributeType].CreateInstance (System.String name) [0x0002c] in <filename unknown>:0 
08-18 16:38:19.130 I/MonoDroid(21457):   at NLog.Layouts.LayoutParser.ParseLayoutRenderer (NLog.Config.ConfigurationItemFactory configurationItemFactory, NLog.Internal.SimpleStringReader sr) [0x00014] in <filename unknown>:0 
08-18 16:38:19.130 I/MonoDroid(21457):   at NLog.Layouts.LayoutParser.CompileLayout (NLog.Config.ConfigurationItemFactory configurationItemFactory, NLog.Internal.SimpleStringReader sr, Boolean isNested, System.String& text) [0x0009a] in <filename unknown>:0 
08-18 16:38:19.130 I/MonoDroid(21457):   at NLog.Layouts.SimpleLayout.set_Text (System.String value) [0x00013] in <filename unknown>:0 
08-18 16:38:19.130 I/MonoDroid(21457):   at NLog.Layouts.SimpleLayout..ctor (System.String txt, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x0000d] in <filename unknown>:0 
08-18 16:38:19.130 I/MonoDroid(21457):   at NLog.Layouts.Layout.FromString (System.String layoutText, NLog.Config.ConfigurationItemFactory configurationItemFactory) [0x00000] in <filename unknown>:0 
08-18 16:38:19.130 I/MonoDroid(21457):   at NLog.Layouts.Layout.FromString (System.String layoutText) [0x00006] in <filename unknown>:0 
08-18 16:38:19.130 I/MonoDroid(21457):   at NLog.Layouts.Layout.op_Implicit (System.String text) [0x00000] in <filename unknown>:0 
08-18 16:38:19.130 I/MonoDroid(21457):   at NLog.Targets.TargetWithLayout..ctor () [0x00006] in <filename unknown>:0 
08-18 16:38:19.130 I/MonoDroid(21457):   at NLog.Targets.TargetWithLayoutHeaderAndFooter..ctor () [0x00000] in <filename unknown>:0 
08-18 16:38:19.130 I/MonoDroid(21457):   at NLog.Targets.ConsoleTarget..ctor () [0x00000] in <filename unknown>:0 
```
- Are there any work arrounds? 
  -- Perhaps using the xml configuration, but I cannot get that to work.
- Is there a version in which it did worked? 
  -- I tried 4.3.6 to no avail.

It seems that NLog fails on creating the default `ConsoleTarget` `Layout`. The same thing occurs for other `Target`s, tested with `DebuggerTarget`.
NLog was installed using NuGet, Xamarin.Forms has version 2.3.1.114.

**Comment by 304NotModified** [comment] 2016-08-18 17:42
Could you post the internal on traceand could you try ${logger}? 

Thanks!

**Comment by 304NotModified** [comment] 2016-08-18 18:48
you can print the internallog by setting internalogger.Write property (e.g. textWriter)

**Comment by 304NotModified** [comment] 2016-08-18 18:49
Are you sure this is the correct code?`${longdate}` isn't used?

**Comment by 304NotModified** [comment] 2016-08-18 18:55
I;m looking for this log: (and others after it)

https://github.com/NLog/NLog/blob/7035e5bda5126ef46faa517e9a6ae8301ef0835b/src/NLog/Config/ConfigurationItemFactory.cs#L203

**Comment by Babbie** [comment] 2016-08-18 21:36
I'm unable to access the code at the moment so I cannot give you the other information until tomorrow, but I am 100 percent sure longdate is not used in my code, only in NLog itself. 
What I meant by being unable to give the internal log is that console doesn't seem to work on Android. I'll try a file tomorrow.

**Comment by Babbie** [comment] 2016-08-19 07:40
I've attempted to use the InternalLogger. However, with the following code:
```c#
InternalLogger.LogLevel = LogLevel.Trace;
InternalLogger.LogWriter = new StreamWriter(Android.OS.Environment.ExternalStorageDirectory + "/internallog.txt");
```
The file internallog.txt is created, but is 0 bytes (so empty). Attempting to use LogToTrace is impossible as InternalLogger.LogToTrace is not defined (bug?).
Attemptying to use ``${logger}`` results in the same exception. 
The InnerException appears to be null.

**Comment by Babbie** [comment] 2016-08-19 08:40
As a side note, I cannot get the NLog.config to work either. I've tried placing it in Assets, with build action AndroidAssets and Copy Always and with build action Content and Copy Always and just in the project with build action Content and Copy Always, however nothing is ever written to the logger.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Trace" internalLogFile="/storage/sdcard1/internallog.txt">

  <!-- optional, add some variables
  https://github.com/nlog/NLog/wiki/Configuration-file#variables
  
  <variable name="myvar" value="myvalue"/>
  -->


  <!--
  See https://github.com/nlog/nlog/wiki/Configuration-file
  for information on customizing logging rules and outputs.
   -->
  <targets>

    <!--
    add your targets here
    See https://github.com/nlog/NLog/wiki/Targets for possible targets.
    See https://github.com/nlog/NLog/wiki/Layout-Renderers for the possible layout renderers.
    -->

    <!--
    Write events to a file with the date in the filename.
    <target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message}" />
    -->

    <target
      xsi:type="Console"
      name="Console"
      layout="${date:format=HH\:mm\:ss.fff}|${pad:padding=5:inner=${level:uppercase=true}}|${pad:padding=30:fixedLength=True:inner=${logger}}: ${message}"
    />

    <target
      xsi:type="Debugger"
      name="Debugger"
      layout="${date:format=HH\:mm\:ss.fff}|${pad:padding=5:inner=${level:uppercase=true}}|${pad:padding=30:fixedLength=True:inner=${logger}}: ${message}"
    />
  </targets>

  <rules>
    <!-- add your logging rules here -->

    <!--
    Write all events with minimal level of Debug (So Debug, Info, Warn, Error and Fatal, but not Trace)  to "f"
    <logger name="*" minlevel="Debug" writeTo="f" />
    -->

    <logger
      name="*"
      minlevel="Info"
      writeTo="Console"
    />

    <logger
      name="*"
      minlevel="Debug"
      writeTo="Debugger"
    />

  </rules>
</nlog>

```

**Comment by 304NotModified** [comment] 2016-08-19 09:50
> The file internallog.txt is created, but is 0 bytes (so empty).

I guess you need to flush. or setting the .Write property is too late





> The internal log contains the same error when I use the config file, so I do have a log for you now!

Thanks, but there is a lot missing in the logs which we need to diagnose the problem

**Comment by Babbie** [comment] 2016-08-19 10:08
I'll have to edit the log a bit to erase some references as the code I'm working on is not open source, but I'll give you the full log. <private> is what I've replaced.

[log.txt](https://github.com/NLog/NLog/files/426759/log.txt)

**Comment by 304NotModified** [comment] 2016-08-19 12:04
Thanks, the relevant lines are:

```
2016-08-19 10:32:40.7454 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null')
2016-08-19 10:32:41.3954 Debug Start auto loading, location: /storage/sdcard1/Android/data/<private>/files/.__override__
2016-08-19 10:32:41.4039 Debug Auto loading done
2016-08-19 10:32:41.4382 Error Error in Parsing Configuration File. Exception: NLog.NLogConfigurationException: Exception occurred when loading configuration from assets/NLog.config ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: LayoutRenderer cannot be found: 'longdate'

```

So it does scanning (ScanAssembly) NLog.dll, but strange that ${longdate} isn't registered welll

**Comment by Babbie** [comment] 2016-08-19 12:06
Does it maybe have something to do with Version=4.0.0.0? Isn't that supposed to say 4.3.7 or something?

**Comment by 304NotModified** [comment] 2016-08-19 17:37
4.0.0.0 is correct, its the assembly version

**Comment by 304NotModified** [comment] 2016-08-19 17:39
Is its possible to set up a sample application? (Preferred as Github repos). We have limited. Experience with xamarin

**Comment by Babbie** [comment] 2016-08-26 15:04
Done! Note that if I create a new application and add NLog there, it works fine, but not when I reinstall it onto this project.
https://github.com/Babbie/NLogTest

**Comment by 304NotModified** [comment] 2016-08-26 15:28
that's strange!

I on holiday for two weeks, so probable I will check this after it

**Comment by Babbie** [comment] 2016-09-21 07:07
Any update on this?

**Comment by 304NotModified** [comment] 2016-09-21 15:47
I will look into it today. Thanks for the reminder

**Comment by 304NotModified** [comment] 2016-09-21 18:39
trying now. You get the error in the emulator?

**Comment by 304NotModified** [comment] 2016-09-21 18:48
```
Android application is debugging.
Could not connect to the debugger.

```

The debugger crashes every time?  I can;t see any error, but also not any breakpoint being hit or running app

**Comment by Babbie** [comment] 2016-10-05 07:03
No, I got the error when running it on a connected phone. I have no idea why it isn't working on your end.

**Comment by 304NotModified** [comment] 2016-10-05 19:52
Do you get the error also in the emulator?

**Comment by Babbie** [comment] 2016-10-13 07:01
The emulator has never worked on my work computer, so I can't say.

**Comment by 304NotModified** [comment] 2016-11-20 13:23
I'm sorry but I don't know how to continue with this one. I don't have any Xamarin apps or a lot of Xamarin experience

**Comment by snakefoot** [comment] 2018-02-22 22:48
Probably a duplicate of #2468 . Because linker optimizes everything non referenced out of the assemblies. Because NLog depends heavily on reflection, then nothing is left (Including `${longdate}`)

The solution is to tell Xamarin to skip link optimization for NLog, by adding this to the project-file:

```
<PropertyGroup>
    <AndroidLinkSkip>NLog</AndroidLinkSkip>
</PropertyGroup>
```

**Comment by 304NotModified** [comment] 2018-02-22 22:54
:+1:

**Comment by 304NotModified** [comment] 2018-04-06 22:33
I assume this is fixed with:

```
<PropertyGroup>
    <AndroidLinkSkip>NLog</AndroidLinkSkip>
</PropertyGroup>
```

So closing this one. Will reopen if this is still an issue

**Closed by 304NotModified** 2018-04-06 22:33 UTC
Labels: Xamarin, bug, needs info

**Comment by snakefoot** [comment] 2019-01-30 22:10
While waiting for NLog ver. 4.6 then you can do this:


```C#
[assembly: Preserve(typeof(NLog.LayoutRenderers.LongDateLayoutRenderer), AllMembers = true)]
```

This will force the AOT-linker to include code even if not referenced directly.
