### ISSUE TITLE
EventLogTarget does not seem to expand layout renderers for the 'source' attribute

### ISSUE THREAD

**Issue by oniony** [NLog/NLog#669] opened 2015-04-16 21:00 UTC
We are using 2.0.0.0 but I have confirmed this problem still exists in 3.2.0.0. When I have a target of type `EventLog` and use layout renderers such as `${processname}` in the `source` attribute, the raised events have a source of `${processname}` (literally) rather than the process's name.

This made me first think that the layout renderers are not expanded for this attribute but for two reasons:

1. The example on the [Eventlog target](https://github.com/nlog/nlog/wiki/EventLog-target) page actually uses one (`${appname}`) in the example.
2. If I specify a variable instead of one of the predefined layout renderers it then includes the literal value of that variable (with no further layout renderer resolution). For example, if I define a variable `${processname2}` that is defined as `${replace:searchFor=e:replaceWith=E:inner=${processname}}` and then specify the `source` in the target as `${processname2}` then the items logged have a source of the literal text `${replace:searchFor=e:replaceWith=E:inner=${processname}}` and not the modified process name 'chEEsE', for example.

**Comment by 304NotModified** [comment] 2015-04-16 21:02
The example is wrong. The source is a string. Not a layout.

**Comment by 304NotModified** [comment] 2015-04-16 21:06
Duplicate of https://github.com/NLog/NLog/issues/508

**Comment by 304NotModified** [comment] 2015-04-16 21:07
I have updated the wiki.

**Comment by oniony** [comment] 2015-04-16 21:10
Apologies: I did actually search for somebody having reported this previously but obviously failed.

Just to be clear: for fields of type `string`, is it correct that variables are expanded?

**Comment by 304NotModified** [comment] 2015-04-16 21:15
Only `Layouts` are expanded. `Strings` should remain the same.

**Comment by oniony** [comment] 2015-04-16 21:18
In which case I think my point 2 in the ticket suggests there is another bug: the variable I was using was expanded to the literal value of that variable.

E.g.

    <variable name="test" value="hello"/>
    ...
    <target xsi:type="EventLog"
            ...
            source="${test}"/>

The events raised have a source of `hello` not `${test}`.

**Comment by 304NotModified** [comment] 2015-04-16 21:24
That would be strange as https://github.com/NLog/NLog/blob/master/src/NLog/Targets/EventLogTarget.cs

wont change the `Source`

**Comment by 304NotModified** [comment] 2015-04-16 21:27
it seems indeed that `ExpandVariables` is ran on all strings (see 
[XmlLoggingConfiguration.cs](https://github.com/NLog/NLog/blob/master/src/NLog/Config/XmlLoggingConfiguration.cs)

**Comment by oniony** [comment] 2015-04-16 21:31
OK, that makes sense, thanks. I'll leave it to you to decide whether that's correct behaviour or not!

**Comment by 304NotModified** [comment] 2015-04-16 21:36
Well I dunno if it's a bug. But it is bad.

**Comment by 304NotModified** [comment] 2015-04-16 21:39
added a unit test for this. #670

**Comment by 304NotModified** [comment] 2015-04-19 21:10
Created a new issue for the discussion point. Closing this because it's a duplicate.

**Closed by 304NotModified** 2015-04-19 21:10 UTC
Labels: duplicate
