### ISSUE TITLE
Url encoding with WebserviceTarget and HttpPost

### ISSUE THREAD

**Issue by yetanotherchris** [NLog/NLog#380] opened 2014-06-27 09:37 UTC
I've created a WebService target and am calling an MVC controller using it, but it looks like NLog is incorrectly URL encoding a space (0xFEFF). Here's an example of the form that gets sent across:

	{%ufeffempty=&guid=336cec87129942eeabab3d8babceead7&m=Debg&
	date=2014-06-26+23%3a15%3a14.6348&logger=TestClient.Program&
	level=Debug&machinename=DELL}

The config file for the logger client is:

	<targets>
		<target xsi:type="WebService"
				name="webservice"
				url="http://localhost:57953/Home/Foo2"
				protocol="HttpPost"
				encoding="UTF-8"
				methodName="Foo">
			<parameter name="empty" type="System.String" layout=""/> 
			<parameter name="guid" type="System.String" layout="${guid}"/>
			<parameter name="m" type="System.String" layout="${message}"/>
			<parameter name="date" type="System.String" layout="${longdate}"/>
			<parameter name="logger" type="System.String" layout="${logger}"/>
			<parameter name="level" type="System.String" layout="${level}"/>
			<parameter name="machinename" type="System.String" layout="${machinename}"/>
		</target>
	</targets>

**Comment by 304NotModified** [comment] 2015-02-21 21:34
This is BOM issue (FEFF = UTF-8 BOM). And so this is a duplicate of #212. 

This hasn't been fixed yet. An unit test will boost the progress ;)

**Closed by 304NotModified** 2015-02-21 21:34 UTC
Labels: bug, duplicate
