### ISSUE TITLE
Event Log targets fails to load when program is published using Publish Single File

### ISSUE THREAD

**Issue by pockets3407** [NLog/NLog#4798] opened 2022-02-17 16:51 UTC
Hi! Thanks for reporting this bug! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**NLog version**:  4.7.12
**NLog.Extensions.Logging version**: 1.7.4
**NLog.WindowsEventLog version**: 4.7.12

**Platform**: .NET 6.0

**Current NLog config** (xml or C#, if relevant)

```json
{
  "NLog": {
    "autoReload": true,
    "internalLogFile": "c:\\temp\\nlog-internal.log",
    "throwExceptions": false,
    "internalLogLevel": "Debug",
    "targets": {
      "EventLog": {
        "type": "EventLog",
        "log": "My Product",
        "source": "My Product",
        "layout": "${level} | ${logger} | ${message}${onexception: | ${exception:format=tostring}}",
        "EntryType": {
          "type": "CompoundLayout",
          "layouts": [
            {
              "type": "SimpleLayout",
              "text": "${when:when=contains('${message}','SuccessAudit'):inner=SuccessAudit}"
            },
            {
              "type": "SimpleLayout",
              "text": "${when:when=contains('${message}','FailureAudit'):inner=FailureAudit}"
            },
            {
              "type": "SimpleLayout",
              "text": "${when:when=length('${event-properties:item=EntryType}')>0:inner=${event-properties:item=EntryType}",
              "IsFixedText": false
            }
          ]
        }
      },
      "ColoredConsole": {
        "type": "ColoredConsole"
      },
      "DebugConsole": {
        "type": "Debugger"
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Info",
        "writeTo": "EventLog"
      },
      {
        "logger": "*",
        "minLevel": "Info",
        "maxLevel": "Fatal",
        "writeTo": "ColoredConsole"
      },
      {
        "logger": "*",
        "minLevel": "Trace",
        "maxLevel": "Debug",
        "writeTo": "DebugConsole"
      }
    ]
  }
}
```
```c#
var config = new ConfigurationBuilder()
   .SetBasePath(Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName))
   .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
   .Build();

LogManager.Configuration = new NLogLoggingConfiguration(config.GetSection("NLog"));
```

- What is the current result?
Event Log target throws an error "Failed to create Target Type"
- What is the expected result?
Event log target to successfully load
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes
- Please post full exception details (message, stacktrace, inner exceptions)

2022-02-17 11:39:37.3468 Debug Skipping unknown 'NLog' property name=NLog
2022-02-17 11:39:37.3468 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2022-02-17 11:39:37.3747 Warn Ignoring assembly location because location is empty: NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
2022-02-17 11:39:37.3747 Debug Auto loading based on NLog-Assembly found location: 
2022-02-17 11:39:37.3747 Warn Ignoring assembly location because location is empty: MyProduct, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2022-02-17 11:39:37.3761 Debug Auto loading based on GetEntryAssembly-Assembly found location: 
2022-02-17 11:39:37.3761 Debug Auto loading based on AppDomain-BaseDirectory found location: {PublishedLocation}
2022-02-17 11:39:37.3761 Debug Search for auto loading files in location: {PublishedLocation}
2022-02-17 11:39:37.3761 Debug Start auto loading, location: {PublishedLocation}
2022-02-17 11:39:37.3761 Debug ScanAssembly('NLog.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2022-02-17 11:39:37.3761 Debug Auto loading done
2022-02-17 11:39:37.3761 Info Message Template Auto Format enabled
2022-02-17 11:39:37.3977 Debug Setting 'NLog.LayoutRenderers.Wrappers.UppercaseLayoutRendererWrapper.uppercase' to 'true'
2022-02-17 11:39:37.3977 Debug Setting 'NLog.Targets.ColoredConsoleTarget.name' to 'ColoredConsole'
2022-02-17 11:39:37.3977 Info Adding target ColoredConsoleTarget(Name=ColoredConsole)
2022-02-17 11:39:37.3977 Debug Registered target ColoredConsole: NLog.Targets.ColoredConsoleTarget
2022-02-17 11:39:37.3977 Debug Setting 'NLog.LayoutRenderers.Wrappers.UppercaseLayoutRendererWrapper.uppercase' to 'true'
2022-02-17 11:39:37.3977 Debug Setting 'NLog.Targets.DebuggerTarget.name' to 'DebugConsole'
2022-02-17 11:39:37.3977 Info Adding target DebuggerTarget(Name=DebugConsole)
2022-02-17 11:39:37.3977 Debug Registered target DebugConsole: NLog.Targets.DebuggerTarget
2022-02-17 11:39:37.4073 Warn Error has been raised. Exception: NLog.NLogConfigurationException: Failed to create target type: EventLog
 ---> System.ArgumentException: Target cannot be found: 'EventLog'
   at NLog.Config.Factory`2.CreateInstance(String itemName)
   at NLog.Config.LoggingConfigurationParser.CreateTargetType(String targetTypeName)
   --- End of inner exception stack trace ---
2022-02-17 11:39:37.4073 Warn Error has been raised. Exception: NLog.NLogConfigurationException: Target 'EventLog' not found for logging rule: *.
2022-02-17 11:39:37.4073 Debug --- NLog configuration dump ---
2022-02-17 11:39:37.4073 Debug Targets:
2022-02-17 11:39:37.4073 Debug ColoredConsole Target[ColoredConsole]
2022-02-17 11:39:37.4231 Debug Debugger Target[DebugConsole]
2022-02-17 11:39:37.4231 Debug Rules:
2022-02-17 11:39:37.4231 Debug logNamePattern: (:All) levels: [ Info Warn Error Fatal ] appendTo: [ ]
2022-02-17 11:39:37.4231 Debug logNamePattern: (:All) levels: [ Info Warn Error Fatal ] appendTo: [ ColoredConsole ]
2022-02-17 11:39:37.4231 Debug logNamePattern: (:All) levels: [ Trace Debug ] appendTo: [ DebugConsole ]
2022-02-17 11:39:37.4231 Debug --- End of NLog configuration dump ---
2022-02-17 11:39:37.4231 Info Validating config: TargetNames=ColoredConsole, DebugConsole, ConfigItems=25
2022-02-17 11:39:37.4231 Debug Unused target checking is started... Rule Count: 3, Target Count: 2
2022-02-17 11:39:37.4231 Debug Unused target checking is completed. Total Rule Count: 3, Total Target Count: 2, Unused Target Count: 0
2022-02-17 11:39:37.4387 Debug Debugger(Name=DebugConsole): System.Diagnostics.Debugger.IsLogging()==false. Output has been disabled.
2022-02-17 11:39:37.9131 Debug Targets for MyNamespace by level:
2022-02-17 11:39:37.9131 Debug Trace => DebugConsole
2022-02-17 11:39:37.9131 Debug Debug => DebugConsole
2022-02-17 11:39:37.9131 Debug Info => ColoredConsole
2022-02-17 11:39:37.9131 Debug Warn => ColoredConsole
2022-02-17 11:39:37.9131 Debug Error => ColoredConsole
2022-02-17 11:39:37.9131 Debug Fatal => ColoredConsole
2022-02-17 11:39:37.9316 Info AppDomain Shutting down. Logger closing...
2022-02-17 11:39:37.9316 Debug Flush completed
2022-02-17 11:39:37.9316 Debug Targets not configured for logger: MyNamespace 
2022-02-17 11:39:37.9386 Debug Closing logging configuration...
2022-02-17 11:39:37.9386 Debug Closing target 'ColoredConsole Target[ColoredConsole]'.
2022-02-17 11:39:37.9386 Debug Closed target 'ColoredConsole Target[ColoredConsole]'.
2022-02-17 11:39:37.9386 Debug Closing target 'Debugger Target[DebugConsole]'.
2022-02-17 11:39:37.9386 Debug Closed target 'Debugger Target[DebugConsole]'.
2022-02-17 11:39:37.9386 Debug Finished closing logging configuration.
2022-02-17 11:39:37.9386 Info Logger has been shut down.

- Are there any workarounds? yes/no
Yes, disable single file publishing
- Is there a version in which it did work? 
Not sure
- Can you help us by writing an unit test?
Maybe

**Comment by snakefoot** [comment] 2022-02-19 16:10
The problem is this:

```
2022-02-17 11:39:37.4073 Warn Error has been raised. Exception: NLog.NLogConfigurationException: Failed to create target type: EventLog
---> System.ArgumentException: Target cannot be found: 'EventLog'
at NLog.Config.Factory`2.CreateInstance(String itemName)
at NLog.Config.LoggingConfigurationParser.CreateTargetType(String targetTypeName)
--- End of inner exception stack trace ---
2022-02-17 11:39:37.4073 Warn Error has been raised. Exception: NLog.NLogConfigurationException: Target 'EventLog' not found for logging rule: *.
```

The EventLog-target on NetCore-platform requires a nuget-package: https://www.nuget.org/packages/NLog.WindowsEventLog

And it has to be included in the NLog.config:

```json
{
  "NLog": {
    "extensions": [
      { "assembly": "NLog.WindowsEventLog" }
    ]
  }
}
```

See also: https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json

**Comment by snakefoot** [comment] 2022-02-21 20:15
NLog 5.0 includes #4602 that helps people that forgets to add extensions.

NLog 5.0 also allows you to declare extension-targets like this:

```json
      "EventLog": {
        "type": "EventLog, NLog.WindowsEventLog"
      }
```

**Comment by pockets3407** [comment] 2022-02-22 00:22
Thanks, it works.

**Comment by snakefoot** [comment] 2022-02-22 06:20
Closing issue as resolved.

**Closed by snakefoot** 2022-02-22 06:20 UTC
Labels: question, nlog-configuration
