### ISSUE TITLE
OutOfMemoryException in Target.WriteAsyncLogEvent() (3.1.0.0)

### ISSUE THREAD

**Issue by gen3ric** [NLog/NLog#513] opened 2015-01-22 15:25 UTC
On occasion, my application does a lot of logging. Once in a while, I get a `System.OutOfMemoryException` from that method. I'm wary of using the `bool LogExceptions` flag, so I felt compelled to at least report that it's happening out there. 

It occurred  in the `try` `catch` which executes this line:

`204:    this.Write(logEvent.LogEvent.WithContinuation(wrappedContinuation));`

![Image](http://i.imgur.com/vDgZjQO.png)

**Comment by Xharze** [comment] 2015-01-22 16:12
Could you provide a sample project reproducing this issue?

**Comment by gen3ric** [comment] 2015-01-22 16:15
I will work on that, but essentially, log about 230mb worth of 1-line strings overnight and it will probably happen. My priority is fixing the bug that is clearly abusing NLog -- I imagine that supporting this edge  case is not high on the priority list for you either.

**Comment by Xharze** [comment] 2015-01-22 16:53
Thanks that would be great.
Depending on the cause you are correct. But most likely there's not much
which can done about it, when we're working with strings.

**Comment by 304NotModified** [comment] 2015-01-25 20:50
Hi @gen3ric. Is this a single string of 230mb, or a total of multiple strings? I wouldn't expect an out of memory when writing synchronously. Have you tried that?

**Comment by ImdotnetJunkie** [comment] 2015-08-07 08:31
Hi, I'm also facing the same issue. Below is the stack trace:
:  System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write(Byte[] bytes)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.WriteToTargets[T](LogLevel level, IFormatProvider formatProvider, T value)
   at NLog.Logger.Log(LogLevel level, String message)

My Nlog config looks like this:

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">
  <targets>
    <target name="file" xsi:type="File"
            fileName="${basedir}../../Logs/${processname}.log"
            archiveFileName="${basedir}../../Logs/Archive/${processname}-${shortdate}.{#}.log"
            archiveEvery="Day"
            archiveNumbering="Sequence"
            maxArchiveFiles="10"
            archiveAboveSize="20971520"
            keepFileOpen="false"
            concurrentWrites="true"
            layout="${longdate} [${uppercase:${level}}] [Thread: ${threadid}] [&lt;${logger}&gt;.${callsite:className=false}] ${message} ${exception:tostring}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="file" />
  </rules>
</nlog>

**Comment by 304NotModified** [comment] 2015-08-07 15:01
Same question: do you write large strings? 

Can you post the full config? (in code blocks: https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks)

Which NLog version? See https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md#bug-reports

**Comment by ImdotnetJunkie** [comment] 2015-08-10 05:19
No, we don't write large strings. However, we write too frequently and lots of data being written to the file. The NLog version being used is : 3.2.0.0

````
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true">
  <targets>
    <target name="file" xsi:type="File"
            fileName="${basedir}../../Logs/${processname}.log"
            archiveFileName="${basedir}../../Logs/Archive/${processname}-${shortdate}.{#}.log"
            archiveEvery="Day"
            archiveNumbering="Sequence"
            maxArchiveFiles="10"
            archiveAboveSize="20971520"
            keepFileOpen="false"
            concurrentWrites="true"
            layout="${longdate} [${uppercase:${level}}] [Thread: ${threadid}] [&lt;${logger}&gt;.${callsite:className=false}] ${message} ${exception:tostring}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="file" />
  </rules>
</nlog>
````
Let me know if you need any further information.

**Comment by 304NotModified** [comment] 2015-08-10 12:25
Hi @ImdotnetJunkie ,

this seems not to be related to async writing? So this is another case?

**Comment by ImdotnetJunkie** [comment] 2015-08-10 14:40
Yeah, it's related to asynch. But we are sil

**Comment by ImdotnetJunkie** [comment] 2015-08-10 17:59
Yes, you are right, it's not related to asynch. But still we are getting this exception: ```` System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count) at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write(Byte[] bytes) at NLog.Targets.FileTarget.WriteToFile(String fileName, Byte[] bytes, Boolean justData) at NLog.Targets.FileTarget.Write(LogEventInfo logEvent) at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent) at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent) at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException) at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory) at NLog.Logger.WriteToTargetsT at NLog.Logger.Log(LogLevel level, String message) ````

**Comment by 304NotModified** [comment] 2015-08-10 19:13
Can you create a new ticket for this?

**Comment by pablohiga** [comment] 2015-10-29 18:02
Hi,
I'm using NLog version 2.1.0 and I'm facing this same issue under high logging load conditions. 
Was it fixed in later versions?  

thanks!

**Comment by 304NotModified** [comment] 2015-11-02 22:38
Hi,

We have improved a lot in the newer version, but not an isolated memory issue (too bad?).

If you experience still problems with NLog 4.2, we are ready to help to diagnose and fix the problem!

**Comment by 304NotModified** [comment] 2015-11-02 22:39
I that case, please open a new issue.

We cannot fix this issue because we don't have enough feedback, so closing it.

**Closed by 304NotModified** 2015-11-02 22:39 UTC
Labels: needs info
