### ISSUE TITLE
FileTarget fails when path with null event is invalid (e.g ${logger} in path)

### ISSUE THREAD

**Issue by ohyubun** [NLog/NLog#2395] opened 2017-11-17 07:19 UTC
**Type** : Bug

**NLog version**: 5.0.0-beta11

**Platform**: UWP(Windows IOT)  on Raspberry Pi Model 3

**Current NLog config** (xml or C#, if relevant)
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off"
      >

  <!-- optional, add some variables
  https://github.com/nlog/NLog/wiki/Configuration-file#variables
  -->
  <!--
  See https://github.com/nlog/nlog/wiki/Configuration-file
  for information on customizing logging rules and outputs.
   -->
  <targets async="true">

    <!--
    add your targets here
    See https://github.com/nlog/NLog/wiki/Targets for possible targets.
    See https://github.com/nlog/NLog/wiki/Layout-Renderers for the possible layout renderers.
    -->

    <!--
    Write events to a file with the date in the filename.
    <target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message}" />
    -->
    <!--fileName="${specialfolder:folder=ApplicationData}/${logger}/${shortdate}.txt"-->
     <target name="Raspberry" 
               xsi:type="File" 
               fileName="${var:LogPath}/${shortdate}.txt"
               layout="${longdate} ${level:uppercase=true} ${message}"              
               concurrentWrites="true"
       />
     <target name="Raspberry1" 
               xsi:type="File" 
               fileName="${var:LogPath}/${logger}/${shortdate}.txt"
               layout="${longdate} ${level:uppercase=true} ${message}" 
       />
  </targets>

  <rules>
    <!-- add your logging rules here -->

    <!--
    Write all events with minimal level of Debug (So Debug, Info, Warn, Error and Fatal, but not Trace)  to "f"
    <logger name="*" minlevel="Debug" writeTo="f" />
    -->
    <logger name="*" minlevel="Trace" writeTo="Rasberry" />

  </rules>
</nlog>
```

In case of a BUG:

- What is the current result?
  It refers to https://github.com/NLog/NLog/issues/2237.
  I want NLog can write file in LocalCache using Windows.Storage.ApplicationData.Current.LocalCacheFolder.
  Target = "Raspberry" work well
  Target = "Raspberry1" does not work
- What is the expected result?
 Write log file normally
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  No
- Please post full exception details (message, stacktrace, inner exceptions)
  No
- Are there any work arrounds?  No
  No,but I try two kind of Targets.
- Is there a version in which it did worked? 
- Can you help us by writing an unit test?

in case of a FEATURE REQUEST:
 
 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by 304NotModified** [comment] 2017-11-17 21:21
> What is the current result?
> It refers to #2237.

What do you mean with that?

**Comment by ohyubun** [comment] 2017-11-20 02:25
Hi ,
Because UWP has restricted permission for directory access,so 
I followed #2237 's solution to define a Nlog variable named 'LogPath' in C# code.
LogPath could be got using Windows.Storage.ApplicationData.Current.LocalCacheFolder .
Then,I tried to add a variable ${Logger} under LogPath as sub folder  in Nlog configuration for storing different logger. (see NLog.Config target name='Raspberry1')
I expected Nlog could work in defined path,but it did not write any file and not create any sub folder.
I also tried to manually make a sub folder with Logger name  under LogPath ,but Nlog still did not write file.
Finally,I removed the variable ${Logger} and NLog wrote file sucessfully.(see NLog.Config target name='Raspberry')

**Comment by snakefoot** [comment] 2017-11-20 18:29
@ohyubun Does it work when using a hard-coded subfolder name instead of ${logger} ?

What is the output of the internal logger if you enable at runtime:

```
Windows.Storage.StorageFolder storageFolder = Windows.Storage.ApplicationData.Current.LocalFolder;
NLog.Common.InternalLogger.LogLevel = LogLevel.Trace;
NLog.Common.InternalLogger.LogFile = Path.Combine(storageFolder.Path, "internal.txt");

// Do some logging
```

**Comment by ohyubun** [comment] 2017-11-21 05:40
@snakefoot , answer as following :
(1)Does it work when using a hard-coded subfolder-name instead of ${logger} ?
Ans : Yes

(2)I turn on the NLog internal logging as your advise and find some error ~
[internal.txt](https://github.com/NLog/NLog/files/1490158/internal.txt)

**Comment by snakefoot** [comment] 2017-11-21 08:02
Thank you for the internal log. Can you also give me the internal-log when using file-target not working (changing the logging rule to use the other target with logger in path)



Sent from my Samsung device


-------- Original message --------

**Comment by ohyubun** [comment] 2017-11-21 08:59
@snakefoot ,

(1)code snippet

> 
            //enable NLog debugging log
            Windows.Storage.StorageFolder storageFolder0 = Windows.Storage.ApplicationData.Current.LocalCacheFolder;
            NLog.Common.InternalLogger.LogLevel = LogLevel.Trace;
            NLog.Common.InternalLogger.LogFile = Path.Combine(storageFolder0.Path, "internal.txt");

            string logRootFolder = "TryNLog";
            //Get UWP local path with permission
            Windows.Storage.StorageFolder storageFolder = Windows.Storage.ApplicationData.Current.LocalCacheFolder;
            await storageFolder.CreateFolderAsync(logRootFolder, Windows.Storage.CreationCollisionOption.OpenIfExists);

            //Add variables for log folder

            //for Target name='Rasberry' without ${logger}
            string logRootPath = $"{storageFolder.Path}//{logRootFolder}";
           
            //for Target name='Rasberry1' with ${logger}
            //string logRootPath = $"{storageFolder.Path}";

            NLog.LogManager.Configuration.Variables.Add("LogPath", logRootPath);
            logger = NLog.LogManager.GetLogger(logRootFolder);

(2)internal log file
   work -
[internal_Work.txt](https://github.com/NLog/NLog/files/1490637/internal_Work.txt)
  not work -
[interna_not Workl.txt](https://github.com/NLog/NLog/files/1490638/interna_not.Workl.txt)

**Comment by snakefoot** [comment] 2017-11-21 09:22
Can see the exception now. It is a bug in Nlog 5.0. Could you try Nlog 4.5 Beta 08 until the bug is fixed?



Sent from my Samsung device


-------- Original message --------

**Comment by ohyubun** [comment] 2017-11-21 10:45
@snakefoot ,
Thank you for your advise.
It works using NLOG 4.5 beta 8.

**Comment by snakefoot** [comment] 2017-11-21 11:17
Super. Are you running UWP or NetCoreApp ? There is no native UWP build of NLOG 4.5 so are you using NetStandard 2.0 or 1.5 ?



Sent from my Samsung device


-------- Original message --------

**Comment by ohyubun** [comment] 2017-11-23 03:11
@snakefoot ,
I installed Microsoft.NETCore.UniversalWindowsPlatform.

**Comment by snakefoot** [comment] 2017-11-23 06:12
@ohyubun What version of the Microsoft.NETCore.UniversalWindowsPlatform nuget-package?

**Comment by ohyubun** [comment] 2017-11-23 08:49
@snakefoot ,
I am using the latest version- v6.0.2

**Comment by snakefoot** [comment] 2017-11-23 13:03
Perfect. That explains why Nlog 4.5 works. UWP ver. 5 (or older) is not supported.

NLog 4.5 is just about to leave BETA, and become the next official version.


Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment] 2017-11-23 13:59
As I understand it correctly, this isn't a problem with `${logger}`, isn't? (did not read all the posts)

**Comment by snakefoot** [comment] 2017-11-25 13:48
> As I understand it correctly, this isn't a problem with ${logger}, isn't?

Yes the title of the issue is wrong. The problem is that NLog ver. 5 file-target cannot initialize when the FileName-layout cannot render a valid file-path from `LogEventInfo.CreateNullEvent()`

NLog 4.5 file-target delays the "validation" of the FileName-layout until actually logging a real LogEventInfo (Allowing `${logger}` to work).

**Comment by 304NotModified** [comment] 2017-11-25 13:55
Ah clear, thanks!

**Comment by 304NotModified** [comment] 2017-11-25 13:57
Closing this as rc is live.

**Closed by 304NotModified** 2017-11-25 13:57 UTC
Labels: bug, file-target
