### ISSUE TITLE
Logging to database works but error is reported using apsettings.json

### ISSUE THREAD

**Issue by RichCrittenden** [NLog/NLog#4419] opened 2021-05-05 12:04 UTC
I am getting logs to files fine and database is logging but when I look in the internalLogFile.log I see
Error DatabaseTarget(Name=ProcessLoggingDb): Error when writing to database. Exception: System.InvalidOperationException: The ConnectionString property has not been initialized.
   at System.Data.SqlClient.SqlConnection.PermissionDemand()

I am using  <target name="ProcessLoggingDb" xsi:type="Database"
            connectionString="${configsetting:item=ProcessLoggingDb}"
Where ProcessLoggingDb is in my appsettings.json as one element.
I am a bit confused?

**Comment by snakefoot** [comment] 2021-05-07 05:48
So database-logging is working, but you are seeing errors ?

Maybe you are logging to the database-target before having loaded the appsettings.json. Please show how the startup code for loading NLog along with `appsettings.json`.

**Comment by RichCrittenden** [comment] 2021-05-07 08:32
My startups is
 ```
public static void Main(string[] args)
        {
            var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
            try
            {
                logger.Debug("init main");
                CreateHostBuilder(args).Build().Run();
            }
            catch (Exception exception)
            {
                //NLog: catch setup errors
                logger.Error(exception, "Stopped program because of exception");
                throw;
            }
            finally
            {
                // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
                NLog.LogManager.Shutdown();
            }
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
            .UseWindowsService()

            .ConfigureLogging((hostingContext, logging) =>
            {

                logging.ClearProviders();
                logging.SetMinimumLevel(LogLevel.Trace);
             //   logging.AddConfiguration(hostingContext.Configuration.GetSection("ProcessLoggingDb"));

            })
                .UseNLog();
            
            
    }
```
And my Appsettings.json is
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Trace",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",

  "ProcessConfigFile": "C:\\OWInvoiceExtract\\ProcessConfig.json",
  "ProcessLoggingDb": "Server=XXXXXXXXXXXXXX;Database=XXXXX;Trusted_Connection=True;",
  "logApplicationName": "OWInvoiceExtract",
  "ConnectionStrings": {
    "ProcessDB": "Server=XXXXXXXXX;Database=XXXXXXX;Trusted_Connection=True;"
  }
}
```

nlog.config is

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogLevel="info"
      internalLogFile="C:\OWInvoiceExtract\Logs\OWInvoiceExtract.log">

  <!-- enable asp.net core layout renderers -->
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <!-- File Target for all log messages with basic details -->
    <target xsi:type="File" name="allfile" fileName="C:\OWInvoiceExtract\Logs\nlog-OWInvoiceExtract-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id:whenEmpty=0}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />

    <!-- File Target for own log messages with extra web details using some ASP.NET core renderers -->
    <target xsi:type="File" name="ownFile-web" fileName="C:\OWInvoiceExtract\Logs\nlog-OWInvoiceExtract-own-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id:whenEmpty=0}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}|" />

    <!--Console Target for hosting lifetime messages to improve Docker / Visual Studio startup detection -->
    <target xsi:type="Console" name="lifetimeConsole" layout="${level:truncate=4:lowercase=true}: ${logger}[0]${newline}      ${message}${exception:format=tostring}" />

    <target name="ProcessLoggingDb" xsi:type="Database"
            connectionString="${configsetting:item=ProcessLoggingDb}"
            commandText ="INSERT INTO XXXXXXX (
          [LogTime],[Level], [ProcessName], [LogEntry])
          VALUES (@Logged,@Level, @Application,  @Message)">

      <parameter name="@application" layout="${configsetting:item=logApplicationName}" />
      <parameter name="@level" layout="${level}" />
      <parameter name="@message" layout="${message}" />
      <!--<parameter name="@logger" layout="${logger}" />
    <parameter name="@callSite" layout="${callsite:filename=true}" />
    <parameter name="@exception" layout="${exception:tostring}" />-->
      <parameter name="@logged" layout="${date}" />
    </target>"
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />

    <!--Output hosting lifetime messages to console target for faster startup detection -->
    <logger name="Microsoft.Hosting.Lifetime" minlevel="Info" writeTo="lifetimeConsole, ownFile-web" final="true" />

    <!--Skip non-critical Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" maxlevel="Info" final="true" />
    <!-- BlackHole -->

    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
    
    <logger name="*"  minlevel="Info" maxlevel="Info"  writeTo="ProcessLoggingDb" />
  </rules>
</nlog>
```

**Comment by snakefoot** [comment] 2021-05-07 15:55
The issue is that `nlog.config` is loaded before loading `appsettings.json`:
```c#
public static void Main(string[] args)
{
   var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
   logger.Debug("init main");
}
```

What happens if you change to this:
```c#
public static void Main(string[] args)
{
   var logger = LogManager.Setup()
                          .LoadConfigurationFromAppSettings()
                          .GetCurrentClassLogger();
   logger.Debug("init main");
}
```

**Comment by RichCrittenden** [comment] 2021-05-07 16:28
That’s great thanks, all fixed 

Regards
  Richard Crittenden 
  07880 748178

**Comment by snakefoot** [comment] 2021-05-08 12:17
Closing issue as resolved

**Closed by snakefoot** 2021-05-08 12:17 UTC
Labels: database-target, needs info, nlog-configuration, question
