### ISSUE TITLE
Nlog.config Jsonlayout array footer doesnt work for me

### ISSUE THREAD

**Issue by frank2211** [NLog/NLog#4006] opened 2020-06-09 09:25 UTC
One of the simplest solution is configure `NLog.Layouts.CompoundLayout` to concat `NLog.Layouts.JsonLayout` and `NLog.Layouts.SimpleLayout(",")`. Then set Header to `"["` and the Footer to `"{}]"` :)

Then the log file will be closed correctly and the result is valid json.
`[`
`{ "level": "error", "message": "msg1"},`
`{ "level": "info", "message": "msg2"},`
`{}]`

_Originally posted by @tpilat in https://github.com/NLog/NLog/issues/1658#issuecomment-360911742_

hi I wanted to do exactly what you suggested but for some reason the footer text is not written in the logfile.
my nlog config looks like this:

```xml
 <targets>
    <target name="jsonfile" xsi:type="File" writeFooterOnArchivingOnly="false" fileName="${basedir}/logfile/${date:format=yyyy-MM-dd HH-mm}.json">
      <layout xsi:type="LayoutWithHeaderAndFooter">
        <header xsi:type="SimpleLayout" text="[" />
        <footer xsi:type="SimpleLayout" text="{}]" />
        <layout xsi:type='CompoundLayout'>
      <layout xsi:type="JsonLayout">
        <attribute name="time" layout="${date:format=yyyy-MM-dd HH-mm}" escapeUnicode="false"/>
        <attribute name="level" layout="${level:upperCase=true}" escapeUnicode="false"/>
        <attribute name="message" layout="${message}${exception:format=tostring}" escapeUnicode="false"/>
      </layout>
      <layout xsi:type='SimpleLayout' text="," />
      </layout>
        </layout>
    </target>
  </targets>

```
and the logfile looks like this:

[
{ "time": "2020-06-09 11-02", "level": "INFO", "message": "random logg message ÜüÄÄä" },
{ "time": "2020-06-09 11-02", "level": "WARN", "message": "$$3$$10,26" },
{ "time": "2020-06-09 11-02", "level": "INFO", "message": "random logg message ÜüÄÄä" },
{ "time": "2020-06-09 11-02", "level": "WARN", "message": "$$1$$3,42" },
{ "time": "2020-06-09 11-02", "level": "INFO", "message": "random logg message ÜüÄÄä" },
{ "time": "2020-06-09 11-02", "level": "WARN", "message": "$$2$$6,84" },

as you can see the "[" and the "," after every logmessage are working fine but the text of the footer is never written in the logfile even when I restart the program or when a new logfile gets created because of the timestamp in the filename. Ive played around with a few archiving functions but I was never able to get the footers text written into the file. 
Does anyone have an idea what im doing wrong?

**Comment by snakefoot** [comment] 2020-06-09 17:43
This issue is a duplicate of #1658, and if you read all the comments for that issue then you will notice the advice is to either:
- Fix your LogViewer-tool so it can handle that Json-file is not completely valid, but each line is a json-document.
- Create PullRequest for the NLog-project that enables NLog FileTarget to rewrite the Footer-Layout on file-append in an elegant way.

**Closed** 2020-06-16 17:43 UTC
Labels: duplicate, file-target
